### ISSUE TITLE
ListView styles

### ISSUE THREAD

**Issue by mkoutroupis** [pnp/sp-dev-fx-controls-react#1007]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 3.0.0 ]

#### Expected / Desired Behavior / Question
I would like to control the height of the ListView control by passing a className or styles object.
In the code, the **wrapper** has a set height of **50vh**. While this is great in some occasions, when using a collapsible section or adding more controls under it, it appears weird. Is there a way to set the height of the wrapper?

#### Observed Behavior
Because of wrapper has a default height of 50vh, when trying to limit the size of the ListView, the results are appearing under the next control.

![image](https://user-images.githubusercontent.com/5746869/132130060-8995b0fc-789d-4043-9586-26ae74acefe6.png)

#### Steps to Reproduce
Create a SPFX webpart and wrap the ListView control with a div and set the height of the div to 300 px. Build it and serve it. 
In the workbench, create 2 sections, add the webpart to both sections and populate them with as many items so that the scrollable pane appears.

Thanks!

**Comment by joelfmrodrigues** [comment]
Hi @mkoutroupis thanks for the information provided, will definitely be a good improvement.
Would you be willing to work on it and submit a PR?
