### ISSUE TITLE
FilePicker, Site Tab, List View, Column Header, Sorting Not Working as Expected

### ISSUE THREAD

**Issue by Arknev** [pnp/sp-dev-fx-controls-react#1011]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.3.0 ]

#### Expected / Desired Behavior / Question
FilePicker control, list view column headers to properly sort on single click.

#### Observed Behavior
When the FilePicker is open, in the site tab, viewing a library with files, the sorting of items by clicking on columns headers does not always work on single click and the sorting is not as expected. Modified date and file sizes are displayed in an unknown order when sorted.

#### Steps to Reproduce
1. Scaffold new project
2. Install spfx react controls
3. Add FilePicker as per guidance, removing Bing property (I don't have one of these right now), to HelloWorld.tsx
4. Run gulp serve --nobrowser
5. Navigate to workbench
6. Open File Picker, browse Site > Library (with files), from the list view, click header for column one or more times
7. Observe sorting order

**Comment by AJIXuMuK** [comment]
Thank you @Arknev for reporting the issue.
It has been fixed and will be included in the next release.
You can test the functionality in the latest [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by Arknev** [comment]
@AJIXuMuK This is fantastic, thank you!
