### ISSUE TITLE
ListItemAttachments control not behaving as expected when itemId is loaded asynchronously from the state variable.

### ISSUE THREAD

**Issue by SitaP-Wip** [pnp/sp-dev-fx-controls-react#1015]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[## ] Bug

[ ] Question

#### Version 

Please specify what version of the library you are using: [   3.3.0      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The ListItemAttachments control is not working as expected when the itemID is passed from a state variable which is loaded asyncronously. I am adding the files in another list and the item ID is fetched on page load. when the itemID is hard coded its working as expected.

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by AJIXuMuK** [comment]
@SitaP-Wip - thank you for reporting this one.
Could you please explain you scenario a bit more?
You add an attachment control on the page. And then, at some point of time, you're providing the id as a prop?
