### ISSUE TITLE
<ListPicker> baseTemplate option should allow string or multiple numbers

### ISSUE THREAD

**Issue by Xiyitifu** [pnp/sp-dev-fx-controls-react#1016]
#### Category
[x] Enhancement

#### Version

Please specify what version of the library you are using: [ Latest : 3.3.0]

#### Expected / Desired Behavior / Question
ListPicker Component should allow input of a string or multiple numbers because filter request is allowing it.
(Example : ?$filter=(BaseTemplate eq 100 or BaseTemplate eq 106))

#### Observed Behavior
ListPicker actually do not allow other input than number.

#### Steps to Reproduce
Use ListPicker component and set baseTemplate option.

**Comment by joelfmrodrigues** [comment]
@Xiyitifu thanks for this suggestion, definitely a good enhancement.

**Comment by joelfmrodrigues** [comment]
Merged and will be included on the next release
