### ISSUE TITLE
FieldUserRenderer - error on loading Person card (SPHelper -> Cannot read properties of undefined (reading 'getUserById'))

### ISSUE THREAD

**Issue by VladNS90** [pnp/sp-dev-fx-controls-react#1025]
#### Category

[x] Bug

#### Version

Please specify what version of the library you are using: [  2.9.0 ]

If FieldUserRenderer used for example on a Display form of SharePoint list then Person card fail to load.

Error in console 

**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getUserById')**

I suppose some import is missing in SPHelper file
If I add 

**import '@pnp/sp/webs';**

then issue will not occur.

Also I noticed that sp.web used in other methods of this file and I think it also broken.

I think this should be fixed at least for versions 2.x.x

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @VladNS90 - thank you for reporting this issue.
Could you please provide a sample or more detailed instructions on how to repro it?
How did you add a People Picker to the Display form?

Thanks!

**Comment by VladNS90** [comment]
Hi @AJIXuMuK. Sorry, my mistake. I used FieldUserRenderer in my Solution. Display form was just an example. Any way it's easy to reproduced with using of FieldUserRenderer. Person card will not load because of missing import in SPHelper class. Suppose this came with migratiob to pnpjs v2. I think it could be easy fix and could help to fix other possible issue with methods in SPHelper. Hope now it's clear. Could this be included in next release of v 2.x.x?

**Comment by AJIXuMuK** [comment]
Fixed as part of v 3.4.0
