### ISSUE TITLE
SitePicker control do not show all sites?

### ISSUE THREAD

**Issue by spverma03** [pnp/sp-dev-fx-controls-react#1026]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

We are observing that not all sites are fetched by PnP Site Picker Control. It seems 500 items are getting fetched on load of control. There are more sites in the tenant. When user types, the intended result is not shown as it was not fetched initially. New call for data do not trigged as we type the search-keyword.

This is certainly a bug.

Reference: https://pnp.github.io/sp-dev-fx-controls-react/controls/SitePicker/ 

<SitePicker
  context={this.props.context}
  label={'Select sites'}
  mode={'site'}
  allowSearch={true}
  multiSelect={false}
  onChange={(sites) => { console.log(sites); }}
  placeholder={'Select sites'}
  searchPlaceholder={'Filter sites'} />

**Comment by AJIXuMuK** [comment]
Hi @spverma03 - thank you for reporting this one.
I don't think I have any environment to test with more than 500 sites, so I will need your help here.

Could you please check how many `_api/search/query` requests you see in the Network when opening the site picker?
Could you also send me screenshots or results for PrimaryResults.RelevantResults.TotalRows from these request(s)?

Thanks!

**Comment by spverma03** [comment]
Hi @AJIXuMuK - Thank you for your prompt reply. I cannot share exact data due to data protection policies of my client. Following are details that maybe useful for you to triage:

API: *Tenant URL*/sites/*mysite*/_api/search/query?querytext=%27contentclass:STS_Site%20Path:<Tenant URL>*%27&selectproperties=%27SiteId,SiteID,WebId,DepartmentId,Title,Path%27&rowlimit=500&startrow=0


**Query String Parameters:**
querytext: 'contentclass:STS_Site Path:*tenant url**'
selectproperties: 'SiteId,SiteID,WebId,DepartmentId,Title,Path'
rowlimit: 500
startrow: 0**

![image](https://user-images.githubusercontent.com/41669778/135744229-4cc80d27-66a8-47b2-beee-ce224f88b7b8.png)

**Comment by spverma03** [comment]
@AJIXuMuK ,

I tried modifying the definition to increase the row limit by changing code inside node-modules but it didn't worked. The SitePicker kept on loading. I could see continuous search query being made in the network tab of browser.

As I'm looking for a quick solution currently, may you think of some work-arounds for time being until the resolution is pushed to repo:

1. Can we add more filters to the control so that we can specify site type? The mode 'site/hub/web' is not sufficient. For example, in my case, I just want to get all Communication sites only.

Suggest if I can modify query in node-modules in current implementation as a quick-fix, if possible.

2. Can we increase row-limit somehow? Is there any threshold/limit etc.

I have also observed that this issue is more prominent when I open a previously populated SitePicker instead of adding a new one. I see some more sites missing in edit mode.

**Comment by AJIXuMuK** [comment]
Hi @spverma03,

1. You can try to make the change in `node_modules`. And it would be a good enhancement in future.
2. the maximum row limit for search query is 500. That's why there is a loop in the code to do multiple requests if needed.

I'll try to repro it.

**Comment by AJIXuMuK** [comment]
@spverma03 I decreased `rowLimit` locally to 5 to repro the issue. But it behaves correctly.

When you're saying you see continuous search requests in network tab - what is the `startrow` in these requests? Is it changing?

In my case I see like that:
<img width="670" alt="Screen Shot 2021-10-03 at 11 45 00 AM" src="https://user-images.githubusercontent.com/17036219/135761477-f6323701-dd1b-493d-bd21-48dbaa2c4890.png">

**Comment by AJIXuMuK** [comment]
@spverma03 - I have changed the query to be POST and added support for `trimDuplicates` and `additionalQuery`.
You can try these new features in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) and check if it works.

**Comment by spverma03** [comment]
@AJIXuMuK - Thank you for your prompt assistance. I tried the beta version and it is working for me. Eagerly waiting for the stable release (3.4.0). We are not allowed to use beta versions in client/production. Do you have any expected timeline for version 3.4.0 roll-out?

Again, thank you promptly addressing this issue. It will help the community.

**Comment by spverma03** [comment]
@AJIXuMuK - Thank you for the update.

Meanwhile I observed similar issue in **@pnp/spfx-property-controls** where the OOB shows 5 search results by default and has option of *Show More*. In case of **PropertyFieldSitePicker control** there are only 3 search results *(Can we make this configurable at least or have a show more CTA)*. Unlike OOB control, we cannot search by URL *(Good to have search by URL feature)*. Due to this, the control sometimes do not show the searched site in the 3 options. 

For example, in my case there are many sites having keyword 'Home' in the site title such as various department home sites, teams home sites etc. There is also one landing site whose title is just 'Home'. When I search for keyword 'Home' I get random 3 search results but I do not find any option to search for the landing home site. In OOB webpart I can see the 'Home' site in default 5 search results, also I can search for the site using exact URL.

*Any suggestions?*
