### ISSUE TITLE
Accordion doesn't have any props to change default chevron icon

### ISSUE THREAD

**Issue by pineaulo** [pnp/sp-dev-fx-controls-react#1033]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [3.3.0]

#### Expected / Desired Behavior / Question

It would be very handy to have a prop that allow to define custom icon for the chevron.

**Comment by joelfmrodrigues** [comment]
@pineaulo this change has been merged and will be available in the next release. It is also available in the latest beta release.
