### ISSUE TITLE
pt-br.js loc file not included on v3.3.0

### ISSUE THREAD

**Issue by BrunoAlmeidaKotesky** [pnp/sp-dev-fx-controls-react#1034]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [    3.3.0     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The pt-br.js file shold be included on the dist folder.

#### Observed Behavior
It seens that it was supposed to included on version 2.7.0 
Merge Commit: https://github.com/pnp/sp-dev-fx-controls-react/pull/865/commits/26391390074cc0bdb7d621d193d733abc0abbe2d

#### Steps to Reproduce
Run npm install or yarn add on the latest version.

**Comment by joelfmrodrigues** [comment]
@BrunoAlmeidaKotesky Thanks for spotting this!

**Comment by joelfmrodrigues** [comment]
@BrunoAlmeidaKotesky this has now been fixed and will be in the next release.
If you have the chance, you can test it by installing the latest beta version. Happy to get PRs if you spot anything that is not right :)
