### ISSUE TITLE
Treeview expandtoselected not working and event handler not running when defaultSelectedKeys are updated.

### ISSUE THREAD

**Issue by cclarke3** [pnp/sp-dev-fx-controls-react#1040]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [6.14.11]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
When I update state of the defaultSelectedKeys to select another node, I expect the control to run the onselect event and expandtoselected to run.  This would make it possible to update the selected node from another control.

#### Observed Behavior
When I update the defaultSelectedKeys state variable through this.setState, the nodes to not expand to reveal the selected node, however, when you expand the nodes manually the background color has changed to indicate the updated selection has taken effect.  When debugging, its also revealed that the onselect event does not occur even though the selected node has been updated.  A caveat to this is that it updates on the first run of the render() method, so inside the componentdidmount function I can set it to any node key and it will expand to that node.

#### Steps to Reproduce
1. Set up state on the sharepoint framework control
2. Add treeItemSelected to the state
3. defaultSelectedKeys={this.state.treeSelected}
4. on an onclick event in the spfx webpart run a setstate to indicate a different node be selected
5. Notice the nodes did not expand to reveal the selected node and it did not run the select event handler

**Comment by AJIXuMuK** [comment]
Hi @cclarke3,

Sorry, I don't quite get what version of the library you're using. The latest is 3.5.0, there is no 6.14.11.

I've just tested `defaultSelectedKeys` on the latest version, and it's working fine. I was using button click to update the keys:
```typescript
<PrimaryButton onClick={() => { this.setState({ treeViewSelectedKeys: ['gc1', 'gc3'] }); }}>Change selection</PrimaryButton>
```

Could you double-check the library version?
