### ISSUE TITLE
FilePicker Recents tab selection is not visible

### ISSUE THREAD

**Issue by MonalisaBaltatescu** [pnp/sp-dev-fx-controls-react#1048]
In the Recents tab I can select the files but the selection circle is shown only on hover

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

SPFx 1.12.1
sp controls 1.12.1

#### Expected / Desired Behavior / Question
For the sake of consistency, I expect the files in the recent tabs to be displayed as a list (same as OneDrive or Site Files). The selected file should be visible.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/32879490/138691503-8fc7d98f-66dd-4779-a644-87d0306bc35f.png)
The files are displayed as tiles, taking so much space and the selection circle is visible only on hover. Not mobile-friendly.

#### Steps to Reproduce
Add a FilePicker component and go to the Recents tab.

**Comment by joelfmrodrigues** [comment]
Merged PR to fix the checkbox display issue and will be in the next release
