### ISSUE TITLE
PeoplePicker in ListView Command Set Extension

### ISSUE THREAD

**Issue by jonesron** [pnp/sp-dev-fx-controls-react#1054]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [ 2.10.0 ]

Hello

I'm trying to use the People in a ListView command set extension, but I keep receiving the following error:

Type 'ExtensionContext' is not assignable to type 'WebPartContext | ExtensionContext'

Please let me know if you need more info.  Thanks in advance.

**Comment by jonesron** [comment]
I just tried to add the people picker to a webpart and I received the following error: 

Type 'WebPartContext' is not assignable to type 'WebPartContext | ExtensionContext'.
  Type 'import("_%ProjectDirectory%_/node_modules/@microsoft/sp-webpart-base/dist/index-internal").WebPartContext' is not assignable to type 'import("_%ProjectDirectory%_/node_modules/@pnp/spfx-controls-react/node_modules/@microsoft/sp-webpart-base/dist/index-internal").WebPartContext'.
    Types have separate declarations of a private property '_domElement'.

**Comment by jonesron** [comment]
I don't know if this matters, but on the repository, context is set to BaseComponentContext

![image](https://user-images.githubusercontent.com/7633261/139498255-706e074a-431e-4cda-b47f-83293a0847a2.png)

But when I install the package, context is WebPartContext | ExtensionContext

![image](https://user-images.githubusercontent.com/7633261/139498147-9ff2d126-b623-47d7-93d5-25f3436e3d96.png)

**Comment by AJIXuMuK** [comment]
@jonesron - what version of SPFx and Controls are you using?
v2 is for SPFx <= 1.11
v3 is for SPFx 1.12.1
v3 beta is for SPFx 1.13

**Comment by jonesron** [comment]
1.12.1 for the extension.  1.13 for the webpart.

**Comment by jonesron** [comment]
the package.json says is '2.10.0' for both solutions.

I ran the npm that was on the home page:
![image](https://user-images.githubusercontent.com/7633261/139500548-6f6aba4b-b974-4878-b4ec-73ab3ff160ea.png)

**Comment by AJIXuMuK** [comment]
@jonesron sorry - there was a glitch with the pipeline and incorrect version has been released as the latest one.

Could you please reinstall the package again and see if it works.

Also, if your SPFx solution is 1.13 (for example, @microsoft/sp-component-base package has version 1.13.0 in `package.json`) you'll need to install the beta version with `npm i --save --save-exact @pnp/spfx-controls-react@next`

Let me know if that works.

**Comment by jonesron** [comment]
@AJIXuMuK the peoplepicker is now working in both of my solutions after the package update.

As always, thank you for your help.
