### ISSUE TITLE
ModernTaxonomyPicker - how to Add initial terms manually without query the term store

### ISSUE THREAD

**Issue by RubenHerrera86** [pnp/sp-dev-fx-controls-react#1055]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [     3.4.0   ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by RubenHerrera86** [comment]
The initialterms have changed  in ModernTaxonomyPicker to ITermInfo[], 
is it possible  to add the manually the ITermInfo[] without query the term?

**Comment by patrikhellgren** [comment]
@RubenHerrera86 You can pass an array of objects like the example below but you need to know the Id of the term and preferrably the correct label (even though it will work with any label value):
``` typescript
initialValues={[{labels: [{name: "Sub process A1", isDefault: true, languageTag: "en-US"}], id: "29eced8f-cf08-454b-bd9e-6443bc0a0f5f", childrenCount: 0, createdDateTime: "", lastModifiedDateTime: "", descriptions: [], customSortOrder: [], properties: [], localProperties: [], isDeprecated: false, isAvailableForTagging: [], topicRequested: false}]}
```
All that is needed as an initial value is label name ("Sub process A1" in the example) for the language of the user ("en-US" in the example) and the term Id but the rest is needed just to be a correct ITermInfo and can be any valid value and will be loaded by the control later on.

**Comment by joelfmrodrigues** [comment]
@RubenHerrera86 closing this issue as like @patrikhellgren mentioned, you need to pass an array of objects and you need to know the term Id
