### ISSUE TITLE
File Picker - "Your organisation" tab, breadcrumb not working. 

### ISSUE THREAD

**Issue by STGHMAAV** [pnp/sp-dev-fx-controls-react#1056]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.3.0]

#### Expected / Desired Behavior / Question
If you access the "Your organisation" tab and access a folder, be able to go back to the parent folder using the breadcrumb to see all folders.

#### Observed Behavior
If you access the "Your organisation" tab it showsthe root of the library (in my case containing folders), accessing a folder shows the images that it contains, clicking on the parent folder on the breadcrumb doesn't work to go back (it's not even a button), to be able to go back you need to change the tab and go back to the mentiones tab. This is confusing since other tabs like "Site" have this option available.

#### Steps to Reproduce
Having folders on the library that the "Your organisation" tab points to, accessing the mentioned tab on the FilePicker and accessing a folder. Trying to use the breadcrumb to go back to the parent folder.

**Comment by joelfmrodrigues** [comment]
@STGHMAAV many thanks for reporting this issue.
A fix has been implemented and will be part of the next release.
