### ISSUE TITLE
Save button has the wrong german translation

### ISSUE THREAD

**Issue by sancezz2k** [pnp/sp-dev-fx-controls-react#1059]
Category
[ ] Enhancement

[ x] Bug

[ ] Question

Version
3.4.1

Expected / Desired Behavior / Question
I expect the correct German translation for the text of the save button.

Observed Behavior
The German translation for the text of the Save button is wrong. The text should be: 'Speichern' - currently the text is 'Retten'.
Here are the German translations: https://github.com/pnp/sp-dev-fx-controls-react/blob/440c2af2b5750e6ec5e609d0ef254e9524544596/src/loc/de-de.ts

Steps to Reproduce
Set the language of the browser to German and then test e.g. a DynamicForm Webpart.

**Comment by joelfmrodrigues** [comment]
@sancezz2k many thanks for raising the issue and providing a solution.
The label is now updated and will be included as part of the next release.
