### ISSUE TITLE
Changes in TreeView

### ISSUE THREAD

**Issue by amirmsai** [pnp/sp-dev-fx-controls-react#1062]
**To define the expanded nodes and dont lose it after a refresh: only to add a block of code in TreeviewItem in componentWillReceiveProps,**
It will be like this: 
 public componentWillReceiveProps(nextProps: IMyTreeItemProps): void {
    // If selection is turned on, set the item as selected
    if (this.props.selectionMode != MyTreeViewSelectionMode.None) {
      let active = nextProps.activeItems.filter(item => item.key === this.props.treeItem.key);

      let _isExpanded:boolean=this.state.expanded;
      if(!_isExpanded &&  this.props.nodesToExpand.indexOf(this.props.treeItem.key) != -1) {
        _isExpanded = true;
      }
      if(_isExpanded && this.props.nodesToExpand.indexOf(this.props.treeItem.key) == -1){
        _isExpanded=false;
      }

      this.setState({
        selected: active.length > 0,
        expanded: _isExpanded
      });
    }
  }

**And add the property  defaultExpandedKeys?: string[]; in TreeViewProps**

**Comment by AJIXuMuK** [comment]
Hi @tounsiAli,

Thank you for the suggestion.
As you've already dig into it - would you be interested in submitting the PR?

Thanks!

**Comment by tounsiAli** [comment]
Hi Alex,
how can i do it ?


Le sam. 4 déc. 2021 à 18:30, Alex Terentiev ***@***.***> a
écrit :

**Comment by tounsiAli** [comment]
Hello,

the changes are defined. I created a PR #default expanded treeItem by
tounsiAli · Pull Request #1084 · pnp/sp-dev-fx-controls-react (github.com)
<https://github.com/pnp/sp-dev-fx-controls-react/pull/1084>

Amir MSAI

Le mar. 7 déc. 2021 à 15:08, Alex Terentiev ***@***.***> a
écrit :

**Comment by tounsiAli** [comment]
Hello,

can you please add my name "Amir MSAI" like a contributor :)
thanks
Amir MSAI

**Comment by AJIXuMuK** [comment]
The changes have been merged and will be available in the next release.
