### ISSUE TITLE
Listview filter with AND/OR

### ISSUE THREAD

**Issue by clechner77** [pnp/sp-dev-fx-controls-react#1063]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ v3 ]

#### Expected / Desired Behavior / Question
Can listview filter on multiple fields/colums with AND/OR ?  I could not figure out a syntax that would accommodate that scenario.  Also note, documentation has a spelling mistake  -->ColumndName

**Comment by AJIXuMuK** [comment]
Hi @clechner77,

For now ListView supports filtering based on all columns or one specific column, with the contains check of the value.
There is no way to do AND/OR filtering on multiple columns.
I'd say "filter" is more "search" in that case.

We'd be happy if you enhance the control with additional functionality. 
If you are interested - feel free to create a PR.
