### ISSUE TITLE
Dashboard component, widget content is not scrollable

### ISSUE THREAD

**Issue by gmorken** [pnp/sp-dev-fx-controls-react#1068]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [   3.4.1      ]

#### Expected / Desired Behavior / Question
In widget, if content is to long, there should be a scrollbar?

#### Observed Behavior
Content is not scrollable

#### Steps to Reproduce
New webpart, added dashboard component

**Comment by Jwaegebaert** [comment]
@gmorken, to make your content scrollable on overflow you can add your own custom styling.

Easy example:

`   
                content: (
                  <div style={{overflowY: "auto"}}>
                    ... your content 
                  </div>
                )
`

Result: 

![afbeelding](https://user-images.githubusercontent.com/38426621/145072876-715aa997-0121-4c75-a533-0879d9ccd307.png)

Hope this helps!

**Comment by joelfmrodrigues** [comment]
@gmorken were you able to resolve the issue using @Jwaegebaert 's suggestion?

**Comment by gmorken** [comment]
great @Jwaegebaert ! its working now
