### ISSUE TITLE
DynamicForm does not load or save correctly when field name starts with special character

### ISSUE THREAD

**Issue by t0mgerman** [pnp/sp-dev-fx-controls-react#1077]
#### Category
[ ] Enhancement

[*] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.5.0]

#### Expected Behavior 

DynamicForm should display and save all field values, regardless of internal field name in SharePoint

#### Observed Behavior

When a field is created in SharePoint with a special character at the start of the field name, SharePoint replaces this character with a unicode representation like `\_x####\_` - where #### is the unicode character reference. For example: if you name a field "% Complete" - SharePoint will call this field "_x0025_Complete" internally. To complicate matters further, the property returned from the API will be named "OData__x0025_Complete". At present, because of this difference, fields named in this way will not work in DynamicForm.

This does not affect fields where a special character is used in the middle or at the end of the field name. Only those used at the beginning.

#### Steps to Reproduce

1. Add a SharePoint field to a list, beginning with a special character such as %
2. Create or edit a list item to ensure that this field has a value
3. Amend [ControlsTest.tsx#L886](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/webparts/controlsTest/components/ControlsTest.tsx#L886) to uncomment and display the DynamicForm control, point this control at the list and list item, then view the test in Workbench
4. Observe that the list item value does not load correctly, and values cannot be saved back to the list

#### Proposed Solution

The necessary data to fix this issue is already being retrieved. Instead of using `field.InternalName`, use `field.EntityPropertyName`. In most cases this matches `field.InternalName` - but it _also matches_ the field property name as the SharePoint API expects it. 

So on [DynamicForm.tsx#L326](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/dynamicForm/DynamicForm.tsx#L326) use:

```ts
defaultValue = item[field.EntityPropertyName];
```

and on [DynamicForm.tsx#L458](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/dynamicForm/DynamicForm.tsx#L458) use:

```ts
columnInternalName: field.EntityPropertyName,
```

**Comment by murtuzamj** [comment]
Any idea why the "Person Group" type fields on the list, renders an arbitrary (user) value when left blank?

Any workaround to mitigate the behavior
