### ISSUE TITLE
FilePicker - feature -  preventing hash change on Tab navigation

### ISSUE THREAD

**Issue by Katli95** [pnp/sp-dev-fx-controls-react#1080]
#### Category
- [x] Enhancement
- [x] _Bug_

#### Version 
- [current]

#### Desired Behavior/Expected
Expected to be able to use the control within a SPFx Library Extension without issue. I'm opening it with an extension in a Document Library while the user is in the context of a Document Set. I should be able to navigate the Tabs of the `<FilePicker/>` without it affecting the surrounding context.

#### Observed Behavior
When I select e.g. the "Upload Files" tab, it adds the "#Multipleupload" hash to the URL, which causes SP to navigate the user to the root of the library (barely noticeable in the background of the panel), resulting in loss of context when the `<FilePicker/>` panel closes.

#### Steps to Reproduce
Open the `<FilePicker/>` panel while in the context of a Document Set and navigate to a new tab within the `<FilePicker/>`.

#### Thoughts/Suggestion
This could be solved by adding a parameter called something like `shouldPreventHashChangeOnTabClick` or something to that effect that could then be checked in the `_handleLinkClick()` function to dynamically call `preventDefault()` on the event.

I would contribute myself but I simply don't have the time because of the pre-holiday load.

**Comment by joelfmrodrigues** [comment]
@Katli95 Really sorry for the late reply.
There was a similar issue reported here #1090 and a reply providing info on how to avoid URL changes. https://github.com/pnp/sp-dev-fx-controls-react/issues/1090#issuecomment-1050167556
Could you please confirm if this resolves your issue?
