### ISSUE TITLE
PeoplePicker control same user not accept while email is different.

### ISSUE THREAD

**Issue by CV-Ankit** [pnp/sp-dev-fx-controls-react#1082]
We have one license internal user and one external user. both have same name but different email id.

In one people picker both user cant be selected as both share same name. 

**Version using** 
@pnp/spfx-controls-react ^2.10.0
Control: https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/

Thank you in advance.

**Comment by AJIXuMuK** [comment]
Transferred to the appropriate repo.

**Comment by joelfmrodrigues** [comment]
@CV-Ankit really sorry for the long delay. Could you please provide more details about the problem? Is the issue happening when trying to select both user accounts within the same field? If so, can both accounts be selected separately?

**Comment by CV-Ankit** [comment]
Hello @michaelmaillot 

Yes, still same issue with the updated version 3.15.0.

**Comment by michaelmaillot** [comment]
I think that this is related to #1603 & #1612 which has a PR submitted by @NishkalankBezawada [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1620).

**Comment by michaelmaillot** [comment]
Closing as fixed in version 3.16.0
