### ISSUE TITLE
ModernTaxonomyPicker InitialValues does not work

### ISSUE THREAD

**Issue by omarelanis** [pnp/sp-dev-fx-controls-react#1086]
#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   3.5   ]

#### Expected / Desired Behavior / Question

I am using the Modern Taxonomy Picker (https://pnp.github.io/sp-dev-fx-controls-react/controls/ModernTaxonomyPicker/) and it's working great and look awesome however I cannot get it to accept a default values using the initialValues property.

According to the documentation it should be of the type ITermInfo[] _(separate issue here as well as documentation states to use import { ITermInfo } from '@pnp/sp/taxonomy' however in fact it needs to be import { ITermInfo } from "@pnp/spfx-controls-react/node_modules/@pnp/sp/taxonomy/" - but that maybe an issue with my SPFx version)_ 

#### Observed Behavior

I retrieve an object of ITermInfo[] and pass this into the initialValues property via the state but it is just ignored and leaves the field blank

#### Steps to Reproduce

First retrieve a term ID from the term store, I've used the following to get the currently selected term ID from the SharePoint field to retrieve the ITermInfo object back from the term store

```
      const taxGrpInfo: ITermGroupInfo[] = await sp.termStore.groups();
      const siteTaxGroup: ITermGroupInfo = taxGrpInfo.filter( item => {return item.name.indexOf("Site Collection - ") > -1})[0];
      const taxSetInfo: ITermSetInfo[] = await sp.termStore.groups.getById(siteTaxGroup.id).sets();
      const taxTermInfo: ITermInfo = await sp.termStore.groups.getById(taxGrpInfo[0].id).sets.getById(taxSetInfo[0].id).getTermById(**IDofTHEterm**)();
      try{
        this.setState({
          selectedTaxFields: {
            Operation_x0020_Unit_x0020_Type: taxTermInfo
          }
        });
      }
      catch (error) {}
```

```
              <ModernTaxonomyPicker
                allowMultipleSelections={false}
                label="Operation Unit Type"
                termSetId={this.state.choiceFields.Operation_x0020_Unit_x0020_Type}
                panelTitle="Select Operation Unit Type"
                context={this.props.spfxContext as any}
                onChange={myHelpers._onTaxPickerChange.bind(this, "Operation_x0020_Unit_x0020_Type")}
                initialValues={this.state.selectedTaxFields.Operation_x0020_Unit_x0020_Type}
              />
```

When I run through the code I can see the term is being correctly pulled into the state and ready to be set in the control but nothing actually gets set, I've tried casting as a single object instead of an array but that doesn't work either, I've also noticed the OnChange property is called a few times during initial load but always returns a blank term - same problem occurs if I set OnChange to null.

![image](https://user-images.githubusercontent.com/35841910/147829117-7d75814f-3090-4251-a115-c639a42ce3cc.png)

![image](https://user-images.githubusercontent.com/35841910/147830060-14780a82-8f6d-4612-8f0b-362662fe207e.png)

![image](https://user-images.githubusercontent.com/35841910/147829136-3d5b9700-31ec-44cc-97a5-0d589a7c7485.png)

Any help would be greatly appreciated!

**Comment by patrikhellgren** [comment]
Hi @omarelanis,
the initialValues property is what it says, i.e. the values to have selected during the initial render so you cannot change or set it after the control has already been rendered which would be the case in your example.
In your example you also pass the initial term as a single value, not as an array, but that might just be an error in the example code.

One way to solve your problem in your example would be to do a conditional rendering of the control like this and pass the property as an array:

```TypeScript
{this.state && this.state.selectedTaxFields && this.state.selectedTaxFields.Operation_x0020_Unit_x0020_Type && 
  <ModernTaxonomyPicker
    allowMultipleSelections={false}
    label="Operation Unit Type"
    termSetId={this.state.choiceFields.Operation_x0020_Unit_x0020_Type}
    panelTitle="Select Operation Unit Type"
    context={this.props.spfxContext as any}
    onChange={myHelpers._onTaxPickerChange.bind(this, "Operation_x0020_Unit_x0020_Type")}
    initialValues={[this.state.selectedTaxFields.Operation_x0020_Unit_x0020_Type]}
  />
}
```

I cannot seem to be able to repro your problem with the import of ITermInfo. I install pnp-js and use ITermInfo in the code, gets the red squiggly underline in VS Code, right click the underline and VS Code suggests to import ITermInfo from @pnp/sp/taxonomy and after doing that everything just works.

**Comment by omarelanis** [comment]
Hi @patrikhellgren ,

Many thanks for the response, greatly appreciated.

I should have mentioned I'm setting the state on component during componentDidMount() so it's set before the controls are rendered, I can see it is in the state item when the control gets rendered. However you hit the nail on the head about it not being returned as an array - D'OH!! It's a single select Taxonomy field so I was returning a single object instead of an array - fixed it and it's now working - thank you!! :)

Re the ITermInfo error that is because the ModernTaxonomyPicker is loading ITermInfo from "node_modules/@pnp/spfx-controls-react/node_modules/@pnp/sp/taxonomy/" for some weird reason, 
![image](https://user-images.githubusercontent.com/35841910/147880489-c7e393aa-56f7-4b36-9aa0-231b0ff190df.png)
But in my interface when I load it from there it is loading from the correct location @pnp/sp/taxonomy
![image](https://user-images.githubusercontent.com/35841910/147880546-449c11c4-4515-4d13-aacc-c06d37ee25f4.png)

 Both files are actually different so I end up with an error about them being incompatible and about a missing property
 Property 'properties' is optional in type 'ITermInfo' but required in type 'ITermInfo'.ts(2322)
![image](https://user-images.githubusercontent.com/35841910/147880647-6db33374-8a87-44e4-9ba5-0846dd510513.png)

So I have to load the ITermInfo in the interface from the following module instead:
import { ITermInfo } from "@pnp/spfx-controls-react/node_modules/@pnp/sp/taxonomy/";

and then it all works, not sure if this is a bug on my setup or something else causing it but it's working now - thanks again!

**Comment by webdevelperify** [comment]
Hi,
I am also facing this issue. I am able to get the required information but the initial values are never populated in the control.


```
export const ModernTaxonomyFormControl = ({control, context, saveToState, pnpService }: { control: IFormField; context: WebPartContext; saveToState: (value: string, key: string) => Promise<void>; pnpService:  IPnPService;  }) : JSX.Element => {
    
const [initalManagedMetadata, setInitalManagedMetadata] = React.useState<ITermInfo[]>([])
    
    React.useEffect(()=>{
        (async () => {
            const data: ITermInfo = await pnpService.getManagedMetadataTermInfo(termSetId,termId);
            setInitalManagedMetadata([data]);
        })();
    },[])

    return (
        <>
        <FieldDisplayMoreInformation id={control.id} label={control.fieldDisplayName} description={control.description} />
        {setInitalManagedMetadata.length > 0 && <ModernTaxonomyPicker 
            allowMultipleSelections={control.AllowMultipleValues}
            termSetId={control.termSetId}
            panelTitle={control.fieldDisplayName}
            label={null}
            required={control.required}
            context={context as any}
            onChange={changeTaxonomyField}    
            initialValues={initalManagedMetadata}
        />}
    </>  
    )
}

```

**Comment by stevebeauge** [comment]
> Hi @omarelanis, the initialValues property is what it says, i.e. the values to have selected during the initial render so you cannot change or set it after the control has already been rendered which would be the case in your example. In your example you also pass the initial term as a single value, not as an array, but that might just be an error in the example code.

In this case, how can you "control" the values within the picker ?

I have a full repro here : https://github.com/stevebeauge/pnpreactrepromoderntaxonomy/blob/main/src/webparts/repro/components/Repro.tsx

I don't get how it should works. Your suggestion only hide the issue (as far as I understand). It does not solve it.

Or I missed something ?

**Comment by stevebeauge** [comment]
> According to the documentation it should be of the type ITermInfo[] _(separate issue here as well as documentation states to use import { ITermInfo } from '@pnp/sp/taxonomy' however in fact it needs to be import { ITermInfo } from "@pnp/spfx-controls-react/node_modules/@pnp/sp/taxonomy/" - but that maybe an issue with my SPFx version)_

This point can reveal a version mismatch beetween @pnp/js used by the spfx controls react and your project.

What you can do either to ensure you use the same version or you can trick with some nice TS feature to alias types:

````
import { IModernTaxonomyPickerProps, ModernTaxonomyPicker } from '@pnp/spfx-controls-react';

type PartialTermInfo = IModernTaxonomyPickerProps["initialValues"];
  const initialTerms: PartialTermInfo = [
    {
      id: "f786ab93-e92c-aaa9-8642-ad24b74476e6",
      labels: [
        {
          isDefault: true,
          languageTag: 'fr-FR',
          name: "MyTerm"
        }
      ]
    }
  ];
````

**Comment by omarelanis** [comment]
> > Hi @omarelanis, the initialValues property is what it says, i.e. the values to have selected during the initial render so you cannot change or set it after the control has already been rendered which would be the case in your example. In your example you also pass the initial term as a single value, not as an array, but that might just be an error in the example code.
> 
> In this case, how can you "control" the values within the picker ?
> 
> I have a full repro here : https://github.com/stevebeauge/pnpreactrepromoderntaxonomy/blob/main/src/webparts/repro/components/Repro.tsx
> 
> I don't get how it should works. Your suggestion only hide the issue (as far as I understand). It does not solve it.
> 
> Or I missed something ?

The control will manage the selected choices so you just need to set them the state or similar using the OnChange property:

onChange={myHelpers._onTaxPickerChange.bind(this

In my case _onTaxPickerChange is a function that sets a state variable to the selected taxonomy values.

The initial values property has to be an array and is only used to set which terms are selected on load, in my case it was a single object like {} instead of [{}] so when i updated it then it worked as expected

**Comment by stevebeauge** [comment]
@omarelanis I think my PR https://github.com/pnp/sp-dev-fx-controls-react/pull/1308 should also fix your issue

**Comment by omarelanis** [comment]
> 

Hi Steve,

There is no issue anymore technically, the resolution was to send the taxonomy data as an array instead of as a single object (even if just one taxonomy is retrieved). 

I've had a look at your PR  #1308 but I'm not experiencing this issue of it looping like you are, this was for an old project but essentially all I had to do was retrieve the selected taxonomy objects of the field using the code below, but I needed to make sure taxTermInfo was returned as an array not as an object

`      const taxGrpInfo: ITermGroupInfo[] = await sp.termStore.groups();
      const siteTaxGroup: ITermGroupInfo = taxGrpInfo.filter( item => {return item.name.indexOf("Site Collection - ") > -1})[0];
      const taxSetInfo: ITermSetInfo[] = await sp.termStore.groups.getById(siteTaxGroup.id).sets();
      const taxTermInfo: ITermInfo = await sp.termStore.groups.getById(taxGrpInfo[0].id).sets.getById(taxSetInfo[0].id).getTermById(**IDofTHEterm**)();
      try{
        this.setState({
          selectedTaxFields: {
            Operation_x0020_Unit_x0020_Type: taxTermInfo
          }
        });
      }
      catch (error) {}`
