### ISSUE TITLE
FilePicker controls appends the string to the url that affects my react router page

### ISSUE THREAD

**Issue by fareedmohammad** [pnp/sp-dev-fx-controls-react#1090]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The Filepicker tab is appearing, when i click on other tabs, the page is getting refreshed because of the routes that am using, the control should not have refreshed the page

#### Observed Behavior
the page gets blank when other tabs in hte file picker control is selected

#### Steps to Reproduce
1. create a spfx application with react router
2. in the route page add the filepicker control
3. select any other tab after the default is populated 
4. the content on the page which was loaded earlier disappears, ie., a new page will be loaded

Thanks!

**Comment by notariorob** [comment]
You can set the storeLastActiveTab to false to prevent the component from appending anything to the url, which will fix the problem :-) I just faced the same problem and that's what solved it.
https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/#:~:text=should%20be%20hidden.-,storeLastActiveTab,-boolean

**Comment by notariorob** [comment]
You can set the storeLastActiveTab to false to prevent the component from appending anything to the url, which will fix the problem :-) I just faced the same problem and that's what solved it.
https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/#:~:text=should%20be%20hidden.-,storeLastActiveTab,-boolean

**Comment by joelfmrodrigues** [comment]
@notariorob many thanks for your comment.
@fareedmohammad could you please confirm if the suggestion above resolved your problem?
