### ISSUE TITLE
TaxonomyPicker control allows select deprecated/untaggable terms when typing

### ISSUE THREAD

**Issue by kallejar** [pnp/sp-dev-fx-controls-react#1093]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     3.5.0    ]

#### Expected / Desired Behavior / Question
We have in our term set deprecated and untaggable terms set. On the control I have both these options true.
`hideTagsNotAvailableForTagging={true}
hideDeprecatedTags={true}`

The true value works when you pick the terms via the tag-icon
![image](https://user-images.githubusercontent.com/35795546/149506154-b15fc933-757a-48c7-a599-e02d3bdd4968.png)

But if you type directly to the control field you are able to find and pick the term
![image](https://user-images.githubusercontent.com/35795546/149506314-c5c0afa2-91f8-49b9-89b8-f8d902031da3.png)
![image](https://user-images.githubusercontent.com/35795546/149506330-6900d79e-64c0-47d5-a765-e7a0567c0688.png)
Console.log
![image](https://user-images.githubusercontent.com/35795546/149506463-eaa619e7-e962-480d-9fdc-38081feb7345.png)

I would expect both typing and selecting term via picker would work the same when using those control propeties

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
I have following configuration for the control:
`<TaxonomyPicker 
  allowMultipleSelections={false}
  termsetNameOrID={this.props.webPartProperties.termSets.reportType.guid}
  panelTitle={strings.newReportTypeLabel}
  placeholder={strings.newReportTypeDescription}
  label={strings.newReportTypeLabel}
  context={this.props.context}
  onChange={this._onTaxPickerChangeReportTypeProxy}
  isTermSetSelectable={false}   
  required={true}
  hideDeprecatedTags={true}
  hideTagsNotAvailableForTagging={true}
  />`

There seems to have been similar issues in past
https://github.com/pnp/sp-dev-fx-controls-react/issues/506
https://github.com/pnp/sp-dev-fx-controls-react/issues/109

**Comment by manipk** [comment]
Also request this issue to be resolved. Can we know the status on this bug

**Comment by ekapic** [comment]
Hi there! 
I've fixed this issue in PR #1354

**Comment by joelfmrodrigues** [comment]
@kallejar many thanks for reporting the issue.
The PR from @ekapic has now been merged and the fix will be in the beta release shortly. Will also be included in the next main release.
