### ISSUE TITLE
NEW CONTROL - Adaptive Card Host

### ISSUE THREAD

**Issue by fabiofranzini** [pnp/sp-dev-fx-controls-react#1096]
Hello,
I've been working with Adaptive Cards, I really like the new ACE model and in general I like the fact that I can describe the UI of a Web Part in a declarative way and be able to change it at runtime, like a configuration.

After some tests on this, **I created a React control that allows you to render an Adaptive Card as a component**, also using the templating part and the ability to invoke commands defined using the "Action.Execute" model.

I would like to make it a control of this library, what do you think?

**Comment by joelfmrodrigues** [comment]
Hi @fabiofranzini , that would be a great addition in my opinion. I was actually discussing this with @joaojmendes a few days ago as he was considering a similar control. Perhaps we could use this thread as a starting point to avoid duplication of effort and duplicated PRs?

Are you both able to describe your approach so we could all brainstorm the best way to move this forward and hopefully benefit from both solutions?

**Comment by fabiofranzini** [comment]
Hi @joelfmrodrigues,
in recent days I chatted with @joaojmendes about this thing, we can join forces and bring the best of our solutions.

The idea is to have a control that can host Adaptive Cards in both Web Parts and Application Customizer, so that they can be used as a UI.

Also, as I have already implemented in some examples, we could extend the Adaptive Cards 'standard' set of controls with Fluent UI controls or as suggested by @joaojmendes with Microsoft Graph Toolkit controls.

@joaojmendes , we need to set up a call to discuss this :)

**Comment by fabiofranzini** [comment]
Hi @AJIXuMuK, yes and thanks for the suggestion! The purpose is to create a reusable control and extend the common set of controls that come from Adaptive Cards.

**Comment by joaojmendes** [comment]
Hi, all,

I think that we can accept the control of @fabiofranzini and the new improvements will be implemented on that .

Thanks
João

From: Fabio Franzini ***@***.***>
Date: Tuesday, 18 January 2022 at 16:24
To: pnp/sp-dev-fx-controls-react ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-controls-react] NEW CONTROL - Adaptive Card Host (Issue #1096)

Hi @AJIXuMuK<https://github.com/AJIXuMuK>, yes and thanks for the suggestion! The purpose is to create a reusable control and extend the common set of controls that come from Adaptive Cards.

**Comment by fabiofranzini** [comment]
Tomorrow I and @joaojmendes will synchronize and let's see how to collaborate on this component 👍
