### ISSUE TITLE
Wrong documentation - LivePersona

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/sp-dev-fx-controls-react#1104]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Hello,

The page at https://pnp.github.io/sp-dev-fx-controls-react/controls/LivePersona/ is showing an incorrect information on how to use LivePersona control.

import { LivePersona } from "@pnp/spfx-controls-react/lib/LivePersona";

should be replaced with 

import { LivePersona } from "@pnp/spfx-controls-react/lib/controls/LivePersona";

Can you please update the documentation?

Thanks
Miguel

**Comment by AJIXuMuK** [comment]
Dupe of #1069
