### ISSUE TITLE
LivePersona - hover not working

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/sp-dev-fx-controls-react#1105]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

3.5.0

#### Expected / Desired Behavior / Question

Hover should be showing the information of the user as in SharePoint Online and Teams.

#### Observed Behavior

Hover is not working when I mouse over the persona card.

#### Implementation details

import { LivePersona } from "@pnp/spfx-controls-react/lib/controls/LivePersona";
import { ServiceScope } from '@microsoft/sp-core-library';

export default class MyTeamsGraph extends React.Component<IMyTeamsGraphProps, IMyTeamsGraphState> {

    constructor(props, serviceScope: ServiceScope) {
     super(props);
     this._serviceScope = serviceScope;
  }

   public render(): React.ReactElement<IMyTeamsGraphProps> {
     return (
         <LivePersona disableHover={false} serviceScope={this._serviceScope} upn="miguel.isidoro@testsite.onmicrosoft.com"
              template={
                <>
                  <Persona imageUrl='/_layouts/15/userphoto.aspx?size=M&accountname=miguel.isidoro@testsiteonmicrosoft.com' text='Miguel Isidoro' secondaryText='Dev' coinSize={48} />
                </>
              }
              context={this.props.context}
            />
     );
}

Can you help?

Thanks
Miguel

**Comment by miguelisidoro** [comment]
I was able to solve it by passing a null serviceScope. Is this expected?

**Comment by AJIXuMuK** [comment]
@joaojmendes - could you please answer this question?
I don't see `serviceScope` in the docs, so don't know why it's needed if it is populated from the `context`.

**Comment by joaojmendes** [comment]
Hi Alex,

I’m already talked with Miguel and is working.   I will refactor some code… the ServiceScope is not need ,  and you are right we can get the serviceScope from context.

Thanks!
João

From: Alex Terentiev ***@***.***>
Date: Saturday, 29 January 2022 at 17:45
To: pnp/sp-dev-fx-controls-react ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-controls-react] LivePersona - hover not working (Issue #1105)

@joaojmendes<https://github.com/joaojmendes> - could you please answer this question?
I don't see serviceScope in the docs, so don't know why it's needed if it is populated from the context.

**Comment by joaojmendes** [comment]
For compatibility with other controls that use "LivePersona". I remove the context, the control has only  has the serviceScope  property. 

This change only be effect on the next release os controls.

here a sample  how to use. 

<LivePersona upn="joao.j.mendes@spteck.com"
  template={
    <>
      <Persona text="João Mendes" secondaryText="joao.j.mendes@sapteck.com" coinSize={48} />
    </>
  }
 serviceScope={this.context.serviceScope}
/>

**Comment by joelfmrodrigues** [comment]
Hey @miguelisidoro, is this issue now resolved?
The PR from Joao Mendes to remove the property for SPFx context is also now merged
