### ISSUE TITLE
FilePicker "From Link" produces unusable file

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1113]
#### Category
[X ] Bug (Maybe)

#### Expected / Desired Behavior / Question
When user chooses the "From Link" and enters the URL provided by SharePoint like:
`https://ecgmcdev.sharepoint.com/:w:/r/teams/1462.401/DPCDocuments/Test1.docx?d=w8f7d831d619c4aa4a31ac848fb003c51&csf=1&web=1&e=F4OEkl`
Using the blob produced by download to upload to SharePoint, should be a valid file.

#### Observed Behavior
The uploaded office files are not valid office documents.
Word:
"Word found unreadable content in "ATR Test 27.docx". Do you want to recover the contents of this document? If you trust the source of this document, click Yes."
Excel:
"This workbook couldn't be opened because the file format may not be matching with the file extension."
PowerPoint:
"PowerPoint found a problem with content in https://ecgmcdev.sharepoint.com/teams/2840.014/DPCDocuments/test.pptx. PowerPoint can attempt to repair the presentation.
If You trust the source of this presentation, click Repair."

#### Steps to Reproduce
The code snippet to get and upload the file:
```
const fixFileName = files[index].file.fileName.split(`'`).join();
if (files[index].file.fileAbsoluteUrl) setcurrentMessage(`Wait, Downloading ${fixFileName}`);
const blob = await files[index].file.downloadFileContent();
try {
	//chunks and is defaulted to 10485760 bytes (10 MB).Number of Chanks is calculated by dividing the file size by the chunk size.
	const chunks: number = Math.round(blob.size / 10485760);
	let file = await web.getFolderByServerRelativeUrl(`${siteUrl}/DPCDocuments/`).files.addChunked(fixFileName, blob, data => {
		setcurrentMessage(`Wait,  part #${data.blockNumber} of ${chunks}`);
		setPercentComplete(((data.blockNumber / chunks) )); 
	}, false); 
	setcurrentMessage(`File ${fixFileName} uploaded to site`);

```
Should I change the URL coming from SharePoint? Upload these file differently?

Thanks!

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal really sorry for the long delay. Is this still an issue, or were you able to resolve it?

**Comment by Ofer-Gal** [comment]
Works fine in SPFx 1.15.2 and  spfx-controls-react 3.9.0 
thanks
