### ISSUE TITLE
listItemComments ability to filter mentionings

### ISSUE THREAD

**Issue by fonbrauzen** [pnp/sp-dev-fx-controls-react#1114]
#### Observed Behavior
https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/listItemComments/components/AddComment/AddComment.tsx

here  in new comment control on @ => opened list of users for using in the comment as mentions, this is nice, but when you have lots of users on the site will be nice to have filtering (either):
1. @ + letters afterwards, like if want to find user "MyFake, Name" => "@MyF" => suggestions  (same as it is in MS Teams, or here, in GitHub)
2. if leave on @ => suggestions - add search field there to be able to filter them by name 

#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.5.0 ]

**Comment by joelfmrodrigues** [comment]
@fonbrauzen the control should allow you to filter in the way you describe in option 1 (@myname...) As you type, it will keep filtering, the same it does out of the box in a list item comments box.
Can you double-check that you have granted all the required graph permissions for the control to work?
Documentation mentions `People.Read` and `User.ReadBasic.All` but if you still don't get this experience, can you check if you get an error in the console related to insufficient permissions when trying to retrieve users?

**Comment by fonbrauzen** [comment]
sorry, User.ReadBasic.All was missing, now working
