### ISSUE TITLE
sortItems Property in ListView Control not working as expected.

### ISSUE THREAD

**Issue by ShashaShet** [pnp/sp-dev-fx-controls-react#1117]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  3.5.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I am using ListView Control in my spfx solution and have the following fields as IViewField Type which are Name (fileLeaf Ref), Document Type (choice field), Modified By and Modified.  Please refer attached file Image 1 for your reference. I have enabled sorting on all the fields in IViewField. For custom sorting of all fields, i am using sortItems property in ListView Control with code as below in render method

 <ListView
          items={this.state.items}
          viewFields={this.state.viewFields}
          iconFieldName="ServerRelativeUrl"
          compact={false}
          showFilter={true}
          filterPlaceHolder="Search by File Name..." 
          sortItems={this.itemsSorting}
          
          />

As a test, in the itemsSorting function , I am not actually doing any sorting but  just returning this.state.items as a test with code as below 

public itemsSorting = (sortItems:any[],colName:string,descending:boolean):any[] =>
{      
    return this.state.items;   
}

I actually did not do any custom sorting in the above itemsSorting functin and just returned this.state.items as a test.

I was expecting to see the same data as in Image1 file.
 

#### Observed Behavior
What i observed is that when i click on Document Type column, it returned list items but Document Type and Modified By came as blank as per Image 2 attached file. Even if i click on any other columns , i am getting the same behaviour.

#### Steps to Reproduce
1) Render a custom List View with IViewField types as file name, choice field type, Editor Type(Modified By) and Modified
2) Render the List View control which includes above field Types as below
 <ListView
          items={this.state.items}
          viewFields={this.state.viewFields}
          iconFieldName="ServerRelativeUrl"
          compact={false}
          showFilter={true}
          filterPlaceHolder="Search by File Name..." 
          sortItems={this.itemsSorting}
          
          />
3) Please call a function for sortItems and just return the existing items as below
public itemsSorting = (sortItems:any[],colName:string,descending:boolean):any[] =>
{      
    return this.state.items;   
}
4) On workbench.aspx after running Gulp Serve, after the first render, please click on any of the columns and you shall notice that Choice field and Modifed By will be blank like Image2 file

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!
![Image1](https://user-images.githubusercontent.com/99235232/152926004-89752729-3515-49d8-8c89-c692bc3221dc.JPG)
![Image2](https://user-images.githubusercontent.com/99235232/152927301-808a9df2-bc63-4218-8bbc-af0a8831749e.JPG)

**Comment by AJIXuMuK** [comment]
Hi @ShashaShet - I tested this behavior with my data and don't see any issues.
Could you please check if the `items` array in your state is modified between render and sorting?
Just check in debug if the values for fields you're mentioning are there.

**Comment by ShashaShet** [comment]
> Hi @ShashaShet - I tested this behavior with my data and don't see any issues. Could you please check if the `items` array in your state is modified between render and sorting? Just check in debug if the values for fields you're mentioning are there.

HI @AJIXuMuK  - Yes, the item array does get modified in render  via  IViewField. Thanks for Pointing out. I will need to work on that. Thanks or your help.
