### ISSUE TITLE
PeoplePickerField: new property className

### ISSUE THREAD

**Issue by Luksys5** [pnp/sp-dev-fx-controls-react#112]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
 Property className on PeoplePickerField 
#### Observed Behavior
 Property doesn't exist. 
To use className you have to add field to div element container

**Comment by estruyf** [comment]
Hi @Luksys5, the `PeoplePicker`control already has the following properties to specify the class name for the control:

```
/**
 * Class Name for the whole People picker control
 */
peoplePickerWPclassName?:string;
/**
 * Class Name for the People picker control
 */
peoplePickerCntrlclassName?: string;
/**
 * Class Name for the Error Section
 */
errorMessageclassName?: string;
```

**Comment by AJIXuMuK** [comment]
Closed due to lack of activity.

@Luksys5 if you still have issues - please open a new issue
