### ISSUE TITLE
PNP Treeview control is not working as excepted on binding the dynamic data from SP list  

### ISSUE THREAD

**Issue by ManjulaMasthanvali09** [pnp/sp-dev-fx-controls-react#1121]
after adding treearr.push(tree); in Else part the child nodes are binded and Expand and collapse are not working
using Node-version v12.18.0 version

Please suggest on this below is the code

whole code is as below 

```typescript
import * as React from 'react';
import styles from './SpfxPnpTreeview.module.scss';
import { ISpfxPnpTreeviewProps } from './ISpfxPnpTreeviewProps';
import { ISpfxPnpTreeviewState } from './ISpfxPnpTreeviewState';
import { TreeView, ITreeItem, TreeViewSelectionMode, TreeItemActionsDisplayMode } from "@pnp/spfx-controls-react/lib/TreeView";
import { autobind } from 'office-ui-fabric-react/lib/Utilities';

import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

export default class SpfxPnpTreeview extends React.Component<ISpfxPnpTreeviewProps, ISpfxPnpTreeviewState> {
  constructor(props: ISpfxPnpTreeviewProps) {
    super(props);
    sp.setup({
      spfxContext: this.props.context
    });
    this.state = {
      TreeLinks: []
    }
    this._getLinks();
  }

  private async _getLinks() {
    const allItems: any[] = await sp.web.lists.getByTitle("TreeLinks").items.getAll();
    var treearr: ITreeItem[] = [];
    allItems.forEach(function (v, i) {

      if (v["ParentId"] == null) {
        const tree: ITreeItem = {
          key: v.Id,
          label: v["Title"],
          data: v["Link"],
          children: []
        }
        treearr.push(tree);
      }
      else {
        const tree: ITreeItem = {
          key: v.Id,
          label: v["Title"],
          data: v["Link"]
        }
        treearr.push(tree);
        var treecol: Array<ITreeItem> = treearr.filter(function (value) { return value.key == v["ParentId"] })
        if (treecol.length != 0) {
          treecol[0].children.push(tree);
        }
      }

      console.log(v);
    });
    console.log(treearr);
    this.setState({ TreeLinks: treearr });
  }

  public render(): React.ReactElement<ISpfxPnpTreeviewProps> {
    return (
      <div className={styles.spfxPnpTreeview}>
        <TreeView
          items={this.state.TreeLinks}
          defaultExpanded={false}
          selectionMode={TreeViewSelectionMode.None}
          selectChildrenIfParentSelected={true}
          showCheckboxes={true}
          treeItemActionsDisplayMode={TreeItemActionsDisplayMode.Buttons}
          onSelect={this.onTreeItemSelect}
          onExpandCollapse={this.onTreeItemExpandCollapse}
          onRenderItem={this.renderCustomTreeItem} />


      </div>
    );
  }

  private onTreeItemSelect(items: ITreeItem[]) {
    console.log("Items selected: ", items);
  }

  private onTreeItemExpandCollapse(item: ITreeItem, isExpanded: boolean) {
    console.log((isExpanded ? "Item expanded: " : "Item collapsed: ") + item);
  }

  private renderCustomTreeItem(item: ITreeItem): JSX.Element {
    return (
      <span>
        <a href={item.data} target={'_blank'}>
          {item.label}
        </a>
      </span>
    );
  }


}
```

**Comment by ManjulaMasthanvali09** [comment]
after adding treearr.push(tree); in Else part the child nodes are binded and Expand and collapse are not working
using Node-version v12.18.0 version

Please suggest on this below is the code

whole code is as below

import * as React from 'react';
import styles from './SpfxPnpTreeview.module.scss';
import { ISpfxPnpTreeviewProps } from './ISpfxPnpTreeviewProps';
import { ISpfxPnpTreeviewState } from './ISpfxPnpTreeviewState';
import { TreeView, ITreeItem, TreeViewSelectionMode, TreeItemActionsDisplayMode } from "@pnp/spfx-controls-react/lib/TreeView";
import { autobind } from 'office-ui-fabric-react/lib/Utilities';

import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

export default class SpfxPnpTreeview extends React.Component<ISpfxPnpTreeviewProps, ISpfxPnpTreeviewState> {
constructor(props: ISpfxPnpTreeviewProps) {
super(props);
sp.setup({
spfxContext: this.props.context
});
this.state = {
TreeLinks: []
}
this._getLinks();
}

private async _getLinks() {
const allItems: any[] = await sp.web.lists.getByTitle("TreeLinks").items.getAll();
var treearr: ITreeItem[] = [];
allItems.forEach(function (v, i) {

**Comment by AJIXuMuK** [comment]
@ManjulaMasthanvali09 - I don't know what exactly you mean under "not working" or "stopped working", but you're adding the same tree item twice in the tree.
So, you will have duplicating keys. As a result, tree can't differ these nodes.
```typescript
else {
        const tree: ITreeItem = {
          key: v.Id,
          label: v["Title"],
          data: v["Link"]
        }
        // HERE YOU ADD IT FOR THE FIRST TIME
        treearr.push(tree);
        var treecol: Array<ITreeItem> = treearr.filter(function (value) { return value.key == v["ParentId"] })
        if (treecol.length != 0) {
          // HERE YOU ADD IT FOR THE SECOND TIME
          treecol[0].children.push(tree);
        }
      }
```
Ideally, I would "massage" your data first, before constructing the tree.
It seems to me that your implementation may fail if child trees are processed before parent - they will be added to the root instead of the specific parent node.

**Comment by ManjulaMasthanvali09** [comment]
its working the problem was it was not able to read the data from Hyperlink column value

**Comment by ManjulaMasthanvali09** [comment]
on changing the column type it started working .If you can fix for hyper link column that would be great

**Comment by AJIXuMuK** [comment]
@ManjulaMasthanvali09 - it's developer's responsibility to provide data based on contract.

**Comment by ManjulaMasthanvali09** [comment]
Can we change the Treeview Icon from 
![image](https://user-images.githubusercontent.com/70963603/154153099-36a930de-270a-4216-a0bd-f573022a6d3d.png)

to 

plus minus please let us know as shown in below 

![image](https://user-images.githubusercontent.com/70963603/154153324-fa45a9c4-4aa2-4ceb-a725-ccf5f42557f7.png)
