### ISSUE TITLE
LocationPicker width

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-controls-react#1125]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [3.5.0]

#### Expected / Desired Behavior / Question
How can I force the width of the LocationPicker? Or have it fit in its container?
I thought the components were built on Office UI Fabric, but I don't see a style prop.

#### Observed Behavior

Here is what it looks like in my test, I am unable to change the address once it is set:
![image](https://user-images.githubusercontent.com/40323257/153700282-a2aecc36-5cf3-4525-b82e-e451e8c7a75b.png)

Thanks!

**Comment by joelfmrodrigues** [comment]
Hi @PathToSharePoint , I just tested this and there is no option to style.
Would you be interested in submitting a PR? It should be a simple change and similar to the properties available in the People picker control

**Comment by joelfmrodrigues** [comment]
@PathToSharePoint that's great ☺️
I have assigned this issue to you (no pressure), but let me know if you change your mind and I can remove it. It's only to try to prevent more than one person working on it

**Comment by PathToSharePoint** [comment]
I took a closer look, and here is the issue I am trying to address (no pun intended): if the address is too long, it pushes the delete control (cross) outside of the viewport, and it becomes impossible to edit the field.

I think the easiest way to fix the issue is to crop the address and append an ellipsis, like it's done in the list picker. Another way would be to display the address on multiple lines, like in the screenshot below.

It seems that the control is built on the Fluent UI Persona component, let me see what styling it allows.

![image](https://user-images.githubusercontent.com/40323257/159146382-4a67cc14-d88c-4ebf-a38e-297e9ec2f886.png)

**Comment by PathToSharePoint** [comment]
Looking at the code, I found in `LocationPicker.module.scss` a class name `persona`. That should allow me to inject some additional styling, without major refactoring.

**Comment by PathToSharePoint** [comment]
@ravichandran-blog  and @AJIXuMuK, I see that you are the authors of this control.

I plan to remove `width: fit-content;` in `LocationPicker.module.scss` as it seems to be what's causing the issue. Do you see any objection?
```
.pickerItemContainer {
  display: flex;
  border-style: solid;
  border-color: "[theme: themePrimary, default: #0078d7]";
  border-radius: 22px;
  min-width: 16px;
  border-width: 2px;
  width: fit-content;
}
``` 
Once I remove it, the text gets truncated and the control fits in the width. For context, all my screenshots are from the SPFx Property Pane, which has a width of around 300 px.

<img width="300px" src="https://user-images.githubusercontent.com/40323257/159148117-cfa470ac-60f1-466f-aec2-912188922ce2.png" />

**Comment by ravichandran-blog** [comment]
@PathToSharePoint Awesome! go ahead

**Comment by PathToSharePoint** [comment]
@ravichandran-blog PR submitted!

Unrelated to this issue, the only event handler I see is onChange, I didn't see an event handler for clear. If you clear the control, the app will still retain the previous value until you pick a new location. Am I missing something?

**Comment by PathToSharePoint** [comment]
And I just ran into another issue, the location finder gives me a 401 when I run it from the root site tenant.sharepoint.com/_layouts/15/workbench.aspx. I'll need to do more testing before opening an issue but wanted to pass the info.

**Comment by PathToSharePoint** [comment]
I have posted my sample to Github, here is the link in case you want to test:
https://github.com/PathToSharePoint/React-PPP-PnP-Controls

**Comment by joelfmrodrigues** [comment]
@PathToSharePoint awesome updates :)
PS: I was able to recreate the issue on the root site as well.

**Comment by ravichandran-blog** [comment]
Root site issue fixed
https://github.com/pnp/sp-dev-fx-controls-react/pull/1162

**Comment by joelfmrodrigues** [comment]
@ravichandran-blog many thanks @ravichandran-blog , merged

**Comment by PathToSharePoint** [comment]
So the final touch would be to accommodate an `onClear` event handler similar to`onChange`.

Does this look right @ravichandran-blog 
```
  private onIconButtonClick = () => {
    this.setState({ currentMode: Mode.empty, selectedItem: null });
    if (this.props.onClear) {
      this.props.onClear();
    }
  }
```
I prefer to ask as I am more familiar with function components, not so much with `this.setState`.

**Comment by PathToSharePoint** [comment]
On second thoughts, we could reuse the onChange event handler:
```
  private onIconButtonClick = () => {
    this.setState({ currentMode: Mode.empty, selectedItem: null });
    if (this.props.onChange) {
      this.props.onChange(null);
    }
  }
```

**Comment by PathToSharePoint** [comment]
I have submitted a PR with the second option: #1165.
