### ISSUE TITLE
Site tab in FilePicker URL and Library

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1129]
#### Category
[ ?] Bug

#### Version 3.6.0
When I use webAbsoluteUrl={`${window.location.origin}/teams/${dpcRequest.projectNumber}`} it works fine but I want to show the "General" folder under Shared%20Documents (we renamed it "Working Papers")
So I added defaultFolderAbsolutePath={`${window.location.origin}/teams/${dpcRequest.projectNumber}/Shared%20Documents/General`}
But it errors with : status='404'' dist/node_modules/@pnp/spfx-controls-react/lib/services/FileBrowserService.js:148 [FileBrowser._getListItems]: Something went wrong when executing request. Status='[HTTP]:404 - [CorrelationId]:885b20a0-a02b-1000-97bf-669cb5b3b6d9 [Version]:16.0.0.22126' and shows "This folder is empty" (it always have 6 folders)

What is the right way to set the default folder?

Also, I use webAbsoluteUrl with a state variable but the Picker has the URL cashed or something. 
When I change the state to other URL, it does not change the site in the site tab. 
Is there a way I can force the URL change?

Thank you

**Comment by AJIXuMuK** [comment]
@Ofer-Gal - this has been fixed and will be included in the next release

**Comment by Ofer-Gal** [comment]
Thank you much! My users love you :-)
Will I need both `defaultFolderAbsolutePath={${window.location.origin}/teams/${dpcRequest.projectNumber}/Shared%20Documents/General}`
and
`webAbsoluteUrl={${window.location.origin}/teams/${dpcRequest.projectNumber}}` or just the first?

**Comment by AJIXuMuK** [comment]
Yes - you will need both. otherwise the api requests can be screwed up
