### ISSUE TITLE
File Picker Control not working on Dark Theme in SharePoint and Teams

### ISSUE THREAD

**Issue by DJoshi23** [pnp/sp-dev-fx-controls-react#1132]
Hi,

I am using File Picker control in my SPFx solution. But File Picker not working in dark theme mode in SharePoint and In Teams Application as a Tab .

Please find the below screenshot for reference.

![image](https://user-images.githubusercontent.com/86624727/154469582-26ad66ff-e6ce-4db9-b04d-269e8eff0e74.png)

Versions:
 "@pnp/spfx-controls-react": "3.2.1",
SPFx : 1.12.1

Thank you and advance

**Comment by joelfmrodrigues** [comment]
Hi @DJoshi23, many thanks for reporting this issue. Would you be interested in submitting a PR?
If so, please keep in mind that the solution has been upgraded to SPFx 1.14.0, which introduces some changes to themes
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.14#web-part-lifecycle-method-for-theme-changes

**Comment by BollietMZK** [comment]
Hi,
This problem is still present and the FilePicker component does not take into account the SharePoint theme.
Do you know if there are plans to fix this behavior in the roadmap?

**Comment by nbelyh** [comment]
Created PR to fix the issue
