### ISSUE TITLE
Richtext control, can not undo ordered lists 

### ISSUE THREAD

**Issue by tobysroof** [pnp/sp-dev-fx-controls-react#1135]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  3.6.0       ]

#### Expected / Desired Behavior / Question
When using the RichText Component, when selecting a ordered (numbered) list, and then clicking the ordered list control, we expect the numbered list to be unmade. (this works for unordered lists)

#### Observed Behavior
When selecting a numbered list in a richtext component, and then clicking the numbered list control, the numbered list is unaffected.

#### Steps to Reproduce
Using the richtext control. Add some lines and then make them into a ordered list by selecting the text and clicking the ordered list option. Click the same option again to "unmake" the list. Note that nothing happens.

Do the same thing with a unordered list and note that the unordered list is "unmade" correctly

**Comment by joelfmrodrigues** [comment]
Hi @tobysroof  many thanks for reporting the issue. Would you be interested in trying to fix it and submit a pull request?

**Comment by Ateina** [comment]
Hi @joelfmrodrigues!
I think I found the reason for this bug, I can create a PR for it
could you assign this issue to me?

**Comment by michaelmaillot** [comment]
Hi @Ateina,

Sure, it's all yours!

**Comment by Ateina** [comment]
@michaelmaillot Thank you!

**Comment by michaelmaillot** [comment]
Linked PR has been merged, the fix should be available in the next beta release.
