### ISSUE TITLE
Package version 1.21.2 not available

### ISSUE THREAD

**Issue by Whiteshark57** [pnp/sp-dev-fx-controls-react#1136]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Current version 1.21.1 trying to update to version 1.21.2

#### Expected / Desired Behavior / Question
Trying to execute command npm install @pnp/spfx-controls-react@1.21.2 --save I'm supposed to be able to update the 1.21.1 version currently used.
Unfortunately, I received an error saying that "No matching version found for @pnp/spfx-controls-react@1.21.2".
Running command npm view @pnp/spfx-controls-react versions, the 1.21.2 version is indeed not present.

#### Steps to Reproduce
Running the npm install @pnp/spfx-controls-react@1.21.2 --save command from the terminal.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/74719323/155291874-caf71384-4661-42d7-9ab6-8983a3b91f51.png">

Runnng the npm view @pnp/spfx-controls-react versions command.
<img width="89" alt="image" src="https://user-images.githubusercontent.com/74719323/155292097-eeb40990-a46c-407e-8a3e-bae942aeb4d2.png">

Thanks for your help

**Comment by joelfmrodrigues** [comment]
Hi @Whiteshark57 , I can confirm that 1.21.2 is not available.

@AJIXuMuK could this be related to the issues we had with GitHub Actions recently?
Found this failed action on the v1 branch from 12 days ago
https://github.com/pnp/sp-dev-fx-controls-react/actions?query=branch%3Av1

**Comment by AJIXuMuK** [comment]
There are 2 things in there:
- GH actions
- some of the used indirect dependencies can't be installed anymore

I will take a look there again to see if we can actually do a release.

**Comment by Whiteshark57** [comment]
Hi @AJIXuMuK,
Thanks for your reply. Hope you'll succeed resolving those issue.
Indeed, if everything is fine, I plan to implement the Modern Taxonomy Picker in this version.

**Comment by kodofix** [comment]
Hello,

Any updates on that? Is still missing on NPM

**Comment by Whiteshark57** [comment]
Hi @AJIXuMuK,
Do you have any update on this ticket?

**Comment by AJIXuMuK** [comment]
Hi @Whiteshark57 - I was finally able to fix all build issues.
Version 1.21.3 is available on nom!

**Comment by Whiteshark57** [comment]
Hi @AJIXuMuK, Thank you it works like a charm.
See you for the Modern Taxonomy Picker integration. ;-)
