### ISSUE TITLE
SPHelper -> Cannot read properties of undefined (reading 'getByTitle'))

### ISSUE THREAD

**Issue by yungfu** [pnp/sp-dev-fx-controls-react#1140]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.6.0 ]

#### Expected / Desired Behavior / Question
When FieldRendererHelper.getFieldRenderer try to get a note(multiline) type field render, SPHelper.ts will throw **Cannot read properties of undefined(reading 'getByTitle')** error. 
There is a similar bug [#1025](https://github.com/pnp/sp-dev-fx-controls-react/issues/1025).  

Thanks!

**Comment by joelfmrodrigues** [comment]
@yungfu Thanks for reporting the issue and it should now be fixed. Can you test with the latest beta version?
