### ISSUE TITLE
Support for SPFx 1.14.0

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/sp-dev-fx-controls-react#1141]
[X ] Enhancement

[ ] Bug

[ ] Question

When will SPFx 1.14 be supported? I am using version 3.6.0 and some controls are not working properly with SPFx 1.14. One of the controls is LivePersona.

Thanks
Miguel

**Comment by joelfmrodrigues** [comment]
Hey @miguelisidoro 
This is something we have in mind and have discussed already, but it's not yet in beta version.

**Comment by miguelisidoro** [comment]
Thanks @joelfmrodrigues. Do you have an estimation on when a new release will be available with support for SPFx 1.14?
It would also be great to remove the dependency on Office UI Fabric and upgrade to Fluent UI.

**Comment by AJIXuMuK** [comment]
@miguelisidoro - Fluent UI is not something that is provisioned by SPFx.
PnP Controls is based on the same set of dependencies as SPFx.

**Comment by miguelisidoro** [comment]
@AJIXuMuK  thanks. If you take a look at https://github.com/pnp/sp-dev-fx-controls-react/blob/master/package.json, you see that there is a dependency on Office UI Fabric 

 "office-ui-fabric-react": "7.174.1",

What I am suggesting is to remove this dependency and make all controls use fluent ui instead and if possible the latest version of fluent ui.

Do you think this is possible?

Thanks
Miguel

**Comment by miguelisidoro** [comment]
Hello,

Sorry to be questioning again:

- Do you have an estimation on when a new release will be available with support for SPFx 1.14?
- About migration to fluent UI: If you take a look at https://github.com/pnp/sp-dev-fx-controls-react/blob/master/package.json, you see that there is a dependency on Office UI Fabric

"office-ui-fabric-react": "7.174.1",

What I am suggesting is to remove this dependency and make all controls use fluent ui instead and if possible the latest version of fluent ui.

Do you think this is possible?

Thanks

**Comment by joelfmrodrigues** [comment]
@miguelisidoro try the latest beta version 🙂
@AJIXuMuK upgraded the dev branch yesterday

**Comment by miguelisidoro** [comment]
Hello @joelfmrodrigues, I tried the latest beta version and the LivePersona control is still not working with SPFx 1.14. 
Can you confirm if this control was already tested with SPFx 1.14?

Thanks

**Comment by miguelisidoro** [comment]
Hello @joelfmrodrigues, I tried the version 3.7.0 and the LivePersona control is still not working with SPFx 1.14.
I deleted node_modules and executed npm install again.
Can you confirm if this control was already tested with SPFx 1.14?

About upgrading dependencies from Office UI Fabric to Fluent UI when do you think this will be possible?

Thanks

**Comment by joelfmrodrigues** [comment]
Hey @miguelisidoro 
Sorry for the lack of communication, really struggling to keep on top of everything that is going on

I am not sure if Live persona was explicitly tested with 1.14, so if it's not working for you it may be an issue - could you please open a new one and provide details?

Regarding Fluent UI, as Alex mentioned, the idea is to keep the same dependency that is used by default by SPFx. If Microsoft updates default dependencies to Fluent UI, we could look into doing the same. Hope this makes sense.

**Comment by miguelisidoro** [comment]
Hello @joelfmrodrigues it is working well. Thanks
