### ISSUE TITLE
Add SPFx theme & context property to the AdaptiveCardHost control

### ISSUE THREAD

**Issue by fabiofranzini** [pnp/sp-dev-fx-controls-react#1145]
#### Category
[X] Enhancement
[-] Bug
[-] Question

#### Version
Please specify what version of the library you are using: [3.6.0]

#### Expected
Speaking with @joaojmendes about the possible evolutions of the control, and specifically in the creation of a library of additional elements (using MGT for example), it is necessary to pass the "Theme" object and values that come from the "Context" of SPFx, so to be used with the Adaptive Card "templating" syntax and therefore to be passed to the new elements.

The idea is to directly inject these values into the "Data" object which is then used to do the "binding" in the rendering phase.

An example could be to pass the colors of the theme applied to a template to discriminate which image to load (understand if the theme is dark or not), etc., etc.

Or, thanks to the context of SPFx, you can have information on the site, current user, etc., etc. and use that information as properties in the "data" object

**Comment by joelfmrodrigues** [comment]
@fabiofranzini are you aiming to create a PR for this? If so, I can assign this item to you

**Comment by fabiofranzini** [comment]
@joelfmrodrigues yes! I'll create the PR in 30 mins 😀

**Comment by fabiofranzini** [comment]
@joelfmrodrigues and @joaojmendes done 😀
