### ISSUE TITLE
Text formatting Font size property does not update

### ISSUE THREAD

**Issue by mhammadsiddiqui** [pnp/sp-dev-fx-controls-react#1151]
#### Category
[ ] Enhancement

[ x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.5.0 ]

#### Expected / Desired Behavior / Question

If I update the font size of text through extended menu then Font size property pane value should also be changed. 

#### Observed Behavior
Font size of text is changed, but property pane value remains unchanged.

#### Steps to Reproduce
Add text in text editor. select a part of the text and chnage the font size through extended menu. 

![image](https://user-images.githubusercontent.com/42937945/158182983-ea21c996-0bb3-49fc-8222-aead70ab5a87.png)

Thanks!

**Comment by joelfmrodrigues** [comment]
@mhammadsiddiqui many thanks for reporting this issue. It's now fixed in the latest beta release and will be included in the next release.
