### ISSUE TITLE
Different background color to even and odd rows in ListView

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1153]
#### Category
[? ] Enhancement
[? ] Question

#### Version

Please specify what version of the library you are using: [    3.6.0     ]

#### Expected / Desired Behavior / Question
Is there a way to Style even and odd rows in ListView with different color?

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal thanks for the suggestion.
@milanholemans more than happy to get a PR with the change :) Any improvements are welcome.
Please just keep in mind to make the property optional and disabled by default, so anyone upgrading versions would not experience a different behaviour by default.

**Comment by Ofer-Gal** [comment]
@AJIXuMuK
What will the property be? or How would I get it to work?

**Comment by milanholemans** [comment]
> As far as I know I'm afraid the answer is no. Although this seems relatively easy to implement by exposing an extra property called 'onRenderRow' used in this [example](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemrows). I can add this, but it's not up to me to decide whether or not to add it.

@Ofer-Gal you can use the same approach as in the example linked above.

**Comment by SharePointReady** [comment]
Hi @milanholemans,

The example given at [example](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemrows) is not working for listView control. It is giving below error. Can you please check?

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/37682980/3f9c9297-8872-4078-9642-04378c80c1ad)

**Comment by milanholemans** [comment]
Hi @SharePointReady, I think the issue is that an SPFx web part and PnP SPfx controls are targeting a different version of fluent UI. An SPFx web part uses version `^8.106.4`, SPFx controls use `8.106.4` strictly.
I suggest that you run `npm i @fluentui/react@8.106.4 -SE` so you're always on the same version of Fluent UI.
