### ISSUE TITLE
react ListView component:  Can you show multi-select columns in a view?

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#1158]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Version
Please specify what version of the library you are using: [    Latest     ]

#### Expected / Desired Behavior / Question
I would like to be able to show a multi-select column in a view.

#### Observed Behavior
I can't find anything in docs indicating how to do this outside of first convert all the values into a single string.

#### Steps to Reproduce
Just a question since I can't find anything in docs about if it is possible or not.

**Comment by mikezimm** [comment]
Just a small update... I did manage to engineer a temporary solution in my web part by:

1. Checking all columns to see if they value is 'an array' and if it is, 
2. Then if they are an array....
3. 'Join' all the values in the array with a semi-colon
4. Create a new property on the item called 'OldColumNameMultiValue'.
5. Add the joined string to that new property.
6. Then update the IView column names by appending 'MultiValue' to any that were detected as 'Multi-select'

It works, but not sure if there is a better way.

Thanks again!

**Comment by joelfmrodrigues** [comment]
Hi @mikezimm, sorry for the late reply
You should be able to do this using the render method for the field (IViewField) as it overrides how the field is rendered. Inside this method, you can do anything, like parsing the multiple values and rendering them. You can even use a custom component to display the info (for example from Fluent UI).
Does this answer your question?
