### ISSUE TITLE
react list view - is there a way to not make link if the value in linkPropertyName is empty or ''

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#1171]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version
"@pnp/spfx-controls-react": "2.0.0",
I am on an older version of spfx so I don't want to try to upgrade the version at this point.

#### Expected / Desired Behavior / Question
I have a view where I'm passing in the 'linkPropertyName' property which is a calculated field which builds up a url.
However, in some cases, the url string will be empty.

I am wondering if there's a simple way (outside of a custom render function), that the list component does not turn it into a link unless it has a valid value (starts with http... or /sites/).

Or does a future version already address this?

#### Observed Behavior

At least in this version, it shows as a link and just goes to the current page when you click on it.

#### Steps to Reproduce

  {
    "name": "LinkTitle",
    "displayName": "Name",
    "minWidth": 150,
    "maxWidth": 300,
    "linkPropertyName": "CalculatedLinkColumn"
  },

Thanks for any tips :)

**Comment by joelfmrodrigues** [comment]
@mikezimm sorry for the late reply to this. Based on your comments to https://github.com/mikezimm/drilldown7/issues/114, can this be closed, or is it still an issue?

**Comment by mikezimm** [comment]
@joelfmrodrigues ,
To be honest, it has been a while and I think I just added a band-aid to my component because I had to make it obvious to the end user not to click the link.  See attached...

I think it probably would be pretty simple logic to check if the url part of the item has a value before making it a link, but I do not know where to check in the code.

If someone can point me to the file / approximate line where the ListView creates that link, I'd be  happy to see what I can do and maybe post a commit to update it.

## Just to explain a use case why I would ever have a label text without a link....
We might have a simple text column with an Incident Number or Drawing in our system.
There would be a calculated column which would build up a link directly to this item.
However, the calculated column might have logic to only create the link if a status field indicates there should be a link.
So that is why we might have text to display in a column but not have a url.

![image](https://user-images.githubusercontent.com/49648086/201823492-720d2a21-e4a2-4d4f-a6b6-52b2e60bc982.png)

**Comment by joelfmrodrigues** [comment]
@mikezimm I think in this case you could use the render property to override the render method on that column and have your own logic. 
Something like: if condition is true, render a link, if not, render something else or just an empty element.

https://pnp.github.io/sp-dev-fx-controls-react/controls/ListView/
This is what I am referring to:
![image](https://user-images.githubusercontent.com/19577724/202297099-03731355-2023-435a-b8cc-92ea4702532f.png)

**Comment by mikezimm** [comment]
@joelfmrodrigues ,
The issue is that I use this control in a web part where the user can define the fields... ie not hard coded.
So I would have to do extra validation every time I use a link column.  It would be more robust if it was built in to the react component.

@AJIXuMuK and @milanholemans , Since you both have made updates to this component, I was wondering if you might be able to assist?

I did some testing myself by editing the raw ListView.js and this logic seemed to work.  It's not a 100% guarantee the link is good but at least it checks for known url patterns.  I'm sure there is a simpler/more elegant regex out there to do it but these few lines do the trick.  Unfortunately I do not know how the rest of the component works so I do not know if it would impact anything else.

I will propose an update directly in the code but I don't know how to compile and test to verify it won't impact anything else.

## Tested modification to raw code in @pnp\spfx-controls-react\lib\controls\listView\ListView.js
```javascript
    ListView.prototype._fieldRender = function (field) {
        // Check if a render function is specified
        if (field.render) {
            return field.render;
        }
        // Check if the URL property is specified
        if (field.linkPropertyName) {
            return function (item, index, column) {

              // Testing to see if Url value is valid... has a value, is a string, and either starts with http or /sites/
              const isValid = item[field.linkPropertyName] && typeof item[field.linkPropertyName] === "string" &&
                ( item[field.linkPropertyName].indexOf("/sites/") === 0 || item[field.linkPropertyName].indexOf("http") === 0 ) ? true : false;

              // Return element as a link if the Url passes simple validation.  Else just return the displayed value as normal span
              return isValid ? React.createElement("a", { href: item[field.linkPropertyName] }, item[column.fieldName]) :
                React.createElement("span", null , item[column.fieldName])
                ;
            };
        }
    };
```


## This would be the actual jsx (I think)

```typescript
// Check if the URL property is specified
if (field.linkPropertyName) {
  return (item: any, index?: number, column?: IColumn) => { // eslint-disable-line @typescript-eslint/no-explicit-any
     // Testing to see if Url value is valid... has a value, is a string, and either starts with http or /sites/
     const isValid = item[field.linkPropertyName] && typeof item[field.linkPropertyName] === "string" &&
                ( item[field.linkPropertyName].indexOf("/sites/") === 0 || item[field.linkPropertyName].indexOf("http") === 0 ) ? true : false;

    // Return element as a link if the Url passes simple validation.  Else just return the displayed value as normal span
    return isValid === true ? <a href={item[field.linkPropertyName]}>{item[column.fieldName]}</a> :
      <span>{item[column.fieldName]}</span>;
  };
}
```

**Comment by joelfmrodrigues** [comment]
@mikezimm thanks for the PR, we have some delay in reviewing PRs at the moment, but we will for sure look at it as soon as possible.

As for testing the controls solution, this is an SPFx solution, so overall is likely not different from your solutions. You can clone, npm install, and run with `gulp serve`. There is a test web part in the project that contains most of the controls for testing, just add it to the SharePoint workbench page :)
If you want to test the changes in your own project, you can use [npm link](https://docs.npmjs.com/cli/v6/commands/npm-link) to link the solutions locally. Your solution will load the PnP controls from the local folder instead of installed from npm (there are lots of articles online on how to use npm link)

Hope this helped

**Comment by joelfmrodrigues** [comment]
Closing as related PR was closed as no response was provided for a long period. Can reopen if required
