### ISSUE TITLE
[ModernTaxonomyPicker] Display the full path of a term

### ISSUE THREAD

**Issue by AdiuTankT72** [pnp/sp-dev-fx-controls-react#1172]
#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.5.0]

#### Expected / Desired Behavior / Question
In ModernTaxonomyPicker, It would be great to have the possibility to display the whole path to the term as in the OOTB control. Currently, it is possible just to see the label of the term. In the SharePoint, it is possible to display also the full path of a term, eg. TermA:ChildTermB:ChildTermC

**Comment by joelfmrodrigues** [comment]
@AdiuTankT72 thanks for the suggestion. Would you be interested in submitting a PR with the change?
This could be something simple like a new property to control what is the format rendered.

**Comment by ekapic** [comment]
Hello folks! 
I would like to tackle this improvement. As far as I see it, it's about adding a property into the Modern Taxonomy Picker control that toggles term labels to include all the parents' labels joined with ":" (like OOB SP UI). 

Any performance best practices? This would involve getting parent terms for all the items, recursively. Should the result be memoized?

**Comment by AJIXuMuK** [comment]
@AdiuTankT72 - this will be included in the next release

**Comment by AdiuTankT72** [comment]
@AJIXuMuK Wow thank you very much! For sure it will be useful in my feature projects.

**Comment by joelfmrodrigues** [comment]
New release just published, closing
