### ISSUE TITLE
Peoplepicker: search users in nested security groups

### ISSUE THREAD

**Issue by RicoNL** [pnp/sp-dev-fx-controls-react#1173]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.7.0 ]

#### Expected / Desired Behavior / Question
Make users from nested Security groups searchable when the groupId is specified in the PeoplePicker.

Changing 'members' to 'transitiveMembers' in PeopleSearchService.ts | searchTenant should do the trick. Ideally implement a switch to choose between members and transitiveMembers

![image](https://user-images.githubusercontent.com/35333175/160586848-bbf2cd02-56d7-438f-b047-97e76b462e7d.png)

#### Observed Behavior
 Currently only users directly added to the group are returned when searched for. Users added to a nested group are not found.

#### Steps to Reproduce
- Create a webpart with peoplepicker control
- Specify a groupid-string from a security group with both users fromnested security group and users directly added to the group. Only users directly added to the AD group are returned when searched for.

**Comment by AJIXuMuK** [comment]
Thank you @RicoNL for reporting and implementing this one!
