### ISSUE TITLE
Dynamic form not working on list validation setting

### ISSUE THREAD

**Issue by bansalanshuman** [pnp/sp-dev-fx-controls-react#1174]
#### Category
[] Enhancement

[X ] Bug

[X] Question

#### Version

Latest

#### Expected / Desired Behavior / Question
I have column in my list of type number where I want to capture % value,  and on this column I have configured a max value of 100. This works fine on List form but with Dynamic form, this validation fails and the user can enter any value.

Also I wanted to understand how can I use the methods onBeforeSubmit and onSubmitError, in either methods I am not able access ItemData

#### Observed Behavior
The user can enter any value even greater than 100

#### Steps to Reproduce
Create list list column of type number and set max value to 100
Render the list form via, PnP Dynamic form
Add any value to this column even greater than 100, the form submits the data.

Thanks!

**Comment by joelfmrodrigues** [comment]
@bansalanshuman thanks for raising this. Documentation for onBeforeSubmit was recently updated and I hope it's now easier to understand: https://pnp.github.io/sp-dev-fx-controls-react/controls/DynamicForm/

@IRRDC many thanks for the example

**Comment by joelfmrodrigues** [comment]
@bansalanshuman regarding the max value validation, I don't think that the control currently supports this. Would you be interested in helping implementing it and submit a pull request?

**Comment by bansalanshuman** [comment]
Hello @joelfmrodrigues, I have never done this before but I will be super interested in working on this. I will try to implement this and submit a pull request.

**Comment by mtburkett** [comment]
> @bansalanshuman thanks for raising this. Documentation for onBeforeSubmit was recently updated and I hope it's now easier to understand: https://pnp.github.io/sp-dev-fx-controls-react/controls/DynamicForm/
> 
> @IRRDC many thanks for the example

I do not find the documentation easy to understand at all. Could we see an example of doing a simple thing like sending the listItem object to another function to do something with it?

**Comment by michaelmaillot** [comment]
Hi @bansalanshuman,

Latest version (3.15.0) handles correctly both `MaximumValue` & `MinimumValue` for percent number fields.

Just be sure that you specify "1" (and not "100") as max value for the field.

Can you confirm on your side?

**Comment by michaelmaillot** [comment]
Hi @mtburkett,

FYI the `listItemData` param declared in the `onBeforeSubmit` prop is type of `any` because it depends of refered list structure. You can define an interface instead of `any` or specify the property you want to get (ex.: `listItemData.Title`). Moreover, in the case of `onBeforeSubmit`, you'll have all the fields for a new item and only modified ones for an existing item (feel free to put a `console.log(listItemData)` in the `onBeforeSubmit` method for example, to see what's inside).

Of course, you can send this object to another function during the process, like this (beware that this is really simple example):

```tsx
public render(): React.ReactElement<IDynamicFormBoilerplateProps> {
    return (
      <div>
        <DynamicForm
          context={this.props.context as any}
          listId={"LIST-GUID"}
          listItemId={2}
          onBeforeSubmit={this._formBeforeSubmit} />
      </div>
    );
  }

  private _formBeforeSubmit = async (listItemData: any): Promise<boolean> => {
    return this._checkFields(listItemData);    
  }

  private _checkFields = (listItemData: any): boolean => {
    if (listItemData.Title === "") {
      // Do something that will display an error message to the user

      return false;
    }

    return true;
  }
```

Does this sound clearer to you?

**Comment by joelfmrodrigues** [comment]
@bansalanshuman does the info provided by Michael answer your question?

**Comment by mtburkett** [comment]
Hi @michaelmaillot - thanks for the example. I eventually figured this out on my own, but I'm sure the example will be useful to everyone moving forward.
