### ISSUE TITLE
FilePicker still needs webAbsoluteUrl for sites not in the context. And Help with "From a link"

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1176]
#### Category
[ x] Documentation
[x ] Question
#### Version  [ 3.7.2      ]

The documentation states that "webAbsoluteUrl" is not needed but I discovered that it is necessary if it is other than the path of the current context. 
If it is using a state variable, make sure it is not null like:
```
{ (webAbsoluteUrl) && <FilePicker buttonLabel={'Upload More Files'}                 //buttonIcon="FileImage" dpcRequest
                                webAbsoluteUrl={webAbsoluteUrl}
                                defaultFolderAbsolutePath={webAbsoluteUrl + '/Shared%20Documents/General'} ...
```
Please fix the documentation

One more Question:

I have hard time downloading from the `IFilePickerResult[]` When using "From a link" 
The `file.fileAbsoluteUrl` is like this:
`https://ecgmcdev.sharepoint.com/:w:/r/teams/ecg-it/Shared%20Documents/Be%20Epic%20-%20Manager%27s%20Preparation%27s%20Guide%20and%20Checklist.docx?d=wa43df85995eb4d60ad98a3f80e986ecc&csf=1&web=1&e=biRol4`
So how can I get the blob with PnPjs 3.1.0?

Thank you!

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal regarding the reference to downloading the content from files, was this the same issue as raised previously here: https://github.com/pnp/sp-dev-fx-controls-react/issues/1113 ?

**Comment by Ofer-Gal** [comment]
No it was a different issue that was fixed in later versions.
