### ISSUE TITLE
FilePicker, Tiles View, Unable to Select Images from Site Tab

### ISSUE THREAD

**Issue by Arknev** [pnp/sp-dev-fx-controls-react#1177]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.7.2]

#### Expected / Desired Behavior / Question
To be able to select images while in Tiles View for Site and Your organisation tabs.

#### Observed Behavior
In some cases, the tiles can be clicked but do not show as being selected and the "Open" button remains disabled.

#### Steps to Reproduce
1. Add the FilePicker to TSX file in WebPart.
2. Set minimum configuration to render control.
3. Run serve or deploy to site with images
4. Open picker and Recent tab should be default
5. Switch to Site tab and navigate to location with images
6. ***IF Tiles is the default view when opening the tab, the images cannot be selected.
7. ***IF Tiles is not the default view, switch to tiles view, change to the Recent tab, then return to Site tab. The images cannot be selected.
8. Switching to list then back to tiles while in the Site tab will allow the images to be selectable again.
9. Future uses of the control when Tiles is the default view, images in the Site tab cannot be selected. This appears to be the same for the Your organisation tab as well.

**Comment by josemonkey** [comment]
Wondering if there's any update on this? Seeing the same behavior. Cannot select files in "tiles" view.

**Comment by josemonkey** [comment]
I'm actually wondering if something went wrong in the last commit. (add39f8724e09d5acf60b3b95376670f9b77fead) When the component was updated to allow multiple selections, the logic in SiteFilePickerTab.tsx (and elsewhere) that is trying to decide whether to enable the primary button once you make a selection has changed:

`           <PrimaryButton
              disabled={this.state.filePickerResults && !this.state.filePickerResults.length}
              onClick={() => this._handleSave()} className={styles.actionButton}>{strings.OpenButtonLabel}</PrimaryButton>`

The logic is likely trying to check whether 1) the filePickerResults is defined and 2) that it has items. (Before it was just checking if filePickerResult was defined.) Could that be related?

**Comment by josemonkey** [comment]
Sorry if the comment above about PrimaryButton is unhelpful or on the wrong track. Just FYI, I downloaded the sp-dev-fx-controls-react code to try to debug, and it looks as if when **TilesList** is calling **FileBrowser._itemSelectionChanged** the selection object (i.e., this._selection) doesn't appear to be set for some reason. (When DetailsList invokes that same callback, this._selection is set properly and everything works well.)

**Comment by Arknev** [comment]
> Sorry if the comment above about PrimaryButton is unhelpful or on the wrong track. Just FYI, I downloaded the sp-dev-fx-controls-react code to try to debug, and it looks as if when **TilesList** is calling **FileBrowser._itemSelectionChanged** the selection object (i.e., this._selection) doesn't appear to be set for some reason. (When DetailsList invokes that same callback, this._selection is set properly and everything works well.)

I was just about to upgrade my solution to the most recent versions. Are you saying that the issue persists in 1.15?

**Comment by josemonkey** [comment]
> I was just about to upgrade my solution to the most recent versions. Are you saying that the issue persists?

Yes, it is present in 3.9.0 as far as I can tell.

**Comment by josemonkey** [comment]
Just FYI, I tried version **3.10.0** today, and I still have this problem. (I was hopeful, because I see that **FileBrowser.tsx** appears to have changed in the commit five days ago that @AJIXuMuK did - 256d4a7592913ca97658f3d45bb6bb1f9cb51490)

**Comment by AJIXuMuK** [comment]
@josemonkey - my changes were related to upgrading the solution to SPFx 1.15.2. 
But thanks for bumping this up - we'll take a look

**Comment by josemonkey** [comment]
> @josemonkey - my changes were related to upgrading the solution to SPFx 1.15.2. But thanks for bumping this up - we'll take a look

Hi, just wondering if there's any update on this? Thanks!

**Comment by josemonkey** [comment]
> @josemonkey - my changes were related to upgrading the solution to SPFx 1.15.2. But thanks for bumping this up - we'll take a look

Hi, @AJIXuMuK - Just curious if you or anyone else has been looking into this? Thanks!

**Comment by josemonkey** [comment]
@Arknev I'll take a look soon and reply here. Might not be until Monday, though.

**Comment by Arknev** [comment]
@josemonkey any luck on using the most recent version of the FilePicker component?

**Comment by josemonkey** [comment]
> @josemonkey any luck using the most recent version of the FilePicker component?

I just tried 3.12.0 and it might be working correctly? I haven't tested extensively, though. Might want to check it out. 

Sorry for the late response.

**Comment by josemonkey** [comment]
Something's definitely weird now, @Arknev - I just tried with a project that I didn't even update or rebuild, and the FilePicker control is behaving strangely. Seems to be loading the same contents repeatedly, and it eventually got throttled just like you said.

I don't get why the component that I haven't rebuilt is doing that, though - makes me feel like something else changed with the APIs that are being invoked.

**Comment by Arknev** [comment]
> Something's definitely weird now, @Arknev - I just tried with a project that I didn't even update or rebuild, and the FilePicker control is behaving strangely. Seems to be loading the same contents repeatedly, and it eventually got throttled just like you said.
> 
> I don't get why the component that I haven't rebuilt is doing that, though - makes me feel like something else changed with the APIs that are being invoked.

Thanks for take a look. I might have to move this to a new issue. Can't seem to get any traction.

**Comment by ag0059985** [comment]
Hello All, has it been fixed in the latest version, because I am still facing the same issue.
thanks
