### ISSUE TITLE
Treeview collapses on selection of a child node

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-controls-react#1182]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.7.2]

#### Expected / Desired Behavior / Question
When a child node gets selected the expand/collapse state of the tree nodes should not change.

#### Observed Behavior
The tree collapses to the root node of the selected child node.

#### Steps to Reproduce
After noticing the problem in my solution I created a new SPFx 1.14.0 webpart via yeoman, added @pnp/spfx-controls-react and the sample code from https://pnp.github.io/sp-dev-fx-controls-react/controls/TreeView/. Clicking on a child node will collapse to the topmost parent node.

**Comment by AJIXuMuK** [comment]
Thank you @IRRDC for reporting this one!
The fix has been done and will be included in the next release.
