### ISSUE TITLE
defaultSelectedUsers for Person field on Dynamic Form

### ISSUE THREAD

**Issue by whoisdob** [pnp/sp-dev-fx-controls-react#1186]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[ X ] Question

#### Version

Please specify what version of the library you are using: [ 3.7.2 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

Hello, 

The [DynamicForm Component](https://pnp.github.io/sp-dev-fx-controls-react/controls/DynamicForm/) is great and saves me the trouble of manually building a new/edit form for my project. I have a requirement to populate a person field when the DynamicForm is being used as a new item form (no item id supplied). I see the [PeoplePicker Component](https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/) has a property of defaultSelectedUsers to achieve this on a field level. I would like to do the same for a person column while using the DynamicForm Component.

Is their a supported way of achieving this? 

Best, Dan

**Comment by IRRDC** [comment]
It would be nice to generalize this and be able to not only edit values in onSubmitted after the user has finished filling the form but to set initial values too.
