### ISSUE TITLE
filePicker null Properties

### ISSUE THREAD

**Issue by walleford** [pnp/sp-dev-fx-controls-react#1189]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [   3.7.2      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

Hello, I am trying to use the property pane file picker for a grid layout I have built, but when I reference the filePicker control in my .tsx file, I get the following error:
ERROR:
Cannot read properties of null (reading 'fileNameWithoutExtension')

CALL STACK:
TypeError: Cannot read properties of null (reading 'fileNameWithoutExtension')
    at GridLayout.Q8Iu.GridLayout.render (https://localhost:4321/dist/grid-layout-web-part.js:35118:222)
    at Bo (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:75856)
    at No (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:75651)
    at ys (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:111120)
    at pc (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:102601)
    at uc (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:102526)
    at ac (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:99556)
    at Zs (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:96324)
    at Bc (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:117533)
    at https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_2500f5e303c8340c021add7043120a34.js:69:118737

I have gone through and made sure everything is imported and exported correctly, and I know it even runs on a coworkers machine. Just wanted to see if someone would be able to point me in the right direction to find the issue causing this. 

Thanks!

**Comment by PeterWCox** [comment]
Hi Walleford,

I've used this control without issue before - what code are you using for the onSave and onChange event handlers?

**Comment by walleford** [comment]
@PeterWCox Sorry for the late response. This is what I use currently, and it works only with uploading from Site assets. I sort of gave up on the uploading from local computer, and just made it to where they could only upload if the picture was already in the site assets. `onChange: (filePickerResult: IFilePickerResult[]) => {
                                          console.log('changing....', field);
                                          onUpdate(field.id, filePickerResult[0]);

                                          this.context.propertyPane.refresh();
                                          this.render();
                                      },
                                      onSave:
                                          async (filePickerResult: IFilePickerResult[]) => {
                                              for (const filePicked of filePickerResult) {
                                                  if (filePicked.fileAbsoluteUrl == null) {
                                                      filePicked.downloadFileContent().then(async r => {
                                                          let fileresult = await this.sp.web.getFolderByServerRelativePath(`${this.context.pageContext.site.serverRelativeUrl}/SiteAssets/SitePages`).files.addChunked(filePicked.fileName, r);
                                                          this.properties.gridItems[0].filePickerResult = filePicked;
                                                          this.properties.gridItems[0].filePickerResult.fileAbsoluteUrl = `${this.context.pageContext.site.absoluteUrl}/SiteAssets/SitePages/${fileresult.data.Name}`;
                                                          this.context.propertyPane.refresh();
                                                          this.render();
                                                      });
                                                  } else {
                                                      console.log('saving....', filePicked);
                                                      onUpdate(field.id, filePicked);
                                                      this.context.propertyPane.refresh();
                                                      this.render();
                                                  }
                                              }
                                          },`

**Comment by joelfmrodrigues** [comment]
@walleford sorry for the late reply. Like @PeterWCox , I have used this control multiple times without issues.
This is an example for the onSave from a recent project:
``` TypeScript
onSave={async (filesPicked: IFilePickerResult[]) => {
  for (const filePicked of filesPicked) {
    const filePickedContent = await filePicked.downloadFileContent();
    const fileNamed= _renderFileName(filePicked);
    uploadFiles(filePickedContent,fileNamed,props.contentType );
  }
}}
```
uploadFiles is just a function that handles the file upload.

Would you be able to provide more details about the issue?

**Comment by PeterWCox** [comment]
I also uploaded a (very rough and ready) sample to illustrate the process of using the FilePicker.

There is a separate demo for both URL's and Images (the latter of which also supports uploading files from your local hard drive)

![image](https://user-images.githubusercontent.com/51972024/201803007-053b471a-7d47-4308-9568-32b73ebb851e.png)

https://github.com/PeterWCox/SPFX-FilePicker-Sample

Hope someone finds this helpful!
