### ISSUE TITLE
Issue in ListItemComments control

### ISSUE THREAD

**Issue by AnsariFurqan** [pnp/sp-dev-fx-controls-react#1191]
Hello,

I am using ListItemComment control in my spfx web part. I have installed and imported the required package successfully. Please someone help me out that what needs to be passed in the "ServiceScope" props of the 'ListItemComment' component? I am getting an error which is pasted below 

Error
Type 'import("D:/Spfx Webparts/Commentstest1/node_modules/@microsoft/sp-core-library/dist/index-internal").ServiceScope' is not assignable to type 'import("D:/Spfx Webparts/Commentstest1/node_modules/@pnp/spfx-controls-react/node_modules/@microsoft/sp-core-library/dist/index-internal").ServiceScope'.
 Types have separate declarations of a private property '_registrations'.ts(2322)
ListItemComments.d.ts(7, 5): The expected type comes from property 'serviceScope' which is declared here on type 'IntrinsicAttributes & IListItemCommentsProps & { children?: ReactNode; }'

![ListItemCommentIssue](https://user-images.githubusercontent.com/53113561/164736853-6d8bcd8c-6e88-41cd-9a79-c359e3ba0956.png)

I have also tried to used imported "Service scope" getting this below error message.
Type 'typeof ServiceScope' is missing the following properties from type 'ServiceScope': _registrations, _parent, _pendingCallbacks, _finished, and 10 more.ts(2740)
ListItemComments.d.ts(7, 5): The expected type comes from property 'serviceScope' which is declared here on type 'IntrinsicAttributes & IListItemCommentsProps & { children?: ReactNode; }'
![ListItemCommentIssue1](https://user-images.githubusercontent.com/53113561/164737445-e6a9f8ea-f254-4b06-9f45-2f3706c20de1.png)

**Comment by joelfmrodrigues** [comment]
@AnsariFurqan I wonder if this is caused by different interfaces due to SPFx version differences. Can you please provide which versions of SPFx and controls you are using?
Also, can you try to pass the scope as 'any' to try to avoid issues with different SPFx versions?
`serviceScope={this.serviceScope as any}`

**Comment by AnsariFurqan** [comment]
Hello @joelfmrodrigues ,

Thanks for the reply.
Below is the screenshot of currently installed version of SPFX in my system. 
![SpfxVersion](https://user-images.githubusercontent.com/53113561/165518132-58d5603a-3cf4-47a0-8d98-833bea5ddcd4.png)

**Comment by AnsariFurqan** [comment]
Hello @joelfmrodrigues ,
Issue has been solved successfully by passing scope as 'any'. Thanks for your help.


Thanks & Regards,
Furqan Ansari

**Comment by AnsariFurqan** [comment]
Hello @joelfmrodrigues ,
Issue has been solved successfully by passing scope as 'any'. Thanks for your help.

Thanks & Regards,
Furqan Ansari

**Comment by joelfmrodrigues** [comment]
@AnsariFurqan glad it worked. It's an unfortunate workaround but we should be able to avoid it when we upgrade the project to the latest SPFx version.
