### ISSUE TITLE
[RichText] Icons not visible in Teams

### ISSUE THREAD

**Issue by BraunJonathan** [pnp/sp-dev-fx-controls-react#1203]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 3.7.2

#### Observed Behavior
Icons of the toolbar are not visible in teams.
![image](https://user-images.githubusercontent.com/35366413/166450459-ee1be2e0-20f4-4dfd-ad82-0585948eec8e.png)
The loadLegacyFabricCss property is true in the manifest and i did an explicit initializeIcons() in the onInit of my webpart.

#### Steps to Reproduce
Just include the component in any webpart the deploy it in Teams

Thanks!

**Comment by michaelmaillot** [comment]
Hi @BraunJonathan is the problem still occur? I've tested the control in the following context:

- version of PnP SPFx Controls: 3.15.0
- version of SPFx: 1.17.2

And everythings works fine:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/38515e89-1132-407b-96c9-52e686eb0646)
