### ISSUE TITLE
DateTimePicker: Clear Date

### ISSUE THREAD

**Issue by RicoNL** [pnp/sp-dev-fx-controls-react#1217]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.8.0 ]

#### Expected / Desired Behavior / Question
When using the DateTimePicker it would be nice to be able to remove a selected date. 

#### Observed Behavior
It is not possible to remove a selectedDate. It is however possible so remove the date by passing in a null value as described in https://github.com/pnp/sp-dev-fx-controls-react/issues/799 . 

#### Steps to Reproduce
Add a datepicker to a webpart and try to remove the date. No clear button available in the (fluent ui) datepicker itself.

**Comment by PeterWCox** [comment]
I'm happy to do this one as a proper first issue :)

@joelmrodrigues - How should we implement the clear button - as a Fluent UI link or primary button? I think the former is a bit nicer - see below crappy paint sketch...

![image](https://user-images.githubusercontent.com/51972024/176201112-1ba6b972-c8f2-467a-b893-d68a3c82de0c.png)

**Comment by RicoNL** [comment]
hi @PeterWCox, please be aware that a PR for the clear-button on the datepicker already has been accepted. See #1218 If you see any improvements on that PR, we can discuss it here. Thanks!
