### ISSUE TITLE
New Control: [fieldPicker]

### ISSUE THREAD

**Issue by sparkitect** [pnp/sp-dev-fx-controls-react#1219]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  latest  ]

#### Enhancement
tl;dr: very similar in concept to sitePicker, listPicker, folderPicker, etc. but for Site/List Columns.

Occasionally we need users to select a Column from a specific scope - Site, by Group, by Type, from List, etc.

Having a configurable control that will populate itself accordingly would be very helpful.

**Comment by milanholemans** [comment]
Hi @sparkitect 

Nice suggestion! If I find the time I'm definitely willing to make the controls above.
Can I ask you to create 1 issue for each control? This way we can link each new control to the corresponding issue. So rename this issue to the FieldPicker control and create another similar issue for the ContentTypePicker control.

Thanks!

**Comment by sparkitect** [comment]
> Nice suggestion! Can I ask you to create 1 issue for each control? This way we can link each new control to the corresponding issue. So rename this issue to the FieldPicker control and create another similar issue for the ContentTypePicker control.
> 
> Thanks!

✔ done: Updated this one and added #1220

**Comment by AJIXuMuK** [comment]
Thanks to @milanholemans this has been implemented and will be included in the next release.
