### ISSUE TITLE
New Control: [contentTypePicker]

### ISSUE THREAD

**Issue by sparkitect** [pnp/sp-dev-fx-controls-react#1220]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  latest  ]

#### Enhancement
tl;dr: very similar in concept to sitePicker, listPicker, folderPicker, etc. but for Content Types.

Occasionally we need users to select a Content Type from a specific scope - Current/Other Site, Gallery, Published, by Group, from Library, etc.

Having a configurable control that will populate itself accordingly would be very helpful.

CC: @milanholemans

**Comment by AJIXuMuK** [comment]
Thank you @sparkitect for the suggestion!
Would you be able to submit a PR for this new control?

**Comment by sparkitect** [comment]
@AJIXuMuK This was a _suggestion_ for a new control, similar to #1219 and I believe that @milanholemans intends to actually develop it...

**Comment by milanholemans** [comment]
I'll try to make a PR of this in the next couple of weeks when I find the time.
