### ISSUE TITLE
What about a modern audio control? 

### ISSUE THREAD

**Issue by mmsharepoint** [pnp/sp-dev-fx-controls-react#1224]
#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ latest]

#### Expected / Desired Behavior / Question
I was thinking if it makes sense to also have a FluentUI-like audio control.
I already implemented one in the following Teams sample:
https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-meeting-record-name 
If you agree I could try to share/adjust it for this repo SPFx targeted ...

![Audio control](https://camo.githubusercontent.com/98b652df47832aec53de3072774ab1d0d15442d8dd23adf9ec5b2af6cdcda2ff/68747470733a2f2f6d6d7368617265706f696e742e66696c65732e776f726470726573732e636f6d2f323032312f30392f696e6d656574696e675f6170702d312e6a7067)

**Comment by AJIXuMuK** [comment]
@mmsharepoint - sure, it would be really great to have such a control here!

**Comment by mmsharepoint** [comment]
Okay, I'll try that one.
Will start soon as I am currently working on another contribution.
