### ISSUE TITLE
npm package @pnp/spfx-controls-react is not installing

### ISSUE THREAD

**Issue by manjunathreddy1** [pnp/sp-dev-fx-controls-react#1225]
Hi,

When I try to run the npm installation command npm install @pnp/spfx-controls-react, I'm getting the following error and I'm not able to use pnp spfx controls in my project. Please let us know how we can fix this issue.

Not Found - GET https://registry.npmjs.org/react-mentions/-/react-mentions-4.4.1.tgz - Not found
'react-mentions@https://registry.npmjs.org/react-mentions/-/react-mentions-4.4.1.tgz' is not in this registry.

**Comment by FaganSC** [comment]
I'm getting the same thing this morning.
![image](https://user-images.githubusercontent.com/810028/170826117-9e703481-108c-477b-b6fe-72b00bfd864b.png)

**Comment by MarkusLanger** [comment]
Same
Node v14.16.1
NPM 6.14.12
SPFx 1.14.0
![image](https://user-images.githubusercontent.com/12131918/170840399-3c5a5036-e73f-4601-b2c5-9c10e21c39f7.png)

**Comment by hesperanca** [comment]
Same problem here. 

Node: v14.19.1
NPM: V6.14.15
SPFX: 1.14.0

**Comment by hesperanca** [comment]
As a workaround for anyone having this issue (until the owners of the 'react-mentions' package fix the issue). Just manually install the previous version of the ''react-mentions' package and then try to install the pnp package again. 

Install the previous version of the 'react-mentions':
npm install react-mentions@4.4.0 --save --save-exact

Install the pnp controls:
npm install @pnp/spfx-controls-react --save --save-exact

That should get you going for now.

**Comment by manjunathreddy1** [comment]
> As a workaround for anyone having this issue (until the owners of the 'react-mentions' package fix the issue). Just manually install the previous version of the ''react-mentions' package and then try to install the pnp package again.
> 
> Install the previous version of the 'react-mentions': npm install react-mentions@4.4.0 --save --save-exact
> 
> Install the pnp controls: npm install @pnp/spfx-controls-react --save --save-exact
> 
> That should get you going for now.

This solutions working. Thanks.

**Comment by FaganSC** [comment]
> As a workaround for anyone having this issue (until the owners of the 'react-mentions' package fix the issue). Just manually install the previous version of the ''react-mentions' package and then try to install the pnp package again.
> 
> Install the previous version of the 'react-mentions': npm install react-mentions@4.4.0 --save --save-exact
> 
> Install the pnp controls: npm install @pnp/spfx-controls-react --save --save-exact
> 
> That should get you going for now.

Thanks @hesperanca ! This worked for me as well!

I'm assuming after the package owner resolves their issue, we should be able to remove the "react-mentions" from the package.json
![image](https://user-images.githubusercontent.com/810028/170871832-9e5ea738-b43e-4225-b516-055a18c7a92e.png)

**Comment by hesperanca** [comment]
@FaganSC  To ensure that your package.json and the package-lock.json are kept in sync, to uninstall the package you should run: `npm uninstall --save react-mentions@4.4.0`  instead of manually changing the package.json file.

You should then re-run: 
`npm install @pnp/spfx-controls-react --save --save-exact`

Which should update the dependencies and, in this case, bring the fixed version of the react-mentions package.

**Comment by joelfmrodrigues** [comment]
@hesperanca many thanks for providing a workaround!

Can someone confirm if this is now resolved? I have just tested at my end and was able to install 3.8.0, so assume the issue was fixed in react-mentions itself

**Comment by MarkusLanger** [comment]
Yes, works fine with my original configuration.

**Comment by AJIXuMuK** [comment]
it is resolved by now
