### ISSUE TITLE
Should WebPartTitle documentation use something else than ControlsTest?

### ISSUE THREAD

**Issue by mcraiha** [pnp/sp-dev-fx-controls-react#125]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version
1.7.0

#### Expected / Desired Behavior / Question
[WebPartTitle](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/WebPartTitle/) documentation mentions **ControlsTest** and **IControlsTestProps**, but should it just be vanilla example with something like
```
import { WebPartTitle, IWebPartTitleProps } from "@pnp/spfx-controls-react/lib/WebPartTitle";


const titleText: React.ReactElement<IWebPartTitleProps> = React.createElement(
            WebPartTitle,
            {
              title: this.properties.title,
              displayMode: this.displayMode,
              updateProperty: (value: string) => {
                this.properties.headerTitle = value;
              }
            }
          );


ReactDom.render...
```
since it is easier to understand?

**Comment by estruyf** [comment]
@mcraiha this your React component which you want to load. When you start a new SPFx React project, this will already be in place for you in the web part file. The only thing you have to do is add the required properties (title, displayMode, updateProperty).

`ControlsTest` and `IControlsTestProps` will be your component name.

**Comment by AJIXuMuK** [comment]
Closing this one as answered.

We have scheduled a task #581 to revise the documentation and make it more self-explanatory.
