### ISSUE TITLE
[ListPicker] Incorrect returned value in onSelectionChanged callback for multiSelect

### ISSUE THREAD

**Issue by OverkillTV** [pnp/sp-dev-fx-controls-react#1254]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version
Please specify what version of the library you are using: [ **3.8.0** ]

#### Expected / Desired Behavior / Question
When multiSelect is set to true, "onSelectionChanged" should return an array of currently selected list Ids

#### Observed Behavior
multiSelect is set to true but onSelectionChanged only returns an array of single string. So it always returns either empty array (when uncheck any list) or an array of single string (when check any list) which make it impossible to detect what have been unchecked.

Example: 

- Available options are: List A, List B, List C, list D.
- Check on List A, check on list B then console.log only returns ['List B Id']
- Uncheck List A then console.log returns [] even though List B is still selected.

#### Steps to Reproduce
set multiSelect and console.log in the onSelectionChanged callback

**Comment by michaelmaillot** [comment]
Hi @OverkillTV,

I've tested with latest version (3.15.0) and the `console.log` in the `onSelectionChanged` callback reflects what I've checked / unchecked in multi-selection.

Did you have the chance to retry recently? Do you still have an issue with this one?

**Comment by OverkillTV** [comment]
Hi @michaelmaillot,

Checked in 3.15.0 and it is working as expected. So This issue has been fixed somewhere between 3.8.0 till 3.15.0

We can close this now.

**Comment by OverkillTV** [comment]
Closed
