### ISSUE TITLE
Lodash version can be updated to 4.17.21 for spfx-control-react version 1.21.3 to get rid of vulnerabilities?

### ISSUE THREAD

**Issue by kodofix** [pnp/sp-dev-fx-controls-react#1255]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [  1.21.3  ]

#### Expected / Desired Behavior / Question
Hello everyone,

Is possible to update lodash version to 4.17.21 and get rid of vulnerabilities which exist in lodash 4.17.13? 
For the on-prem tech stuck I can not use npm "overrides" as I use node 10 and npm 6.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/17184220/177798479-e57defcd-c35e-4079-aa20-5b9096d71037.png)

#### Steps to Reproduce
Go to https://snyk.io/test/npm/%40pnp/spfx-controls-react/1.21.3 there is a health status.

**Comment by joelfmrodrigues** [comment]
@kodofix closing this issue as PR was merged. Many thanks!

**Comment by mmohamedbasith** [comment]
@kodofix Were you able to address the issue ? I am having the same issue. Your reply would be helpful

**Comment by kodofix** [comment]
@mmohamedbasith I change version of Lodash within spfx-controls-react PR was merged so should be available for everyone.

**Comment by mmohamedbasith** [comment]
@kodofix @joelfmrodrigues For some reason , this package V1.21.3 download only the lodash@4.17.13 . Not downloading the lodash@4.17.21. I have checked from registry directly as well (Below screenshot)

<img width="958" alt="Screenshot 2023-01-04 162331" src="https://user-images.githubusercontent.com/28502351/210540028-a8ba2dca-a0e2-4db6-af94-403f1649d83c.png">

**Comment by mmohamedbasith** [comment]
@kodofix @joelfmrodrigues can someone publish this change to npm registry . It is not currently available. I tested with few user machine , Lodash 1.17.13 is the version coming with spfx-control-react version 1.21.3
