### ISSUE TITLE
error TS2786: 'RichText' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1266]
#### Category
[x ] Bug
#### Version

Please specify what version of the library you are using: [     3.9.0 and   3.10.0-beta.2656830  ]

#### Expected / Desired Behavior / Question
`    <RichText value={m.message} isEditMode={false} /> `
worked fine before SPFx 1.15.0

#### Observed Behavior

I get error:
```
'RichText' cannot be used as a JSX component.
  Its instance type 'RichText' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactElement<IRichTextProps, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<IRichTextProps, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
```

Thanks!

**Comment by joelfmrodrigues** [comment]
Hi @Ofer-Gal , this is likely an issue with imports. Would you be able to help with the issue?

**Comment by Ofer-Gal** [comment]
Be happy to. How do you want me to test it?

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal not sure what is the exact cause of the issue at this point, but may be worth checking two previous pull requests for other controls that may be related as having similar issues:
https://github.com/pnp/sp-dev-fx-controls-react/pull/1336/files
https://github.com/pnp/sp-dev-fx-controls-react/pull/1338/files

**Comment by Ofer-Gal** [comment]
With newer vesion there is another less problematic problem.
Closing this one
