### ISSUE TITLE
Bug: DynamicForm does not properly handle NULL default values for Taxonomy fields

### ISSUE THREAD

**Issue by erik-larson-bwp** [pnp/sp-dev-fx-controls-react#1267]
Taxonomy fields (multi select or single select) with a NULL default value cause the form to fail loading, leaving the user only seeing the spinner and no error message.  Blank string default values are handled properly.

**Comment by michaelmaillot** [comment]
I think that it's the same code that the one behind #1268, I think I can handle it also @joelfmrodrigues 🙂

**Comment by joelfmrodrigues** [comment]
@erik-larson-bwp The PR from Michael was merged and the fix should be in the beta release within a few minutes
