### ISSUE TITLE
Bug: DynamicForm errors when submitting blank Taxonomy field values

### ISSUE THREAD

**Issue by erik-larson-bwp** [pnp/sp-dev-fx-controls-react#1268]
When saving from the DynamicForm, if a taxonomy field is blanked out, it tries to process the null value and throws the following error:  "Cannot Read Properties of Undefined (reading 'name')".

Steps to reproduce:
1. Open the DynamicForm for a list item that has an existing Taxonomy field value.
2. Remove the value for the Taxonomy field.
3. Click Save.

Alternatively you can add a taxonomy field value to a new or existing item, then remove it, then click Save.

**Comment by michaelmaillot** [comment]
Hi @erik-larson-bwp 

I confirm I can repro this one.

@joelfmrodrigues can you assign it to me?
