### ISSUE TITLE
FilePicker not select in tile view

### ISSUE THREAD

**Issue by vfcupido** [pnp/sp-dev-fx-controls-react#1272]
Hi!
I´m using the component for a development but not working correctly.
When I try to select a file of my sharepoint online and I have the tile view selected, I can´t choose an element. I have change the view and jet work. Any bug??

Thanks!

**Comment by joelfmrodrigues** [comment]
@vfcupido many thanks for raising this issue. A PR from @VRomanovTau has now been merged into the dev branch and should fix this problem
