### ISSUE TITLE
People Picker not taken webAbsoluteUrl with ensureUser set to true

### ISSUE THREAD

**Issue by VRomanovTau** [pnp/sp-dev-fx-controls-react#1273]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.9.0]

#### Expected / Desired Behavior / Question
I am using this component in my Teams Tab app. My app installed not in root site collection
I expect, that PeoplePicker will search on the web, url I provided in webAbsoluteUrl. But instead it is searching in the root site, because [this.context.pageContext.web.absoluteUrl](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/services/PeopleSearchService.ts#L365) reference to root site - in this case user id is wrong

#### Observed Behavior
```typescript
<PeoplePicker
            context={context as any}
            webAbsoluteUrl={webAbsoluteUrl}
            disabled={formType === RequestFormType.View}
            peoplePickerWPclassName={formType === RequestFormType.View && styles.disabled}
            defaultSelectedUsers={selectedUsers}
            titleText={field.Title}
            placeholder={field.Description}
            personSelectionLimit={999}
            required={field.Required}
            onChange={_selectPeople}
            showHiddenInUI={false}
            ensureUser
            principalTypes={[PrincipalType.User]}
            resolveDelay={0}
            errorMessage={_validate()}
            validateOnFocusOut={true}
        />
```

Thanks!

**Comment by joelfmrodrigues** [comment]
Hi @VRomanovTau , many thanks for logging the issue. 
If you have the chance to submit a PR to fix the issue, it would be really appreciated 🙂
