### ISSUE TITLE
onChange not triggered when clearing date

### ISSUE THREAD

**Issue by Leif-Frederiksen** [pnp/sp-dev-fx-controls-react#1277]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     3.9.0    ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
When using the new "showClearDate" feature of the date/time picker, I would expect the "onChange" event to be triggered, just like when the user enters a date.

#### Observed Behavior
"onChange" is not triggered.

**Comment by milanholemans** [comment]
Hi @Leif-Frederiksen 

Thanks for reporting this issue. According to me this is indeed not ideal, the `onChange` event should be fired every time the date changes in the date picker.
I made a PR to fix this issue.

**Comment by AJIXuMuK** [comment]
@Leif-Frederiksen - the fix has been merged and will be included in the next release.

**Comment by joelfmrodrigues** [comment]
New release just published, closing
