### ISSUE TITLE
Update docs for `Placeholder` with an example to hide it in read mode

### ISSUE THREAD

**Issue by Jwaegebaert** [pnp/sp-dev-fx-controls-react#1280]
#### Category

- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: Latest

### Update

The feature request is a bit to verbose to implement within the control itself. To compensate, we will update the docs with an example how this can be achieved. 

``` typescript
{
  this.displayMode === DisplayMode.Edit ?
  <Placeholder ...placeholderProps /> :
  <div />  
}
```

More info: https://github.com/pnp/sp-dev-fx-controls-react/pull/1295#discussion_r971673826

> #### Question
> 
> Extending the control `Placeholder` with an extra option that would hide the control when the display mode of the page is in `Read`. This way users could use the control and configure it so the look and feel is similar like a default SP WebPart. For example: When you use the conversations WebPart from Yammer you get the following UI in edit mode.
> 
> ![afbeelding](https://user-images.githubusercontent.com/38426621/184078824-545c858e-efd0-4819-9947-750158c801a0.png)
> 
> But if you don't configure the WebPart and publish the page, the placeholder is hidden.
> 
> ![afbeelding](https://user-images.githubusercontent.com/38426621/184079082-82a4d108-15c3-4d0c-9525-f075ded55da0.png)
> 
> #### Implementation
> 
> This could be achieved by adding a new variable to the interface `IPlaceholderProps` that looks a bit like the following.
> 
> ``` typescript
> /**
>  * Specify if you want to hide the placeholder when the page is in view mode
>  */
> hideViewMode?: boolean;
> ```

**Comment by Jwaegebaert** [comment]
If everyone agrees that this could be a nice enhancement, then I can take it up. 😄

**Comment by joelfmrodrigues** [comment]
Hi @Jwaegebaert sorry for the late reply. Enhancements are always welcome 🙂
As you have volunteered to implement it, I will assign this item to you. Thanks!
