### ISSUE TITLE
ListItemComments no user photos for users with custom images

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-controls-react#1283]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.9.0]

#### Expected / Desired Behavior / Question
When @-mentioning users while writing a comment user photos or placeholder images should be shown for all users.

#### Observed Behavior
When @-mentioning users the preview list of users shows broken image icons for users that have custom images. The list of comments shows a colored default user image for those user's comments (class is-notLoaded is set).
I checked the code and can't see a reason why this happens since both controls use /_layouts/15/userphoto.aspx?size=M&accountname= + user mail. Which btw. when called in a browser returns {"HttpStatus":"NotFound","ErrorMessage":"Asset does not exist","ErrorCode":404001} for users with custom images in our SPO. This no longer seems to work. I also noticed that our SPO's webparts no longer display the user icons but only the initials. Maybe custom user icons for SPO will be a thing of the past (or there is a problem with our tenent). Anyway, there is at least one issue: There is no fallback to display a default icon if /_layouts/15/userphoto.aspx returns no image in the @-mention preview list similar to what happens in the comments list via the ActivityItem.

**Comment by IRRDC** [comment]
I wonder if it is a problem of the Rest API backend since the requests sent by the control do not differ for lists and libraries.

**Comment by michaelmaillot** [comment]
Hi @IRRDC,

Do you still encounter this issue and if you do, could you post some screenshots / code snippet?

**Comment by IRRDC** [comment]
The behavior has changed. Now I'm getting the placeholder silhouette for all users (which is better) when using the control while SharePoint Online's build-in comments panel shows me the placeholder silhouette for users without custom icons and the colored initials for users who have custom icons (instead of their custom icons) while typing a comment and the colored initials with a broken image icon overlay after a comment has been posted... The screenshot is from SharePoint Online's build-in comments panel showing the suggestions list and an existing comment for a user with a custom image:
![Zwischenablage01](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/e1d8da34-2b27-4c09-81a9-0967f7bd3acd)
While this is from the ListItemComments control showing users with and without custom icons:
![Zwischenablage02](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/343d3bf1-d8b5-449c-9763-ae08a3bcf1a0)

**Comment by michaelmaillot** [comment]
That's because the control uses the `userphoto.aspx` to get the photo like you mentioned in the first place.

If I remember, the initials are generated dynamically through SPO's JS function on the fly (but can't confirm that, I haven't checked for a while).

Regarding the recent test, is it ok for you?

**Comment by IRRDC** [comment]
It doesn't quite match what the SharePoint UI shows but the placeholder images are way better than the broken image icons that we got last year. Back than I manually queried the userphoto.aspx and got very strange results. Seems like it still hasn't been completely fixed so no error of the control.
