### ISSUE TITLE
Does not compile when used with SPFx 1.15.2

### ISSUE THREAD

**Issue by cwdata** [pnp/sp-dev-fx-controls-react#1288]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.10.0-beta.2834849]

#### Expected / Desired Behavior / Question
Would be great if this lib could be used with SPFx v1.15.2.

#### Observed Behavior
We used version 3.9.0 without any problems in a project configured for SPFx 1.15.0. After upgrading the project to SPFx 1.15.2 gulp bundle fails with errors referring to @fluentui/scheme:
```
Error - [webpack] 'dist':
./node_modules/@pnp/spfx-controls-react/lib/common/utilities/ThemeUtility.js
Module not found: Error: Can't resolve '@fluentui/scheme-utilities' in 'C:/Projects/SharePointFramework/BusinessMain2018/node_modules/@pnp/spfx-controls-react/lib/common/utilities'
resolve '@fluentui/scheme-utilities' in 'C:/Projects/SharePointFramework/BusinessMain2018/node_modules/@pnp/spfx-controls-react/lib/common/utilities'
  Parsed request is a module
  using description file: C:/Projects/SharePointFramework/BusinessMain2018/node_modules/@pnp/spfx-controls-react/package.json (relative path: ./lib/common/utilities)
```
After upgrading to the latest beta the problem still persists.

#### Steps to Reproduce
Maybe this will always happen when using the lib in conjunction with SPFx 1.15.2.

**Comment by 6gal6ler6** [comment]
Hello, I am using SPFx version 1.15.2 and I have no problem

These are the dependencies I am using at `package.json`
```json
  "dependencies": {
    "@fluentui/react": "^8.86.4",
    "@microsoft/sp-core-library": "1.15.2",
    "@microsoft/sp-lodash-subset": "1.15.2",
    "@microsoft/sp-office-ui-fabric-core": "1.15.2",
    "@microsoft/sp-property-pane": "1.15.2",
    "@microsoft/sp-webpart-base": "1.15.2",
    "@pnp/core": "^3.5.1",
    "@pnp/sp": "^3.5.1",
    "@pnp/spfx-controls-react": "3.9.0",
    "lodash": "^4.17.21",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-html-parser": "^2.0.2",
    "react-router-dom": "^5.3.0",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.15.2",
    "@microsoft/eslint-plugin-spfx": "1.15.2",
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@microsoft/sp-build-web": "1.15.2",
    "@microsoft/sp-module-interfaces": "1.15.2",
    "@rushstack/eslint-config": "2.5.1",
    "@types/lodash": "4.14.184",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@types/react-router-dom": "^5.3.3",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "spfx-fast-serve-helpers": "~1.15.0",
    "typescript": "4.5.5"
  }
```

**Comment by cwdata** [comment]
Ok, you are using "@fluentui/react". We stick to the SPFx standard and use "office-ui-fabric-react".
Afaik it is not supported to use a different major version of UI fabric with SPFx, so we'd like to keep using the standard.

**Comment by Perneel** [comment]
I'm having the same issue with "office-ui-fabric-react" and SPFx 1.15.2.

> [12:19:50] Error - [webpack] 'dist':
./node_modules/@pnp/spfx-controls-react/lib/common/utilities/ThemeUtility.js
Module not found: Error: Can't resolve '@fluentui/scheme-utilities' in 'C:\gitroot\SPDICT-Archief\node_modules\@pnp\spfx-controls-react\lib\common\utilities'
resolve '@fluentui/scheme-utilities' in 'C:\gitroot\SPDICT-Archief\node_modules\@pnp\spfx-controls-react\lib\common\utilities'
  Parsed request is a module
  using description file: C:\gitroot\SPDICT-Archief\node_modules\@pnp\spfx-controls-react\package.json (relative path: ./lib/common/utilities)

package.json

> "dependencies": {
    "@microsoft/sp-core-library": "1.15.2",
    "@microsoft/sp-lodash-subset": "1.15.2",
    "@microsoft/sp-office-ui-fabric-core": "1.15.2",
    "@microsoft/sp-property-pane": "1.15.2",
    "@microsoft/sp-webpart-base": "1.15.2",
    "@pnp/core": "3.5.1",
    "@pnp/graph": "3.5.1",
    "@pnp/logging": "3.5.1",
    "@pnp/sp": "3.5.1",
    "@pnp/spfx-controls-react": "3.9.0",
    "office-ui-fabric-react": "7.185.7",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.15.2",
    "@microsoft/eslint-plugin-spfx": "1.15.2",
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@microsoft/sp-build-web": "1.15.2",
    "@microsoft/sp-module-interfaces": "1.15.2",
    "@rushstack/eslint-config": "2.5.1",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@types/sharepoint": "^2016.1.10",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "typescript": "4.5.5"
  }

**Comment by cwdata** [comment]
The problem persists after upgrading to the latest release 3.10.0 of spfx-controls-react even though the release notes say "SharePoint Framework v1.15.2 support".

**Comment by salascz** [comment]
@cwdata - what is your node.js version?

There seems to be reference to @microsoft/mgt-spfx "2.3.0" pointing to spfx 1.12.1 :(

**Comment by cwdata** [comment]
@salascz  I'm using NodeJS v16.16.0

**Comment by cwdata** [comment]
@salascz Thanks for the tip with NodeJS.
I can confirm that my project compiles when using NodeJS v14.15.5
What I did:
- Downgraded NodeJS to v14.15.5 (supported by SPFx v1.12.1)
- Deleted the node_modules folder and package-lock.json from my project
- Did 'npm install'
- Did 'gulp clean' and 'gulp bundle --ship'
There were a bunch of warnings regarding ESLint not supporting that NodeJS version but at least it compiled without errors. So for now that could be used as a workaround.

**Comment by cebud** [comment]
Package @microsoft/mgt-spfx is supporting spfx 1.15 from version 2.6.1, but in spfx-controls-react 3.10 is used is 2.3.0. 

@AJIXuMuK 
Shouldn't be @microsoft/mgt-spfx package upgraded to version 2.6.1 for fully supporting spfx 1.15 in spfx-controls-react? Thank you

**Comment by salascz** [comment]
@AJIXuMuK: Any update on this?

Thanks

**Comment by AJIXuMuK** [comment]
I've updated the `mgt` packages.
Please, let me know if the issue still exists.

**Comment by cwdata** [comment]
@AJIXuMuK 
I just tested with this version: 
`"@pnp/spfx-controls-react": "3.10.0-beta.3081239"`
and it did compile without issues using NodeJS v16.
Thanks for the fix.
