### ISSUE TITLE
Dynamic Form: Add `enableDefaultSuggestions` true by default for Lookup fields

### ISSUE THREAD

**Issue by 6gal6ler6** [pnp/sp-dev-fx-controls-react#1289]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

3.9.0

#### Desired Behavior

That lookup fields have the property `enableDefaultSuggestions` for the `ListItemPicker` set to true by default. Just like in SharePoint OOB form. This will show options to the end user right away

**Comment by michaelmaillot** [comment]
Hi @6gal6ler6,

Latest version (3.15.0) uses `DynamicField` under the hood of `DynamicForm`, and for Lookup fields, it uses `DefaultPicker` with `enableDefaultSuggestions ` set to true.

Did you have the chance to try it?

**Comment by 6gal6ler6** [comment]
> Hi @6gal6ler6,
> 
> Latest version (3.15.0) uses `DynamicField` under the hood of `DynamicForm`, and for Lookup fields, it uses `DefaultPicker` with `enableDefaultSuggestions ` set to true.
> 
> Did you have the chance to try it?

I haven't tried, thanks for the tip.

**Comment by joelfmrodrigues** [comment]
@6gal6ler6 can we close this issue as resolved?

**Comment by 6gal6ler6** [comment]
> @6gal6ler6 can we close this issue as resolved?

Yes please
