### ISSUE TITLE
People Picker returns no results on 3.10.0

### ISSUE THREAD

**Issue by c-eiser13** [pnp/sp-dev-fx-controls-react#1292]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.10.0     ]

#### Expected / Desired Behavior / Question
Using tenant search in people picker should return results.

#### Observed Behavior
No results are returned and network error is observed.
![image](https://user-images.githubusercontent.com/42096464/186507508-4d9ebd30-637d-452a-9664-037f2c8e3086.png)

I pulled the latest version of project and debugged and it looks like the issue is with this change:
 
![peoplepicker3](https://user-images.githubusercontent.com/42096464/186508192-a0c6afd7-a1fd-478a-9df1-30bfafe69908.png)

I've reverted just those 3 changes back and the people picker is working properly again. I will create a PR with this change if it helps. 

#### Steps to Reproduce
Add the people picker control to a page and do not add groupName or groupId params.

**Comment by trueleader** [comment]
Same problem here

**Comment by HarminderSethi** [comment]
I am also getting below error while using PeoplePicker control. Versions used - "@pnp/spfx-controls-react": "^3.10.0",     "@fluentui/react": "^8.92.1", SPFx: 1.15.2
![image](https://user-images.githubusercontent.com/17841313/187191702-5f12a638-bf05-427a-980e-c120e3f04c67.png)

**Comment by c-eiser13** [comment]
Created this PR that should address this issue https://github.com/pnp/sp-dev-fx-controls-react/pull/1293

**Comment by HarminderSethi** [comment]
@c-eiser13  I am getting the same error even if I use version 3.5.0 for @pnp/spfx-controls-react with "@fluentui/react": "^8.92.1", SPFx: 1.15.2. Any temporary fix for this?

**Comment by c-eiser13** [comment]
@HarminderSethi I'm using 3.9.0 and do not have these issues, also on SPFx 1.15.2

**Comment by HarminderSethi** [comment]
@c-eiser13  this is my package.json 

{
  "name": "local-workflow",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "serve": "gulp bundle --custom-serve --max_old_space_size=4096 && fast-serve"
  },
  "dependencies": {
    "@fluentui/react": "^8.93.0",
    "@microsoft/sp-core-library": "1.15.2",
    "@microsoft/sp-lodash-subset": "1.15.2",
    "@microsoft/sp-office-ui-fabric-core": "1.15.2",
    "@microsoft/sp-property-pane": "1.15.2",
    "@microsoft/sp-webpart-base": "1.15.2",
    "@pnp/sp": "^3.6.0",
    "@pnp/spfx-controls-react": "^3.9.0",
    "@xstate/react": "^3.0.1",
    "camljs": "^2.13.0",
    "moment": "^2.29.4",
    "nunjucks": "^3.2.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "tslib": "2.3.1",
    "xstate": "^4.33.4"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.15.2",
    "@microsoft/eslint-config-spfx": "1.15.2",
    "@microsoft/sp-build-web": "1.15.2",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "gulp": "4.0.2",
    "typescript": "4.5.5",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "eslint-plugin-react-hooks": "4.3.0",
    "@microsoft/sp-module-interfaces": "1.15.2",
    "spfx-fast-serve-helpers": "~1.15.0"
  }
}

**Comment by HarminderSethi** [comment]
@c-eiser13 Payload:  ![image](https://user-images.githubusercontent.com/17841313/187233477-e8ff6f28-0c42-4aa2-9bbb-b23f0ea3bb83.png)

response : {"error":{"code":"-1, Microsoft.OData.Core.ODataException","message":"A null value was found for the property named 'SharePointGroupID', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}

**Comment by trueleader** [comment]
you did not fixiate the version of spfx control.
Either:
`"@pnp/spfx-controls-react": "3.9.0",`

or skip the broken version (expecting 3.10.1 will be the next bugfix version fixing this bug):
`"@pnp/spfx-controls-react": "^3.10.1 || 3.9.0",`

**Comment by HarminderSethi** [comment]
^ before the version was the issue. I did not notice this . Thanks for your help :)

**Comment by ekdegerman** [comment]
Any chance for a resolution to this one anytime soon? It would really help, since it is the first version in a long time that doesn't require casting the context as any and breaking the default ESLint rules (no-explicit-any) that came with SPFx 1.15. It also seems to resolve the strange issue described in #1235

**Comment by joelfmrodrigues** [comment]
@ekdegerman the PR from @c-eiser13 should be merged very soon

**Comment by joelfmrodrigues** [comment]
The fix from @c-eiser13 is now on the dev branch and should be in the beta release within a few minutes. If anyone has the chance to test, please let us know if the issue persists.

**Comment by ekdegerman** [comment]
> The fix from @c-eiser13 is now on the dev branch and should be in the beta release within a few minutes. If anyone has the chance to test, please let us know if the issue persists.

Works fine in my component with the beta version. Probably a pretty simple case, though, just using the people picker separately to allow picking people from all users inside a react function component. This version seems to resolve both issues I've experienced on earlier releases.

**Comment by vystartasv** [comment]
> The fix from @c-eiser13 is now on the dev branch and should be in the beta release within a few minutes. If anyone has the chance to test, please let us know if the issue persists.

People Picker issue is fixed on beta release. You saved my day. Thanks a million @c-eiser13  and @joelfmrodrigues :)

**Comment by alexabramkin** [comment]
Fix in beta version works

**Comment by martinlingstuyl** [comment]
Does anyone know when we can expect the release of 3.11? 

I need a feature in 3.10 as well as the people picker fix 😁

Using the beta version is ok, but not great for production purposes.

**Comment by joelfmrodrigues** [comment]
Hi @martinlingstuyl 
Maybe in a few days, if we can find the time to review pending PRs :)

**Comment by martinlingstuyl** [comment]
Ok 👍
And introduce possible bugs by last minute PR merges? exciting! 😁

**Comment by ekdegerman** [comment]
I see that 3.11.0 is now available as a release here in Github, however [npm](https://www.npmjs.com/package/@pnp/spfx-controls-react) still has 3.10.0 as the latest release. When can we expect 3.11.0 to be available there as well? It seemed instant for the beta release so I thought I'd ask if it is to be expected or something is wrong...

**Comment by Vertamin** [comment]
Yes please, Im craving for this update!

**Comment by joelfmrodrigues** [comment]
@ekdegerman thanks for the heads up, there seems to have been some issue with the action that publishes the release and we will look into it

**Comment by joelfmrodrigues** [comment]
3.11.0 is now available on npm. Please let us know if you find any issues
