### ISSUE TITLE
PeoplePicker late suggestions with groupName assigned

### ISSUE THREAD

**Issue by EA12** [pnp/sp-dev-fx-controls-react#1301]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.8.1 ]

#### Expected / Desired Behavior
The suggestions should come up after typing the 3rd char.

#### Observed Behavior
Most of the time, we need to type 5 or 6 Chars to get suggestions.
Sometimes, depending on the amount of people with nearly same letters, the suggestions are working after 3 chars.
If we don't use a groupName, the suggestion works always after 3 chars.

#### Steps to Reproduce
Create a SPFX-Solution
Install spfx-controls-react
Add a functional component
Import and add a PeoplePicker
Create a SharePoint Security Group and add some People
Assign the groupName to the PeoplePicker

```
import { PeoplePicker, PrincipalType } from '@pnp/spfx-controls-react/lib/PeoplePicker';

<PeoplePicker
      context={props.context as any}
      titleText=""
      defaultSelectedUsers={[]}
      personSelectionLimit={1}
      groupName={"ZSN Ansprechpartner"} 
      showtooltip={true}
      styles={ppStyle}
      disabled={false}
      onChange={_clerkChanged}
      showHiddenInUI={false}
      principalTypes={[PrincipalType.User]}
      resolveDelay={1000} />
```

Here is my onChange method:

```
     // eslint-disable-next-line
    const _clerkChanged = useCallback(async (items: any[]) => {
        if(items && items.length > 0) {
            const u: IUser = {
                DisplayName: items[0].secondaryText,
                ID: ""
            }
        
             // We ensure the selected user:
            const user: ISiteUserProps = await sharePointService.ensureUser(items[0].loginName);
            u.ID = user.Id.toString();
            setClerk([u]);
        }
    },[sharePointService]);
```

Here are the dependencies from tha package.json:

```
"dependencies": {
    "@microsoft/decorators": "1.15.0",
    "@microsoft/sp-core-library": "1.15.0",
    "@microsoft/sp-listview-extensibility": "1.15.0",
    "@microsoft/sp-lodash-subset": "1.15.0",
    "@microsoft/sp-office-ui-fabric-core": "1.15.0",
    "@pnp/sp": "^3.4.1",
    "@pnp/spfx-controls-react": "3.8.1",
    "draft-js": "^0.11.7",
    "draftjs-to-html": "^0.9.1",
    "office-ui-fabric-react": "7.185.7",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-draft-wysiwyg": "^1.15.0",
    "react-html-parser": "^2.0.2",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.15.0",
    "@microsoft/eslint-config-spfx": "1.15.0",
    "@microsoft/sp-build-web": "1.15.0",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "gulp": "4.0.2",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "eslint-plugin-react-hooks": "4.3.0",
    "@microsoft/sp-module-interfaces": "1.15.0"
  }
```

Can you please have a look into it? - Thx.

**Comment by cardinalpipkin** [comment]
I also have this issue.
The dependencies I use:
  "dependencies": {
    "@microsoft/sp-core-library": "1.15.0",
    "@microsoft/sp-lodash-subset": "1.15.0",
    "@microsoft/sp-office-ui-fabric-core": "1.15.0",
    "@microsoft/sp-property-pane": "1.15.0",
    "@microsoft/sp-webpart-base": "1.15.0",
    "@pnp/logging": "^3.7.0",
    "@pnp/sp": "^3.7.0",
    "@pnp/spfx-controls-react": "^3.9.0",
    "bootstrap": "^5.2.2",
    "filepond": "^4.30.4",
    "office-ui-fabric-react": "7.185.7",
    "react": "16.13.1",
    "react-bootstrap": "^2.5.0",
    "react-dom": "16.13.1",
    "react-dropzone": "^14.2.3",
    "react-filepond": "^7.1.2",
    "react-quill": "^1.3.5",
    "styled-components": "^5.3.6",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.15.0",
    "@microsoft/eslint-config-spfx": "1.15.0",
    "@microsoft/sp-build-web": "1.15.0",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "gulp": "4.0.2",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "eslint-plugin-react-hooks": "4.3.0",
    "@microsoft/sp-module-interfaces": "1.15.0",
    "spfx-fast-serve-helpers": "~1.15.0"
  }
}

**Comment by michaelmaillot** [comment]
Hi @EA12 & @cardinalpipkin,

I tried with latest version (3.15.0) and suggestions within a group are displayed as quick as  if I didn't have one.

Did you have the chance to give a try recently?

**Comment by EA12** [comment]
Hi @michaelmaillot, 
sorry for my late response. I am still facing the issue.
The related SharePoint-Security-Group has 54 Users. The more far the users are in alphabetical order, like "Wessel", the user cannot be found if we just type 3 or 4 or 5 chars. If we write the whole Name, the user will be found.
As I wrote previously, we are using version 3.8.1
In the meanwhile we upgrade sharepoint from 1.15.0 to 1.19.0 but a higher version of the peoplepicker than 3.8.1 is not compatible with 1.19.0

When you have tested with version 3.15.1, did you had as many users as we have in the group?
If you just have 10 it will work...

**Comment by EA12** [comment]
Hi @michaelmaillot,

we tried with IPeoplePickerContext, with any and with never.
The problem with a large group (54 users in our case) is still the same.

![Image](https://github.com/user-attachments/assets/60a8bd7d-e46b-412b-824a-1210f297b061)

![Image](https://github.com/user-attachments/assets/c929cd40-8170-4de5-b5f8-5379eb1d0545)

What i see from the network traces is:
Searching for "Wess", creates a har file of 4.734 KB and the user will not be found.
Searching for "Wessel " ceates a har file of 107 KB.

I will attach both .har files as .txt (tenant name has been changed and also site- and user names).
Hope you can help.

[Searching4Wess.txt](https://github.com/user-attachments/files/20901565/Searching4Wess.txt)
[Searching4Wesselplusemptyspace.txt](https://github.com/user-attachments/files/20901566/Searching4Wesselplusemptyspace.txt)

**Comment by EA12** [comment]
Dear @michaelmaillot ,

all members are direct members.
No, we are not using useSubstrateSearch, but we will test it, soon.
If this will not help, we will raise this issue on sp-dev-docs repo.
Thanks for taking a look into it.

All the Best, Ronny
