### ISSUE TITLE
Dynamic form select term not working

### ISSUE THREAD

**Issue by Perneel** [pnp/sp-dev-fx-controls-react#1303]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.10.0]

#### Observed Behavior
I'm using DynamicForm to edit an item in my list. I have some taxonomy fields which are correctly rendered. However, when clicking on the select terms icon, the panel opens but no terms are loaded. Looking in my network traffic, no call is executed.

![image](https://user-images.githubusercontent.com/4124110/188608575-11a29afb-5c37-449f-be57-8e355fb41059.png)

#### Steps to Reproduce
Simply add a DynamicForm

**Comment by Perneel** [comment]
This seems to be related to the TaxonomyPicker control: https://github.com/pnp/sp-dev-fx-controls-react/issues/1299

**Comment by SmarterJB** [comment]
Hey!
I submitted a PR fixing that problem here #1311!
Hopefully this is going to be included in Version 3.11!

**Comment by AJIXuMuK** [comment]
The PR has been merged and will be included in the next release.
In a meanwhile you can use [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
