### ISSUE TITLE
FolderPicker: get folders of other site url instead of the current context/site

### ISSUE THREAD

**Issue by frankyvc** [pnp/sp-dev-fx-controls-react#1305]
Hi team,

#### Category
[ ] Enhancement, Bug

#### Version
Please specify what version of the library you are using: [ "@pnp/spfx-controls-react": "3.10.0" ]

#### Expected / Desired Behavior / Question
When using the FolderPicker component, i need to be able to select a site url of another site collection (not the one i'm currently at).
With this site url i want to open the FolderPicker component.

#### Observed Behavior
The FolderPicker component always takes the this.props.context (current context and site).
When i check the code in the FolderPicker component, behind the scenes it calls the FolderExplorer and passes the current context. 

#### Steps to Reproduce
Implement the FolderPicker and try to use this for another site, not the current site/context

#### Submission Guidelines
The FolderExplorer component CAN ACCEPT also a property 'siteAbsoluteUrl'.
To fix the issue, i think we only need to add a 'siteAbsoluteUrl' property to the FolderPicker component and pass the correct siteUrl behind the scenes to the FolderExplorer.

Thanks!

**Comment by BlazeOfFeathers** [comment]
Any update about issue?

**Comment by NishkalankBezawada** [comment]
Hello, I have opened a [pull request](https://github.com/pnp/sp-dev-fx-controls-react/pull/1345) and tested it (Please check the screenshots attached in the PR). 

Fingers crossed. 

//Nishkalank Bezawada

**Comment by AJIXuMuK** [comment]
Thanks to @NishkalankBezawada it will be fixed/improved in the next release.
