### ISSUE TITLE
Dynamic form onBeforeSubmit cancels on return true , misleading 

### ISSUE THREAD

**Issue by kanade-saket** [pnp/sp-dev-fx-controls-react#1319]
Hi Team,
I have observed in dynamic form control , for onBeforeSubmit to cancel submission we have to return true from the callback.
Usually in javascript we return false to cancel that event , it is little misleading , at first i could not get it working and after checking the code i observed it cancels on true .
If it cannot be changed , I  am just putting it here so developers like me spend less time figuring this out :)
Thanks.

![image](https://user-images.githubusercontent.com/114055549/191436654-94c4fec9-5c44-47fa-84d9-ee6a33ac4a1a.png)

**Comment by joelfmrodrigues** [comment]
@kanade-saket thanks for raising this. The PR from @SmarterJB was just merged and documentation will be updated in the next release
