### ISSUE TITLE
Unable to find componenet MonacoEditor

### ISSUE THREAD

**Issue by TheThor59** [pnp/sp-dev-fx-controls-react#1323]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version 

- Node: 12.17
- yeoman generator @microsoft/sharepoint: 1.12.1
- SPFx: 1.12.1
- TypeScript: 3.7.7
- React: 16.9
- Gulp: 4.0
- @pnp/spfx-controls-react: 3.10 or 3.7.2

#### Expected / Desired Behavior / Question
I'm not sure that's a bug or a wrong usage from my side.

According to the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/controls/MonacoEditor/#how-to-use-this-control-in-your-solutions) I need to import it using this code :
```import { MonacoEditor } from "@pnp/spfx-controls-react/lib/MonacoEditor";```

#### Observed Behavior
When trying to use the component MonacoEditor provided in the solution the system does not find it.

When doing so, the system does not find this particular component.
![image](https://user-images.githubusercontent.com/20814460/192519504-609fd440-1015-4071-8c18-a46d7a51ea2c.png)

Do I miss something to make it work ? (Wrong Node version for example ?)

#### Steps to Reproduce
I've tested with the version 3.10 (latest) and 3.7 (the one where component was added) of the solution @pnp/spfx-controls-react. I'm performing this on a fresh new spfx web part created using the sharepoint generator (version 1.12.1) with Node v12.17.
Just try to render the component MonacoEditor in render function of any component. Intellisense does not find it.

Thanks!

**Comment by TheThor59** [comment]
Hello,

I'm back on my ticket as I found a way to work with the component changing the import by:
```import { MonacoEditor} from '@pnp/spfx-controls-react/lib/controls/monacoEditor'```

It seems that the integration of the control is not declared the same way the others are.

After looking in the code, it seems that, in folder "src", the file MonacoEditor.ts was not created. Content shall be:
```export * from './controls/monacoEditor/index';```

I'll avoid a pull request on this point as the change to perform is very small.

Thanks for you attention and all your work on this components 😃 

Regards

Victor

**Comment by fabiofranzini** [comment]
@TheThor59 I fixed this issue... This fix will be available into the next release... Thanks
