### ISSUE TITLE
how to add style on auto complete dropdown of TaxonomyPicker?

### ISSUE THREAD

**Issue by kongmengfei** [pnp/sp-dev-fx-controls-react#1324]
Hello, i am using TaxonomyPicker in my spfx webpart, it's perfect but has some pity:

![image](https://user-images.githubusercontent.com/57654821/193237847-3dac37b0-a991-4c92-ad0e-ec15c0a5d9eb.png)

-  left margin is too small
-  when the label is too long, it should have some limit 

I tried to add some padding left to the dropdown by custom CSS (did not find style prop ) but no success:
![image](https://user-images.githubusercontent.com/57654821/193238643-f61e2d35-1660-4c9c-bda6-7194babbc3f1.png)

seems that it's located by absolute position. can you help me?

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version
node : 14.18.2
spfx: 1.15.2

Thanks!

**Comment by michaelmaillot** [comment]
Hi @kongmengfei,

For now there's no way to override control suggestions because it's handled internally through Sass.

But it could be an improvment idea.

**Comment by michaelmaillot** [comment]
Here, I've declare an issue as an enhancement idea here: #1637 

Is that ok for you?
