### ISSUE TITLE
ListItemComments. Suggestions won't appear when rendering on FluentUi Pannel (Was working until now)

### ISSUE THREAD

**Issue by Vertamin** [pnp/sp-dev-fx-controls-react#1326]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.5.0 ,   3.9.0   ] Happens on both

#### Observed Behavior
List item comments rendered in panel. Rendered suggestions are not visible (even though something happens because panel scrollbar sometimes appears depending on number of comments), probably hidden behind panel.

When rendering the same component somewhere else, suggestions appear without issues.

#### Steps to Reproduce
Render a list item comments component in a panel. Try to add someone with @XXX, suggestions won't appear.

Thanks!

Nothing changed by our side, and it was working fine a few days ago. Maybe it has something to do with the suggestion panel styles.

![Error comentarios](https://user-images.githubusercontent.com/69040799/193626328-1febb8f7-af5e-4dc1-8918-ddf1e2b7b8aa.png)

I noticed the div is being populated with data correctly when doing the @. But it isn't able to render on top of the panel.

**Comment by Vertamin** [comment]
Some more info:

I was able to freeze the DOM and manipulate the component styles while showing the suggestions. For some reason, it gets the "Left" css property wrongly and gets warped out of the page.

Once you deactivate this property, at least it's close to where it has to be.

![List item comments bug](https://user-images.githubusercontent.com/69040799/193762285-cfd07a91-55ae-4d6a-963b-6877338385d6.png)

**Comment by michaelmaillot** [comment]
Hi @Vertamin,

Did you have the chance to retry recently? Maybe with latest version (3.15.0)?
