### ISSUE TITLE
When 3.11.0  becomes available in npm? 

### ISSUE THREAD

**Issue by bva999** [pnp/sp-dev-fx-controls-react#1330]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

3.10.0  Version

Hi, When 3.11.0  becomes available in npm?  

Thanks!

**Comment by joelfmrodrigues** [comment]
@bva999 thanks for raising this issue. 3.11.0 is now available on npm. Please let us know if you find any problems.
