### ISSUE TITLE
PeoplePicker component with SPBrowser

### ISSUE THREAD

**Issue by divewoot** [pnp/sp-dev-fx-controls-react#1349]
#### Category
[ x] Question

#### Version
Please specify what version of the library you are using: [ 3.10.0 ]

#### Question
While not able to deploy a solution as Spfx. . . have a react app loaded to sharepoint page via content editor webpart. Using SPBrowser from @pnp/sp to handle authentication, the react app is able to read people fields from a list and display these in a desired table format.  
Is it possible to use the PeoplePicker component from @pnp/spfx-controls-react also in the same react app? When attempting, see error "PeoplePicker' cannot be used as a JSX component.
  Its instance type 'PeoplePicker' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactElement<IPeoplePickerProps, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<IPeoplePickerProps, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
index.d.ts(181, 9): 'children' is declared here.

here is the full PeoplePicker component and how it is currently setup. 

```
import * as React from 'react';
import styles from './SpfxPnpPeoplepicker.module.scss';
import { ISpfxPnpPeoplepickerProps } from './ISpfxPnpPeoplepickerProps';
import { ISpfxPnpPeoplepickerState, IUserDetail } from './ISpfxPnpPeoplepickerState';
import { PeoplePicker, PrincipalType } from "@pnp/spfx-controls-react/lib/PeoplePicker";
import { autobind } from 'office-ui-fabric-react/lib/Utilities';
import { spfi, SPBrowser } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const myTenant: string = 'xxx'
const mySite: string = "xxx"


 // you should use the baseUrl value when working in a SPA to ensure it is always properly set for all requests
 const sp: any = spfi().using(SPBrowser({ baseUrl: "https://"+myTenant+".sharepoint.com/sites/"+mySite }));


export default class SpfxPnpPeoplepicker extends React.Component<ISpfxPnpPeoplepickerProps, ISpfxPnpPeoplepickerState> {
  constructor(props: ISpfxPnpPeoplepickerProps, state: ISpfxPnpPeoplepickerState) {
    super(props);
    sp.setup({
      spfxContext: this.props.context
    });
    this.state = { SuccessMessage: '', UserDetails: [], selectedusers: [] };
    this._getListItem();
  }

  @autobind
  private async _getListItem() {
    const item: any = await sp.web.lists.getByTitle("Teams").items.getById(1).select("Title", "Team/Name").expand("Team").get();
    let usernamearr: string[] = [];
    item.Team.forEach((user: { Name: string; }) => {
      usernamearr.push(user.Name.split('|membership|')[1].toString());
    })
    this.setState({
      selectedusers: usernamearr
    });
  }

  public render(): React.ReactElement<ISpfxPnpPeoplepickerProps> {
    return (
      <div className={styles.spfxPnpPeoplepicker}>
        <PeoplePicker
          context={this.props.context}
          titleText="People Picker"
          personSelectionLimit={3}
          showtooltip={true}
          isRequired={true}
          selectedItems={this._getPeoplePickerItems}
          showHiddenInUI={false}
          principalTypes={[PrincipalType.User]}
          defaultSelectedUsers={this.state.selectedusers}
          resolveDelay={1000} />
        <br></br>
        <button className={styles.button} onClick={this._updateListItem}>Save</button>
        <br></br>
        <br></br>
        <label className={styles.label}>{this.state.SuccessMessage}</label>
      </div>
    );
  }

  @autobind
  private _getPeoplePickerItems(items: any[]) {
    let userarr: IUserDetail[] = [];
    items.forEach(user => {
      userarr.push({ ID: user.id, LoginName: user.loginName });
    })
    this.setState({ UserDetails: userarr })
  }

  @autobind
  private async _updateListItem() {
    let userids: object[] = [];
    this.state.UserDetails.forEach(user => {
      userids.push({ key: user.LoginName });
    })
    const updatedItem = await sp.web.lists.getByTitle("Teams").items.getById(1).validateUpdateListItem(
      [{
        FieldName: "Team",
        FieldValue: JSON.stringify(userids),
      }]);
    this.setState({ SuccessMessage: 'Successfully saved' });
  }
}
```

**Comment by bcobra** [comment]
3.13.0 does not work with es6. 
'PeoplePicker' cannot be used as a JSX component.
  Its instance type 'PeoplePicker' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactElement<IPeoplePickerProps, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<IPeoplePickerProps, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
index.d.ts(192, 9): 'children' is declared here.

**Comment by divewoot** [comment]
Thanks for responding on this. Will mark this closed since using the PeoplePicker outside of SPFx is not possible.
