### ISSUE TITLE
FilePicker, browsing Site / Doclibs loops and floods SPO Service with requests and causes http 429

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/sp-dev-fx-controls-react#1350]
#### Category
[x] Bug

#### Version

Please specify what version of the library you are using: [ 3.11.0]

#### Expected Behavior
Use of the FilePicker to browse a document library with at least one document and select the document

#### Observed Behavior
Open file picker, select Site and then a document library with at least one document causes a flood of requests to the SPO services resulting in HTTP 429 Throttling and temporary tenant disruption.
The user only see data flickering on the screen.

**Develop Toolbar Screenshot**
![Screenshot 2022-11-04 at 11 26 30](https://user-images.githubusercontent.com/5904018/199953390-6a977549-78d7-401c-8e28-f0aad214e09a.png)

#### Steps to Reproduce
1. Create a new SPFx Solution, Webpart with the 1.15.2 Version
2. [Follow the offical installation instructions ](https://pnp.github.io/sp-dev-fx-controls-react/#installation)
3. Implement the default Picker as describe in the [official docs](https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/)
4. gulp serve --nobrowser
5. Start your hosted workbench, add you webpart and browse to a site / document library with at least one file.

Please be aware that reproducing these steps may cause some disruption in your tenant !

**Comment by ferrarirosso** [comment]
Fixed in this [PR](https://github.com/pnp/sp-dev-fx-controls-react/pull/1352)

**Comment by AJIXuMuK** [comment]
Thanks to @ferrarirosso this will be fixed in the next release.

**Comment by PeterWCox** [comment]
In the meantime you can downgrade to V2 @ferrarirosso which worked for me.

  "@pnp/spfx-controls-react": "^2.9.0",

**Comment by erkanch** [comment]
@AJIXuMuK Has this issue been fixed yet? I'm having the same issue with 3.12 version, too. Browsing to the Site or Your Organization tab and picking a library like Site Assets, results in an infinite loop of RenderListDataAsStream calls and the tenant gets throttled. Also, the issue causes the same folders to be rendered repeatedly.
![image](https://user-images.githubusercontent.com/55555837/216789406-25d82acb-7c49-49bc-85ca-a4aac9bc6a44.png)

**Comment by PeterWCox** [comment]
@erkanch I'm no longer involved in SPFX development, but try downgrading to the package version in my above post - that worked for me at time of posting.
