### ISSUE TITLE
FilePicker: 404 error when trying to reach sharepoint

### ISSUE THREAD

**Issue by F-Benjamin** [pnp/sp-dev-fx-controls-react#1353]
#### Category
[ ] Enhancement

[X] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 1.19.0 ]

#### Bug
Using FilePicker to reach a sharepoint site I got a 404 error with this function getSiteMediaLibraries 

Can I access and/or modify FileBrowserService.ts ?
I need to change line 63 64 from attached file below

![fileBrowserService](https://user-images.githubusercontent.com/72012288/200888522-d2d9cea6-33d9-41f6-8713-cc0df06f97ba.PNG)

**Comment by joelfmrodrigues** [comment]
@F-Benjamin as suggested by Michael, can you update to latest version, or do you need to use V1?
