### ISSUE TITLE
ListItemPicker - use list name as well as GUID to point to list

### ISSUE THREAD

**Issue by SemperYak** [pnp/sp-dev-fx-controls-react#1355]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  v3.11  ]

#### Expected / Desired Behavior / Question
Currently, you need the list GUID to point to a list using the 'listId' property. However, can you also add the option to point to a list name? It would be consistent with other PnP patterns.

If we migrate a solution, create a new list with the same name, or reuse a custom component, we need to make sure to change this property based on the new GUID. 

#### Observed Behavior
Add a new property for listName or modify current property to allow entering the list name instead of the GUID.

Thank you!

**Comment by joelfmrodrigues** [comment]
@SemperYak many thanks for the suggestion. Would you be interested in submitting a pull request with the changes?

**Comment by ekapic** [comment]
I'm working on this issue. I'll submit a PR in a day or two.

**Comment by joelfmrodrigues** [comment]
@SemperYak the PR from @ekapic has been merged and the changes will be part of the next release.
Thanks for the great suggestion

**Comment by SemperYak** [comment]
Wonderful! 
Thank you @joelfmrodrigues and @ekapic!
