### ISSUE TITLE
Image picker enhancements

### ISSUE THREAD

**Issue by Moataz-Vodafone** [pnp/sp-dev-fx-controls-react#1367]
Site menu interface should match the way the OneDrive section displays folders. When you select the OneDrive section, folders are displayed using the yellow folder icon, but when you select the Site section, only a grey box is displayed.

<img src="https://user-images.githubusercontent.com/118532886/202696236-24988063-1f3c-44de-9427-460efa6c2268.png" width="600" height="400" />

<img src="https://user-images.githubusercontent.com/118532886/202696263-9c9c2035-cdcc-4258-9e09-083479a8fb2f.png" width="600" height="400" />

Upload doesn't prompt with browser file picker when selected. When you click on Upload using the OOTB image picker, it displays a file picker without the user having to click the Choose file link first.
From a link needs the instruction text updating, and doesn't have any placeholder text. OOTB there is "https://" as placeholder text, and different instructions are provided.

<img src="https://user-images.githubusercontent.com/118532886/202696447-5ff5dcdf-9b33-4aae-86fd-c2415269d598.png" width="950" height="300" />

<img src="https://user-images.githubusercontent.com/118532886/202696486-a44256d3-1f9d-46f8-afcc-7ee44499856c.png" width="950" height="250" />

Selected text doesn't match site theme colour (our theme in the example screenshots uses red):

<img src="https://user-images.githubusercontent.com/118532886/202696533-5e094b96-6540-4ba9-956f-8e8226b556d0.png" width="397" height="300" />

<img src="https://user-images.githubusercontent.com/118532886/202696566-c50c662a-48d3-4c4b-bc40-94e0e21459e8.png" width="600" height="400" />

**Comment by michaelmaillot** [comment]
Hi @Moataz-Vodafone,

Sounds like interesting improvment ideas!

FYI regarding the selected text which doesn't match theme colour, this has been fixed with latest version:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/46f502dc-9e36-4f54-9f80-ecc73c49a504)

**Comment by Ateina** [comment]
Hi @michaelmaillot 
I want to contribute to this issue. Could you please assign it me?
