### ISSUE TITLE
Using FilePicker on "SiteFilesTab", breadcrumb problems

### ISSUE THREAD

**Issue by dalejo09** [pnp/sp-dev-fx-controls-react#1368]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   3.12      ]

#### Expected / Desired Behavior / Question
We expected navegate deep on folders and use the breadcrumb to go back on folders

#### Observed Behavior
Error after go back when we use "Breadcrumb"

#### Steps to Reproduce
Open the "File pickers" and selected the "Site files tab", navigate on folders and use the "breadcrumb" to go back on folders and it doesn't work.

Error: folders.serverRelativeUrl 

Thanks!

**Comment by FredrikEkstroem** [comment]
Hi, I have the exact same issue, it looks like the if statements are wrong in onBreadcrumpItemClick SiteFilePickerTab.tsx

changing from
```typescript
if (node.libraryData === null && node.folderData === null) {
else if (node.folderData !== null) {
else if (node.libraryData !== null) {
```
to
```typescript
if (node.libraryData === undefined && node.folderData === undefined) {
else if (node.folderData !== undefined) {
else if (node.libraryData !== undefined) {
```
fixes the issue

My guess is that the bug was came from when updating to newer spfx version (where new eslint rules comaplains about using == instead of ===)
```typescript
undefined === null
//false
undefined == null
//true
```
https://github.com/pnp/sp-dev-fx-controls-react/tree/ea4c4b157f2b79f8977b0753ff765f3462d7f66f
 @AJIXuMuK

**Comment by joelfmrodrigues** [comment]
@dalejo09 many thanks for raising this issue. A PR from @FredrikEkstroem has just been merged to fix this
