### ISSUE TITLE
FilePicker is not responsive

### ISSUE THREAD

**Issue by jacksonv1lle** [pnp/sp-dev-fx-controls-react#1369]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: 3.12.0

#### Expected / Desired Behavior / Question
The FilePicker component is not usable on mobile devices. Is there a plan to implement a responsive interface for this component? 

I would expect it to behave the same way as the native SharePoint Image web part where the menu can be opened as a floating panel when you click 'Select source'.

![SharePoint-FilePicker](https://user-images.githubusercontent.com/2648490/203305859-041b2a6a-0a8b-4b3e-b8cc-e075513a69f7.png)

#### Observed Behavior
The left navigation menu is still visible on mobile which is occupying most of the screen width leaving very little space for the right-side panel.

**Comment by michaelmaillot** [comment]
Hi @jacksonv1lle,

Did you have the chance to test with latest version (3.15.0)?

I've tested and it's responsive as expected from my side:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/34fa8269-159f-4a50-b08a-61bfb73e00e1)

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/49f71882-76bb-4907-8e28-fe0414e4e6a8)

Can you confirm it?
