### ISSUE TITLE
Dynamic Form - New Item saving broken in 3.12.0

### ISSUE THREAD

**Issue by t0mgerman** [pnp/sp-dev-fx-controls-react#1370]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 3.12.0

#### Expected / Desired Behavior / Question
DynamicForm should save a new item when no listItemId is provided, and when a valid contentTypeId is provided

#### Observed Behavior
The line of source responsible for adding a new item is not reachable when no `listItemId` is provided, and when a valid `contentTypeId` is provided. 

#### Steps to Reproduce
Using version 3.12.0, add a DynamicForm to the page, omitting listItemId, but providing contentTypeId

I believe this is because of the following change in source in the transition from 3.11.0 to 3.12.0 as 3.11.0 still works: https://github.com/pnp/sp-dev-fx-controls-react/commit/eb476041d40ca285fc85628b4c8c304c4c2444eb

**Comment by mgitta** [comment]
I also have the same issue. Any workaround idea?

**Comment by bva999** [comment]
I also have the same issue. Any workaround idea?

`Error onSubmit TypeError: Cannot read properties of undefined (reading 'startsWith')
    at DynamicForm.<anonymous> (DynamicForm.js:247:1)
    at step (DynamicForm.js:58:1)
    at Object.next (DynamicForm.js:39:45)
    at DynamicForm.js:33:1
    at new Promise (<anonymous>)
    at ./node_modules/@pnp/spfx-controls-react/lib/controls/dynamicForm/DynamicForm.js.__awaiter (DynamicForm.js:29:1)
    at DynamicForm._this.onSubmitClick (DynamicForm.js:88:44)
    at Object.onClick (DynamicForm.js:762:124)
    at BaseButton._this._onClick (BaseButton.js:192:1)
    at Object.Ve (sp-pages-assembly_en-us_037878821c0a639b1a1bff69163f3274.js:69:21733)`

**Comment by rkmighwal** [comment]
I have same issue. Any workaround?

**Comment by t0mgerman** [comment]
@rkmighwal try SPFX 1.13.x and Fluent UI @ 7.174.1 

@mgitta @bva999 For me, downgrading to 3.11.0 worked. If nobody submits a PR with a fix soon, I'd be happy to

**Comment by rkmighwal** [comment]
Still not fixed, have tried with 3.10.0 as well, with SPFx 1.15.2

**Comment by mgitta** [comment]
@rkmighwal  Reverting back to 3.11.0 solved it for us also.

**Comment by rkmighwal** [comment]
Reverting back to 3.11.0 solved it for me as well.

**Comment by joelfmrodrigues** [comment]
@t0mgerman would be great if you could send a PR 🙂

**Comment by SpDev17** [comment]
Reverting back to 3.11.0 does not solve the problem for my document library dynamic form with custom content type, Title column is not rendering in case of 3.11.0
while in 3.12.0, Title column was rendering on dynamic form which will be used as a document set name(It should). As mentioned above, creation of new item is broken when creating a new document set.

SPFX : 1.6

**Comment by bva999** [comment]
Can somebody send a PR? I found the problem. 
![image](https://user-images.githubusercontent.com/12149939/215447921-f9c54db6-1072-4b76-aec5-b0b857c86cff.png)
This line is superfluous and always leads to an error

**Comment by bva999** [comment]
Can somebody send a PR? I found the problem. 
![image](https://user-images.githubusercontent.com/12149939/215447921-f9c54db6-1072-4b76-aec5-b0b857c86cff.png)
This line is superfluous and always leads to an error
Could you ? @AJIXuMuK

**Comment by IRRDC** [comment]
I came across the same issue and when I checked the code I did so (without noticing - which led me to believe that just the compiled code was wrong) in the 'dev' branch where those two lines have been changed to
`else if (contentTypeId === undefined || contentTypeId === '' || !contentTypeId.startsWith('0x0120')) {`
which should work.

**Comment by bva999** [comment]
Fixed in version 3.13.0

**Comment by joelfmrodrigues** [comment]
Closing, thanks everyone
