### ISSUE TITLE
listitemattachments shows the file explore 3 times on new attachment on Add click

### ISSUE THREAD

**Issue by aidanbha79** [pnp/sp-dev-fx-controls-react#1373]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[*] Bug

[ ] Question

#### Version 

Please specify what version of the library you are using: [  1.19.0, 1.20.3    ]

#### Expected / Desired Behavior / Question
should upload file and then display in grid

#### Observed Behavior
Uploads the file but then shows the File Explorer window a further 2 times. 

#### Steps to Reproduce
click the Add command bar button on list item and then select file. 

`
import * as strings from "FormFieldStrings";
import * as React from "react";
import { ISPFormFieldProps } from "./SPFormField";
import { PrimaryButton, TextField } from "@fluentui/react";
import { useEffect, useState } from "react";
import { ListItemAttachments } from "@pnp/spfx-controls-react";
import { GQMSAppContext } from "../../components/ContextProvider";

interface ISPFormFieldPropsExtension extends ISPFormFieldProps{
    listId?: string;
    itemId?: number;
}

export const SPFieldAttachmentsEdit: React.FunctionComponent<ISPFormFieldPropsExtension> = (
  props
) => {
   const [context] = React.useContext(GQMSAppContext);
   const [listItemAttachmentsComponentReference, setListItemAttachmentsComponentReference] = useState<React.RefObject<ListItemAttachments>>();
   debugger;
   const [listId, setListId] = useState<string>(props.listInfo.Id);
   const [itemId, setItemId] = useState<number>(props.itemId);
 
   useEffect(() => {
    if (!listItemAttachmentsComponentReference || !listItemAttachmentsComponentReference.current) {
      setListItemAttachmentsComponentReference(React.createRef<ListItemAttachments>());
    }
  }, [listItemAttachmentsComponentReference]);

  
  return (

    <ListItemAttachments 
      ref={listItemAttachmentsComponentReference} 
      context={context.webPartContext}
      listId={listId}
      itemId={itemId}
    />

 );
};
`

**Comment by michaelmaillot** [comment]
Hello @aidanbha79,

Did you have the chance to retry with latest version (3.15.0)?

I've done it using most of your code snippet and it's working on my side:

![spfx-controls-listitemattachment-explorer](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/8a754f42-0d5c-4879-bf06-14cdd292d664)

**Comment by aidanbha79** [comment]
Hi @michaelmaillot thank you for this. We managed to get a workaround for this and it is now being used successfully but hopefully, this will be useful for someone or me in the future if I need to do it again.
