### ISSUE TITLE
EnhancedThemeProvider control should accept other contexts than just the WebPart

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1374]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question

When using the EnhancedThemeProvider control, we should be able to include it in any SPFx app, whether it's a WebPart, an app customizer or a form customizer.

#### Observed Behavior

When trying to use the EnhancedThemeProvider control in a form customizer as an example, we can't, as the "context" property is waiting for a WebPartContext object.

#### Steps to Reproduce

* create an SPFx extension (app customizer or form customizer)
* install the lastest version of @pnp/spfx-dev-fx-controls-react
* try to add the EnhancedThemeProvider control to the extension

My suggestion would be to take the BaseComponentContext instead of the WebPartContext as props object property, then keep the same behavior as it's actually on the component, in order to cover all the SPFx extensions types. Or maybe am I missing something?

**Comment by michaelmaillot** [comment]
Maybe I can give a try on this one?

**Comment by joelfmrodrigues** [comment]
@michaelmaillot absolutely, we love contributions :)
