### ISSUE TITLE
label prop is missing on RichText

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1375]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question

When using the RichText control, I'm expecting to be able to refer  the component to a label (through an id) or mentioning a label text as a prop available

#### Observed Behavior

No label prop or an "id" attribute (which is available in the react-quill library used under the hood) that could be linked to a label.

#### Steps to Reproduce

* create and SPFx app (WebPart, extension,...)
* add the RichText control
* try to add a label with reference to the control through an id, or try to add a label prop

Two approaches from my perspective:

* drill up the "id" prop already available in the react-quill component
* add a new prop "label" as it exists on Fluent UI controls like TextField, which accepts a string

**Comment by michaelmaillot** [comment]
I can give a try on this one if you don't mind 🙂

**Comment by joelfmrodrigues** [comment]
Hi @michaelmaillot , that would be great ☺️

**Comment by michaelmaillot** [comment]
Great, assign it to me please @joelfmrodrigues 🤗
