### ISSUE TITLE
Dynamic Form - PeoplePicker field returns 'Null Mellissa' when new form is submitted.

### ISSUE THREAD

**Issue by S1mpleLim3** [pnp/sp-dev-fx-controls-react#1380]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.11.0]

#### Expected / Desired Behavior / Question
_Editing a list item where user field is empty, loads the form with a person named melissa null

#### Observed Behavior
_When you submit a list item in new form where peoplepicker field is optional and you leave it empty, it submits successfully, but when you edit the item, the peoplepicker field loads a person named Melissa Null, where it should be empty.

#### Steps to Reproduce
_Submit a item keeping user field empty and edit the same item.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @S1mpleLim3,

Is your problem still occur? Did you try with latest version (3.15.0)?

I tried to add a new item with empty PeoplePicker field and load the same item after, nothing is displayed in the field.

**Comment by NishkalankBezawada** [comment]
@michaelmaillot I have already pushed a PR relating to this issue. [PR 1570](https://github.com/pnp/sp-dev-fx-controls-react/pull/1570)

**Comment by michaelmaillot** [comment]
Hi @NishkalankBezawada,

Thanks for this info. Good to know! So this issue should be closed soon if everything's ok 🙂

**Comment by NishkalankBezawada** [comment]
Hello again, Yes this should be closed. Perhaps this was a duplicate to [1421](https://github.com/pnp/sp-dev-fx-controls-react/issues/1421)

Thanks,
Nishkalank

**Comment by joelfmrodrigues** [comment]
Fixed as closed, thanks everyone
