### ISSUE TITLE
Add override for ComboBoxListItemPicker number of items returned

### ISSUE THREAD

**Issue by mtburkett** [pnp/sp-dev-fx-controls-react#1390]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

Currently the ComboBoxListItemPicker control uses query string parameters like the following for its API call: $select=Id,Title&$filter=&**$top=100**&$orderBy=Title%20asc

I suggest having an override for the $top parameter, maybe capped at the current max for API requests (5000 I think?).

Thanks!

**Comment by michaelmaillot** [comment]
Hi @mtburkett,

You can specify the number of items you want to return through the `itemLimit` prop (which is set by default to 100. More info in the control [doc page](https://pnp.github.io/sp-dev-fx-controls-react/controls/ComboBoxListItemPicker/#implementation).

Is it what you've looked for?
