### ISSUE TITLE
Richtext does not support the same text formatting options as the SharePoint Text WebPart

### ISSUE THREAD

**Issue by emilyTeichrib** [pnp/sp-dev-fx-controls-react#1391]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.12.0     ]

#### Expected / Desired Behavior / Question
If you click on "More" in the toolbar and the dialog opens, you should be able to make the same settings in the dialog as in the dialog for the SharePoint Text WebPart.
The SharePoint Text WebPart has for normal text the default font size 18. Additionally the following font sizes are selectable: 
![image](https://user-images.githubusercontent.com/70626311/208069607-462409dd-357c-4bb0-b929-85b1d89c2afa.png)

#### Observed Behavior
However, in the Richtext component, the default font size for normal text is 17 and the following font sizes are selectable instead of the same: 
![image](https://user-images.githubusercontent.com/70626311/208069858-cb62e501-98e4-4436-a43a-b5bc77e02233.png)

#### Steps to Reproduce
Click in the edit mode in the richtext box and then on the right on the three dots (More), then the dialog "Text formatting" opens. If, on the other hand, you go to the SharePoint Text WebPart in Edit mode, click on the three dots (more styles) and then on "more options", an almost identical dialog opens. However, this dialog has different font sizes.

Thanks!

**Comment by Ateina** [comment]
Hello @michaelmaillot 
I suppose it was fixed with https://github.com/pnp/sp-dev-fx-controls-react/pull/1706 
and is part of the package since 3.17

**Comment by joelfmrodrigues** [comment]
@Ateina many thanks for the heads up, I will close this issue.
@emilyTeichrib I know it's been a while since this issue was open, but please let us know if something is still to be resolved and we will reopen it.

Many thanks!
