### ISSUE TITLE
pnp/spfx-controls-react 1.21.1 cannot find module FieldPicker

### ISSUE THREAD

**Issue by Billiardist94** [pnp/sp-dev-fx-controls-react#1399]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/pnpjs": "1.3.5",
    "@pnp/sp": "1.3.5",
    "@pnp/spfx-controls-react": "1.21.1",
    "@pnp/spfx-property-controls": "1.14.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "^5.135.6",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-tabs": "^3.0.0"
]

#### Expected / Desired Behavior / Question
Using FieldPicker to select one or multiple available site fields

#### Observed Behavior
I see an error "Cannot find module '@pnp/spfx-controls-react/lib/FieldPicker' or its corresponding type declarations." at 
import { FieldPicker } from "@pnp/spfx-controls-react/lib/FieldPicker";

#### Steps to Reproduce
Import the control into your component:
import { FieldPicker } from "@pnp/spfx-controls-react/lib/FieldPicker";

#### Submission Guidelines

Thanks!

**Comment by AJIXuMuK** [comment]
@Billiardist94 - `FieldPicker` controls is not part of v1. It was included in v3.
