### ISSUE TITLE
[Documentation] Wrong image name reference in Accordion control

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1408]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question

The documentation of the Accordion control should display images correclty.

#### Observed Behavior

The Accordion control documentation is missing an image reference:

![image](https://user-images.githubusercontent.com/44271458/210312140-a18bcb3f-361c-4c51-8c6a-523b0b10175a.png)

#### Steps to Reproduce

* go to the Accordion documentation page located [here](https://pnp.github.io/sp-dev-fx-controls-react/controls/Accordion/)

**Comment by michaelmaillot** [comment]
I can handle this one if that's ok 🙂

**Comment by joelfmrodrigues** [comment]
@michaelmaillot sure!
