### ISSUE TITLE
[Documentation] Missing image reference in Progress Steps Indicator control

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1409]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question

The documentation of the Progress Steps Indicator control should display images correclty.

#### Observed Behavior

The Progress Steps Indicator control documentation is missing an image reference:

![image](https://user-images.githubusercontent.com/44271458/210313199-d1793c2e-4862-45ec-bddd-21eea5c18d90.png)

#### Steps to Reproduce

* go to the Progress Steps Indicator documentation page located [here](https://pnp.github.io/sp-dev-fx-controls-react/controls/ProgressStepsIndicator/)

**Comment by michaelmaillot** [comment]
The referenced image was missing in the original PR of the control [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1322/files#diff-1cbfe9ca101da64b03e20d2e8c101ba571cd579a90a88aabc617b9a04b3fcfc0R7).

@joaojmendes, would you mind pushing it?

**Comment by joelfmrodrigues** [comment]
@michaelmaillot many thanks for raising this, a PR was just merged to resolve it
