### ISSUE TITLE
[Development] Update the SPFx source project to add an extension + form customizer

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1410]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question

When working on the spfx-controls-react for improving features or fixing bugs, some controls require to be tested on other contexts than a web part.

The improvment would involve:

* the addition of an application customizer
* the addition of a form customizer
* the update of the existing web part's manifest to be available as a Teams Tab
   *  So that everything linked to the TeamsJS SDK will be available for tests
* the update of the developers documentation page / [MPA](https://pnp.github.io/sp-dev-fx-controls-react/guides/mpa/) to indicate how to test the different components (including the deployment of the [SharePoint Framework library for Microsoft Graph Toolkit](https://learn.microsoft.com/en-us/graph/toolkit/get-started/mgt-spfx))

#### Observed Behavior

In the current SPFx solution, there's only a web part.

#### Steps to Reproduce

N/A

**Comment by michaelmaillot** [comment]
I can give a try on this one if that sounds relevant to you, maintainers 🙂 

This is a suggestion based on my own experience during my first contribution. I'm opened to discussion regarding this.

**Comment by joelfmrodrigues** [comment]
Hi @michaelmaillot absolutely, thanks for the suggestion. Every improvement is really appreciated!
I will assign this item to you so no one else picks it up
