### ISSUE TITLE
[Enhancement] Implement custom sorting of fields in a DynamicForm

### ISSUE THREAD

**Issue by tahawkins21** [pnp/sp-dev-fx-controls-react#1416]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [Latest]

#### Expected / Desired Behavior / Question

I would like to see the ability to control the order of list columns that are rendered using a DynamicForm component.
Assumption is that a property could be added to IDynamicFormProps.tsx "fieldOrder" that takes an array of internal field names that will be rendered in order, or similar.

It looks like IDynamicFieldProps already has an Order prop to work with, though I haven't figured out how to make that work in DynamicForm.

Thanks!

**Comment by wuxiaojun514** [comment]
It looks like dynamic form uses the column order on content type level , you can configure content type column order as work around
![image](https://user-images.githubusercontent.com/29603048/215381854-95bf64d9-ea30-45fa-8755-0a5de96c280e.png)

**Comment by michaelmaillot** [comment]
Hi @tahawkins21,

Following linked PR merged, this enhancement should be available in the next beta release.

Thanks to you for raising this and @srpmtt for the contribution!
