### ISSUE TITLE
Conflict error when installing package for SPFx 1.16.1

### ISSUE THREAD

**Issue by sallaadithya** [pnp/sp-dev-fx-controls-react#1420]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [  3.12.0  ]

Please specify what version of the SPFx you are using: [  1.16.1  ]

#### Expected / Desired Behavior / Question
Create a new project with SPFx v1.16.1 using yeoman (yo @microsoft/sharepoint), and install the spfx-controls-react package, the installation should successful without any errors.

#### Observed Behavior
There were a lot of peer dependency, conflict errors in the console related to @fluentUI.
For screenshots, please find the attachment.

#### Steps to Reproduce
1. Create a new project with SPFx v1.16.1
2. Install the spfx-controls-react package using npm commands

Thanks!
Aditya Reddy.
[spfx-controls-react error.docx](https://github.com/pnp/sp-dev-fx-controls-react/files/10392936/spfx-controls-react.error.docx)

**Comment by stevebeauge** [comment]
Hello @sallaadithya 

This controls library is itself a SharePoint project. And the SPFX version of the project is 1.16.1.

This is a common pitfall of creating reusable sharepoint framework component libraries. SPFX libs should be set as peer dependencies out of SPFX project while having a SPFX project for testing, but such pattern are a lot harder to implement.

To sum up, I think you should stick to the 1.16 version of SPFX in your project. Unless you actually need the fixes that came from the patch version 1.16.1, it will be easier I guess.

**Comment by michaelmaillot** [comment]
Hi @sallaadithya,

Does the answer provided by @stevebeauge is what you've expected?

FYI I've tested installing latest version (3.15.0 which is based on SPFx 1.17.3) on a SPFx 1.17.4 project and no peer dependancies are displayed:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/683a5bdd-e927-4c11-9948-6a78c95f3ecd)
