### ISSUE TITLE
PeoplePicker Control - Shows wrong value in Dynamic Form when null is provided

### ISSUE THREAD

**Issue by S1mpleLim3** [pnp/sp-dev-fx-controls-react#1421]
#### Category
[ ] Enhancement

[X] Bug

[X] Question

#### Version

 3.11.0

#### Expected / Desired Behavior / Question
When a list item has a people field empty, when same listItemId is provided to Dynamic form, peoplepicker control should be empty.

#### Observed Behavior
Since Dynamic form uses people picker control for user fields and if a list item has a Person field which is empty, in Dynamic form when same list item id is provided, the people picker control is prepopulated with a person "Null, Melissa". This happens because, empty person field returns field value as null but the peoplepicker control converts null to "null" (string). Which then prepopulates the field with Null, Melissa. 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/112174574/212365691-c1bac6d9-a173-49db-9d10-6bed8042de71.png">
<img width="171" alt="image" src="https://user-images.githubusercontent.com/112174574/212365996-a695fc27-e0e4-4066-a6b4-f0b0a9e2b209.png">

Here you can see, even though in list its empty, but it shows up in Form.

#### Steps to Reproduce
Create a list item with People field as empty, then provide same ListItemId to dynamic form.

I feel this happens because the control converts everything that sharepoint returns to String, hence null becomes "null", because i tried giving null to defaultSelectedUser of peoplePicker field and it behaves correctly.

@AJIXuMuK, @wobba, @joelfmrodrigues Can anyone look into this. 

Thanks.

**Comment by AJIXuMuK** [comment]
From IM conversation: seems like the issue appears when user's name contains `Null` (as on the screenshot in the description).

@S1mpleLim3 - would you be able to implement a fix and create a PR?

Thanks!

**Comment by NishkalankBezawada** [comment]
@S1mpleLim3 I have created a [PR](https://github.com/pnp/sp-dev-fx-controls-react/pull/1570) for this.

//Nishkalank

**Comment by joelfmrodrigues** [comment]
The PR to fix this issue has been merged and the fix should be in the beta release in a few minutes

**Comment by joelfmrodrigues** [comment]
New release just published, closing
