### ISSUE TITLE
Dynamic form trying to load Image tags with wrong internal name

### ISSUE THREAD

**Issue by Perneel** [pnp/sp-dev-fx-controls-react#1422]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The form to open.

#### Observed Behavior
When the dynamic form is loading, I get a 400 bad request error. This is resulting in a spinner that keeps loading, no feedback to the user.

In developer tools (F12):
**Request:**
/_api/web/lists(@listId)/Fields/getByInternalNameOrTitle('**MediaServiceImageTags_0**')/InternalName?@listId=guid'_thelistguid_'
**Response:**
`{"error":{"code":"-2147024809, System.ArgumentException","message":"Column 'MediaServiceImageTags_0' does not exist. It may have been deleted by another user."}}`

If I inspect my list (SP Insider), the field with internal name _MediaServiceImageTags_0_ does not exist. However, _MediaServiceImageTags_ does. Where do the fields get read from? As a work-around, is there a way to exclude fields from being added to the dynamic form?

#### Steps to Reproduce
Create a subsite in a site collection
Add a document library
Create a dynamic form with react

**Comment by AJIXuMuK** [comment]
@Perneel - thank you for reporting the issue!
Could you please provide the configuration you're using to create a `<DynamicForm>`?

Thanks!

**Comment by Perneel** [comment]
@AJIXuMuK , thanks for your response. The goal is to edit metadata of a selected file. Users provide documents in a library and with the help of a React webpart, they get an overview with a list of existing documents. If they select an item, metadata is shown together with the document itself in a custom viewer. By clicking the edit button, an edit form (dynamicform) opens in a Panel (fluent ui):

![image](https://user-images.githubusercontent.com/4124110/215710156-e5bda797-3d46-4e0f-b3e0-09ca7984a1b6.png)

When I click on the edit button, I get the error message as shown in my original post and the form keeps showing the loading spinner.
The code for showing/hiding the panel is a simple boolean parameter. 

````
const dialog = (selectedDocument) ?
    <Panel
      type={PanelType.medium}
      isOpen={!isDialogHidden}
      onDismiss={() => { closeEditForm(); }}
    >
      <DynamicForm
        context={props.context}
        listId={oplaadzoneListId}
        listItemId={selectedDocument.id}
        onCancelled={() => { closeEditForm(); }}
        //onBeforeSubmit={async (listItem) => { return true; }}
        onSubmitError={(listItem, error) => { alert(error.message); }}
        onSubmitted={async (listItemData) => { console.log(listItemData); closeEditForm() }}
      />
    </Panel>
    : <></>;
````

**Comment by martinlingstuyl** [comment]
I'm experiencing the same @AJIXuMuK, @Perneel,

On my dev-tenant, when creating a new list with new Taxonomy Columns, things work as expected.
But on another tenant, the display names of the taxonomy note fields are the same as their internal names. 
There is no Field_0 to find. 

The problem seems to be in this line:
`https://github.com/pnp/sp-dev-fx-controls-react/blob/391c821a229f79867427be0457efa64d84f6ed51/src/controls/dynamicForm/DynamicForm.tsx#L429`

It's trying to get the Taxonomyfields internal name by using its internal name. 
So the entire API call seems superfluous...

**Comment by martinlingstuyl** [comment]
The point is that the code makes the assumption that the corresponding note field has a specific display name. Which is not always the case.

I worked around it by updating the names of the note fields to `<internalNameOfTaxField>_0`. In other words, what the code expects it to be. 

But this is probably not watertight.

**Comment by martinlingstuyl** [comment]
I've created a PR to fix this @joelfmrodrigues, 🤙

**Comment by joelfmrodrigues** [comment]
@martinlingstuyl just saw that, super quick turnaround, many thanks!
Will try to review and test later today/tomorrow

**Comment by martinlingstuyl** [comment]
You've got to forge the iron while it's hot, they say over here 😁
