### ISSUE TITLE
TaxonomyPicker onNewTerm add to selected terms

### ISSUE THREAD

**Issue by Sheikonh** [pnp/sp-dev-fx-controls-react#1429]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [3.3.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I am using the TaxonomyPicker "onNewTerm" to create a new term within the term set, and although this works correctly, I wonder how can we add the newly added term to the picker as if it was selected from the already existing terms. I reviewed the documentation but it does not seem like the TaxonomyPicker can be used in a controlled way.

Thanks!

**Comment by AJIXuMuK** [comment]
@Sheikonh - thanks for bringing this up.
Yes, Taxonomy Picker can't be used in controlled way. It is by design.

My suggestion here would be to have some wrapper that will temporary remove the picker and return it back with the updated set of `initialValues`
