### ISSUE TITLE
[Enhancement] [ListItemComments] Add a parameter to highlight the specified comment to support "Go to Comment" link in Comment Notification

### ISSUE THREAD

**Issue by wuxiaojun514** [pnp/sp-dev-fx-controls-react#1430]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.12 ]

#### Behavior in OOTB List Item Comment
When you @someone in list item comment, he/she will get a notification in outlook like this
![image](https://user-images.githubusercontent.com/29603048/215248903-41d0b29c-b59d-4a78-a0be-557e3971fa7f.png)
Then this user can go to this specified comment directly by click **"Go to Comment"** button in the mail. 
The comment will be highlighted with light blue background color (Perhaps it uses color in theme) in this "Go to Comment" link.
![image](https://user-images.githubusercontent.com/29603048/215249789-ce7a331c-455d-4dfe-94c9-d3d4d38ee8ad.png)
The "Go to Comment" link is like  https://testxxx.sharepoint.com/sites/xxxx/Lists/Project/DispForm.aspx?ID=1&commentId=1&e=LURoEsg5Zki4cS4SgcIG7w&at=15&CT=1674882847351&OR=OWA-NT&CID=c3a04ee0-40b5-9591-e6a4-3fac33046a64, which contains **commentId** in url parameter

#### Expected
Right now I am using **ListItemComments** control in Form Customization. The comment whose id is in **Go to Comment** link won't be highlighted on ListItemComments. So it is hard to figure out which comment is mentioned in the notification.
So I want to add an optional parameter to render the specified comment with different background color. We can call this parameter "highlightedCommentId".
Developer can fetch  **commentId** in url parameter first, then use this new parameter to highlight comment.

I can try to implement this enhancement.
We can have discussion here if there is better idea to handle this kind of scenario.

Thanks!

**Comment by AJIXuMuK** [comment]
@wuxiaojun514 - it is a great idea!
Feel free to create a PR and we can review it.

Thanks!

**Comment by wuxiaojun514** [comment]
Thank you. I will find some time to implement it.
