### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith') when submit DynaimcForm

### ISSUE THREAD

**Issue by yungfu** [pnp/sp-dev-fx-controls-react#1431]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.12 ]

#### Expected / Desired Behavior / Question
Create an item including `Title` field only, submit the DynamicForm, an item should be added to list.

#### Observed Behavior
When the `DynamicForm` property `contentTypeId={undefined}`, exception occurred:

> Error onSubmit TypeError: Cannot read properties of undefined (reading 'startsWith')
>     at DynamicForm.<anonymous> (DynamicForm.js:247:1)
>     at step (DynamicForm.js:58:1)
>     at Object.next (DynamicForm.js:39:45)
>     at DynamicForm.js:33:1
>     at new Promise (<anonymous>)
>     at WgIJ.__awaiter (DynamicForm.js:29:1)
>     at DynamicForm._this.onSubmitClick (DynamicForm.js:88:44)
>     at Object.onClick (DynamicForm.js:762:124)
>     at BaseButton._this._onClick (BaseButton.js:192:1)
>     at Object.Ve (react-dom-17-bundle_none_138dc8c5d231c91f848c.js:2:21796)

#### Steps to Reproduce

1. Create a list with `Title` column only
2. Add a list view commmand extension to open a panel, contains the `DynamicForm`
3. Specify `DynamicForm` required properties,
4. Make `contentTypeId={undefined}` and `listItemId={undeifned}`
5. Type some value to `Title` field in form
6. Click submit, form grayed out, and exception out in browser console.

It seems **DynamicForm.tsx** line 241 make an opposite judgement
```
     if (contentTypeId === undefined || contentTypeId === '') {
         if (!contentTypeId.startsWith('0x0120')) {...}
     }
```

Thanks!

**Comment by AJIXuMuK** [comment]
@yungfu - thank you for submitting the issue.
It will be fixed in the next release.

**Comment by martinlingstuyl** [comment]
@AJIXuMuK, when can we expect the next release? I'm running into this issue as we speak 😁

**Comment by joelfmrodrigues** [comment]
> @AJIXuMuK, when can we expect the next release? I'm running into this issue as we speak 😁

@martinlingstuyl we are discussing a new release but have no exact date yet. Soon, we hope
