### ISSUE TITLE
Cannot get value for projected field Manager_x005f_EMail.

### ISSUE THREAD

**Issue by DesireHarsh11** [pnp/sp-dev-fx-controls-react#1436]
I'm trying to get users using pnp js through people picker field but,I'm (Cannot get value for projected field Manager_x005f_EMail) select query.
My users are active yet,i'm not able to get EMail.

**Comment by michaelmaillot** [comment]
Hi @DesireHarsh11,

Does your issue still occur? If so, do you have a code snippet to share, in order to better understand what you're trying to achieve?

**Comment by rozalinaag** [comment]
I have the same issue. If there are several inserted elements, then you can get only Id and Title using expand. Other fields cannot be obtained if several elements are inserted

.items.select(
      'person/Title',
      'person/avatar',
      'person/Id',
    )
    .expand('person')

Cannot get value for projected field avatar. If items inserted only one, that everything work fine and i can get field avatar.

**Comment by anthonybutcher-sm** [comment]
Today I am getting the same issue email address is not readable - *....sharepoint.com/sites/IGM/_api/web/lists/GetByTitle('Taxonomy')/items?$expand=ReadPermission&$select=Id,Title,ReadPermission/ID,ReadPermission/EMail

Reposnse 
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>-2146232832, Microsoft.SharePoint.SPException</m:code>
<m:message xml:lang="en-US">Cannot get value for projected field ReadPermission_x005f_EMail.</m:message>
</m:error>

even if i Wittle the query down to a min - works for title and ID, but not EMail - ?$expand=ReadPermission&$select=ReadPermission/EMail    -
