### ISSUE TITLE
Request to add ViewPicker similar to SitePicker and ListPicker

### ISSUE THREAD

**Issue by rzempo** [pnp/sp-dev-fx-controls-react#1439]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

#### Version
Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question
Use a controls to get the views from a list similar to SitePicker and ListPicker

#### Observed Behavior
A ViewPicker control doesn't currently exists

Thanks!

**Comment by joelfmrodrigues** [comment]
@rzempo many thanks for the suggestion. 
We do have a view picker control as part of the property controls repository, so perhaps it's not that complex to create a control here using that one as a reference plus the list picker.
Would you be interested in contributing and submitting a PR with the new control?

**Comment by rzempo** [comment]
@joelfmrodrigues, sure. It'll be my first time doing that. Can you please point me in the right direction?

**Comment by joelfmrodrigues** [comment]
@rzempo really sorry for the delay, a lot of projects are ongoing at the moment...
Try to start by following the docs and let us know if you get stuck or find any issues

https://pnp.github.io/sp-dev-fx-controls-react/guides/mpa/

If you never contributed to community repositories before and are looking for more information/suggestions on where to start, I recommend also having a look here: https://pnp.github.io/sharing-is-caring/
There are sessions you can join and ask any questions

**Comment by NishkalankBezawada** [comment]
Hi @rzempo 

Nice suggestion! If I find the time I'm definitely willing to make the controls above. 

@joelfmrodrigues, I will be creating a PR in couple of days for this :) 

Thanks!
Nishkalank

**Comment by NishkalankBezawada** [comment]
Hey @joelfmrodrigues, 

Greetings for the day. I have created a new [PR 1505](https://github.com/pnp/sp-dev-fx-controls-react/pull/1505) for the above issue. Request you to please review. 

Happy Easter in advance, 
Nishkalank Bezawada

**Comment by joelfmrodrigues** [comment]
@NishkalankBezawada many thanks. Only seeing this now as I was off work and away from home with very limited internet access.
Will try to review as soon as possible

**Comment by NishkalankBezawada** [comment]
@joelfmrodrigues Thanks for the reply, Once reviewed please let me know your comments and feedback :) May be change it according to your review

**Comment by NishkalankBezawada** [comment]
Hello @AJIXuMuK, I had deleted the previous PR and created a new PR for this control since i could not find your comments for the PR. Kindly review and comment.

//Nishkalank

**Comment by joelfmrodrigues** [comment]
@rzempo the PR from @NishkalankBezawada was finally merged (sorry for the very long delay) and the control should be available on the beta release in a few minutes.
Many thanks for the suggestion
