### ISSUE TITLE
How to change font size of ListView Cells

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1452]
#### Category
[ ] Enhancement

[ ?] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [   3.12      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I have ` <ListView  listClassName={styles.list}` in my *.tsx
and `
.list {
  font-size: 20px;
}`  in my .module.scss file 

the cells should show as font size 20px

#### Observed Behavior

The font size is still 12PX and I can see it was overridden by other class root-240
![image](https://user-images.githubusercontent.com/5054931/218425335-ad94e76e-031b-4e55-941c-69b58ec7e0d2.png)

#### Steps to Reproduce
follow the documentation and add font size other than 12px

I even overridden class ms-DetailsRow-cell and it did not change.

what other way do I have to make just one Listview cells show in another font or size?

Thank you

**Comment by joaojmendes** [comment]
@Ofer-Gal , the className only apply styles to root component of ListView.  I think the best option is using the  render property  on ViewField to render you custom styles and format.

**Comment by Ofer-Gal** [comment]
Thank you @joaojmendes 
I resolved this by adding zoom 1.3 to the container's DIV
