### ISSUE TITLE
Dynamic Form context is not accepting ListViewCommandSet context

### ISSUE THREAD

**Issue by praveenhooda** [pnp/sp-dev-fx-controls-react#1468]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    "@microsoft/sp-listview-extensibility": "1.16.1", "@pnp/spfx-controls-react": "^3.12.0"     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
ListViewCommandSet is should be assignable to BaseComponentContext of Dynamic Form control

#### Observed Behavior
Type 'import("/node_modules/@microsoft/sp-component-base/dist/index-internal").BaseComponentContext' is not assignable to type 'import("/node_modules/@pnp/spfx-controls-react/node_modules/@microsoft/sp-component-base/dist/index-internal").BaseComponentContext'.
  Types have separate declarations of a private property '_serviceScope'.ts(2322)
IDynamicFormProps.d.ts(9, 5): The expected type comes from property 'context' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<DynamicForm> & Readonly<IDynamicFormProps> & Readonly<...>'

#### Steps to Reproduce

1. context: BaseComponentContext; is declared as property of MyComponent which is rendering DynamicForm as below
<DynamicForm
						context={props.context}
						listId={"List ID"}

						listItemId={1}
						onCancelled={() => { console.log('Cancelled') }}
						onBeforeSubmit={async (listItem) => { return false; }}
						onSubmitError={(listItem, error) => { alert(error.message); }}
						onSubmitted={async (listItemData) => { console.log(listItemData); }}>
					</DynamicForm>

2. MyComponent is created in ListViewCommandSet and this.context of ListViewCommandSet is assigned to context property of MyComponent

Thanks!

**Comment by martinlingstuyl** [comment]
@praveenhooda, did you try working around this by casting it to any?

```typescript 
<DynamicForm context={this.props.context as any} />
```

That works on my side with a Form Customizer.

**Comment by joelfmrodrigues** [comment]
@praveenhooda as suggested by @martinlingstuyl , please try to cast to `any` as a temporary workaround. This is due to differences in SPFx versions between your project and the PnP controls repo, and should be resolved as part of the next release which we expect to happen very soon

**Comment by praveenhooda** [comment]
> @praveenhooda, did you try working around this by casting it to any?
> 
> ```ts
> <DynamicForm context={this.props.context as any} />
> ```
> 
> That works on my side with a Form Customizer.

@martinlingstuyl Thanks for the suggestion it solves the problem, yes I tried that and it worked! Cheers

**Comment by praveenhooda** [comment]
> @praveenhooda as suggested by @martinlingstuyl , please try to cast to `any` as a temporary workaround. This is due to differences in SPFx versions between your project and the PnP controls repo, and should be resolved as part of the next release which we expect to happen very soon

Thanks @joelfmrodrigues  for taking time and confirming the resolution, and thanks for sharing the root cause!

**Comment by joelfmrodrigues** [comment]
> > @praveenhooda as suggested by @martinlingstuyl , please try to cast to `any` as a temporary workaround. This is due to differences in SPFx versions between your project and the PnP controls repo, and should be resolved as part of the next release which we expect to happen very soon
> 
> Thanks @joelfmrodrigues for taking time and confirming the resolution, and thanks for sharing the root cause!

@praveenhooda we released a new version of the controls last Friday that is using SPFx 1.16.1. If your solution is also 1.16.1, you should be able to upgrade and no longer need the workaround.

**Comment by martinlingstuyl** [comment]
> we released a new version of the controls last Friday

oh, nice, I missed that. Will try it out immediately!
