### ISSUE TITLE
<RichText isEditMode={false}

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1477]
[? ] Bug
[? ] Question

#### Version
Please specify what version of the library you are using: [  3.13.0   and   3.14.0-beta.4277292  ]
#### Expected / Desired Behavior / Question

RichText isEditMode={false} should show the full width of the text the same as isEditMode={true}

#### Observed Behavior
The lines are broken as if there is a limit to the line length 
![image](https://user-images.githubusercontent.com/5054931/221592094-5bc8f00a-edde-414a-bb2a-803a686f2cb9.png)

it should look like so
![image](https://user-images.githubusercontent.com/5054931/221592194-e5083d6f-757c-4a37-9579-11c60c97c73e.png)

#### Steps to Reproduce
`       <div style={{ width: '100%', }}>
                    <RichText isEditMode={false} value={importantNotes} />
                    <RichText isEditMode={false} value={detailNotes} />
                    {hasUserInput &&
                        <RichText isEditMode={true} value={userInput} onChange={getUserInput} />
                    }
     </div>
`

Is there a settings or class to override?

Thanks!

**Comment by joaojmendes** [comment]
@Ofer-Gal , I can't reproduce that behaviour , can you check or give more details please...

<img width="1351" alt="Screenshot 2023-03-05 at 18 48 16" src="https://user-images.githubusercontent.com/12551125/222979919-8dd3261b-3acb-4e17-8e61-df521e13e565.png">
<img width="1775" alt="Screenshot 2023-03-05 at 18 50 20" src="https://user-images.githubusercontent.com/12551125/222979949-ffcb60d0-cf5e-4e97-a783-2b788c7cb99b.png">
<img width="1351" alt="Screenshot 2023-03-05 at 18 49 25" src="https://user-images.githubusercontent.com/12551125/222979950-7315fc98-edf9-4a54-8ee4-df3cf253b3e5.png">
<img width="1351" alt="Screenshot 2023-03-05 at 18 48 36" src="https://user-images.githubusercontent.com/12551125/222979951-35c92a50-ccff-46f2-a89a-cea0978d2778.png">

**Comment by Ofer-Gal** [comment]
Thats all I have. I will use another control instead.
Thank you.

**Comment by Ofer-Gal** [comment]
Now with 3.14.0 I have similar issue:
With isEditMode={ture}
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/5054931/51c0130d-588e-4e17-b97f-b16262dfbeed)

with isEditMode={false}
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/5054931/adcceb42-12a9-4197-bccb-801481f5c3fc)

I am glad the read only has no border but why is the text broken at the start?
Is there any style I can apply?

**Comment by michaelmaillot** [comment]
Hi @Ofer-Gal,

I tried with latest version (3.15.0) and couldn't repro. Did you have the chance to try too? If it's the same behavior, do you have a code snippet or how the content is saved / loaded?
