### ISSUE TITLE
FilePicker - tile view always selects the wrong file

### ISSUE THREAD

**Issue by hstuermannfellowmind** [pnp/sp-dev-fx-controls-react#1478]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.12.0 / 3.13.0 ]

Detected bug in 3.12 and updated to 3.13. Still getting this bug and did not found an issue for this here.

#### Expected / Desired Behavior / Question
When I select a file in the FilePicker in tile view, it will select the file I clicked.

#### Observed Behavior
Not the selected file is selected. The file before is selected.
![image](https://user-images.githubusercontent.com/78954504/221838807-113ebb30-6d8f-4b33-9816-1e5427102733.png)

#### Steps to Reproduce
- Create a minimal SPFX Project
- Add FilePicker like this, change the urls to a existing image library and web for example
```
<FilePicker
            hidden={false}
            isPanelOpen={true}
            onCancel={() => {}}
            hideStockImages={true}
            hideLinkUploadTab={true}
            hideLocalMultipleUploadTab={true}
            hideLocalUploadTab={true}
            hideOneDriveTab={true}
            hideOrganisationalAssetTab={true}
            hideRecentTab={true}
            hideSiteFilesTab={false}
            hideWebSearchTab={true}
            webAbsoluteUrl={"url_to_list_web"}
            defaultFolderAbsolutePath={"url_to_list"}
            accepts= {[".gif", ".jpg", ".jpeg", ".bmp", ".dib", ".tif", ".tiff", ".ico", ".png", ".jxr", ".svg"]}
            buttonIcon="FileImage"
            onSave={(filePickerResult: IFilePickerResult[]) => {}}
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            context={context as any}
          />
```
- Run webpart and try tile view

**Comment by ktskumar** [comment]
May I work on this issue!

**Comment by joelfmrodrigues** [comment]
New release just published, closing
