### ISSUE TITLE
FilePicker - recent tab empty until re-render

### ISSUE THREAD

**Issue by c-eiser13** [pnp/sp-dev-fx-controls-react#1482]
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.13.0       ]

#### Expected / Desired Behavior / Question
When the file picker opens and defaults to the recent tab, should show results.

#### Observed Behavior
When the file picker opens and defaults to the recent tab, nothing is shown until a re-render. I can resize the page, or navigate to a different tab, stock images for example, then back to Recent and content is shown correctly. Initial load:
![image](https://user-images.githubusercontent.com/42096464/222832553-c676c554-4527-4a20-85e3-2fa87811e1c5.png)

After resizing the page and a re-render:
![image](https://user-images.githubusercontent.com/42096464/222832766-1a89c923-25d7-4941-8846-e918539dbef3.png)

In debugging the project, looks like the issue is in the _getItemCountForPage method when trying to set the column width, the surfaceRect.width prop is 0, so the width is not set correctly until a re-render.
![FilePickerNaNError](https://user-images.githubusercontent.com/42096464/222832170-86f24cec-ef08-44bd-96f7-04c6fbabd54d.png)

I've added some default values for columnCount and columnWidth when the surfaceRect.width is 0 and this solves the issue, I just do not work with the Fluent List control much so not sure this is the best solution.
![image](https://user-images.githubusercontent.com/42096464/222832373-fe6af612-897e-4a05-b8ee-809b0ee0ca7b.png)

I will create a PR with this change for review.

#### Steps to Reproduce
I was able to debug the project and repro by testing in the ControlsTest web part that is part of the project. Open the file picker when defaulting to the Recent tab and notice there are no results.

**Comment by joelfmrodrigues** [comment]
New release just published, closing
