### ISSUE TITLE
Dynamic Form won't update Single-TaxonomyFieldValue on a ListItem

### ISSUE THREAD

**Issue by SmarterJB** [pnp/sp-dev-fx-controls-react#1488]
#### Category
[ ] Enhancement

[ x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: v3.13.0

#### Expected / Desired Behavior / Question
When saving the dynamic form when changing a Single Taxonomy Field Value, it should save the value to the list item.

#### Observed Behavior
The Single Taxonomy Field Value is not saved at all, and no error is observed. Reproducing this over the SharePoint REST API it seems that there is a problem when updating a list item with a Single Taxonomy Field Value with the standard Update method for the list item.

I tested this out with the UpdateValidateListItem method, and it works fine, so I will try to change the `onSubmitClick` method in the DynamicForm.tsx to not use `listitem.update` but to use `updateValidateListItem` instead! So a Pull Request will come in soon to fix this!

#### Steps to Reproduce
Create a list with a single taxonomy field (AllowMultipleSelection=false), and try to change a list item with the Dynamic Form. It will not change the value of the Single Taxonomy Field.

Thanks!

**Comment by HohoMike** [comment]
Could this be related to [this issue](https://github.com/pnp/pnpjs/issues/2725)? If it is changing the update to a validateUpdateListItem, could fix it.

**Comment by michaelmaillot** [comment]
Hi @SmarterJB,

I've tested on my side with a single taxonomy field value and it's updated without any issue:

{"__metadata":{"type":"SP.Data.EmployeeOnboardingListItem"},"Description":"<p>ezaeazezae</p><p>azezaezaezae</p>","Taxo":{"__metadata":{"type":"SP.Taxonomy.TaxonomyFieldValue"},"Label":"Rights","TermGuid":"042cad7f-276a-44a1-932a-9974a95fd338","WssId":"-1"}}

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/4642095f-75d6-4344-9ffa-49fc3d79b82a)

And under the hood, it's still the "update" method from PnPjs which is called (POST request on the `/_api/web/lists/items` endpoint.

Can you give us more info about the context? Are you trying to interact with a doc item like suggested by @HohoMike?
