### ISSUE TITLE
Can I use a [sp-dev-fx-controls-react] for SP16 On-Premise

### ISSUE THREAD

**Issue by geogikk92** [pnp/sp-dev-fx-controls-react#149]
#### Category
[ ] Enhancement
[ ] Bug
[x] Question

Can I use a [sp-dev-fx-controls-reac] for SP16 On-Premise ?? 

After install **sp-dev-fx-controls-reac** with **npm install @pnp/spfx-controls-react --save --save-exact** i have following errors:

![untitled](https://user-images.githubusercontent.com/14110861/46614767-5547e580-cb1f-11e8-8d4f-fae6295d8163.png)

This is content of my  **.yo-rc.json** file is:

`{
  "@microsoft/generator-sharepoint": {
    "version": "1.4.0",
    "libraryName": "travels",
    "libraryId": "10340777-f8eb-4423-ba85-3fb5794a7bf1",
    "environment": "onprem"
  }
}`

**Comment by estruyf** [comment]
@geogikk92 we recently set the minimal Office UI Fabric version to `5.120.0`, this could have an impact on older project versions.

Could you test out version `1.7.0` by installing it as follows: `npm i @pnp/spfx-controls-react@1.7.0 -S`

**Comment by cameronsibbald** [comment]
I've been testing 1.7.0 with an on premise solution and have been able to get it to working.

I had to manually change the ControlStrings setting to `../node_modules/@pnp/spfx-controls-react/lib/loc/{locale}.js` in order to get it to serve properly. I was receiving the following error until I changed it:
```
Error - 'collectLocalizedResources' sub task errored after 9.43 ms
 "Error for resource \"ControlStrings\": No localized files found under the \"lib\" directory matching pattern \"node_modules/@pnp/spfx-controls-react/lib/loc/{locale}.js\""
```

**Comment by AJIXuMuK** [comment]
Closing as answered
