### ISSUE TITLE
Dynamic form not loading existing list item with DateTime field

### ISSUE THREAD

**Issue by Perneel** [pnp/sp-dev-fx-controls-react#1492]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.13.0]

#### Observed Behavior
When the form is loading, I receive following error.
![image](https://user-images.githubusercontent.com/4124110/226890883-b8ebfa3c-aadd-48de-8283-79e8f41bc4f3.png)

It seems the value is not converted to Date, which causes `toLocaleDateString()` to throw an error as it does not exist on a string. If I check with the debugger, I can see that date variable is actual a string:
![image](https://user-images.githubusercontent.com/4124110/226890748-62d67fce-f83a-4b22-aa90-c85b98974ead.png)

I think it is related to this code in the repo:
https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/dynamicForm/dynamicField/DynamicField.tsx#L305
https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/dynamicForm/dynamicField/DynamicField.tsx#L316

#### Steps to Reproduce
Implement a Dynamic form with a DateField which references to a listItemId

````
<DynamicForm
    context={props.context as any}
    listId={"<list_guid>"}
    listItemId={1}
    onCancelled={() => { console.log('Cancelled') }}
    onBeforeSubmit={async (listItem) => { return false; }}
    onSubmitError={(listItem, error) => { alert(error.message); }}
    onSubmitted={async (listItemData) => {
        console.log(listItemData);
}} />
````

**Comment by GuidoZam** [comment]
Hi @Perneel do you still have this issue? I tried with the latest version (3.14.0) and it's working like a charm.
