### ISSUE TITLE
Readme documents highlight extension does not work correctly

### ISSUE THREAD

**Issue by ValerasNarbutas** [pnp/sp-dev-fx-controls-react#1495]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]
[Latest]
_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Looks like were are breaking symbols in  readme files under guides or contributing:
[https://pnp.github.io/sp-dev-fx-controls-react/guides/contributing/](https://pnp.github.io/sp-dev-fx-controls-react/guides/contributing/)

![image](https://user-images.githubusercontent.com/16476453/228536705-f87111d0-30ee-4158-afd0-f16f7b8fe53a.png)

I can work on this one @joaojmendes 
Just wondering is extension used does not support "```sh " and should be "```bash"

change this:
```sh
# comment
```

to this:
```bash
# comment
```

In all documents which using "#" for commenting.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @ValerasNarbutas,

Are you still interested into submitting a PR? 🙂

**Comment by ValerasNarbutas** [comment]
Hey, Sure @michaelmaillot, i can do it

**Comment by ValerasNarbutas** [comment]
i did forget this one :) 
i will check it soon

**Comment by ValerasNarbutas** [comment]
@michaelmaillot added fixes.
