### ISSUE TITLE
Dynamic form not loading and "SitePages" in Dynamic form error url.

### ISSUE THREAD

**Issue by manuhinCCS** [pnp/sp-dev-fx-controls-react#1504]
#### Category

[ ] Bug

#### Version

Please specify what version of the library you are using: [   "@pnp/spfx-controls-react": "3.12.0"      ]

#### Expected / Desired Behavior / Question

Dynamic Form should load without any issue.

#### Observed Behavior
Dynamic form not loading. Getting below error in console  and getting the error in DynamicForm.js:635.

**Error get field informations Error: Error making HttpClient request in queryable [404]  ::> 
    at new HttpRequestError (parsers.js:130:1)
    at Function.<anonymous> (parsers.js:145:1)
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:45)
    at fulfilled (tslib.es6.js:73:42)**

![image](https://user-images.githubusercontent.com/112081775/230153622-92bcf50e-53d8-4ea1-82dc-33def7332814.png)

#### Steps to Reproduce

Code:
<DynamicForm
                    context={this.props.context as any}
                    listId={"38823001-10ba-4bf1-8107-74d111e25820"}
                    listItemId={1803}
                    onCancelled={() => { console.log('Cancelled') }}
                    onBeforeSubmit={async (listItem) => { return false; }}
                    onSubmitError={(listItem, error) => { alert(error.message); }}
                    onSubmitted={async (listItemData) => { console.log(listItemData); }}>
                </DynamicForm>

Noticed that **"SitePages"** is coming in the failed URL. 
https://tenant.sharepoint.com/sites/sitename/SitePages/_api/web/lists('38823001-10ba-4bf1-8107-74d111e25820')/items(1801)
![image](https://user-images.githubusercontent.com/112081775/230155651-80aa5104-1131-48c3-b601-a163d450cc97.png)

Detailed error:

GET https://tenant.sharepoint.com/sites/sitename/SitePages/_api/web/lists('38823001-10ba-4bf1-8107-74d111e25820')/items(1803) 404
YmBQ.FetchClient.fetch @ net.js:35
retry @ sphttpclient.js:95
(anonymous) @ sphttpclient.js:114
clU1.SPHttpClient.fetchRaw @ sphttpclient.js:113
(anonymous) @ sphttpclient.js:58
step @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
clU1.SPHttpClient.fetch @ sphttpclient.js:25
(anonymous) @ pipeline.js:161
TZA7.PipelineMethods.send @ pipeline.js:144
descriptor.value @ pipeline.js:76
next @ pipeline.js:34
(anonymous) @ pipeline.js:76
Promise.then (async)
descriptor.value @ pipeline.js:76
next @ pipeline.js:34
(anonymous) @ pipeline.js:76
Promise.then (async)
descriptor.value @ pipeline.js:76
next @ pipeline.js:34
pipe @ pipeline.js:46
(anonymous) @ pipeline-binder.js:14
(anonymous) @ operations.js:28
step @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
(anonymous) @ operations.js:13
spGet @ operations.js:50
ncXi._SharePointQueryable.get @ sharepointqueryable.js:103
(anonymous) @ DynamicForm.js:395
step @ DynamicForm.js:58
(anonymous) @ DynamicForm.js:39
fulfilled @ DynamicForm.js:30
Promise.then (async)
step @ DynamicForm.js:32
(anonymous) @ DynamicForm.js:33
WgIJ.__awaiter @ DynamicForm.js:29
DynamicForm._this.getFieldInformations @ DynamicForm.js:380
WgIJ.DynamicForm.componentDidMount @ DynamicForm.js:741
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
enqueueSetState @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
y.setState @ react-16-bundle_none_7c853fe1c9f3209f62bb.js:2
(anonymous) @ ContractUpload.tsx:321
step @ contract-index-web-part.js:436202
(anonymous) @ contract-index-web-part.js:436183
fulfilled @ contract-index-web-part.js:436174
Promise.then (async)
step @ contract-index-web-part.js:436176
(anonymous) @ contract-index-web-part.js:436177
r90l.__awaiter @ contract-index-web-part.js:436173
r90l.ContractUpload._bindDraftData @ ContractUpload.tsx:224
(anonymous) @ ContractUpload.tsx:216
Promise.then (async)
(anonymous) @ ContractUpload.tsx:214
step @ contract-index-web-part.js:436202
(anonymous) @ contract-index-web-part.js:436183
(anonymous) @ contract-index-web-part.js:436177
r90l.__awaiter @ contract-index-web-part.js:436173
(anonymous) @ ContractUpload.tsx:206
Promise.then (async)
(anonymous) @ ContractUpload.tsx:206
step @ contract-index-web-part.js:436202
(anonymous) @ contract-index-web-part.js:436183
(anonymous) @ contract-index-web-part.js:436177
r90l.__awaiter @ contract-index-web-part.js:436173
r90l.ContractUpload.getdata @ ContractUpload.tsx:203
(anonymous) @ ContractUpload.tsx:199
step @ contract-index-web-part.js:436202
(anonymous) @ contract-index-web-part.js:436183
(anonymous) @ contract-index-web-part.js:436177
r90l.__awaiter @ contract-index-web-part.js:436173
(anonymous) @ ContractUpload.tsx:182
Promise.then (async)
(anonymous) @ ContractUpload.tsx:182
step @ contract-index-web-part.js:436202
(anonymous) @ contract-index-web-part.js:436183
(anonymous) @ contract-index-web-part.js:436177
r90l.__awaiter @ contract-index-web-part.js:436173
r90l.ContractUpload.getUserMessageSettings @ ContractUpload.tsx:180
r90l.ContractUpload.componentDidUpdate @ ContractUpload.tsx:159
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
enqueueSetState @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
y.setState @ react-16-bundle_none_7c853fe1c9f3209f62bb.js:2
(anonymous) @ ContractIndex.tsx:227
Promise.then (async)
(anonymous) @ ContractIndex.tsx:208
step @ contract-index-web-part.js:240725
(anonymous) @ contract-index-web-part.js:240706
(anonymous) @ contract-index-web-part.js:240700
RDda.__awaiter @ contract-index-web-part.js:240696
RDda.ContractIndex.getUserMessageSettings @ ContractIndex.tsx:206
(anonymous) @ ContractIndex.tsx:195
step @ contract-index-web-part.js:240725
(anonymous) @ contract-index-web-part.js:240706
(anonymous) @ contract-index-web-part.js:240700
RDda.__awaiter @ contract-index-web-part.js:240696
RDda.ContractIndex.componentDidMount @ ContractIndex.tsx:194
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
rc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Wc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.render @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
VLw2.ContractIndexWebPart.render @ ContractIndexWebPart.ts:54
t._renderWithAccessibleTitle @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
t._onInViewport @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._internalFirstTimeRender @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e._renderWebPart @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
e.loadWebPart @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
ms @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Lc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ki @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ac @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
hc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ki @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Qi @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
qi @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
gc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
ad @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
t.render @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
t._renderSingleCanvasCore @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._renderCanvas @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._tryRenderSingleCanvas @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._tryRenderCanvas @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
a._onFieldsLoad @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
f @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e.processAction @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e.dispatch @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._endInitialize @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
t.componentDidMount @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t.componentDidMount @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
ms @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Lc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ki @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ac @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
hc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
uc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Xc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
gc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
ad @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
t.render @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
t.onRender @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._renderCoreRouter @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t.onRender @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._onRender @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._render @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
e._initializeApplication @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e.startApplication @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e.navigate @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e.navigateToApplication @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
c @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
s @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e._startApplication @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e._startApplication @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
e.start @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ CreateContract.aspx?rid=1490&Aid=3303&loadSPFX=true&debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js:80
(anonymous) @ CreateContract.aspx?rid=1490&Aid=3303&loadSPFX=true&debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js:80

Thanks!

**Comment by Jeremielopo** [comment]
Hello,
I have the same issue with my webpart it was working first but it started to throw this error.
Does someone have an answer ?

**Comment by h3nn3** [comment]
This issue occures also in my solution. Can anyone provide a solution
