### ISSUE TITLE
`DynamicForm` respectETag option error

### ISSUE THREAD

**Issue by 6gal6ler6** [pnp/sp-dev-fx-controls-react#1509]
# Category
[ ] Enhancement

[x] Bug

[ ] Question

## Error

Implementation #1395 is causing error

## Steps to Reproduce

- Update to version 3.13.0
- Leave the `respectETag` default to true
- Try to update an item

**Error message:** Error making HttpClient request in queryable [412]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ClientServiceException","message":{"lang":"en-US","value":"The request ETag value '\"8\"' does not match the object's ETag value '\"68be87d5-96e5-49ab-8477-9b17070c8a33,9\"'."}}}

**Comment by michaelmaillot** [comment]
Hi @6gal6ler6 I can't repro on my side. Can you give me more details, such as the props you're using?

I tried with the following ones:

```
<DynamicForm
      context={this.props.context as any}
      listId={this.props.context.list.guid.toString()}
      listItemId={this.props.context.itemId} />
```

**Comment by 6gal6ler6** [comment]
Hello This is the Code I have:

```typescript

currentIntakeFormProps = {
        context: webpartContext as any,
        listId: LIST_ID,
        listItemId: ItemID,
        contentTypeId: ContentTypeID
}

<DynamicForm
     {...currentIntakeFormProps}
     respectETag={false} //This one was set to false.
     onBeforeSubmit={async (listItem) => { _handleBeforeSaveItem(listItem); return false; }}
     onSubmitError={(listItem, error) => { hideSpinner(); alert(error.message); }}
     onSubmitted={async (listItemData) => { await _handleSaveItem(listItemData); }}>
 </DynamicForm>



```

**Comment by michaelmaillot** [comment]
OK and what does the `_handleSaveItem` method do? Can you show display it here?
