### ISSUE TITLE
DynamicForm MultiChoice field doesn't work

### ISSUE THREAD

**Issue by bva999** [pnp/sp-dev-fx-controls-react#1510]
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

[ 3.13.0 ]

#### Expected / Desired Behavior / Question
If list has MultiChoice field, it doesn't work on DymanicForm. On change of the field you get next error: 

#### Observed Behavior
If list has MultiChoice field, it doesn't work on DymanicForm. On change of the field you get next error: 

`Error MultiChoice_selection TypeError: seletedItemArr_1.splice is not a function
    at DynamicField._this.MultiChoice_selection (DynamicField.js:344:1)
    at DropdownBase._this._onChange (Dropdown.base.js:36:1)
    at DropdownBase.<anonymous> (Dropdown.base.js:699:1)
    at pr (sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:69:54054)
    at ms (sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:69:91499)
    at Lc (sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:69:108084)
    at IKDZ.t.unstable_runWithPriority (sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:69:4739)
    at Ki (sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:69:50343)
    at Ac (sp-pages-assembly_en-us_4cafeb97a327fa2ca2288389688aa683.js:69:104823)`

Thanks!

**Comment by bva999** [comment]
UPD: It doesn't work only when creating an item, when updating it works.

**Comment by bva999** [comment]
Unfortunately with the new version (3.15.0) the bug has not been fixed.... And it’s been almost 4 months now

**Comment by bva999** [comment]
```
private MultiChoice_selection = (event: React.FormEvent<HTMLDivElement>, item: IDropdownOption): void => {
    const {
      changedValue
    } = this.state;

    try {
      let selectedItemArr;
      if (changedValue === null && this.props.fieldDefaultValue !== null) {
        selectedItemArr = [];
        this.props.fieldDefaultValue.forEach(element => {
          selectedItemArr.push(element);
        });
      }
      else
        selectedItemArr = !changedValue ? [] : changedValue;

      if (item.selected) {
        selectedItemArr.push(item.key);
      }
      else {
        const i = selectedItemArr.indexOf(item.key);
        if (i >= 0) {
          selectedItemArr.splice(i, 1);
        }
      }

      this.setState({ changedValue: selectedItemArr });
      this.props.onChanged(this.props.columnInternalName, selectedItemArr);
    } catch (error) {
      console.log(`Error MultiChoice_selection`, error);
    }
  }
```

When Item is Created `changedValue` is a text value. 
And this lines causes an error: 
 ```
else
        selectedItemArr = !changedValue ? [] : changedValue;

      if (item.selected) {
        _selectedItemArr.push(item.key); ( ERROR HERE!!! )
      }
```

Because in this case selectedItemArr  is not an array but text!!
PLEASE FIX IT! It’s been 4  months!!!

**Comment by GuidoZam** [comment]
Hi @bva999 it should be fixed now.

**Comment by bva999** [comment]
Hi @GuidoZam . Thank you.

**Comment by joelfmrodrigues** [comment]
PR merged and the fix should be available on the beta release within a few minutes.
