### ISSUE TITLE
Issues with SPFx 1.16.1 

### ISSUE THREAD

**Issue by penleychan** [pnp/sp-dev-fx-controls-react#1514]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

3.13.0

#### Observed Behavior
Unable to gulp serve SPFx 1.16.1 with @pnp/spfx-controls-react 3.13.0

Getting bunch of errors multiple Module not found such as: 

Module not found: Error: Can't resolve '@ms/sp-telemetry'
Module not found: Error: Can't resolve '@ms/sp-edit-customer-promise' 

Downgraded to 3.12.0, no issues running SPFx 1.16.1 via gulp serve.

**Comment by michaelmaillot** [comment]
Hi @penleychan,

I don't have any issue from my side. Did you have the chance to try with latest version (3.15.0)?
