### ISSUE TITLE
DynamicForm field override - how to set and display preset value

### ISSUE THREAD

**Issue by mtburkett** [pnp/sp-dev-fx-controls-react#1523]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [3.13.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I am using field overrides in dynamic form. I only need to set the text of a field with the result of a function that gets data from a list, does some modifications to the data and changes a state. I run this function on ComponentDidMount and set the state "eventID".

So, this what my field render looks like now:

public renderEventNumber = (fieldProperties: IDynamicFieldProps): React.ReactElement<IDynamicFieldProps> =>{
    // console.log(fieldProperties);
    const {
      columnInternalName,
      required,
      fieldTitle,
      newValue,
      onChanged
    } = fieldProperties;

    onChanged(columnInternalName, **this.state.eventID**);

    return <div>
      <div className={styles.titleContainer}>
        <Icon className={styles.fieldIcon} iconName={"TextField"}/>
        {/* <Label required={required}>{fieldTitle}</Label>  */}
        <label className={(required) ? styles.fieldRequired + ' ' + styles.fieldLabel : styles.fieldLabel}>{fieldTitle}</label>
      </div>      
      <TextField       
        defaultValue={newValue}
        disabled 
      />
    </div>   
  }

So what I am seeing is that the value of the newValue variable does get set with the onChanged function, but it never does display in the text field presumably because when the compnent is rendered newValue is null.

I can definitely use this.state.eventID as the default value and it will display properly.

My question is, is there a better way to handle this scenario, possibly some way to access the dynamicform field values besides the passed onChanged function in fieldproperties?

Thanks!

**Comment by michaelmaillot** [comment]
Hi @mtburkett,

Do you still have an issue with this?

I don't have a "good" answer here, I've tried to use React Ref in the field override but it appears that it's not ready / available in `componentDidMount`. And no, the overriden fields are not available for update as props directly.

Right now, the best I can propose is to set the desired list item field in the DynamicForm `onBeforeSubmit` event, where you'll have the opportunity to update the field value with your state (and just keep the value in the field override like you've done with the init value for displaying purposes).

Is it something that could be possible for you?
