### ISSUE TITLE
PeoplePicker search too strict for organisation formatting. 

### ISSUE THREAD

**Issue by sweco-seerjf** [pnp/sp-dev-fx-controls-react#1534]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.13.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

**_Have not updated, but I saw no fixes for people picker in 3.14.0_**

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

Make search terms less strict. Will improve user experience because they can more freely search for an employee. 

I am not sure if this issue is within your control. But if possible add fuzzy search?

If there are other solutions to this issue I would appreciate some suggestions how to solve it.  

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

My organisation is using the format [Lastname, Firstname] (notice the comma) for employee avatars. Unfortunately this format seems to break the search functionality of the people picker. When searching for a employee the common way would most likely be to write their firstname then press space and then the lastname. But because "Firstname Lastname" != "Lastname, Firstname" no results show up. 

Example 1: Typing only firstname or lastname is fine but as soon as you press space you no longer will match any employees. 

Example 2: Typing lastname and if the employee the user is searching for have a common lastname; they need to include the firstname. But if the user do not include the comma "Lastname, Firstname" no results will show up.

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

I am not sure where this kind of formatting for avatar names are set, but I guess it is within the top level tenant? Or even withing the windows administrator?

If you are able to change this the problem will be quite obvious.

Thanks!

**Comment by akshataggrwal** [comment]
Hi @michaelmaillot, 

We've encountered a similar issue in our application. Upon inspecting the OOB SPO people picker field, it appears to be using the same API(/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser), with the inclusion of an additional parameter called 'UserSubstrateSearch.' However, I've found limited documentation on this parameter. Do you have any guidance or insights on effectively utilizing this parameter in the PnP control to address the issue?

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20832945/df7318d0-2946-45b8-9631-4bbc6e662d25)

Thanks!

**Comment by michaelmaillot** [comment]
Hello,

FYI I've submitted a PR with the ability to enable substrate search

**Comment by michaelmaillot** [comment]
Hello,

Linked PR has been merged, the feature should be soon available in next beta release.

Thanks again @sweco-seerjf & @akshataggrwal for reaising this!
