### ISSUE TITLE
Bundle error with SPFx 1.17.2 in Form Customizer project

### ISSUE THREAD

**Issue by PKOITC** [pnp/sp-dev-fx-controls-react#1540]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   3.14.0  ]
Same problem on 3.13.0 but 3.12.0 seems to work fine.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

`gulp bundle --ship` should build app package.

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

`gulp bundle --ship`  produces the following error:
`Module not found: Error: Can't resolve '@microsoft/sp-property-pane/lib/propertyPaneFields/propertyPaneButton/PropertyPaneButton'`

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

- `yo @microsoft/sharepoint` - Select "Form Customizer" project type and React framework
- `npm install @pnp/spfx-controls-react --save --save-exact`
- in "src\extensions\..\components\...tsx" add `<DynamicForm context={this.props.context as any} listId='...'  />` into render() method along with `import { DynamicForm } from '@pnp/spfx-controls-react';`
- `gulp bundle --ship`  produces the error.

Same problem on 3.13.0 but on 3.12.0 seems to work just fine.

Thanks!

**Comment by AJIXuMuK** [comment]
@PKOITC - could you please provide a test solution? I can't repro it.
