### ISSUE TITLE
Error when trying to use in SPFX 1.17.2

### ISSUE THREAD

**Issue by lhdeveloper** [pnp/sp-dev-fx-controls-react#1543]
#### Category
[x] Bug

#### Version
Please specify what version of the library you are using: latest

#### Expected / Desired Behavior / Question
Error when trying to implement a control inside a webpart:
sp-pages-assembly_en-us_c3101e7c5d8dbbcc3ca06e3e193641cf.js:70 Could not load quick-access-web-part in require. Error: Script error for: @microsoft/sp-lodash-subset

I just installed the dependency, imported it into my TSX file as shown in the documentation and at the same time the webpart stops working and I get the reported error.

**Comment by JacSavage** [comment]
@lhdeveloper 
Are you working in the workbench or have you bundled the webpart to display it on a different page? If not on the workbench, try re-bundling and adding the spfx to the appcatalog.

**Comment by lhdeveloper** [comment]
> @lhdeveloper
> Are you working in the workbench or have you bundled the webpart to display it on a different page? If not on the workbench, try re-bundling and adding the spfx to the appcatalog.

Hello, friend. Yes, I tested it in every way, both on the workbench and on a clean page and also on the home of a communication site. None of the forms occur as expected. I get a script error with something related to the patch.

**Comment by lhdeveloper** [comment]
Hello everybody.
I'm still having this problem.

I'm trying to use the FilePicker component in a webpart, in my TSX file (I don't know if it's possible but I believe so because I'm not using the framework that handles the webpart's controls) and I still keep getting this error:

VM6383:34 GET https://relative-path.invalid/@microsoft/sp-lodash-subset.js net::ERR_NAME_NOT_RESOLVED

VM6383:34 GET https://relative-path.invalid/ControlStrings.js net::ERR_NAME_NOT_RESOLVED

GET https://relative-path.invalid/@microsoft/sp-http.js net::ERR_NAME_NOT_RESOLVED

Could not load page-collab-profile in require. Error: Script error for: @microsoft/sp-lodash-subset

Does anyone know if it's possible to use the spfx-react-controls components within TSX or just in the TS file that handles the settings panel?

Even after calling the component, I built the application and uploaded it again to the appcatalog, but without success.
![Captura de Tela 2023-06-13 às 19 03 00](https://github.com/pnp/sp-dev-fx-controls-react/assets/15928104/435d933a-72e3-4259-9d08-49fa696ddc69)

**Comment by lhdeveloper** [comment]
Testing my application, I was able to run the webpart on the workbench page.

In a page created within the site (sitepages), the webpart does not load due to the errors reported in the previous comment.

**Comment by joelfmrodrigues** [comment]
@lhdeveloper Hi there, the controls can definitely work on TSX pages, that's what they are for. We have a separate repository for web part property pane controls.
Could you please confirm that this is the control you are trying to use? https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/

Could you please share the code you are using with your control? (Remove any sensitive information please)

Also, to build the package can you double-check that you are using `gulp bundle --ship` and `gulp package-solution --ship`? My main point to validate is the `--ship` parameter to ensure that the component doesn't try to link back to your localhost.

**Comment by lhdeveloper** [comment]
@joelfmrodrigues 

Thanks for your feedback, I managed to get it working even running locally.

A doubt that arose is that when I open FilePicker it has taken a while to load the Recent Documents.

Is this normal or is there something I can do to make it faster?
Here's an image of what the screen looks like.
![Captura de Tela 2023-06-16 às 00 07 08](https://github.com/pnp/sp-dev-fx-controls-react/assets/15928104/8ad85c0f-65b0-4116-b077-7f4b36812adf)

**Comment by joelfmrodrigues** [comment]
@lhdeveloper I'm not sure about the time to load recent documents. Can you check on the browser console if you get any API request errors related to that? Is it slow every time, or just sometimes?
Hopefully, someone else can share the experience they found and we can then check if it was an occasional issue or if this is something we need to fix

**Comment by lhdeveloper** [comment]
@joelfmrodrigues 
From what I could see, it's always when it opens. I also noticed that when opening the developer tools of chorme he uploaded the recent documents but very slow. The other tabs work normally, the only one has this problem.

**Comment by lhdeveloper** [comment]
Another problem I encountered, 
When you click on a tab in FilePicker, a hash is added to the URL.

On a page that I already have parameters added to the URL, it is replacing the hash with the selected tab, which makes no sense to me.

Is there any way to disable adding this parameter to the URL?

**Comment by AJIXuMuK** [comment]
@lhdeveloper - this thread is getting difficult - there are multiple different issues.
Could you please create new issues for the problems you're still experiencing.
