### ISSUE TITLE
Localization is wrong - how to override ?

### ISSUE THREAD

**Issue by PKOITC** [pnp/sp-dev-fx-controls-react#1544]
Hi, I'm using the library with polish localization (pl-pl), and I noticed a few errors in there.
Like: english "No" should be "Nie" in polish, but right now is "Nr" - short for "number", and "Save" should be "Zapisz" and not "Zapisać".

My client wants those strings fixed urgently, what is the fastest way to override them in my solution ?

#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

Thanks!

**Comment by GuidoZam** [comment]
Hi, the quickest way is to download the code of the repo, do the changes you need and then replace the compiled code with the one in the node_modules folder of your solution...and once you've done what you need you can PR the updated localization 😉

**Comment by AJIXuMuK** [comment]
@PKOITC - it would be nice if you add a PR so we update the localization for everyone!
