### ISSUE TITLE
Dev branch serve issue

### ISSUE THREAD

**Issue by Saurabh7019** [pnp/sp-dev-fx-controls-react#1555]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   3.15.0    ]

#### Expected / Desired Behavior / Question
`spfx-fast-serve` should serve the project without encountering any warnings or errors.

#### Observed Behavior
`spfx-fast-serve` is experiencing a significant number of warnings and errors.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/18114579/7b5c5eb1-b8a0-4fd5-9262-03f0e3af99d7)

#### Steps to Reproduce

- Sync the dev branch in your fork with original repo
- install dependencies
- execute `npm run serve`

Thanks!

**Comment by joelfmrodrigues** [comment]
@Saurabh7019 many thanks for raising this. We have recently updated the version of SPFx and we still need to update spfx-fast-serve to the relevant version.
As a workaround, can you please confirm if all works with `gulp serve` ?

**Comment by Saurabh7019** [comment]
Thank you! `gulp serve` works fine. I will use that instead.

**Comment by joelfmrodrigues** [comment]
@Saurabh7019 I had a look into this and think I found a fix. Could you please get the latest from the dev branch, run `npm install` (added a new dev dependency), and try `npm run serve` again?

**Comment by joelfmrodrigues** [comment]
@s-KaiNet Sorry to mention you here, but thought you may be interested to look into this. Using fast-serve, there was an issue related to File and Directory Entries API. Only came up today, so possibly related to the latest SPFx version updates.

I think I have resolved it by adding relevant types and also adding a reference of those types within the tsconfig.json file. Not sure if this is how it should be or if this is something you would prefer to handle on the fast-serve side. Any input/thoughts would be appreciated 🙂

Commit with changes for reference: https://github.com/pnp/sp-dev-fx-controls-react/commit/178234dc755ae59441c934ac027e1dd144ccb897

**Comment by Saurabh7019** [comment]
> @Saurabh7019 I had a look into this and think I found a fix. Could you please get the latest from the dev branch, run `npm install` (added a new dev dependency), and try `npm run serve` again?

Thank you, Joel. I have tested it and can confirm that the fix works.

**Comment by s-KaiNet** [comment]
Hi, thank you for the info! For me, it looks more like project-specific configuration, also in fast-serve I do not touch config files, like tsconfig.json. Thus I assume that this "fix" should be added, if you need to work with files api and not in the fast-serve core.

**Comment by joelfmrodrigues** [comment]
@s-KaiNet thanks for the input, appreciated 🙂

**Comment by joelfmrodrigues** [comment]
New release just published, closing
