### ISSUE TITLE
Dynamic Form: Multi User field not allowing more than 1 user and also throwing error on save

### ISSUE THREAD

**Issue by tripathiaman** [pnp/sp-dev-fx-controls-react#1557]
In Dynamic form, **The people picker for multi user field accepts one user.**  The form also throws below error when trying to save a user is selected in the field (probable because it is multi user field but if treated as single user field in dynamic form.)

_Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected."}}}_

#### Category
[X] Bug

#### Version

3.14

#### Expected / Desired Behavior / Question
The people picker for multi user field should accept more than one user.

#### Observed Behavior
The people picker for multi user field accepts one user.  The form also throws error when trying to save a user is selected in the field (probable because it is multi user field but if treated as single user field in dynamic form.)

**Comment by GuidoZam** [comment]
Hi @tripathiaman I tried with version 3.14.0 and it's working, is it possible that you have an expired user session? The 400 status error seems not to be a code issue to me.

**Comment by AJIXuMuK** [comment]
@tripathiaman - I can't repro it too.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/17036219/db8753d8-0006-4e07-a117-606dba71696c)

**Comment by tripathiaman** [comment]
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/38fb35bd-abcc-4d4e-bcfa-8e9f6d629e5f)

In above pic copy to field is Multiple field but here it is not accepting multiple users.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/c89d29f6-7c0f-457a-b6ab-73f818860312)

snapshot of version i m using

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/821640b3-51b5-4575-84fc-181e9d31cf1d)

I m getting below error on save :
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/7feeea3b-bd19-4ff9-a0a8-e2e547e97e10)


snaphot from Dynamic form code showing 'CopyTo' as multiuser.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/a24d6cb9-6b8c-4db4-b278-9b5ffbf16b9e)

Snapshot from the console window

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/e540aa7c-23f7-4c0c-93cd-5917a7a196b5)

snaphot from Dynamic form code showing 'CopyTo' treated as 'User' even though it is multiuser.


![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/596c6f1b-cf61-417e-8110-7bb04c9c649f)

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/8e338639-fff4-40f2-a586-738899249123)

I have tried to explain the issue in detail. Please revert if you need any more info
