### ISSUE TITLE
FilePicker - Tile view issue on first render

### ISSUE THREAD

**Issue by DMichev** [pnp/sp-dev-fx-controls-react#1558]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.15.0 ]

#### Expected / Desired Behavior / Question
"Tiles" view should use all available space for rendering the items on first render

#### Observed Behavior
On initial rendering "Tiles" view option shows its items in a single column with fixed width of 232px. 

<img width="1342" alt="FilePicker-initial-tile-view-rendering" src="https://github.com/pnp/sp-dev-fx-controls-react/assets/35699155/e9b916d0-1492-4f99-a101-d47d2c375469">

After selecting an item or perform window resizing - it renders properly.
<img width="1342" alt="FilePicker-tile-view-after-item-selection" src="https://github.com/pnp/sp-dev-fx-controls-react/assets/35699155/cfd2447b-4078-49d6-a51f-eecc73749906">

I think the problem comes from these default values (lines 100-102):
https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/controls/filePicker/controls/TilesList/TilesList.tsx#L98

Without setting the container width on this line, it works correctly - https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/controls/filePicker/controls/TilesList/TilesList.tsx#L150

#### Steps to Reproduce
Open FilePicker and navigate to a folder. Make sure "View option" is set to "Tiles". It will render the elements in a single fixed-width column.

**Comment by joelfmrodrigues** [comment]
Hey @DMichev many thanks for reporting this issue. Quickly checked the lines you mentioned and it does seem that the page width is being set to the same value as the column width, so it will fit only one item per line.
I assume the fix would be to handle the default value in a different way. Maybe _columnCount * _columnWidth or something similar?

Would you be interested in trying to fix this and submit a pull request?

**Comment by DMichev** [comment]
Hi @joelfmrodrigues. Manual calculation can't help here. I found another way - re-render the component makes FluentUI List component know its surface width. It is in #1559

**Comment by joelfmrodrigues** [comment]
PR merged, will be in the next beta release (in a few minutes) and also part of the next major release. Thanks!

**Comment by joelfmrodrigues** [comment]
New release just published, closing
