### ISSUE TITLE
DynamicForm dropdown combo box must be selected twice for value to be present

### ISSUE THREAD

**Issue by mtburkett** [pnp/sp-dev-fx-controls-react#1563]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.13.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Using the Dynamic Form dropdown combo boxes should reflect the selected item after a single selection.

#### Observed Behavior
Using the Dynamic Form if any combo box in the form is the first control to be interacted with it must be selected twice in order to reflect the selected value - i.e. on the first click the value disappears, but remains after the second.

This is only true if the combo box control is the first interaction with the form - i.e. once data has been entered anywhere else in the form the combo boxes behave as expected.

#### Steps to Reproduce
Create a SharePoint list with one or more choice fields. 
Create an SPFx form customizer
Use the DynamicForm control in the field customizer.
Click in the combo box before entering any other data in the form.

**Comment by GuidoZam** [comment]
Hi @mtburkett could you please retry with the latest version of the package? I tried to repro this with version 3.14.0 without any luck.

**Comment by AJIXuMuK** [comment]
Can't repro it too.
