### ISSUE TITLE
Dynamic Form: Multi User field not allowing more than 1 user and also throwing error on save

### ISSUE THREAD

**Issue by tripathiaman** [pnp/sp-dev-fx-controls-react#1567]
In Dynamic form, **The people picker for multi user field accepts one user.**  The form also throws below error when trying to save a user is selected in the field (probable because it is multi user field but if treated as single user field in dynamic form.)

_Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected."}}}_

#### Category
[X] Bug

#### Version

3.14

#### Expected / Desired Behavior / Question
The people picker for multi user field should accept more than one user.

#### Observed Behavior

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/38fb35bd-abcc-4d4e-bcfa-8e9f6d629e5f)

##### In above pic copy to field is Multiple field but here it is not accepting multiple users.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/c89d29f6-7c0f-457a-b6ab-73f818860312)

##### snapshot of version i m using

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/821640b3-51b5-4575-84fc-181e9d31cf1d)

##### I m getting below error on save :

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/7feeea3b-bd19-4ff9-a0a8-e2e547e97e10)

##### snaphot from Dynamic form code showing 'CopyTo' as multiuser.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/a24d6cb9-6b8c-4db4-b278-9b5ffbf16b9e)

##### Snapshot from the console window

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/e540aa7c-23f7-4c0c-93cd-5917a7a196b5)

##### Snaphot from Dynamic form code showing 'CopyTo' treated as 'User' even though it is multiuser.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/596c6f1b-cf61-417e-8110-7bb04c9c649f)

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/10772218/8e338639-fff4-40f2-a586-738899249123)

##### I have tried to explain the issue in detail. Please revert if you need any more info

_Originally posted by @tripathiaman in https://github.com/pnp/sp-dev-fx-controls-react/issues/1557#issuecomment-1607233062_

**Comment by NishkalankBezawada** [comment]
Hello @tripathiaman, 

I have tried both options as below
1) New Item creation
2) Updating existing item
Both have worked for me. 

I have created a column as you have specified
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/42be965c-e163-4d9d-ac3e-6d6be152fad4)

It havent lead me to error. Could you please give more details on this.

//Nishkalank Bezawada

**Comment by NishkalankBezawada** [comment]
You can check this repository - I have tried to replicate the same as your solution. 
https://github.com/NishkalankBezawada/SPFx-research

@microsoft/generator-sharepoint@1.15.0
node -v 16.18.1
npm -v 8.19.2
and below are the pnp modules used for the project
+-- @pnp/graph@3.16.0
+-- @pnp/logging@3.16.0
+-- @pnp/queryable@3.16.0
+-- @pnp/sp@3.16.0
+-- @pnp/spfx-controls-react@3.14.0

With these, it works for me

//Nishkalank

**Comment by tripathiaman** [comment]
ok..i will check your solution and revert tomorrow...thanks for your time

**Comment by tripathiaman** [comment]
The issue exists for the lists  migrated from on prem environment. The field on which i observed the issue was migrated by on-prem (sp2016). for the new fields there is no issue.

**Comment by NishkalankBezawada** [comment]
Hi @tripathiaman, 

Could you share the snapshot of the field properties? I just wanted to see what changes from the column which is being migrated form 2016, to the new one. 

Thanks,
Nishkalank

**Comment by devspfx** [comment]
Hi,

I have a similar issue for MultiUser field: 
![image](https://github.com/user-attachments/assets/3bd7e516-142d-4d2b-96f1-62e088d67c01)

Error Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'StartArray' was read from the JSON reader when trying to read a value of a property; however, a 'PrimitiveValue' or 'StartObject' node was expected."}}}
    at new HttpRequestError (parsers.js:130:1)
    at Function.<anonymous> (parsers.js:145:1)
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:46)
    at fulfilled (tslib.es6.js:73:43)

On onListItemLoaded this is the value of the field:
    "BoardMemberId": [
        187,
        12
    ],
On onBeforeSubmit the field value is this:
    "BoardMemberId": [187,15]

I am using "@pnp/spfx-controls-react": "^3.19.0".

**Comment by wuxiaojun514** [comment]
I got the similar issue
`Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartArray' node was expected."}}}`

 when I want to clean an multiple lookup field.

**Comment by wuxiaojun514** [comment]
I got the same error message when I want to clean up the value in a multiple lookup field.
Since this ticket is already closed, I will create a new one to report the problem.
