### ISSUE TITLE
Dynamic Form - Error get field informations TypeError: item[field.InternalName].forEach is not a function    

### ISSUE THREAD

**Issue by ravaney** [pnp/sp-dev-fx-controls-react#1568]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[x ] Bug

[ ] Question
Does this work across multiple sharepoint sites (providing the web absolute url). My form renders on the default site on sharepoint, but if I use another site and provide the site relative url as a prop, it doesn't render.
#### Expected / Desired Behavior / Question
a rendered form for different field types

#### Observed Behavior
loading bar, no form rendered

#### Steps to Reproduce
                        context={webPartContext}
                        listId={listId.toString()}
                        listItemId={file.ListItemAllFields.ID}
                        onCancelled={() => { console.log('cancelled') }}
                        onBeforeSubmit={async (listItem) => { return false; }}
                        onSubmitError={(listItem, error) => { console.log(error) }}
                        onSubmitted={() => { console.log('submitted') }}
                        webAbsoluteUrl={siteAbsoluteUrl}

https://company.sharepoint.us/sites/originalSite .... // this works fine without web absolute url

if I change the site to https://company.sharepoint.us/sites/other-site from organization // I get the error with or without the webAbsoluteUrl as a prop

Thanks!

**Comment by IRRDC** [comment]
I just noticed the same error and it happens when you include TaxonomyFieldTypeMulti fields where the values are in a sub-array called results while the code tries to directly access the items of the object and not the sub-array:

![Zwischenablage01](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/aa0fd8c4-592f-4f5d-af9e-315a4f850b8f)
![Zwischenablage02](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/81f62e25-d5f9-4d56-a221-ea52055f0778)

**Comment by IRRDC** [comment]
Could someone please check the PR. It's just two lines of code that have changed and it would be really helpful to have the fix included in one of the next releases.

**Comment by joelfmrodrigues** [comment]
Hey all, reopening and tagging to be fixed in the next release
