### ISSUE TITLE
Broken behavior: files containing dots in the name

### ISSUE THREAD

**Issue by Goncaloo42** [pnp/sp-dev-fx-controls-react#1580]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

Related issues? https://github.com/pnp/sp-dev-fx-controls-react/issues/1022

#### Version

Please specify what version of the library you are using: [3.9.0]

#### Expected / Desired Behavior / Question
I'm having an issue using the **ListItemAttachments** component from your library. Basically after adding and configuring the component on a form inside a SharePoint WebPart, pretty much everything works as expected. **BUT** one thing that does not behave as expected is when adding attachments that contain one or more dots (".") in the name, the file type icon is not displayed (ex. PDF, Word, etc.)

After researching, I found out that this issue was already addressed [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1028)

Can someone help me figure why is it still showing blank icons for me?

Thanks!

**Comment by NishkalankBezawada** [comment]
Hello @Goncaloo42, 

I was able to resolve this issue. Will be creating a pull request. 

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/d843d996-1d6e-4b3b-9bfc-a4008aa2ee40)

Below are the attachments, 

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/93da4eeb-7066-4ab3-b52e-370efcef70f9)

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/f3abf585-6eca-476b-aa91-8ae757d80fe5)


Thanks,
Nishkalank

**Comment by Goncaloo42** [comment]
Hello @NishkalankBezawada,
Thank you for your reply and your help!

Now I just need to wait for your changes to be live so I can update the reference in my solution, correct?

**Comment by NishkalankBezawada** [comment]
> Hello @NishkalankBezawada,
> 
> Thank you for your reply and your help!
> 
> 
> 
> Now I just need to wait for your changes to be live so I can update the reference in my solution, correct?

Hej, Well that's true.

//Nishkalank

**Comment by joelfmrodrigues** [comment]
@Goncaloo42 many thanks for raising this issue, and many thanks @NishkalankBezawada for the PR.
I have just merged the PR and a new beta version of the package containing the fix should be automatically published in a few minutes.

**Comment by joelfmrodrigues** [comment]
New release just published, closing
