### ISSUE TITLE
Dynamic Controls - Number validations on the Percentage column is working, but the value in the percentage column is not getting saved.

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/sp-dev-fx-controls-react#1592]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.15.0 Beta version]

#### Expected / Desired Behavior / Question
Entering the value between 1 to 100 into percentage column should save the form. 

#### Observed Behavior
The number validations are working like a charm, but if we are using a percentage column and trying to save the value to that column, it is not saving the values. Below is the screen for the validations

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/4d13b32d-5cad-4310-9f05-6f12a34fefc0)

#### Steps to Reproduce
1) Add field Number and choose as 'Show as percentage'
2) Use this list in Dynamic form, with New Item, and give the value as 15 and click save

The form will not be saved. 

#### Observations
The properties number field if chosen as 'Shown as percentage', the minimum and maximum values will be retrieved as below, 

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/b39f89c7-7196-45f3-af8a-b4805b086610)

wherein, the properties of number field without choosing 'Show as percentage', the minimum and maximum values will be retrieved as below. 

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/0baf2c85-62d2-40e2-964c-c4c50a1d5af2)

And at ```onSubmitClick```, the validation for percentage column is failing due to the minimum and maximum values for the percentage column. 

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/f63448ca-8f18-472f-b642-5cb546cde8fe)

Thanks,
Nishkalank Bezawada

**Comment by michaelmaillot** [comment]
Following related merged PR, the fix will be available in beta release within a few minutes.
