### ISSUE TITLE
[TaxonomyPicker] Sometimes term path contains "termsetName" sometimes not in "onChange" event 

### ISSUE THREAD

**Issue by wuxiaojun514** [pnp/sp-dev-fx-controls-react#1597]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.14.0   ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The problem is at "**onChange**" event in [TaxonomyPicker](https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/) 
In some scenario the **path** of term contains termset name while sometimes it doesn't have.

I think the term path should not have termset name.

#### Observed Behavior
If you choose term **from panel**, then its term path won't contain termset name
![PickTermInPanel](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/ede31a70-7438-41d0-a4b7-7b3262146264)
However if you pick up term **from the suggestion** , then its path will start with termset name
![PickerTermFromSuggestion](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/31b71638-1927-42c8-93fd-cc81e01f0d15)
Also you will notice that the title of suggestion item contain double termset name

![DoubleTermsetName](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/377d090f-3305-4cc8-a78d-abbeabbc160c)

I debugged a bit on source code, terms **from the suggestion** are generated by [convertSuggestTermToPickerTerm method](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/services/SPTermStorePickerService.ts) which add full path.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/cc806094-cdfb-489a-beef-09c2f8da37cf)

#### Steps to Reproduce
You can follow [https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/](https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/) to add TaxonomyPicker in webpart or extension to reproduce this issue

I can try to fix it.

Thanks!

**Comment by joelfmrodrigues** [comment]
Merged and will be part of the next release, many thanks @wuxiaojun514
