### ISSUE TITLE
PeoplePicker component filtering people with same names

### ISSUE THREAD

**Issue by Matej4386** [pnp/sp-dev-fx-controls-react#1603]
#### Category
[x ] Enhancement
#### Version

Please specify what version of the library you are using: [    2.10 but it is in new version also     ]

#### Expected / Desired Behavior / Question
PeoplePicker should filter selected person not by name

#### Observed Behavior
PeoplePicker - after selecting person 1, second person is filtered - they have same names

Problem:
/**
   * Checks if list contains the person
   *
   * @param persona
   * @param personas
   */
  private listContainsPersona = (persona: IPersonaProps, personas: IPersonaProps[]): boolean => {
    if (!personas || !personas.length || personas.length === 0) {
      return false;
    }
    return personas.filter(item => item.**text** === persona.**text**).length > 0;
  }

Resolution:
/**
   * Checks if list contains the person
   *
   * @param persona
   * @param personas
   */
  private listContainsPersona = (persona: IPersonaProps, personas: IPersonaProps[]): boolean => {
    if (!personas || !personas.length || personas.length === 0) {
      return false;
    }
    return personas.filter(item => item.id === persona.id).length > 0;
  }

**Comment by NishkalankBezawada** [comment]
Hello @Matej4386 , I have created a new PR for this as #1620 

Thanks,
Nishkalank

**Comment by michaelmaillot** [comment]
Closing as fixed in version 3.16.0
