### ISSUE TITLE
[BUG] PeoplePicker won't accept Multiple Users with the same name

### ISSUE THREAD

**Issue by sionjlewis** [pnp/sp-dev-fx-controls-react#1612]
**Bug Description**

When we attempted to add multiple users with the same name (Charlotte Coker was out test for this as there are 3 different users set up with her name) it fails to surface any user after the first when you search:

![image](https://github.com/microsoftgraph/microsoft-graph-toolkit/assets/4746622/c6752999-41db-4883-bbaf-9063edc4a79b)

When we search the user (Charlotte) initially all three user accounts display in the search result but after selecting one and starting to search for the second no more return (as screenshotted)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Azure > Azure Active Directory (AAD) > Users
2. Add three accounts with the same names and different email addresses, for example:
> - John Smith    john.smith.01@ildsnz.onmicrosoft.com
> - John Smith    john.smith.02@ildsnz.onmicrosoft.com
> - John Smith    john.smith.03@ildsnz.onmicrosoft.com
3. Add a four account with the same first name, foe example:
> - John Not-Smith   john.not-smith@ildsnz.onmicrosoft.com
4. Open or create a simple webpart hosting a PeoplePicker control with the following properties"
    <PeoplePicker
        context={this.props.context}
        titleText="People Picker"
        personSelectionLimit={200}
        showtooltip={true}
        onChange={this._getPeoplePickerItems}
        showHiddenInUI={false}
        principalTypes={[PrincipalType.User, PrincipalType.SharePointGroup, PrincipalType.SecurityGroup]}
        resolveDelay={1000} />

**Expected behavior**
I would like to see two or more John Smiths added to the <PeoplePicker /> field and replicate the SharePoint out-of-the-box people picker UX.

**Suggested Fix**
I understand that displaying three [John Smiths] [John Smiths] [John Smiths] will introduce another issue. Which [John Smiths] am I looking at. I currently see two options:
1. Include a tooltip for each Person displaying their email address e.g, john.smith.02@ildsnz.onmicrosoft.com
2. Have an option to display Email Address(es) instead of Display Name(s)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome Version 115.0.5790.110 (Official Build) (64-bit) (and Edge)
 - Framework: SPFx 1.17.1, react 16.13.1, @pnp/spfx-controls-react 3.9.0, @pnp/spfx-property-controls 3.9.0, Node: >=16.13.0 <17.0.0
 - Context Microsoft Teams and SharePoint

**Comment by NishkalankBezawada** [comment]
Hi @sionjlewis 

I tried to reproduce the issue with 
John Smith [john.smith.01@pm3q.onmicrosoft.com](mailto:john.smith.01@pm3q.onmicrosoft.com)
John Smith [john.smith.02@pm3q.onmicrosoft.com](mailto:john.smith.02@pm3q.onmicrosoft.com)
John Smith [john.smith.03@pm3q.onmicrosoft.com](mailto:john.smith.03@pm3q.onmicrosoft.com)

and i guess i have found the fix. 

![MultipleUsersWithSameNamebutDifferentLoginNames](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/b4f8fad3-7576-408e-9984-b585f8c42bfd)

Will soon create a PR on this. 


Thanks,
Nishkalank

**Comment by sionjlewis** [comment]
Brilliant, thank you @NishkalankBezawada

**Comment by michaelmaillot** [comment]
Closing as fixed in version 3.16.0
