### ISSUE TITLE
TaxonomyPicker how to use onGetErrorMessage property

### ISSUE THREAD

**Issue by akashm31** [pnp/sp-dev-fx-controls-react#162]
[ ] Question
<TaxonomyPicker
                        allowMultipleSelections={false}
                        termsetNameOrID={this._getTermStoreId()}
                        panelTitle={strings.TaxonomyPanelTitle}
                        label=""
                        context={this.props.context}
                        onChange={this.onMediaTaxPickerChange}
                        isTermSetSelectable={false}
                        onGetErrorMessage={this.validateMedia}
                      />
 Version "@pnp/spfx-controls-react": "1.6.0"
Question
I use the Taxonomy Picker, and I want to implement validation when the user enters text in the box that is not resolved as a term.
I am trying to use the onGetErrorMessage proeprty and passing a function to it, but the function does not get called.
onChange works fine.
Is there an example you can share on how to achieve this ?

Thanks
Akash

**Comment by AJIXuMuK** [comment]
Hi @akashm31,

It seems like it has never worked and not included in the documentation.
Based on the notation of the function - it should allow you to provide error message but AFTER term is resolved. 

Do you need such a functionality? If no - most probably we'll just remove this property as it doesn't work anyway.

**Comment by OverkillTV** [comment]
Hi @AJIXuMuK ,

It seems that the onGetErrorMessage of TaxonomyPicker has same issue as the PeoplePicker issue #841 .
The new release fixed this issue for PeoplePicker but not TaxonomyPicker.
