### ISSUE TITLE
Filepicker dutch language issue

### ISSUE THREAD

**Issue by advdberg** [pnp/sp-dev-fx-controls-react#1635]
https://github.com/pnp/sp-dev-fx-controls-react/blob/dcd565616a99a8c19272818665f2d97220031418/src/loc/nl-nl.ts#L297C23-L297C30

'Site' is translated into 'Ligging' but should be just 'Site' as this English word is embedded in the Dutch language. 'Ligging' means something completely different.

**Comment by joelfmrodrigues** [comment]
@advdberg many thanks for this. It has been updated in the dev branch and will be part of the next release.
