### ISSUE TITLE
PeoplePicker - Provide a method / prop to Clear the content properly

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/sp-dev-fx-controls-react#1643]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.15.0]

#### Expected / Desired Behavior / Question

When the control contains users / groups and we want it to be cleared programmatically, there should be a method / prop to do so.

#### Observed Behavior

Raised in #1569, the only way to clear the picker is through a `ref.onChange` event trigger with an empty array, which could be improved.

#### Steps to Reproduce

* Add the PeoplePicker control in a React component
* Add entries within the control
* Try to clear its content through code

**Comment by DevPio** [comment]
I would like to work on this task, could you assign it to me?

**Comment by michaelmaillot** [comment]
Linked PR has been merged, it should be available soon in next beta release.

Thanks again for your contribution!
