### ISSUE TITLE
ListItemAttachments - Inconsistent file handling

### ISSUE THREAD

**Issue by rikkerorbak** [pnp/sp-dev-fx-controls-react#1644]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[x?] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [ 3.15.0  ]

#### Expected / Desired Behavior / Question
I am experiencing inconsistent uploading and deletion of files. Often, perhaps only when creating a new list item, a few files will often not be uploaded. Checking the dev tools, the addFile-method fails with a 404 or 409.
I don't know if my code is the issue (this is my first webpart, and I am generally not a terribly experienced developer), but I can't figure out what the issue is. Things seem to work fine on an existing item.
Another observation is that when attaching files to an existing list item, I see the loading animation running, but I don't see that when attaching to a new list item; not sure if that says anything.

Regarding deletion, I sometimes experience that a file, often the last after having added a few, does not get deleted but instead remains in the container.

Thank you so much! I've spent days troubleshooting this and really hope I can get help figuring it out!

/Rikke

**Comment by Tanddant** [comment]
I did a bit of digging on this one - it seems to be related to a concurrency issue.

I can't find any docs confirming it, but several others confirm it:
- https://sharepoint.stackexchange.com/questions/254588/multiple-attachment-upload-causing-409-conflict-error-spfx-pnp
- https://github.com/pnp/pnpjs/issues/428
- https://anomepani.github.io/posts/upload-multiple-attachments-in-sharepoint-list-using-rest-api-on-sharepoint-online/


When uploading attachments Microsoft doesn't like us uploading multiple files at the same time

Quick code the validate:
``` TypeScript

import { sp, IAttachmentAddResult } from "@pnp/sp/presets/all";

(async () => {

  const file = sp.web.lists.getByTitle("Generic list").items.getById(3).attachmentFiles;
  const promises: Promise<IAttachmentAddResult>[] = [];
  for (let x = 1; x <= 100; x++) {
    promises.push(file.add(`${x}.txt`, "This is an attachemnt"));
  }

  const parsed: IAttachmentAddResult[] = await Promise.all(promises);

  for (let p of parsed) {
    console.log(p)
  }


})().catch(console.log)
```

Bingo!

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/6947024/8f18f588-b044-433c-b0b4-87a7d36ac7f6)



I guess the solution would be to change [this](https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/controls/listItemAttachments/ListItemAttachments.tsx#L79)

to something along the lines of 

``` TypeScript
public async uploadAttachments(itemId: number): Promise<void> {
  if (this.state.filesToUpload) {
    for (const file of this.state.filesToUpload) {
      await this._spservice.addAttachment(
        this.props.listId,
        itemId,
        file.name,
        file,
        this.props.webUrl);
    }
  }
  return new Promise<void>((resolve, reject) => {
    this.setState({
      filesToUpload: [],
      itemId: itemId
    }, () => this.loadAttachments().then(resolve));
  });
}
```


@joelfmrodrigues will you look this over and I'll be happy to submit a PR resolving the issue - it will slow down the experience, but will resolve the issue when adding multiple files

**Comment by joelfmrodrigues** [comment]
@rikkerorbak the PR to fix this is now merged and the fix will be in the beta release in a few minutes. If you have the chance to try this, please let us know if it's been fixed
