### ISSUE TITLE
RichText: Add https:// as placeholder instead of textbox value when adding url

### ISSUE THREAD

**Issue by daenur76** [pnp/sp-dev-fx-controls-react#1651]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version
[ 3.15.0 ]

#### Expected / Desired Behavior / Question
When you are adding a url to the text in the RichText control, the url text box should have a place holder text saying "https://". Today, the url text box instead have a default value of "https://", giving that when you paste a url into the box, the value becomes "https://https://...". This is very annoying and can be defined as an incorrect behaviour for editors.

**Comment by michaelmaillot** [comment]
Hi @daenur76,

You're right, this should be displayed as a placeholder instead of a value.

Are you insterested to submit a PR for this one?

**Comment by daenur76** [comment]
@michaelmaillot Of course, PR has been submitted.

**Comment by michaelmaillot** [comment]
Linked PR has been merged and should be available soon in the beta release.
