### ISSUE TITLE
ListView DefaultFilter mapping issues

### ISSUE THREAD

**Issue by lenain71** [pnp/sp-dev-fx-controls-react#1653]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.15.0 ]

#### Expected / Desired Behavior / Question
I'm expecting to see/refresh the search textbox value applied on ListView component when using a State property mapped to the 'defaultFilter' property in react component. But refresh does not apply since I explicitily refresh the component (like the state property mapping was not taking into account ! )

#### Observed Behavior
React component used to display ListView component. Using internal state mapped to the property "DefaultFilter" : 

componenet definition : 
`<ListView
                items={items}
                viewFields={this.state.selectedDetailView ? this.columns : this.columns.filter((col) => !col.name.startsWith('siteFactoryInformation'))}
                compact={true}
                selectionMode={SelectionMode.multiple}
                selection={this._getSelection}
                showFilter={true}
                defaultFilter={this.state.selectedSearch}
                filterPlaceHolder="Search..."
                dragDropFiles={false}
                stickyHeader={true} />`

state definition and manage changed : 

`public componentDidUpdate(prevProps: Readonly<ListGroupsProps>, prevState: Readonly<ListGroupsState>, snapshot?: any) : void {
    //check if new filter/search/export values are received from parent component and set filtering/searaching/exporting
   if(prevProps.selectedSearchValue !== this.props.selectedSearchValue) {
      this.setState({selectedSearch: this.props.selectedSearchValue});
    }
...
    }`

#### Steps to Reproduce
ListView component on React component, with internal state property mapping to 'DefaultFilter' property. Make a textbox and passed new value by props to the sub component, mapped the the state to change value and see the result.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/42752420/8987feb9-e1fb-4f6e-a3ea-dce0dff87230)

After refreshing component : 

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/42752420/e30b1d59-c1b4-42e1-bfa7-0c0f1f03f9f7)

for information, it's not a internal issue of the state, some other properties from props were also passed to the internal state and were working properly ( ex : this.state.SelectedDetailView  mapped to the ViewFields property of the ListView)

Thanks!

**Comment by michaelmaillot** [comment]
Hi @lenain71, 

Thanks for raising this. However, as stated in the docs, the `defaultFilter` is provided to initialize the filter to apply during component mouting. So it's not intended to be controlled afterwards.

But we could think about adding a new (controlled) prop called `filter` for example which could fit your need 🙂

**Comment by lenain71** [comment]
@michaelmaillot,

Thanks for the explaination, it could be good yes to be able to bind this property. Let me know if i can help to test it

**Comment by michaelmaillot** [comment]
Closing as answered.
