### ISSUE TITLE
How to filter a PeoplePicker

### ISSUE THREAD

**Issue by cardinalpipkin** [pnp/sp-dev-fx-controls-react#1657]
#### Category
[ ] Enhancement

[ ] Bug

[/] Question

├── @fluentui/react-components@9.31.0
├── @microsoft/teamsfx-cli@1.2.6
├── @pnp/logging@3.18.0
├── @pnp/sp@3.18.0
├── @pnp/spfx-controls-react@3.15.0
└── react-icons@4.11.0
 Version

Please specify what version of the library you are using: [ 3.15.0 ]

Question
I am trying to filter an sp pnp people picker: 
[PeoplePicker - @pnp/spfx-controls-react](https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/)
I want to filter based on whether the users found have a certain @domain.com
Is there an out of the box solution that comes with the control or is it something I will have build around it?
It's been suggested I use

 `import { PeoplePickerFilter } from '@pnp/spfx-controls-react';`

but I get an error saying it doesn't exist on @pnp/spfx-controls-react:
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/7973051/d185f555-a142-4946-8e5a-6a4116dbc1b7)

How to filter it?

**Comment by GuidoZam** [comment]
Hi @cardinalpipkin, I've created a PR that should match your case.
On the PeoplePicker control you can now (if the PR will be approved) specify the filter to be applied to the results of the search, for example if you want to filter the user with the '@custom-domain.com' you can use the following code:

```
resultFilter={(result: IPersonaProps[]) => {
   return result.filter(p => p["loginName"].indexOf("@custom-domain.com") !== -1);
}}
```

Hope this answer your issue!

**Comment by GuidoZam** [comment]
Hi @cardinalpipkin no worries we've all been novices 😄 
I submitted a PR so now the maintainer of the repository will have a look and decide if it's ok or not, if the PR is accepted it will be included in a future release of the package.

To follow the status of the PR you can check it [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1673).

**Comment by joelfmrodrigues** [comment]
@cardinalpipkin really sorry for the delay on this, the PR is now merged and the feature will be available in the beta release within a few minutes and also part of the next main release (not sure when this will happen at this point).
