### ISSUE TITLE
ListItemAttachments: Attachment preview opens invalid URL in a new form

### ISSUE THREAD

**Issue by yannikreiter-maxworx** [pnp/sp-dev-fx-controls-react#1679]
#### Category
[ ] Enhancement

[**x**] Bug

[ ] Question

#### Version
**3.15.0**

#### Desired Behavior
When using the ListItemAttachments component to upload files in a new form, after a file has been added, clicking the file preview to open the file should be disabled.

#### Observed Behavior
When using the ListItemAttachments component to upload files in a new form, after a file has been added, clicking the image preview results in the url "https://example.sharepoint.com/sites/example/_layouts/15/undefined?web=1" being opened:

![ListItemAttachments](https://github.com/pnp/sp-dev-fx-controls-react/assets/74363617/d6056fb1-dfaf-4961-85c4-4f882f41cd47)

#### Steps to Reproduce
1. Use 'Add Attachment' button to add an attachment in a new form
2. Click the attachment preview

**Comment by michaelmaillot** [comment]
Hi @yannikreiter-maxworx,

I confirm I can repro this issue. Would you like to give a try to fix this one?

**Comment by yannikreiter-maxworx** [comment]
Hello @michaelmaillot,

if the desired behaviour I described above is indeed the way that the fix should be implemented, I will gladly have a look at this.

**Comment by michaelmaillot** [comment]
According to me, since the file is not "loaded" in SharePoint at this point, it can't be previewed from the browser.

So you can take it, it's all yours 🙂

**Comment by yannikreiter-maxworx** [comment]
Hello @michaelmaillot,
just wanting to let you know that I submitted a PR for this issue.

**Comment by michaelmaillot** [comment]
Hi @yannikreiter-maxworx,

I saw that, thanks for pushing this one!

I'll try to have a look at it in the next days, I'll let you know 😉

**Comment by michaelmaillot** [comment]
Issue fixed and merged to `dev` branch. It should be available in the beta release soon.

Thanks again for the work!

**Comment by yannikreiter-maxworx** [comment]
Can this issue be closed? @michaelmaillot

**Comment by michaelmaillot** [comment]
Sure! Thanks for the reminder and again for your contribution!
