### ISSUE TITLE
TaxonomyPicker is hiding children when parent is Available for Tagging == false

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/sp-dev-fx-controls-react#1685]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
3.15.0

#### Expected / Desired Behavior / Question
I have a term group:
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20593570/b71bf9d9-4156-49e1-9df6-6aadb77bed57)

Manufacturing is not available for tagging, as it is just a logic grouping, not an actual department

I would expect all terms to be displayed, and Manufacturing should be not-selectable

#### Observed Behavior

The terms under Manufacturing are not loaded/displayed 

#### Steps to Reproduce
Find a 3 or more level term set, and toggle the Available For Tagging field on one of the not-leaf terms

Perhaps the code be updated to check if the term is a leaf before hiding it?

**Comment by vofflan** [comment]
Can confirm that I have the same problem. Any updates on this issue?

**Comment by vofflan** [comment]
@kasperbolarsen I changed and use ModernTaxonomyPicker instead and then it will work as expected 
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/2813829/40ef8996-3b08-46b5-a8a8-2fa00eec4553)

**Comment by michaelmaillot** [comment]
Hi @kasperbolarsen & @vofflan,

Did you get the chance to test with latest version (3.17.0)? I tried it and it's working as expected if I'm not wrong.

Configuration at site collection level:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/28a72de9-0441-4d30-b082-5f81f4e89238)

Behavior of the TaxonomyPicker:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/377fccc1-3f68-491f-a45b-c36083747bec)

Behavior of the native column in a list:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/b1802654-31e4-422e-b0d6-a9011be0314f)

Can you confirm on your side?

**Comment by kasperbolarsen** [comment]
Hey Michael, I just checked and as far as I can tell the issue have been resolved :-)
