### ISSUE TITLE
ModernTaxonomyPicker not displaying suggestions when typing in values - "API not found" error

### ISSUE THREAD

**Issue by amy-woods** [pnp/sp-dev-fx-controls-react#1688]
**Category**

[ ] Enhancement

[x] Bug

[ ] Question

**Version**
Please specify what version of the library you are using: [3.15.0]

**Expected / Desired Behavior / Question**
when users starts to type into the ModernTaxonomyPicker field they should be presented with a list of suggestions.

**Observed Behavior**

When typing into the ModernTaxonomyPicker the suggestions menu returns "no results found". however there are a number of terms in that area of the term store that should return a match. When i have looked in the console there as a 400 bad request error from the searchTerm api.
The field is anchored correctly because the users can click the slide out and select terms this way. It just fails to display suggestions because the API call fails.

The request URL is formulated as follows in the network console: 

https://####.sharepoint.com/sites/#####/_api/v2.1/termstore/searchTerm(label='a',setId='{guidvalue}',languageTag='en-US',stringMatchId='0',parentTermId='{guidvalue}')?$top=50
 
the response form this call is: 

{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "code": "apiNotFound"
        },
        "message": "API not found"
    }
} 

I have managed to get the call working in a browser window by changing the perameter stringMatchId='0' to stringMatchOption='StartsWith'. 

**Steps to Reproduce**

1) Add the ModernTaxonomyPicker control in a SPFx project
2) Anchor the picker to a parent term that has children
3) start typing a term value into the picker field that matches one of the child terms.

**Comment by sajdak-codes** [comment]
I have the same issue as well. It started today. I am using library version 3.13.0.

**Comment by robertmacnair** [comment]
I have the same issue. Appears stringMatchId has been deprecated / removed from the underlying API... stringMatchOption works. TaxonomyService needs updating I suspect

**Comment by JurajSlavik** [comment]
We have detected the same behavior on 15-th of November 2023. On 9-th of November 2023, the ModernTaxonomyPicker used to work without any problems. 

Probably not required here, but adding used dependencies versions in this case (taken from package.json):
"@microsoft/sp-core-library": "1.16.1",
"react": "17.0.1",
"react-dom": "17.0.1"

Just in case someone needs a workaround unfil this will be fixed - Tag icon (highlighted) on the right side of the control works without any problems.:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/124240729/f6b8b99a-cd1d-4d89-bf36-e9e4231f4043)


Issue occurs only if autocomplete is used.

**Comment by akashpanjwani** [comment]
we are also facing same issue in multiple applications. please let me know in case of any workarounds we have more than 1000 values in sets.

**Comment by lafe** [comment]
@akashpanjwani If you have immediate need to fix the issue, you can use the [`patch-package`](https://www.npmjs.com/package/patch-package) package and modify the "SPTaxonomyService.js" located in "/node_modules/@pnp/spfx-controls-react/lib/services" so that it uses the `stringMatchOption` property with the value `StartsWith`. Afterwards, it should work again. 
That was the approach we choose until a permanent fix is implemented (I provided PR #1704, but we will see if it is accepted or if I oversaw a use case).

**Comment by akashpanjwani** [comment]
@lafe It works Thanks.

**Comment by Foster117** [comment]
Our company has lots forms with this control, please fix this issue as soon as possible. Thank you!

**Comment by IngoHenning** [comment]
We use this control in multiple spfx solutions and I received "some" mails from not so happy users since last week. For the time being I applied the changes made in the pull request @lafe as patch - Thank you for your work! Hopefully the pull request get's merged soon.

**Comment by lafe** [comment]
> [SPTaxonomyService.js.zip](https://github.com/pnp/sp-dev-fx-controls-react/files/13526077/SPTaxonomyService.js.zip)
> 
> If it is necessary to urgently resolve this issue, unpack this archive and replace the file "/node_modules/@pnp/spfx-controls-react/lib/services/SPTaxonomyService.js" with the one in the archive. Or make changes manually. ![Changes](https://private-user-images.githubusercontent.com/21974016/287254921-0a93b341-edd0-4201-adac-bf847168d89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDU0ODksIm5iZiI6MTcwMTcwNTE4OSwicGF0aCI6Ii8yMTk3NDAxNi8yODcyNTQ5MjEtMGE5M2IzNDEtZWRkMC00MjAxLWFkYWMtYmY4NDcxNjhkODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE1NTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ODg2MmE5YzE5ODcxNGVjNTAwOTM5ZjZmMzFmYjFmZjVhZmFjNjJjOTA4YThhMGUyZjMyODY1YjQ2ODFiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2ahbAzkOnPUkEZr_Pkgwi5FOL8WXDpSSBOuix62490)

I would recommend to use [patch-package](https://www.npmjs.com/package/patch-package) or a similar approach instead of manually editing the file. This ensures that the changes are not overwritten by accident, that they are commited to source control, that every developer has the same changes and that you still can use build pipelines (if none of that is a concern, then the benefit is obviously not as big).

> 
> @lafe Thank you for your work!

The main work was done by @amy-woods who already outlined the solution in the issue itself. Thank you for that!

**Comment by raclettierer** [comment]
Any news on this bug ?

**Comment by joelfmrodrigues** [comment]
Hi all, really sorry for the delay in reviewing this item and that it's causing issues for so long.
The PR is now merged and the fix will be in the beta release in a few minutes. It would be great if someone can confirm that it resolves the issue using the beta release.
Considering the impact, we will start discussions for the next release.

**Comment by raclettierer** [comment]
@joelfmrodrigues Fix works in my projects (used 3.17.0-beta.7718771)

**Comment by joelfmrodrigues** [comment]
@raclettierer many thanks for confirming, we are discussing/planning when to do the next main release
