### ISSUE TITLE
Link to immersive profile ("Show more") from FieldUserRenderer

### ISSUE THREAD

**Issue by roncourville** [pnp/sp-dev-fx-controls-react#170]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     1.9.0    ]

In the FieldUserRenderer control, is there any possibility of adding a link that would open the right side panel containing more information about the user (aka the immersive profile)? These links are currently available as "Show more" or "Show organization" in the out of the box user pop out menu. Ideally, I would love it if we could somehow leverage the out of the box interactive organizational tree.

Thanks so much for all the awesome work on this project!

**Comment by AJIXuMuK** [comment]
Thanks for the idea!
I’ll look into it next week or so. At the moment when the control has been created there were limitations. Maybe now it’s doable.

**Comment by AJIXuMuK** [comment]
OK, so, to my opinion it's a HUUUUGE one :)
There are several reasons for that.
1. I didn't find a way to reuse existing Immersive Profile Pane control. It would be the easiest path if there is a module we could import in our code and initiate the whole flow when needed. But... I didn't find it.
2. I didn't find requests that are done in OOTB User Field Renderer to get all the information that is rendered inside Immersive Profile pane. If I could find this then we at least could duplicate the HTML and render all the data from these requests.

Saying that the only way to implement the proposed functionality is to make MS Graph requests to collect data and create the whole markup by ourselves.
I don't see the issue with markup.

**BUT** I do see with MS Graph.
First of all, currently the library is based on SPFx 1.3. There is a [PR](https://github.com/SharePoint/sp-dev-fx-controls-react/pull/168) to update to 1.6 but it hasn't been merged yet.
Second, if we use MS Graph user will need to provide `webApiPermissionRequests` **manually** to make our controls work (Elio mentioned that in other conversation [described here](https://github.com/SharePoint/sp-dev-fx-controls-react/issues/144#issuecomment-429753255)).

@estruyf what are your thoughts on that? 
Maybe you're aware on how to reuse existing Immersive Profile Pane control (it is referenced from Delve modules: https://lpcres.delve.office.com/lpc/versionless/immersiveprofile_full_e211c92384b67108e5f9.js?
I'd love to maximally reuse existing (OOTB) functionality to decrease probability of unexpected changes.

**Comment by estruyf** [comment]
@AJIXuMuK as there are still a lot of projects which use the library in older SPFx versions, so upgrading to 1.6.0 or 1.7.0 is a breaking change. Of course, at some point, we will have to do it.

If we want to reuse that module, we have to know if it's supported. Chances are that it isn't, we had a similar thing for the OneDrive control, which was dropped due to that reason.

**Comment by AJIXuMuK** [comment]
Thanks @estruyf!
That is exactly what I thought.
So, I would say that this one is on hold for now. 
But the idea is good.

**Comment by antonkhrit** [comment]
Hi @AJIXuMuK,

Sure, it is not an official solution and there is no guarantee that it will continue working after some updates from MS, but it may be a temporary solution before something other is released. 

Here is the code to show Immersive Person Profile panel for some account:
`var accountName = "accountName@yourdomain.onmicrosoft.com";
var renderer = window.LPC.getRenderer()
var accountNameEncoded = encodeURIComponent(accountName)
var persona = renderer.getValidMinimalPersona(accountName, { LocationId: undefined, PersonaType: "User" });
renderer.fetchData(persona, undefined);
renderer.immersiveProfileRenderer.renderImmersiveProfile({key: accountNameEncoded + "|-|-|-|-|-"}, renderer.lpcAppContext, "Contact")`

**Comment by AJIXuMuK** [comment]
We need to revise personal card when there is an official component/API from MS.
