### ISSUE TITLE
Wrap FieldUserRenderer around another element

### ISSUE THREAD

**Issue by roncourville** [pnp/sp-dev-fx-controls-react#171]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.9.0     ]

Question

Would it be possible to trigger FieldUserRenderer by mousing over another existing element? Currently the component creates a span, and the user pop out appears when mousing over the span. But what if I wanted to use the FieldUserRenderer component with another component, like Persona? This is the experience with the out of the box People web part, for example.

Perhaps in practice this might look like:
`<FieldUserRenderer users={this.props.userPrincipal} context={this.props.context}>`
`              <Persona imageInititals="RC"/>`
`</FieldUserRenderer>`

**Comment by AJIXuMuK** [comment]
`FieldUserRenderer` has been created to provide similar experience to the out of tge box Person or Group column rendering. 
I would suggest to create a separate control, maybe with common core, to cover other needs
