### ISSUE TITLE
Dynamic Forms with TaxonomyFieldTypeMulti fields don't show

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-controls-react#1717]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.16.0]

#### Expected / Desired Behavior / Question
The fix I made for issue #1568 did not cover all cases and including a TaxonomyFieldTypeMulti field results in the Dynamic Form not stopping to load.

**Comment by bva999** [comment]
I have the same problem. All my fields that have Multi Taxonomy fields doesn't work. 
As I see the issue was fixed. Are there any posibility to publish new minor version like 3.16.1 with this fix? ((((
