### ISSUE TITLE
Build fails due to missing @iconify/react dependency after upgrade to  3.16.0

### ISSUE THREAD

**Issue by ekdegerman** [pnp/sp-dev-fx-controls-react#1719]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

3.16.0

#### Expected / Desired Behavior / Question
gulp bundle --ship completes with no issues, as it does on 3.15.0

#### Observed Behavior
There's a module not found error in webpack:
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/56835119/1f83a07a-6546-4155-9d7b-099850bc6d6a)
@iconify/react is listed under devDependencies rather than dependencies in package.json

#### Steps to Reproduce
1. Create a new spfx component for a web part using react as the framework
2. Install version 3.16.0 of the library
3. Add e.g. a ListItemAttachments component
4. run gulp bundle --ship

**Comment by wuxiaojun514** [comment]
I have the same issue when I upgraded to 3.16.

I installed "@iconify/react" as devDependencies, then it works.
You can try with
`npm i -DE @iconify/react`

**Comment by joelfmrodrigues** [comment]
@ekdegerman thanks for reporting this. The PR from @GuidoZam to fix the issue has just been merged and a new beta release should be published in a few minutes.

**Comment by jeffseiffert** [comment]
> I have the same issue when I upgraded to 3.16.
> 
> I installed "@iconify/react" as devDependencies, then it works. You can try with `npm i -DE @iconify/react`

I tried this then get the following error message.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/8451070/5c1c73ef-2c78-4f11-88b9-8e54beb9e3aa)

**Comment by jtlivio** [comment]
Hello, i have the same issue with version 1.18.2, the PR was published?

Thanks

**Comment by joelfmrodrigues** [comment]
@jtlivio it's not published yet. There was a minor release to try to fix another issue, but didn't include this PR. I will start discussions for a major release to address this issue
