### ISSUE TITLE
DynamicForm - more than 100 lookups and date format in lookup field

### ISSUE THREAD

**Issue by nsoeth** [pnp/sp-dev-fx-controls-react#1721]
#### Category
[ ] Enhancement

[ x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.16.0 ]

#### Expected / Desired Behavior / Question
Show all (or atleast the first 5000) lookup items in a lookup field. 
Display the date in a lookup field in a user friendly format instead an ISO-string.

#### Observed Behavior
Only 100 items are displayed in a lookup field. 
Date is shown as ISO-string in a lookup field.

#### Steps to Reproduce
Add a list with more than 100 items as a lookup.
Make the lookup display column a date column

**Comment by michaelmaillot** [comment]
Linked PR merged, will be available in the next beta release.

Thanks again for your contribution @nsoeth!
