### ISSUE TITLE
TaxonomyPicker Does not allow removing existing selection When the is disabled={!dpcRequest.LockedToMe}

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1728]
#### Category
[X] Bug / question

#### Version

Please specify what version of the library you are using: [         ]
"@pnp/spfx-controls-react": "3.16.0"

#### Expected / Desired Behavior / Question
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/5054931/7f51fb92-c79a-4457-988f-7ed30d7d8198)
Clicking the x on the selected item, should remove it to allow new value.
#### Observed Behavior
The x seams disabled 
#### Steps to Reproduce
` <TaxonomyPicker allowMultipleSelections={false}
          termsetNameOrID="Document Type" panelTitle="Select Document Type" label="Document Type"
          context={wpContext as any} 
          required  initialValues={selDocType}
          placeholder={'Start typing or click the label'}
          onChange={onTaxPickerChange} 
          isTermSetSelectable={false} />
`

I tried with and without required. the same.
Clicking the X and exiting the panel then opening again .
I think the issue is the initialValues={selDocType} does not change when selDocType property changes in onTaxPickerChange.

Other controls have a value property to use with a controlled value.

Any Advice?

Thanks!

**Comment by michaelmaillot** [comment]
Hi @Ofer-Gal,

Do you have a code snippet to share in order to better unerstand / repro your use case?

**Comment by Ofer-Gal** [comment]
This has long been resolved and I can't remember how.
