### ISSUE TITLE
People picker issue when try to search by full name but works with upn

### ISSUE THREAD

**Issue by Igli1994** [pnp/sp-dev-fx-controls-react#1740]
Hello i am using last version of the package but i have a problem with PeoplePicker it suggest when i search by upn but it will not suggest if i search by full name ..

**Comment by NishkalankBezawada** [comment]
Hello @Igli1994 

Could you please share the code synopsis on how you have defined PeoplePicker control.

Thanks,
Nishkalank

**Comment by akshataggrwal** [comment]
Hello @NishkalankBezawada, I am also facing the same issue. Please find below, the implementation in my code.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20832945/2c2dd8b9-ffd0-41ac-bf9f-9f570e0aab7d)

Thanks!

**Comment by michaelmaillot** [comment]
Hi @akshataggrwal & @Igli1994,

I tried on my side with the provided code snippet, without encountering any trouble, whether I search by UPN or full name (both first and last name).

May I ask to both of you to check the following:

* Does the native People Picker in a Person field behaves correctly if you try to search by full name? (even if I know that it's not querying the same API, just to ensure)
* What's the network trace when you're querying the PnP Controls' People Picker with both working and malfunctioning input?
    * Meaning what's inside the `_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser` call, both payload and return

**Comment by akshataggrwal** [comment]
Hi @michaelmaillot,

Upon inspecting the OOB SPO people picker field(which work correctly), it appears to be using the same API(/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser), with the inclusion of an additional parameter called 'UseSubstrateSearch.' and that is the only difference between the two queries.

However, I've found limited documentation on this parameter. Do you have any guidance or insights on effectively utilizing this parameter in the PnP control to address the issue?


![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20832945/cc759706-86a2-4c48-b64f-99555f08bc33)

Related - https://github.com/pnp/sp-dev-fx-controls-react/issues/1534

**Comment by michaelmaillot** [comment]
As I'm not able to repro your issue and as I agree that there's no documentation around this API, may I suggest you to run the Controls locally, udpate the [searchTenant](https://github.com/pnp/sp-dev-fx-controls-react/blob/285cb32559ccb345e53deb388a3ad1aa9e97af6a/src/services/PeopleSearchService.ts#L109) method by including this `UseSubstrateSearch` and test the PeoplePicker control with the `ControlsTest` webpart, provided in the repo.

**Comment by akshataggrwal** [comment]
Hi @michaelmaillot,

Apologies for the delayed response. 

I tested the web part locally by including this property, and it now searches for users based on full names as well.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20832945/42b5eb55-6d35-490c-8b33-1e88a0088e9d)

Thanks!

**Comment by michaelmaillot** [comment]
Hello,

FYI I've submitted a PR with the ability to enable substrate search.

**Comment by michaelmaillot** [comment]
We'll try to 😉

**Comment by michaelmaillot** [comment]
Hello,

Linked PR has been merged, the feature should be soon available in next beta release.

Thanks again everyone for raising & taking time to dig into this one!
