### ISSUE TITLE
Dynamic form loading error in other site

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-controls-react#1758]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.17.0]

#### Expected / Desired Behavior / Question
After updating to 3.17.0: When displaying the dynamic form for a list or library in a different site using webAsboluteUrl the form doesn't load but displays the error "An error occurred while loading: Cannot read properties of undefined (reading 'filter')" instead.

**Comment by joelfmrodrigues** [comment]
Hi @IRRDC , would a new branch not work in this case? I assume you are already working on a fork of the original repo so a new branch should be fine. Or am I missing something?

**Comment by IRRDC** [comment]
Could this fix be released as a minor version since the problem blocks all use of the dynamic form in scenarios that span sites?

**Comment by joelfmrodrigues** [comment]
@IRRDC your fix has been merged, thanks! But I am unable to confirm a release date at the moment. Hoping we can get some time for a release soon.
