### ISSUE TITLE
[Dynamic Form][3.17] Required Field Validation won't work

### ISSUE THREAD

**Issue by wuxiaojun514** [pnp/sp-dev-fx-controls-react#1760]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  **3.17**      ]

#### Expected / Desired Behavior / Question
Dynamic Form should stop submission if there is any empty required field.
However this functionality won't work as expected after I upgraded to 3.17

#### Observed Behavior
[Dynamic Form] changed a lot in new version. I noticed that it will still submit item even the required field is empty

#### Steps to Reproduce
1. Choose a list which has a required field (e.g. title)
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/cd49020e-16f5-4468-8a2b-bae42d157b31)
2. Put "Dynamic Form" in the spfx form customization, no special settings.

```
     <DynamicForm
          context={this.props.context}
          listId={this.props.context.list.guid.toString()}
          listItemId={this.props.context.itemId}
          onSubmitted={(listItemData: any) => {
            console.log(listItemData);       
              setTimeout(() => {
                this.props.onSave();
              }, 1000);
          }} 
          onListItemLoaded={async (listItemData: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
            console.log(listItemData);
          }} />
```
3. Launch it, and leave this required field empty and save it.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/11ce3525-64f0-4da3-bb94-11a59001b4bf)

4. You will see you created a new item which keep this required field empty
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/c7e98947-3c67-412f-9376-db2c27a57002)

#### Trouble Shooting
This is due to the latest "Dynamic Form" changed a lot of things.  The initial value of "**field.newValue**" is "undefined" not "null"
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29603048/571ea64f-6490-43d1-bc36-d7aa97e8cb44)
I will do more testing on it.

**Comment by joelfmrodrigues** [comment]
@wuxiaojun514 , the fix for this has finally been merged, apologies for the long delay.
The fix is now included in the beta release, please let us know if there are any issues.
