### ISSUE TITLE
Module not found - Wrong @fluentui imports cause webpack build errors

### ISSUE THREAD

**Issue by hohenp** [pnp/sp-dev-fx-controls-react#1763]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version
Version: 3.17.0

#### Expected / Desired Behavior / Question
We are using the spfx-controls-react within a webpack project and would expect to build it without webpack errors.

#### Observed Behavior
We are using the spfx-controls-react within a webpack project. When we build the project we get several webpack errors like:
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29328026/56764780-63f3-4b79-b23f-57d220b26d81)

#### Steps to Reproduce
We could identify the used imports of the @fluentui package to cause that issue:
You are using for example the following import: 
`import { ActionButton, PrimaryButton } from "@fluentui/react/lib/components/Button";`
The correct import would be:
`import { PrimaryButton } from '@fluentui/react/lib/Button';`
as described on the [fluent ui page](https://developer.microsoft.com/en-us/fluentui#/controls/web/button)

You can also check the export section of the @fluentui package.json file.
There for example the button is declared as
```
"./lib/Button": {
      "types": "./lib/Button.d.ts",
      "import": "./lib/Button.js",
      "require": "./lib-commonjs/Button.js"
    },
```
so without the /components/ section of the import you are using.

For testing we fixed the wrong imports in the following files and that fixed all build errors we got
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/29328026/a67ea3b6-df75-455e-a973-c7bb3e5792de)

Could you please check all your imports of the @fluentui package?

Thanks
Pascal

**Comment by raclettierer** [comment]
@joelfmrodrigues  fix for the fluentui import are done and ready for review

**Comment by raclettierer** [comment]
@AJIXuMuK wo will approve PRs ? we still waiting on this change.

**Comment by joelfmrodrigues** [comment]
@hohenp the PR from @raclettierer is now merged. Would it be possible for you to test using the beta release please and let us know the outcome?
