### ISSUE TITLE
ListView column widths

### ISSUE THREAD

**Issue by sympmarc** [pnp/sp-dev-fx-controls-react#178]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [1.10.0]

#### Expected / Desired Behavior / Question

When I use the ListView control the spacing of the columns isn't great. It seems that the first column always gets about 2/3 of the overall width, and each of the other columns is squished to the right.

Here's an example screenshot.
![image](https://user-images.githubusercontent.com/1295627/48366224-2b806200-e67b-11e8-8762-45b654fe511a.png)

My ViewFields looks like this:

``` typescript
  private ViewFields: IViewField[] = [
    {
      name: "ManufacturingMaterial.Title",
      displayName: "Manufacturing Material"
    }, {
      name: "LotNumber",
      displayName: "Lot #"
    }, {
      name: "QuantityType.Title",
      displayName: "Quantity Type"
    }, {
      name: "Quantity",
      displayName: "Quantity"
    }
  ];
```
and here's the render function:
``` typescript
  public render(): React.ReactElement<IViewMaterialProps> {
    return (
      <div>
        <ListView
          items={this.state.requestMaterial}
          viewFields={this.ViewFields}
          compact={true}
        />
      </div>
    );
  }
```
I've tried to remove as many settings as possible to reduce complexity, but always get a similar result. I'm also seeing similar results with different items in different components.

To maintain a responsive UI, I'd expect the columns to autospace like they do in the OOB list vies.

**Comment by JakeStanger** [comment]
Having the same problem unless I specify max/min widths.

**Comment by AJIXuMuK** [comment]
This is a default behavior of underlying `DetailsList` even in the latest version of Fluent UI.
