### ISSUE TITLE
How to use OnRenderRow property of ListView control? Can you please provide an example?

### ISSUE THREAD

**Issue by SharePointReady** [pnp/sp-dev-fx-controls-react#1785]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [     3.17.0    ]

#### Expected / Desired Behavior / Question
How to implement the function for OnRenderRow propery of the ListView control?
The example given at the documentation for DetailsList control is not working for ListView control.

Thanks!

**Comment by patrikhellgren** [comment]
Since Fluent UI DetailsList is used under the hood, there are lots of samples available online but you could have a look at the official Fluent UI DetailsList documentation, e.g. [DetailsList - Custom item rows](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemrows).
Nothing special otherwise in @pnp/spfx-controls-react.

**Comment by SharePointReady** [comment]
Hi Patrik,

Thanks for reply. The example given at the [DetailsList - Custom item rows](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemrows) is not working for ListView control. It gives below error.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/37682980/5a2ab276-a04b-49e2-a664-20989f7a61ac)

**Comment by SharePointReady** [comment]
Hi I figured it out as Patrick said. please see below example.

`private _onRenderRow = (props: any) => {

        // console.log('Row Props: ', props);
        
        const customStyles: Partial<IDetailsRowStyles> = {};
        customStyles.root = { backgroundColor: '#ffe680' };

        return props.item.isEmailResponse ? <DetailsRow {...props} styles={customStyles} /> : <DetailsRow {...props} />;
    };`

Thanks,
Jemi
