### ISSUE TITLE
Dynamic Form - enable/disable save button

### ISSUE THREAD

**Issue by srpmtt** [pnp/sp-dev-fx-controls-react#1803]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

Version: 3.17.0

#### Desired Behavior
Add the possibility to explicitly enable/disable the _SAVE_ button via DynamicForm props.

**Comment by michaelmaillot** [comment]
Hi @srpmtt,

Thanks for this enhancement idea, I think that this is something reachable!

Would you like to give a try on this one?

**Comment by michaelmaillot** [comment]
Linked PR has been merged, this enhancement should be available in next beta release.

Thank you again @srpmtt for your contribution!
