### ISSUE TITLE
Richtextbox editor control

### ISSUE THREAD

**Issue by pasipohjola** [pnp/sp-dev-fx-controls-react#1808]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.15.0     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question

Font sizes be adjusted to match Microsoft styles. This text editor has 17px, 15px, etc. font sizes, but Microsoft uses 18px,16px, and so on. This made control somewhat problematic to use.

#### Observed Behavior

This text editor has 17px, 15px which does not match font sizes Microsoft uses.

#### Steps to Reproduce

Add webpart with control to SharePoint page. Observe font size defaults to 17px.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @pasipohjola,

Thank you for this issue.

If I understand correctly your submission, there's already an existing issue related: #1391.

Feel free to reopen if it's not the case.
