### ISSUE TITLE
ListItemAttachments Control Mistranslation of Chinese text and anachronisms

### ISSUE THREAD

**Issue by Haiqi-Wu** [pnp/sp-dev-fx-controls-react#1858]
#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.18.1     ]

Our project needs to implement multi-language support in SPFx, at first I had no hope for the component to adapt to multi-language environments, but when I used it, I found that there was actually multi-language support, which was a pleasant surprise, but unfortunately I found that the support wasn't perfect enough. See the following screenshots for comparison

![image](https://github.com/user-attachments/assets/b2d4b87a-f785-41ae-ae3a-99d80de53d6c)
![image](https://github.com/user-attachments/assets/6df7ff17-a3d2-4be6-aa4c-c4098225fc41)

In Chinese context OK can sometimes be translated as '还行', but the translation here is inappropriate, here it is translated as '好的' or directly as '关闭'.

Whether there are translations elsewhere that don't fit, and whether there are other languages that don't fit, I'm not sure. Please help correct all translations.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @Haiqi-Wu,

Thanks for raising this! FYI, each UI component should use translation files which are located [here](https://github.com/pnp/sp-dev-fx-controls-react/tree/dev/src/loc).

As you can see, there's one dedicated to chinese localization. As you raised this translation issue, would you mind giving us a hand and fix mistranslated text you see in the translation file?

**Comment by Haiqi-Wu** [comment]
Hi @michaelmaillot, sure, but I'm not familiar with operating on github😂, can you give a guide?

**Comment by michaelmaillot** [comment]
Sure! As it's a SPFx project, you can run it locally with the `--locale` argument!

One thing to do first: you'll have to add a zh-cn.js file in each SPFx component (ControlsTest webpart,  testApp, testForm), otherwise, you'll end up with a webpack error. This file can be a copy of existing en-us.js one in each.

Then you can add the `ListItemAttachments` control in the ControlsTest webpart, and just run `npx fast-serve --locale=zh-cn` (or `gulp serve --locale=zh-cn`).

Let me know if you need any guidance.

**Comment by wuxiaojun514** [comment]
Hi @Haiqi-Wu do you need any help on correct resource file?
I found it has a lot funny translation on [zh-cn.ts](https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/loc/zh-cn.ts )
e.g.

![image](https://github.com/user-attachments/assets/1991df93-313f-4f19-918e-1812e4599f25)
I can contribute to fix those translation issue on localization file for Chinese.

**Comment by wuxiaojun514** [comment]
Hi there,

I created a PR to fix the translation problems on Chinese resource files #1894 
![image](https://github.com/user-attachments/assets/76a9102b-fa27-4185-8b04-ac55464c6c00)

**Comment by Haiqi-Wu** [comment]
Thanks guys!
