### ISSUE TITLE
Taxonomy Picker shows a line if no suggestion/match. 

### ISSUE THREAD

**Issue by pavan2920** [pnp/sp-dev-fx-controls-react#188]
Hi,

We are using “Taxonomy Picker” control(https://github.com/SharePoint/sp-dev-fx-controls-react/blob/master/docs/documentation/docs/controls/TaxonomyPicker.md). 
If no suggestion/match found the Picker does not show any message and instead a line will be shown in the bottom. 

![image](https://user-images.githubusercontent.com/10346150/49132624-12c2ae00-f303-11e8-9c34-8aa6e2531952.png)

Can we get rid of this line ? 
OR 
 Is it possible to show any user-friendly message? (as it is in People picker control of office UI fabri) 
Something like this – 
 
![image](https://user-images.githubusercontent.com/10346150/49132634-1a825280-f303-11e8-9c3f-044e983ab4ae.png)

Thanks 
Pavan.

**Comment by estruyf** [comment]
@pavan2920 this is an issue of the Office UI Fabric control we are using. Will check if we can get rid of this.

**Comment by michaelmaillot** [comment]
Hi @pavan2920 

Latest version doesn't display anything if no suggestion / match is found:

![spfx-controls-taxonomy-noresult](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/a92b14cd-7e64-448d-b6cd-3ac5797fa51e)

Can you confirm this?
