### ISSUE TITLE
PeoplePicker - retrived items should contains loginName

### ISSUE THREAD

**Issue by vlad-nvs** [pnp/sp-dev-fx-controls-react#191]
#### Category
[x] Enhancement

#### Version
1.10.0 

#### Expected / Desired Behavior / Question
It will be good if items that PeoplePicker retrieves could contains loginName info. Because not all users/groups has emails, sip, etc.
Suppose also IPrincipal should be expanded to contains loginName.

Thanks!

**Comment by vlad-nvs** [comment]
Also defaultSelectedUsers property in PeoplePicker now should contains only array of Emails but not all users and also Groups (Security, SharePoint) has it. 

At the end it leads to wrong behavior of PeoplePicker control when you try to add (delete) or save value.

Suppose this property also should support loginName.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @vlad-nvs,

Latest version (3.15.0) checks all the enhancements you've requested.

Can you confirm those?
