### ISSUE TITLE
TaxonomyPicker - Termset tree constructed incorrectly

### ISSUE THREAD

**Issue by pjwise** [pnp/sp-dev-fx-controls-react#199]
#### Category
[ ] Enhancement
[x] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [1.9.0]

#### Expected / Desired Behavior / Question
The taxonomy picker should correctly construct and display the tree structure of a termset.

#### Observed Behavior
The taxonomy picker places terms under an arbitrary parent causing the output to look different from the original termset structure.

See here that the term "Get Involved" lives under "Emergency" in the picker: 
![image](https://user-images.githubusercontent.com/13385225/49743769-7b961880-fc69-11e8-9de8-e377509c9b53.png)

And "Human Resources" has no children: 
![image](https://user-images.githubusercontent.com/13385225/49743813-910b4280-fc69-11e8-87ec-1c1cbc527c20.png)

However, in the termstore we can see that "Get Involved" lives under "Human Resources": 
![image](https://user-images.githubusercontent.com/13385225/49743871-ada77a80-fc69-11e8-95d1-88ade5464343.png)

This relationship is also clear in the data returned from the request made by the taxonomy picker: 
![image](https://user-images.githubusercontent.com/13385225/49743917-c6179500-fc69-11e8-950c-84071ea4993e.png)

#### Steps to Reproduce
I tried a few times to reproduce this with standard terms to no avail. It may be that the tree reconstruction fails after a certain number of elements are inserted or it might break because the term is reused. However, the data it is pulling back in the example shows a clear parent-child connection between "Get Involved" and "Human Resources" with the correct guids.

**Comment by estruyf** [comment]
@pjwise I experienced another issue which might be similar to yours and I already implemented a fix for it. Would you be able to test out the latest beta and verify if this also fixes your issue?

More information about how you can test out a beta version can be found here: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by AJIXuMuK** [comment]
@pjwise - is it still an issue on the latest version of the library?
