### ISSUE TITLE
Formatting date/time in ListView?

### ISSUE THREAD

**Issue by jarkaos** [pnp/sp-dev-fx-controls-react#208]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [  1.11.0    ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
How can I format the date/time in the ListView component. I am using the IViewField in this way:
 ```
   private _viewFields: IViewField[] = [
        {
          name: "StartDate",
          displayName: "StartDate",
          minWidth: 25,
          isResizable: true,
          sorting: true
       },
   ]
```
And the I render the list like this: 
```
<ListView 
     items={this.state.items}
     viewFields={this._viewFields}
      selection={this._getSelection}
 />
```

#### Observed Behavior
The result is rendered like this: 2018-12-24T16:00:00Z , what I want is in this format: 2018-12-24 16:00:00
How can I achive that?

Thanks!

**Comment by PzKfWg** [comment]
You may override the rendering of the field. E.g.:
`  private _viewFields: IViewField[] = [
       {
         name: "StartDate",
         displayName: "StartDate",
         minWidth: 25,
         isResizable: true,
         sorting: true,
         render: (item: DFCContract) => {  
          const localizedEndDate = new Date(item.ContractEndingDate); 
          return (<span>{localizedEndDate.toLocaleString()}</span>);
      },
  ]
`
By creating a Date object with your string, you have access to multiple possible outputs.

**Comment by AJIXuMuK** [comment]
@PzKfWg provided correct way to implement it.
