### ISSUE TITLE
People Picker - selectedItems method - items return empty string in secondaryText property if User has no Email

### ISSUE THREAD

**Issue by vlad-nvs** [pnp/sp-dev-fx-controls-react#209]
#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version 

Please specify what version of the library you are using: [   1.11.0    ]

#### Expected / Desired Behavior / Question
People Picker selectedItems method return empty string in case if User does not have Email.

Problem is in PeopleSearchService.ts -> SPPeopleSearchService.prototype.searchTenant in this line:
 var email = element.EntityData.Email !== null ? element.EntityData.Email : element.Description;

element.EntityData.Email never null for User even for User without Email. It's empty if User has no email.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @vlad-nvs. What is the expected behavior? Return empty secondary text if user has no email?
