### ISSUE TITLE
People Picker - no any image in case if user has default image or does not have email

### ISSUE THREAD

**Issue by vlad-nvs** [pnp/sp-dev-fx-controls-react#210]
#### Category
[ ] Enhancement

[ x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.11.0     ]

People Picker selected/suggested users does not have any rendered image in case if it does not have Email or has default image.

It should render icon with initials in such case.

Suppose PeoplePickerService.ts -> SPPeopleSearchService.prototype.generateUserPhotoLink called in all cases even if user does not have email or any image

Thanks!

**Comment by AsunSanLo** [comment]
Hi, as I have commented in the commit #248 

I think this issue is resolved.
I would prefer it to show the user initials when there's no image instead of the default's SharePoint user image, but the ideas that I've tried don't work with 100% success and they add an ugly complexity to the code

**Comment by AJIXuMuK** [comment]
Closing as resolved.
@vlad-nvs feel free open new issue if you still experience problems with People picker/
