### ISSUE TITLE
Custom People List for @pnp/spfx-controls-react/lib/PeoplePicker

### ISSUE THREAD

**Issue by Lilian1331** [pnp/sp-dev-fx-controls-react#215]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

[@pnp/spfx-controls-react : ^1.10.0]

Hi I am new to the sp-dev-fx-controls-react/lib/PeoplePicker.
Is there any way for me to define a list of the users so that the People Picker can pick from the defined list instead of all site users/site group?

For example, I got an array of users ID. I want to put it into the PeoplePicker, then the PeoplePicker will only show the users stated in the array.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @Lilian1331.
Sorry for late response.
Currently the only way to "limit" users to fetch is to provide `groupName` property.
Unfortunately, `PeoplePicker` doesn't work with custom array of users.

But we'd be happy to have this functionality as a PR :)
