### ISSUE TITLE
Add the "required" property to the Taxonomy Picker control

### ISSUE THREAD

**Issue by sortegamartin** [pnp/sp-dev-fx-controls-react#216]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

1.10.0

#### Enhancement

Hi, 
It would be a good improvement to add the "required" property to the Taxonomy Picker component, which will work just like the controls in the office ui fabric library. It would also be interesting to add other additional properties such as id, className, ...

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @sortegamartin!
`required` prop has been added to `TaxonomyPicker`, as well as `errorMessage` and `onGetErrorMessage` to provide error message.
The functionality will be available in the next release.
You can test it right away in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
