### ISSUE TITLE
Expose typeinfo for ChartData type

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#219]
#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

@hugoabernier  your chart control rocks!  Can we gaet it to expose the type info for the ChartData type?

**Comment by hugoabernier** [comment]
Why thank you @russgove ! 

I'd be happy to oblige!

In the meantime, try using `Chart.ChartData` for the `data` attribute. 

For example, you can define your chart data as follows:
```TypeScript
const data: Chart.ChartData = {
   labels:
      [
         'January', 'February', 'March', 'April', 'May', 'June', 'July'
      ],
      datasets: [
         {
            // data goes here
         }
      ]
};
```

The datasets, inside the `Chart.ChartData` are typed as `Chart.ChartDataSets`.

I'm just about to submit a PR to sp-dev-fx-webparts with a ton of examples of how to use each chart type. Once it is approved, I'll move on to this issue.

Hope this helps?

**Comment by russgove** [comment]
Thanks Hugo, that helps!
I just cant figure a way to  create a new strongly typed Dataset:
 let chartData: Chart.ChartData = {};
    chartData.labels = this.props.measures;
    chartData.datasets = [];
    for (var result in results) {
      let dataset = { label: result, data: [] };// how can i create this as a typed object?
      if (this.props.majorGroupFieldValueColors[result]) {
        dataset["backgroundColor"] = this.props.majorGroupFieldValueColors[result];
      }
      for (var measure of this.props.measures) {
        dataset.data.push(results[result][measure]);
      }
      chartData.datasets.push(dataset)
    };

**Comment by hugoabernier** [comment]
What makes the `Chart.ChartDataSets` class so flexible also makes it difficult to strongly type.

The `data` property of the `Chart.ChartDataSets` is defined as:

````TypeScript
Array<number | null | undefined> | ChartPoint[];
```

And the `ChartPoint` is consist of:

```TypeScript
interface ChartPoint {
        x?: number | string | Date;
        y?: number | string | Date;
        r?: number;
        t?: number | string | Date;
    }
```
From looking at your code, I assume you're using an array of numbers, so I would change the code as follows:

```TypeScript
let chartData: Chart.ChartData = {};
    chartData.labels = this.props.measures;
    chartData.datasets = [];
    for (var result in results) {
      let dataset: Chart.ChartDataSets = { label: result }; // get a strongly-typed dataset
      let data: Array<number> = []; // create a strongly-typed data array
      if (this.props.majorGroupFieldValueColors[result]) {
        // background color should now be available.
        dataset.backgroundColor = this.props.majorGroupFieldValueColors[result];
      }
      for (var measure of this.props.measures) {
        data.push(results[result][measure]);
      }

      // Assign data to dataset
      dataset.data = data;

      // Add dataset to chart's datasets
      chartData.datasets.push(dataset);
    }
```
I hope I'm making sense? 

Thanks for using the control!

**Comment by russgove** [comment]
Thanks!

**Comment by russgove** [comment]
btw. I found  '@types/chart.js'.

I tried installing it on my project and it broke a bunch of things. I thing you're right in that thios stuff is best left untyped.

**Comment by hugoabernier** [comment]
@russgove I have created a ton of sample web parts to show various ways to use the Chart Control. It hasn't yet been merged to the master branch, but you can find it on the dev branch in the
[sp-dev-fx-webparts repo](https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-chartcontrol).

I hope at least of the samples will help you. I'd love to hear your comments.

**Comment by russgove** [comment]
Hi Hugo,
I'll download and have a look tomorrow (time permitting)
<rant>
I just rolled my app out to production today with this control.
I'm using dybamic data to communicate between the 3 webparts.
Data provider webpart has  start and endate controls to let user select
date range. Uses Dynamic Data to  feed the listitems to the other 3
webparts so they are always in sync.

Other webparts use your control, (using stacked bar charts off the list
data). I even got the on click wire up so that when you click on a bar it
formats a url with the right FilterField and FilterValue and brings you to
the view showing the underlying data.

f;ing nice!
</rant>

**Comment by russgove** [comment]
https://github.com/russgove/HamiltonVflCharts

**Comment by AJIXuMuK** [comment]
Closing as answered
