### ISSUE TITLE
ListView: _flattenItem Maximum call stack size exceeded

### ISSUE THREAD

**Issue by semopz** [pnp/sp-dev-fx-controls-react#223]
#### Category
[x] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.11  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I should be able to pass an array of objects of any kind of complexity and then use the viewfields options and render method to then decide what is displayed and/or how. I should be able to tell the component to not flatten the objects (as I already tell the component how the objects should be used inside the viewFields prop)

I should be able to skip this flatten function using a parameter or at least obfuscate certain fields. Or maybe limit the evaluation depth to only 1 or two levels (what exactly is the component expecting to find at the end of the rabbit hole?).

#### Observed Behavior
If my items contain an SPFx context object OR an object that has the context nested inside it, the listview component will  throw "Maximum call stack size exceeded" due to the recursive flattenItem function.

#### Steps to Reproduce
Pass an SPFx context, or an object with a field that contains a context to the items prop of the listview component. I've tested using the ListViewCommandSetContext but it will probably break using the webpart context too.

**Comment by sympmarc** [comment]
I would suggest you rethink what you''re passing into the function for items if you have the context in it. If you just pass the array of actual items, you'll probably be fine.

**Comment by michaelmaillot** [comment]
Hi @semopz,

Even if there's something to enhance about the `_flattenItem` object flexibility, did you figure out about passing items without the whole context (which is not recommended)?
