### ISSUE TITLE
titleText doesn't work for people picker

### ISSUE THREAD

**Issue by jeffseiffert** [pnp/sp-dev-fx-controls-react#225]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version
1.11.0

#### Expected / Desired Behavior / Question
using the following code:
```
  <PeoplePicker
                context={this.props.context}
                titleText="Filed By"
                personSelectionLimit={1}
                showtooltip={true}
                isRequired={false}
                selectedItems={this._getPeoplePickerItems}
                showHiddenInUI={false}
                principalTypes={[PrincipalType.User]} />
```

It shows in the input box no placeholder text. I would expect to see "Filed By"

#### Observed Behavior
It shows nothing in the input box for the place holder text.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @jeffseiffert,

Latest version (3.15.0) handles the `titleText` prop:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/9083276a-666a-4027-bf20-39a94891d9ca)

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/4ecb935f-16af-4dd4-8c1c-d37ff9267996)

Is it something required in On-Prem context only (which requests using version 1.x of the controls)? Or would you mind using latest version?
