### ISSUE TITLE
New Control: Search Query Control

### ISSUE THREAD

**Issue by nanddeepn** [pnp/sp-dev-fx-controls-react#23]
[x ] Enhancement

[ ] Bug

[ ] Question

Property control to query the search results.
Similar to Search Results in classic SharePoint.

Thanks!

**Comment by AsishP** [comment]
This is an interesting requirement. I have a similar one upcoming at my client. Would be happy to pick this one up after the people picker, if not picked already.

**Comment by nanddeepn** [comment]
Not started yet. Please let me know, if I can be of any help during implementation

**Comment by estruyf** [comment]
@AsishP @nanddeepn not yet assigned to someone, so feel free to contribute.

**Comment by AsishP** [comment]
Thanks @estruyf. 

Yeah sure @nanddeepn, what are you thoughts on the scope. I think it would be good for us to scope the requirements for this control because the SharePoint classic search results page can do many scenarios and includes refiners, result sources etc which could get complex soon. 

As per me, to start we built an initial keyword based search box control with scoping to all enterprise results and display them in a card view allowing paging of results. Thoughts?

**Comment by AsishP** [comment]
Hi @estruyf, @nanddeepn , I am completed with the people picker and starting with this control. I suppose cards are a great idea, but would they be more horizontal cards (as in Teams) or vertical cards (as in Document cards). I suppose horizontal cards in the same layout as classic search would work? 

Another similar component, we have implemented for a project is a search control with modal results. Below is the screenshot. How does that look?

On property pane, what could be the options - result sources? managed properties? site level? list? 

Also request others share ideas. There is a lot of potential that this control could add.

![image](https://user-images.githubusercontent.com/11584558/39800545-838288f6-53ab-11e8-973e-45fc7ecc8c68.png)

**Comment by nanddeepn** [comment]
@AsishP , That's great!
In the property pane, lets have Result sources as of now.

**Comment by estruyf** [comment]
Looks like a really good control.

About the properties, make it as extensible as possible. 

Great work!

**Comment by AsishP** [comment]
Thanks @estruyf and @nanddeepn for the feedback. Will share updated screenshots as soon as got something ready.

**Comment by AJIXuMuK** [comment]
Hi @nanddeepn, @AsishP - just checking if it's still somewhere in progress? :)

**Comment by nanddeepn** [comment]
Hi @AJIXuMuK 
Almost 3 years ago, when it was started. No recent updates on this and nothing in progress from my side. But please let me know, if anything to be done here.
Thank you.

**Comment by sympmarc** [comment]
One would think these requirements have been covered by the [PnP Modern Search solution](https://microsoft-search.github.io/pnp-modern-search/) ? Differently, sure, but us there a need to rebuild?

**Comment by AJIXuMuK** [comment]
I agree @sympmarc. Just wanted to check first to not lose existing job before closing.
