### ISSUE TITLE
Using ListView Control inside a BaseDialog (@microsoft/sp-dialog)

### ISSUE THREAD

**Issue by DaMichiiii** [pnp/sp-dev-fx-controls-react#238]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

^1.11.0

#### Expected / Desired Behavior / Question
I want to use your ListView Control inside a BaseDialog provided by SharePoint Framework
I expect the Dialog to be opened with the ListView Control opening and showing all the ListItems passed in by my Model. This works perfectly without the Dialog using the same Model

#### Observed Behavior
When the Dialog is opened, it shows the basic Dialog UI including the Search Box from the ListView.
The Fields as well as the ListItems are not visible. As soon as I hit F12 (Developer Tools both in Firefox and Chrome), the ListView is correctly rendered.

#### Steps to Reproduce
Code is attached, only missing the model and the trigger to open the Dialog

[ListViewDialog.zip](https://github.com/SharePoint/sp-dev-fx-controls-react/files/2860806/ListViewDialog.zip)

**Comment by michaelmaillot** [comment]
Hi @DaMichiiii,

I know it's been a while... But did you have the chance to try with 3x version of the Controls?

I've tried with a new webpart which uses sp-dialog and contains the ListView and it displays my loaded data when the Dialog is displayed:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/019cddb7-c53b-4859-b198-1ac8d6b7bc94)
