### ISSUE TITLE
List of Icons / Applications supported for ListView

### ISSUE THREAD

**Issue by DaMichiiii** [pnp/sp-dev-fx-controls-react#250]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

^1.12.0

#### Question
Dear pnp Team,

I have a question regarding the icon paths i can use to display icons in your Listview.
Only ones i found out are extensions, like docx, xlxs, etc.

Is there some sort of list, which ones i can use? I checked the icon Names i found here:
https://developer.microsoft.com/en-us/fabric#/styles/icons

and other sources for offical MS UI Fabric icons, but they wouldn't display correctly.

I wanted to use Folder for example, but it only showed the default icon.

Can you help me out on this one?
Thanks in advance.

**Comment by Luca3082** [comment]
no response in this thread?
is there any way to use a specific file url to render icon in the listview control, please?

**Comment by michaelmaillot** [comment]
Hi everyone,

If I'm not mistaken, for now the icon rendering for ListView (if we're talking about `iconFieldName` prop) relies on the [FileTypeIcon](https://pnp.github.io/sp-dev-fx-controls-react/controls/FileTypeIcon/) control, which has a predefined list of applications (which you can find [here](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/fileTypeIcon/IFileTypeIcon.ts)).

Maybe an improvment could be to allow overriding the render of the icon column or adding new extensions / file type (such as folder) to the control.

**Comment by joelfmrodrigues** [comment]
@DaMichiiii sorry for the extremely late reply...
Michael is right and the rendering of the icon is handled internally using the FileTypeIcon control, which can be extended to accommodate additional requirements. As an alternative, you should be able to use a different column and control the rendering on your side.

Did this answer the question?
