### ISSUE TITLE
ListView select not working

### ISSUE THREAD

**Issue by thespooler** [pnp/sp-dev-fx-controls-react#251]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
1.12.0

#### Expected / Desired Behavior / Question
When putting a ListView inside a React Component that controls its items and selection props, an item should be selectable.

#### Observed Behavior
When putting a ListView inside a React Component, anything that trigger componentDidUpdate, like setState or a prop change, will cause an invalidation of the items selection and cause an invalid call to props.selection().

#### Steps to Reproduce
Call setState on a component containing a ListView with a selected item and watch the selection disapear.
Handy reproduction: https://github.com/thespooler/listview-bughunt

**Comment by thespooler** [comment]
I would suspect that using isEqual in componentDidUpdate might not behave in the expected way. If the select() function is bound in render(), as lodash does strict equality comparison on functions, it likely will always return false.

**Comment by jchilde** [comment]
Any update on this bug.  It prevents anything beyond creating samples - no real world application for this control is possible beyond just displaying list data.

**Comment by thespooler** [comment]
If this PR goes through, that should fix this issue.
This isn't perfect, but now at least, it should basically work.

**Comment by AJIXuMuK** [comment]
Hi @thespooler, @jchilde 

The fix has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by thespooler** [comment]
Fantastic!

**Comment by AJIXuMuK** [comment]
`v2.5.0` has been released.
