### ISSUE TITLE
How to run/debug this project?

### ISSUE THREAD

**Issue by peterremote1980** [pnp/sp-dev-fx-controls-react#252]
Hi , How to run/debug this project?
thanks
Peter

**Comment by estruyf** [comment]
You can clone this project, install the dependencies via `nvm I` and start it with `gulp serve`. On the workbench, you will now have a controls web part available that contains most of the controls of this project to test out.

**Comment by jonathanhotono** [comment]
@estruyf what the node version requirement for this project? Is this based on spfx 1.3? So node v8?

**Comment by estruyf** [comment]
@jonathanhotono the project is indeed still based on 1.3 (we have plans to change this to the latest version, but comes with a UI impact). Version supported in 1.3 was node v6, but v8 should also work.
