### ISSUE TITLE
FieldUserRenderer - No Flyouts in SharePoint App (iOS)

### ISSUE THREAD

**Issue by BigEaseGueldi** [pnp/sp-dev-fx-controls-react#253]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
Please specify what version of the library you are using: [1.12.0]

#### Expected / Desired Behavior / Question
Touching on a FieldUserRenderer element should open the persona control. Maybe it would in general be a good idea to also react on clicks (currently only hovering opens the popup)? 

(I might have just realized that there doesn't seem to be any kind of touch support for this kind of fields in standard lists/libraries at all ;-))

#### Observed Behavior
Touching on a FieldUserRenderer element doesn't do anything in the SharePoint App (tested with iOS).

#### Steps to Reproduce
(see above)

**Comment by michaelmaillot** [comment]
Hi @BigEaseGueldi,

Did you have the chance to test with latest version (3.15.0)? FYI this control is using the [HoverCard](https://developer.microsoft.com/en-us/fluentui#/controls/web/hovercard) Fluent UI one under the hood.

**Comment by BigEaseGueldi** [comment]
Hi @michaelmaillot - unfortunately not - unable to test this at the moment. As this is a rather old bug, you might want to set it to "solved" - chances are high that this is that case any way...

**Comment by michaelmaillot** [comment]
Thanks for your feedback.

In that case I will close the issue, if it's still occurring, an issue will be raised.
