### ISSUE TITLE
New Control: Persona Card

### ISSUE THREAD

**Issue by hugoabernier** [pnp/sp-dev-fx-controls-react#259]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.12.0]

#### Expected / Desired Behavior / Question

The office ui fabric library provides a way to create a persona card that looks and feels like the out-of-the-box persona card in SharePoint. However, it requires the developer to do all the work to retrieve the information.
![Example Persona Card](https://user-images.githubusercontent.com/13972467/54941713-e6f7b380-4f03-11e9-8c74-9e257ca0ab1d.png)
[Picture credit Heinrich Ulbricht](https://sharepoint.stackexchange.com/questions/259908/how-to-display-the-sharepoint-live-persona-card/259930#259930)

While it ultimately gives developers full control over what to render in the persona card, there are times where a developer just wants to render a standard/out-of-the-box persona card in their custom solutions.

Would it be useful to have a standard control to render an out-of-the-box persona card?

#### Observed Behavior
Office UI Fabric offers persona card control, but does not retrieve data for you.

#### Steps to Reproduce
1. Go to the [Office UI Fabric example](https://developer.microsoft.com/en-us/fabric-js/components/personacard/personacard) and copy into your own solution.
2. Control will require you to populate the data

> This idea originated from a [StackExchange post from Heinrich](https://sharepoint.stackexchange.com/questions/259908/how-to-display-the-sharepoint-live-persona-card/259930#259930). If you think it's a good idea, he deserves the credit. If you think it's a bad idea, I deserve the credit :-)

Thanks!

**Comment by hugoabernier** [comment]
By the way, the proposed control would leverage the existing hovercard in the FieldUserRenderer control, but make it more generic so that it can be used outside of the FieldUserRender control.

**Comment by heinrich-ulbricht** [comment]
Note: Re-using the [standard control](https://social.technet.microsoft.com/wiki/contents/articles/52249.sharepoint-online-live-persona-card-in-custom-webpart.aspx) would be my preferred solution as this would always be up-to-date. But if that's not possible a PnP control would be really handy!

**Comment by hugoabernier** [comment]
Yes, you're right, I should have been clearer. It should use the standard control, but make it easier for developers to use in their solutions.  That way, the behavior remains consistent when Microsoft updates the functionality.

**Comment by heinrich-ulbricht** [comment]
Oh and looking at the `PersonaCard` component: this is Fabric JS only, there is no [React](https://developer.microsoft.com/en-us/fabric) component. I'd like the new component to be a React one.

**Comment by hugoabernier** [comment]
@heinrich-ulbricht I started putting something together last night.  It uses the Office UI Fabric [HoverCard](https://developer.microsoft.com/en-us/fabric#/components/hovercard) and retrieves the user profile information from their username. I would have preferred to hook into SharePoint's own livepersonacard but I suspect it isn't supported for us to do so.

If anyone has any ideas how to leverage the OOB livepersonacard, I would appreciate any tips you may have.

My goal would be to avoid having every developer to re-write the profile loading and persona card rendering bits, but with the ability to pass the persona information (to avoid loading it from the profile) and optionally override rendering (to create your own version of a persona card).

I'll post it as a sample on my own repo over the next few days, and we can see about converting it to a control if there is interest.

**Comment by heinrich-ulbricht** [comment]
Don't know who could give more information about whether using the standard card is supported or not - maybe @estruyf?

**Comment by AJIXuMuK** [comment]
As far as I know, standard card is not exposed as a component. That’s why we can’t use it. And that’s why I implemented the functionality using `HoverCard` in `FieldUserRenderer`. You can partially reuse code from there, and maybe add additional info if you find a way to get more profile details (like LinkedIn profile)

**Comment by heinrich-ulbricht** [comment]
@AJIXuMuK Well technically it seems to be possible to load and use the standard card as demonstrated [here](https://github.com/Anil-Lakhagoudar/SPFxLivePersonaCard/blob/c4696234852850a4db201c664d420067bb43048d/src/webparts/spContactCard/components/SPFXPeopleCard/SPFxPeopleCard.tsx#L58). Now we need a sign if we are supposed to do this.

**Comment by hugoabernier** [comment]
@AJIXuMuK the example you linked uses the `loadComponentById` method of the `SPComponentLoader`. If I'm reading [this](https://github.com/SharePoint/sp-dev-docs/issues/2376) right, that method is no longer available and shouldn't be used. I believe the best way to do it (as @AJIXuMuK  pointed out) would be to use the `HoverCard`.

If you have success with the sample you linked to, please do not hesitate to share with us. I'd love to avoid duplicating what SharePoint does.

**Comment by jonathanhotono** [comment]
This might not be related, but there is also a nice Org Chart feature within the persona when clicking the "Show more" button that perhaps can be extracted and decoupled into different component:
![image](https://user-images.githubusercontent.com/6864547/55206974-fe3be700-520a-11e9-8e21-0cec934dc060.png)
![image](https://user-images.githubusercontent.com/6864547/55207060-596dd980-520b-11e9-8754-c7158da16e6b.png)

**Comment by yeshwanthjagannath** [comment]
@AJIXuMuK @heinrich-ulbricht @hugoabernier @VesaJuvonen  - Is there a blog that showcases the steps to implement a custom HoverCard functionality with custom attributes to be displayed on the hovercard? or any article out there which shows us how to incorporate the FIeldUserRenderer? In my case i do not think this would work, since i am reading data from a custom list on SharePoint and rendering the data in a Persona Office UI Fabric react component and i am trying to surface custom attributes onhover of the persona card. Can you confirm if this is doable with the FieldUserRenderer?

**Comment by AJIXuMuK** [comment]
@yeshwanthjagannath 
`FieldUserRenderer` is created to provide UI similar to OOTB rendering on User or Group field in SharePoint - display name as a link + `HoverCard` on hover.
There is a [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/fields/FieldUserRenderer/) on how to use `FieldUserRenderer`.
You can also look at [FieldUserRenderer](https://github.com/SharePoint/sp-dev-fx-controls-react/tree/dev/src/controls/fields/fieldUserRenderer) code itself to see how `HoverCard` is used.

**Comment by yeshwanthjagannath** [comment]
@AJIXuMuK - Thanks for pointing me out to this. Looking at it looks like i would have to implement my own FieldUserRenderer and HoverCard because of my custom attributes i want to surface as part of the HoverCard. Correct me if am wrong.

**Comment by AJIXuMuK** [comment]
@yeshwanthjagannath 
Yes, `FieldUserRenderer` doesn't have any API or something to allow to add custom elements into `HoverCard`.

**Comment by yeshwanthjagannath** [comment]
@AJIXuMuK - Sounds good. Thank you for your response. I will dig through and code this out from scratch for my need.

**Comment by hugoabernier** [comment]
Ok, since `loadComponentById` is available again, I was able to create `ProfileCard` component with Denis Molodtsov's help (he did all the hard work, I just made it into a potential PnP control). 

This is what it looks like:

![PersonaCard](https://user-images.githubusercontent.com/13972467/62267024-aac7e880-b3f8-11e9-8e20-c2ddcf0ee4d9.gif)

The question I have is: do we want a control that wraps around any element, e.g.:
```Typescript
<ProfileCard>
<FieldUserRenderer users={event.fieldValue} context={this.context} className={'some-class'} cssProps={{ background: '#f00' }} />
</ProfileCard>
```
Or do we want a control that allows passing all the properties of a persona card in? Which is what I have now...

```Typescript
 public render(): React.ReactElement<IHelloPersonaProps> {
    const currentUserProps = {
      text: this.props.context.pageContext.user.displayName,
      email: this.props.context.pageContext.user.email ? this.props.context.pageContext.user.email : this.props.context.pageContext.user.loginName,
      serviceScope: this.props.context.serviceScope,
      //className: 'persona-card',
      //size: PersonaSize.size32,
      // moreDetail: this.personaDetail(), /* pass react element */
      //moreDetail: '<div>Details</div>', /* pass html string */
      // onCardOpenCallback: () => {
      //     console.log('WebPart', 'on card open callback');
      // },
      // onCardCloseCallback: () => {
      //     console.log('WebPart', 'on card close callaback');
      // }
  };
    return (
      <div className={ styles.helloPersona }>
        <h3>User with automatic picture</h3>
        <PersonaCard {...currentUserProps} />
        <h3>User with smaller picture</h3>
        <PersonaCard {...currentUserProps} size={PersonaSize.size32} />
        <h3>User name for list</h3>
        <PersonaCard {...currentUserProps} size={PersonaSize.size10} hideCoin={true} />
        <h3>External user</h3>
        <PersonaCard
        text="Denis Molodtsov"
        email="Denis.Molodtsov@hugoabernier.com"
        serviceScope={this.props.context.serviceScope}
        secondaryText={"Deserves all the credit"}
        //size={PersonaSize.size32}
        />
        <h3>Totally fake user</h3>
        <PersonaCard
        text="Fake User"
        email="Fake.User@hugoabernier.com"
        serviceScope={this.props.context.serviceScope}
        //size={PersonaSize.size32}
        />
      </div>
    );
  }
```

I suspect that we want option 1, so that we don't have two controls that render user information and so that it can be re-used in other situations, but I'd like your opinion.

Either way, I can submit the PR today.

**Comment by hugoabernier** [comment]
Oh, and also, what do you want to call the control? `PersonaCard` or `ProfileCard`?

**Comment by heinrich-ulbricht** [comment]
Looking at the developer tools:
![image](https://user-images.githubusercontent.com/3469970/62299185-c83a9800-b474-11e9-8062-8bc13fee182f.png)

![image](https://user-images.githubusercontent.com/3469970/62299348-1354ab00-b475-11e9-9dc0-77f6bc0baf52.png)

Seems to be called "LivePersonaCard" by Microsoft - so I would say something with "Persona" is good.

**Comment by hugoabernier** [comment]
`LivePersonaCard` it is! Thank you @heinrich-ulbricht -- it was you idea in the first place! (Don't worry, I gave you credit in the code)

**Comment by heinrich-ulbricht** [comment]
No worries! So far I did nothing but wanting to have such a component. I'm thankful you guys found the time to work on this.

@joaojmendes over here on Twitter https://twitter.com/joaojmendes/status/1155945428027768834  was the one getting this topic rolling again - maybe some development efforts could be coordinated? Just discovered he has a pull request open: https://github.com/SharePoint/sp-dev-fx-webparts/pull/930

**Comment by joaojmendes** [comment]
Soon I will work  on new reusable control persona card that will have a live persona card associated.

Thank you. ☺️

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by hugoabernier** [comment]
@joaojmendes  Great minds think alike! I submitted PR # 352, but I would love to see how we can combine our efforts to avoid duplicates.

The version I wrote is intended as a wrapper around any HTML elements, for flexibility purposes. If you create an empty `<LivePersonaCard />` element, it will attempt to create a `PersonaCard` with the user info that's passed it.

There is an opportunity to combine some elements with `FieldUserRenderer`, but I didn't want to make those changes until I discussed it with you guys.

Let me know what you think! I welcome any and all suggestions... just be kind :-)

**Comment by joaojmendes** [comment]
Hi Hugo,


I saw your PR now, that's what I was going to do! 🙂 It's looking pretty good. is what I use in the React-directory Web Part.

It seems-very well to change the FieldUserRenderer, and include the Live Persona Card.


Thanks for sharing!

João

________________________________

**Comment by joaojmendes** [comment]
Thank you @Hugo Bernier<mailto:notifications@github.com>.

Done !  😊

**Comment by robiharid** [comment]
> @joaojmendes @heinrich-ulbricht @AJIXuMuK I opened a uservoice feedback to ask (nicely) that Microsoft supports the LPC for 3rd-party developers. Your votes would help: https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38451154-provide-support-for-livepersonacard-in-3rd-party-s

Hey can I ask what happened with this? I voted for your web part too.

I want a Persona web part so I can use the Graph API to call 'People I work with' and provide a list of users via Graph displayed through the Live Persona Card. Do I have to manually create it through https://docs.microsoft.com/en-us/graph/toolkit/components/person-card?

**Comment by joelfmrodrigues** [comment]
@hugoabernier we now have a persona control in the library. Can we close this issue?

**Comment by hugoabernier** [comment]
Absolutely! Thank you!!!
