### ISSUE TITLE
List view with filter does not render properly

### ISSUE THREAD

**Issue by Leomaradan** [pnp/sp-dev-fx-controls-react#261]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.12.0 ]

#### Expected
Select a value in the List View, type some text in the filter. If the item is hidden, the selection disapear and the selection event is triggered. If the item isn't hide by the filter, it remain selected

#### Observed Behavior
The selected item seems to be bound to the index of displayed items.

For exemple, if I select the item number 2 on the unfiltered listview, and I start to filter, the selection is shown on the new number 2 item, and the event for selection are not triggered. If I want to select the falsy-selected item, I have to click two-time on the element.

![bug1](https://user-images.githubusercontent.com/3043485/55238678-66072780-5235-11e9-8320-b608e29d2bba.png)
![bug2](https://user-images.githubusercontent.com/3043485/55238679-66072780-5235-11e9-9a73-d58ba409704c.png)
![bug3](https://user-images.githubusercontent.com/3043485/55238680-669fbe00-5235-11e9-8a1b-5d9f55533ace.png)

#### Steps to Reproduce
Put a list-view with item on a page
Add a trigger to check is the selection change
Typesome filter text

`<ListView`
`        items={this.props.items}`
`        selection={this._getSelection}`
`        selectionMode={SelectionMode.single}`
`        showFilter={true}`
`></ListView>`

**Comment by Ameralajore** [comment]
I have a list with people field when render it with list view it returns ID, so I override the render of the field to a function that took the ID and return the Display name, the function correctly return the Display name but the list view return does not render it.

**Comment by michaelmaillot** [comment]
Hi @Leomaradan,

In the latest version (3.15.0), the selected index is not bound to the index anymore:

![spfx-controls-listview-selection-filter](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/2a98b087-d7c5-43fa-88c6-e20d1e9285b4)

However, if selection is outside the filtered data, it's not kept once filter reset. By now, it's the same behavior than the Fluent UI [DetailsList](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) component on which the ListView control relies.

Is it something required in On-Prem context only (which requests using version 1.x of the controls)? Or would you mind using latest version?
