### ISSUE TITLE
RichText control - Request for inline image support

### ISSUE THREAD

**Issue by semopz** [pnp/sp-dev-fx-controls-react#264]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.13.0-beta]

#### Expected / Desired Behavior / Question
I'm very interested in the RichText control. My immediate requirement is for support for inline images. At this point I'm not sure what is going to work best for storing the image so an option of the following would be great:

1. Inline base64 encoded data URI
2. Relative links to site assets folder (similar to classic forms rich text fields)

I think option one is the most practical for most scenarios but I don't know how much raw data a SharePoint Online multi line field can accept (I've seen 1GB mentioned for 2013).

As a more general request, would it be possible to pass props directly to the underlying roosterjs component or is it not as simple as that? I can't seem to find much documentation on rooster so I have no idea how it is implemented.

I think to begin with, the simplest form of inline images would be a great addition to this component (you can always use an image to represent something that the control does not support).

#### Observed Behavior
Images are not supported.

**Comment by Constey** [comment]
I would love aswell this feature, I guess here is no workaround currently or?

**Comment by michaelmaillot** [comment]
Hi @semopz & @Constey,

This feature is available since [v2.2.0](https://github.com/pnp/sp-dev-fx-controls-react/pull/705).

Does it fit your need? Or is it something specific for On-Prem environment (which should be available in v1)?
