### ISSUE TITLE
TaxonomyPicker: Style issue in term check box if term label too short

### ISSUE THREAD

**Issue by jonepo** [pnp/sp-dev-fx-controls-react#272]
![spfx-taxpicker-bug](https://user-images.githubusercontent.com/49401152/55726644-f6552180-5a18-11e9-9aa3-7e1e3b012905.JPG)

#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 1.12.0

#### Expected / Desired Behavior / Question

Terms should be aligned correctly in the term picker panel.

#### Observed Behavior

The checkbox moves to the right if the term label gets too short. See the attached screenshot.

I investigated the reason and it looks like corev15.css from SharePoint sets min-width for buttons to 6em. When I overrode that in developer toolbar and set the min-width to auto, inherit or initial, it corrected itself.

#### Steps to Reproduce

Have term in the selected term set with very short label.

Thanks!

**Comment by vipulkelkar** [comment]
Hi @jonepo , are you still seeing this issue ? Just tested on Chrome and Edge, seems to be working fine

![TaxonomyPicker](https://user-images.githubusercontent.com/13727430/69621222-ac32b600-1064-11ea-8f03-819b6e9a4afb.PNG)

**Comment by jonepo** [comment]
Hi @vipulkelkar, unfortunately I haven't been in the particular customer project in a while so I can't confirm it just now. But if you could reproduce it in 1.12 version and now in the latest version it doesn't happen anymore, I trust that it's ok. But if I have any spare time, I'll try to quickly test this so you could close it as confirmed.

**Comment by michaelmaillot** [comment]
Hi @jonepo,

I confirm @vipulkelkar's screen, it displays correctly in latest version:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/1ff5cc03-716a-43bd-b2e3-b65ba4dabba5)

Is it ok for you?

**Comment by jonepo** [comment]
Hi!

Based on the screenshot, it looks good. And as you have also confirmed it, I trust it to be ok. You can close the issue.

**Comment by joelfmrodrigues** [comment]
Thanks @jonepo and @michaelmaillot !
