### ISSUE TITLE
[People Picker] Lodash UniqBy undefined on onSearchFieldChanged

### ISSUE THREAD

**Issue by costada1** [pnp/sp-dev-fx-controls-react#273]
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.12.0     ]

Hello everyone,

I've been experiencing an strange problem, I have a simple empty react web part on SPFX project - just this single web part. It is a sharepoint 2016 on premises solution.

I've installed @pnp/spfx-controls-react and followed the guidelines on the PeoplePicker section.

When I do a gulp serve and test the web part - which has just this PeoplePicker control - I get the following error:

PeoplePickerComponent.tsx:112 Uncaught (in promise) TypeError: sp_lodash_subset_1.uniqBy is not a function
    at PeoplePicker.<anonymous> (PeoplePickerComponent.tsx:112)
    at step (version.ts:1)
    at Object.next (version.ts:1)
    at fulfilled (version.ts:1)

TSX Code:
import * as React from 'react';
import styles from './HelloWorld.module.scss';
import { IHelloWorldProps } from './IHelloWorldProps';
import { escape } from '@microsoft/sp-lodash-subset';
import { PeoplePicker, PrincipalType } from "@pnp/spfx-controls-react/lib/PeoplePicker";

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {gulp
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <div className={ styles.helloWorld }>
        <div className={ styles.container }>
          <div className={ styles.row }>
            <div className={ styles.column }>
              <span className={ styles.title }>Welcome to SharePoint!</span>
              <PeoplePicker
    context={this.props.context}
    titleText="People Picker"
    personSelectionLimit={3}
    groupName={""} // Leave this blank in case you want to filter from all users
    showtooltip={true}
    isRequired={true}
    disabled={false}
    selectedItems={this._getPeoplePickerItems}
    showHiddenInUI={false}
    principalTypes={[PrincipalType.User]}
    resolveDelay={5000} />
            </div>
          </div>
        </div>
      </div>
    );
  }

  private _getPeoplePickerItems(items: any[]) {
    debugger;
    console.log('Items:', items);
  }
}

**Comment by HarshitGupta20** [comment]
I am facing the same issue. Were you able to solve it.?

**Comment by bbraeu** [comment]
Im also facing the same issue

**Comment by HarshitGupta20** [comment]
I am not sure, why the issue is appearing, however, I have found the below workaround.

Comment out line no. 80 in the file, \node_modules\@pnp\spfx-controls-react\lib\controls\peoplepicker\PeoplePickerComponent.js

This will resolve the issue. Hope it helps you.

**Comment by joelfmrodrigues** [comment]
@costada1 apologies for the delay in getting back to this. I assume this is no longer an issue, are you able to confirm?
