### ISSUE TITLE
TaxonomyPicker: finding terms with label

### ISSUE THREAD

**Issue by JarecN** [pnp/sp-dev-fx-controls-react#288]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.12.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
As term could have other labels (synonyms and abbreviations) it would be great to be able to find a term by typing other label, not just typing default label. Let's say I have term which default label is "Internal Memo" and it has other labels "Executive Board Memo" and "HR Memo". Now when I type "executive" or "hr" on TaxonomyPicker I don't get any suggestions. I would love to get that "Internal Memo" suggested when typing "executive" or "hr".

Thanks!

**Comment by TheThor59** [comment]
Hello,

I've implemented a version that should do the trick for alternate labels on terms. I didn't had solution for alternative languages. If any one has solution to detect user's current LCID (1033) and not local (en-US) that could be perfect to fine tune the feature.
The commit somehow went into my pull request #631 so it complete the fix I did here on issue with empty anchorId
