### ISSUE TITLE
Rich Text editor styles

### ISSUE THREAD

**Issue by vvvvvvvesna** [pnp/sp-dev-fx-controls-react#290]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Not complete styles from oob

#### Observed Behavior
Not all styles complete before add className from OOB RTE 
   ```
<RichText value={text} 
                        className="cke_editable rte--read"
                            onChange={(newText) => this.onTextChange(newText)}
                        /> 


```
#### Steps to Reproduce
add webpart with rich text editor control and then paste ul for example. not completely same styles as OOB RTE

![image](https://user-images.githubusercontent.com/18404399/57062377-99bbee00-6cc8-11e9-8974-a24e8d79748c.png)

**Comment by estruyf** [comment]
@hugoabernier something you can check?

**Comment by hugoabernier** [comment]
@estruyf  I'd be happy to do so while I'm at SPC, next week.

**Comment by michaelmaillot** [comment]
Hi @vvvvvvvesna,

By now, latest version (3.15.0) takes the site's theme style even if pasted from an existing text (from native Text webpart for example).

Can you confirm it on your side?
