### ISSUE TITLE
ListItemAttachments error after removing attachment

### ISSUE THREAD

**Issue by bva999** [pnp/sp-dev-fx-controls-react#294]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.13.0  ]

In the listItemAttachments control,  when you delete a file you have got an error.

**Steps to Reproduce**
Delete a file and follow the steps. After the file has been deleted, you get an error: 

> Uncaught TypeError: Cannot read property 'width' of undefined
>     at DocumentCardPreview._renderPreviewImage (DocumentCardPreview.tsx:47)
>     at DocumentCardPreview.render (DocumentCardPreview.tsx:26)
>     at DocumentCardPreview.obj.<computed> [as render] (BaseComponent.ts:254)
>     at Dn (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)
>     at Mn (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)
>     at Fn (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)
>     at xr (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)
>     at wr (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)
>     at Vr (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)
>     at Wr (sp-pages-assembly_en-us_cb7c5ac05a2eaa8aa94733475559e220.js:957)

![image](https://user-images.githubusercontent.com/12149939/57371944-4274bc80-71a5-11e9-9cbb-478c82a99c3c.png)

**Comment by chrisobriensp** [comment]
Yes, I see the same. Would be great to get this fixed in this otherwise awesome control :)

**Comment by estruyf** [comment]
@bva999 or @chrisobriensp would you be able to test out the latest beta version? It might be that a fix to the `ListItemAttachments` control has also fixed this one.

Here you can read more information on how you can test out the latest beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by bva999** [comment]
Yes, it works for me in beta version!

**Comment by AJIXuMuK** [comment]
Seems to be fixed a while ago.
