### ISSUE TITLE
Rich text editor control - image support

### ISSUE THREAD

**Issue by glyn-clough-wm-reply** [pnp/sp-dev-fx-controls-react#298]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

An enhancement request, as per [table support](https://github.com/SharePoint/sp-dev-fx-controls-react/issues/297), would it be possible to allow for the insertion of images? Again, it was referenced by @hugoabernier [here](https://github.com/SharePoint/sp-dev-fx-controls-react/issues/20#issuecomment-460111104).

I agree in most cases about wanting to replicate the out of the box behaviour, so perhaps this could be added as an option to enable/ disable.

I think I saw in another sample a really good asset/ image picker that replicated the OOB one - but can't find it again sorry!

**Comment by jonathanhotono** [comment]
perhaps we could incorporate the functionality that @hugoabernier  built on his cool react comparer sample:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-comparer

**Comment by hugoabernier** [comment]
Thanks @jonathanhotono, I'm already working on integrating it into a future update

**Comment by jonathanhotono** [comment]
Thanks @hugoabernier . I'm also curious to know whether this rich text editor can also supports custom inject elements? So just in case in future developers need to add its own inject control into the editor configuration. For now adding images/videos/custom media + table is quite needed, but could be good if we could make it configurable.

**Comment by glyn-clough-wm-reply** [comment]
Thank you @jonathanhotono - I knew I'd seen it somewhere!

**Comment by Tanddant** [comment]
In case you missed it

**Comment by joelfmrodrigues** [comment]
Feature added, closing issue
