### ISSUE TITLE
SPFx React States issues

### ISSUE THREAD

**Issue by rafakil** [pnp/sp-dev-fx-controls-react#306]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [    15.4     ]

## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

Hello,
I get this error when executing my solution that contains 7 SPFx webparts using React 15.4, but just on the customer side , in my side everything works as expected.
"Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '@-moz-keyframes animation_do0sdn{from{opacity:0;}to{opacity:1;}}'.
I have also an issue about setState, actually each time I need to set the state of my controls (enabled, disabled) I set that using states, on my side it's working fastly, but on the customer side it take about 10 secondes to update the state.

Any suggestions please?

**Comment by michaelmaillot** [comment]
Hi @rafakil,

Do you still have issues with your SPFx solution?

Hard to know what could be the problem without code snippets or details about what contains your solution. It could come from performance issues depending on how is structured the solution, from SPFx Controls, or any other third-party libraries.
