### ISSUE TITLE
People Picker in webpart sample ?

### ISSUE THREAD

**Issue by alexabramkin** [pnp/sp-dev-fx-controls-react#308]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [1.12.0]

#### Question
Is there a good functioning code sample (as opposed to snippet) on how to use People Picker in the SPFx web part ? 

Trying to understand managing props/state during control's life cycle. 
For example imagine it being connected to the list item for CRUD and on create and update scenarios: 
- On Create: loading it/initializing, enforcing rule or dependency/validating, capturing the data on the save;
- On Update/Edit: getting existing data into it on the web part/form load, enforcing rule or dependency/validating, capturing the data on the save.

**Comment by AJIXuMuK** [comment]
@alexabramkin there are examples right in that repo.
You can look at [web part component](https://github.com/SharePoint/sp-dev-fx-controls-react/blob/master/src/webparts/controlsTest/components/ControlsTest.tsx), lines 336 - 399.

Let me know if that's not enough.

**Comment by alexabramkin** [comment]
This is helpful, thank you. However it would have been much more helpful if we have had fully fledge example (web part) showing CRUD for this control in a react web part (including state management). Does such example exist to your knowledge ?

**Comment by AJIXuMuK** [comment]
@alexabramkin unfortunatelly, I'm not aware of any other example.

**Comment by joelfmrodrigues** [comment]
@alexabramkin I know this is an old issue and you have probably found a solution, but adding this here in case you still need a sample or to help others in the future that may find this issue from web search.

The react-list-form solution from [PnP web part samples](https://github.com/pnp/sp-dev-fx-webparts) should have what you are looking for as it uses the people picker component:
https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-list-form/src/webparts/listForm/components/formFields/SPFieldUserEdit.tsx

Closing this item
