### ISSUE TITLE
IFramePanel width problems

### ISSUE THREAD

**Issue by bva999** [pnp/sp-dev-fx-controls-react#318]
#### Category
[ ] Enhancement

[ x] Bug

[ x] Question

#### Version

sp-dev-fx-controls-react: [ 1.13.2 ], 
office-ui-fabric-react: [6.187.0] ,
SPFX: [1.8.2]

#### Expected / Desired Behavior / Question
How set the width of the IFramePanel? `type` doesn't work! 

#### Observed Behavior
if you set prop `type` you will get an error: 
![image](https://user-images.githubusercontent.com/12149939/58616715-64a6b980-82cf-11e9-9a7a-625d9b2f44a4.png)

#### Steps to Reproduce
```
import { PanelType } from 'office-ui-fabric-react/lib/Panel';
import { IFramePanel } from "@pnp/spfx-controls-react/lib/IFramePanel";
```
```
<IFramePanel url={`/sites/template/Lists/Experts/DispForm.aspx?ID=${this._currentItemId}&IsDlg=1`}
          type={PanelType.custom}
          headerText="Panel Title"
          allowFullScreen={true}
          customWidth={"500px"}
          closeButtonAriaLabel="Close"
          isOpen={this.state.isItemDisplaypanelOpen}
          onDismiss={this._closeItemDisplayPanel}
        />
```

Thanks!

**Comment by Kristofferkirk** [comment]
Can confirm/reproduce the same issue when trying to use PanelType from office ui fabric react package in the type prop.

**Comment by estruyf** [comment]
The library doesn't support OUIF version 6 yet, we are working on that. In order to make it work, you can import from the local project dependency as follows: `import { PanelType } from '@pnp/spfx-controls-react/node_modules/office-ui-fabric-react/lib/Panel';` that should make it work.

**Comment by ColinGardner** [comment]
Yes, that makes the PanelType available but it is inconsistent with the PanelType defined in the IPanelProps.  Specifically, the enum value customNear, is not available and this option does not work with this control in any case.  Also, I can't access the styles element which seems to be missing as well.

**Comment by michaelmaillot** [comment]
Hi everyone,

Latest version (3.15.0) inherits from Fluen UI version 7.174 as stated [here](https://pnp.github.io/sp-dev-fx-controls-react/#library-versions) and IFramePanel accepts same props as the Fluent UI `Panel`.

Is the problem still relevant today?
