### ISSUE TITLE
How to display removed users from group in PeoplePicker

### ISSUE THREAD

**Issue by mappinger** [pnp/sp-dev-fx-controls-react#324]
#### Category
[ ] Enhancement

[ ] Bug

[ X ] Question

#### Version

Please specify what version of the library you are using: [ 1.13.0  ]

#### Question
How do you handle the display of users which are not in the group anymore? 

My setting: I have a people picker restricted to a SharePoint group. At some point in time a user is selected and saved. When the user is removed from the group and the people picker control is given the user as defaultSelectedUser, the people picker is empty.

Thanks!

**Comment by AJIXuMuK** [comment]
@mappinger  - finally the change has been done and will be available in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

Please, check out [#768](https://github.com/pnp/sp-dev-fx-controls-react/issues/768#issuecomment-751370297) for the details
