### ISSUE TITLE
RichText control doesn't render as a child component on a page

### ISSUE THREAD

**Issue by naveedullahk** [pnp/sp-dev-fx-controls-react#326]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Using RichText in a webpart, where it is used as a child component (field). the rich text should update the value (text displayed in the field) as soon as the state change occurs in the containing control (parent)

#### Observed Behavior
The RichText displays the value for the first time and then doesn't render the new value passed to it on subsequent renders.
Reviewing the code in RichText.tsx reveals that the props (value) being passed is only being assigned to the state (text) in the constructor. Subsequent render calls will not invoke the constructor and hence new value will not be updated in text. Missing componentWillReceiveProps lifecycle method
 
#### Steps to Reproduce
Create a component with a textbox, button and RichText control. In button click handler, set the value of textbox to the state which is passed to the RichText as props (value). 

Please note that I tested the RichText after adding the method componentWillReceiveProps to the control and the issue seems to be fixed
`
public componentWillReceiveProps (nextProps:IRichTextProps){
  
  this.setState({text:nextProps.value});   
        
      }`

**Comment by nileshlaxmi** [comment]
Any updated on above request. When we are using componentWillReceiveProps or static getDerivedStateFromProps, it becomes very slow as it is being rendered.
Please help.
