### ISSUE TITLE
Question: Pagind and scrolling in ListView

### ISSUE THREAD

**Issue by dheepai** [pnp/sp-dev-fx-controls-react#344]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Question

#### Version

Please specify what version of the library you are using: [1.14.0]

#### Expected / Desired Behavior / Question
How can I add paging and/or scrolling to the ListView control?

**Comment by michaelmaillot** [comment]
Hi @dheepai,

Scrolling can be done by placing the control into a height-defined parent container (such as a div). 

Regarding paging feature, I think that Sudharsan's public repo / articles has some good examples about it: https://github.com/sudharsank/pnpcontrols-demo

Hope that it helps.

**Comment by joelfmrodrigues** [comment]
Closing as answered
