### ISSUE TITLE
DateTimePicker: what to do with amDesignator and pmDesignator?

### ISSUE THREAD

**Issue by robert-lindstrom** [pnp/sp-dev-fx-controls-react#348]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question
Setting the amDesignator and pmDesignator strings as shown below has no effect on the DateTimePicker component.
```typescript
<DateTimePicker strings={{ amDesignator: 'newAM', pmDesignator: 'newPM', ...  }} ... />
```
This has never worked and is not easily fixed (and probably not needed).

What should be done about this?

Is it safe to just remove these properties since it has never worked?

Do we have a way of deprecating this?

**Comment by AJIXuMuK** [comment]
I would just remove them.
I don't think these properties were used by someone.

**Comment by joelfmrodrigues** [comment]
Closing as answered
