### ISSUE TITLE
TaxonomyPicker freetext validation

### ISSUE THREAD

**Issue by gbminnock** [pnp/sp-dev-fx-controls-react#354]
[x ] Question

#### Expected / Desired Behavior / Question
TaxonomyPicker textfield should validate or remove free text that is not a valid taxonomy item or the user has not selected it.

#### Observed Behavior
User enters text into textfield which shows autocomplete. If the user enters text that does not resolve to a taxonomy item the text stays in the textfield.

#### Steps to Reproduce
Enter text in textfield of taxonomypicker. Click out of the textfield and the text stays there.

Tks,
Gary

**Comment by gbminnock** [comment]
Hi, any update on this one please?

**Comment by gbminnock** [comment]
@estruyf any updates or workaround for this?

**Comment by Matej4386** [comment]
+1 i would really appreciate this function (also for v1)

**Comment by Matej4386** [comment]
I made for my project workaround:
1. In TermPicker.js:
`onFilterChanged: before return filteredTerms i check if (filteredTerms.length === 0) {
filteredTerms.push(
                              {
                                    key: 'MyOwnUndefined',
                                    name: 'Please select valid value',
                                    path: 'MyOwnUndefined',
                                    termSet: 'MyOwnUndefined'
                                }
                            )
}`
So if you type free text it will show as Please select valid value
then in onRenderItem:
`if (term.key === 'MyOwnUndefined') {
i render my own item
}`
then in <TaxonomyPicker element
`onChange={(terms: IPickerTerms) => {
            if (terms.length > 0) {
                if (terms[0].key !== 'MyOwnUndefined') {
                    props.valueChanged(terms[0]);
                }
            } else {
                props.valueChanged(terms[0]);
            }
            
        }}`
this will handle Undefined text as empty ... not nice but for my project it is OK :-)

**Comment by joelfmrodrigues** [comment]
@gbminnock does the answer from @Matej4386 answer your question?
