### ISSUE TITLE
TaxonomyPicker: Save and cancel buttons are out of reach in mobile view

### ISSUE THREAD

**Issue by Lahtiharju** [pnp/sp-dev-fx-controls-react#358]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version
Please specify what version of the library you are using: [ 1.14.0 ]

#### Expected / Desired Behavior / Question
When selecting terms, there should be save and cancel buttons below termlist. 

#### Observed Behavior¨
However at least on my phone (Pixel XL) buttons are too low and hiding behind phones bottom banner. Only the termlist is scrolling when I'm trying to reach the buttons.

![image](https://user-images.githubusercontent.com/54259931/63244338-c8ed6f80-c265-11e9-9f86-df098af6e5f5.png)

#### Steps to Reproduce
Use TaxonomyPicker with mobile phone. The buttons are showing correctly when you scroll the previous page all the way to the bottom, but otherwise the problem is showing.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @Lahtiharju,

I've tested on latest version (3.15.0) from Edge as a mobile context:

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/2d1d6a81-e895-4895-987e-27371da2f172)

It seems to work.

Can you confirm on your side?
