### ISSUE TITLE
Show User Job Title on user search in People Picker 

### ISSUE THREAD

**Issue by ravi2311** [pnp/sp-dev-fx-controls-react#360]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Question

#### Version

Please specify what version of the library you are using: [ 16.4.2  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
In current People Picker when we search a user, its showing email ID underneath person name as a secondary text, is there any way or configuration which i change to show Job Title in place of Email ID.

#### Observed Behavior
Show Selected User Job Title 

#### Steps to Reproduce
Import "@pnp/spfx-controls-react/lib/PeoplePicker" package and on webpart search a user. you will see user list with name and Email ID  will be display.

#### Submission Guidelines

Thanks!

**Comment by michaelmaillot** [comment]
Hi @ravi2311,

For now there's no such prop to override the suggestion results. And from what I know, currently the code that gathers people info doesn't get job title property.

But maybe this could be an impovment idea to investigate 🙂

**Comment by joelfmrodrigues** [comment]
@ravi2311 closing as answered.
If you try to extend the control to support your scenario, you are welcome to send a PR with the new capabilities :)
