### ISSUE TITLE
Ability to reset the TaxonomyPicker (Remove all selected Terms)

### ISSUE THREAD

**Issue by M-SGFx** [pnp/sp-dev-fx-controls-react#367]
#### Category
Question

#### Version
 1.14.0  

#### Expected / Desired Behavior / Question
I need to remove the selected Term(s) from multiple TaxonomyPicker controls when the "Clear" button is clicked. Seems like there is no Clear function available? Please suggest how can I achieve this?

Basically the webpart has multiple TaxonomyPicker controls used for filtering the data in a grid. I need a functionality where users can click a button and all the filters needs to be removed.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @M-SGFx 
Have you tried to implement custom Clear button and change `initialValues` property to be `[]`?
Like
```typescript
private clear() {
this.setState( { pickerInitialValues: [] });
}

public render() {
// ...
<TaxonomyPicker
  initialValues={this.state.pickerInitialValue} />
}
```

But keep in mind that in that case the picker becomes "controlled" component and you will need to handle `onChange` event as well to update selected terms collection.

**Comment by AJIXuMuK** [comment]
It seems like it was broken.

The fix has been implemented and will be included in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
