### ISSUE TITLE
dialog inside IFrameDialog rendering issue

### ISSUE THREAD

**Issue by lvasiliou** [pnp/sp-dev-fx-controls-react#369]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 6.189.2  ]

#### Expected / Desired Behavior / Question
Child, modal dialogs should show on top of the IFrameDialog

#### Observed Behavior
child modal dialogs apepar behiind the IFrameDialog

#### Steps to Reproduce
Have a list with a field of type taxonomy picker in classic experience
Show the list item edit form via IFormDialog as modal
Click the taxonomy picker browse button

**Comment by AJIXuMuK** [comment]
Hi @lvasiliou 
Could you please provide some screen shot or code of what exactly you're doing and trying to achieve.
I didn't quite get it from the description, sorry...

**Comment by lvasiliou** [comment]
I am using the iframedialog to show a list edit form which happens to be in classic experience. One of the list fields is a taxonomy picker. When the window size is small-ish then the taxonomy picker dialog shows up behind the iframedialog control. This doesnt happen on 4k UHD res.
Also raising a second issue, when i press Save, the dialog doesnt close, but it works as expected with Cancel.
<img width="872" alt="bug" src="https://user-images.githubusercontent.com/8229290/65185671-f6ddf380-da5f-11e9-9d8b-4f8a7cd1f14b.png">

**Comment by AJIXuMuK** [comment]
@lvasiliou 
I wouldn't say that this is an `IFrameDialog` issue...
We're just providing a way to show the iframe-d page in Office UI Fabric Dialog.
If the page opens something else - we're not aware of it.

In your specific situation taxonomy picker dialog is implemented using old JS model for SharePoint. And most probably it handles logic how to render itself on the page (that's probably why it's rendered outside the iframe).

I would recommend to check on 2 things:
1. when you open Edit form in `IFrameDialog` you should provide IsDlg=1 parameter in the url. In that case form should understand that it is opened as an iframe.
2. You can try to apply styles to `IFrameDilaog` to decrease `z-index`. It can solve your problem as well.

> Also raising a second issue, when i press Save, the dialog doesnt close, but it works as expected with Cancel.

Again, we don't know what's happening on the page.
Try to handle `IFrameDialog`'s `iframeOnLoad` event to get loaded document and handle dismiss or something from there. BTW, `IsDlg=1` may help here as well.

Please, let me know if that makes sense.

**Comment by lvasiliou** [comment]
> 
> 
> @lvasiliou
> I wouldn't say that this is an `IFrameDialog` issue...
> We're just providing a way to show the iframe-ed page in Office UI Fabric Dialog.
> If the page opens something else - we're not aware of it.
> 
> In your specific situation taxonomy picker dialog is implemented using old JS model for SharePoint. And most probably it handles logic how to render itself on the page (that's probably why it's rendered outside the iframe).
> 
> I would recommend to check on 2 things:
> 
>     1. when you open Edit form in `IFrameDialog` you should provide IsDlg=1 parameter in the url. In that case form should understand that it is opened as an iframe.
> 
>     2. You can try to apply styles to `IFrameDilaog` to decrease `z-index`. It can solve your problem as well.
> 
> 
> > Also raising a second issue, when i press Save, the dialog doesnt close, but it works as expected with Cancel.
> 
> Again, we don't know what's happening on the page.
> Try to handle `IFrameDialog`'s `iframeOnLoad` event to get loaded document and handle dismiss or something from there. BTW, `IsDlg=1` may help here as well.
> 
> Please, let me know if that makes sense.

IsDlg=1 is already in place. Will try and look into figuring out when the page is saved using JS I guess

**Comment by joelfmrodrigues** [comment]
@lvasiliou did this resolve your issue?
