### ISSUE TITLE
People Picker: starting the search after digiting n characters

### ISSUE THREAD

**Issue by gioce90** [pnp/sp-dev-fx-controls-react#374]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.14.0  ]

#### Expected / Desired Behavior / Question
I noticed that the People Picker doesn't give the chance of choose the number of characters for starting the search. I know the related performance issues, but I think that is a bit limitating.

The responsable line code is:
https://github.com/SharePoint/sp-dev-fx-controls-react/blob/329cbc86051b306c072a741a721da8e2bcfc24dd/src/controls/peoplepicker/PeoplePickerComponent.tsx#L105

I think would be usefull to have a optional prop in IPeoplePickerProps for set this number.

#### Observed Behavior
The search starts only after have digit the third character. I think is limitating.

Thanks!

**Comment by gioce90** [comment]
This issue is still in triage...?

**Comment by NishkalankBezawada** [comment]
Hey @michaelmaillot, 
I am working on this issue too, Could you assign this to me :)

Thanks,
Nishkalank

**Comment by joelfmrodrigues** [comment]
@gioce90 PR from @NishkalankBezawada was merged and the change is now in the beta release. If you have the chance to test, please let us know if this is now resolved
