### ISSUE TITLE
Drag, Drop and select file control.

### ISSUE THREAD

**Issue by nsksaisaravana** [pnp/sp-dev-fx-controls-react#390]
Currently, I am missing this control in SPFX space. I am using Dropzone to achieve this feature (https://www.npmjs.com/package/@types/react-dropzone), it works well but if we place inside panel it doesn't glue well. 

#### Category
[*] Feature

[ ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please check the below url for the drop zone issues with modals and panels.

https://github.com/OfficeDev/office-ui-fabric-react/issues/8491

**Comment by joelfmrodrigues** [comment]
@nsksaisaravana Many thanks for the suggestion.
I know this is an old issue, but we now have a recently added DragDropFiles control that will be available in the next release.

**Comment by nsksaisaravana** [comment]
@joelfmrodrigues thaks a lot.

**Comment by AJIXuMuK** [comment]
Implemented a while ago.
