### ISSUE TITLE
People Picker - Data Binding - Show Text Value If A User is Deleted

### ISSUE THREAD

**Issue by anthonynhn** [pnp/sp-dev-fx-controls-react#393]
#### Category
[X] Enhancement

[X] Bug

[ ] Question

#### Version
Please specify what version of the library you are using: [  1.12       ]

#### Expected / Desired Behavior / Question
This is a grey area between bug and enhancement: a People Picker (SFPx version 1.12) should display the text value of a user even if the user is deleted from Azure AD.

For example, we can use the API call to extract the text value of the deleted user : /_api/web/lists/getbytitle('Current_List')/items(99)?$expand=PeoplePickerField&$select=PeoplePickerField/Title

#### Observed Behavior
In resignation scenario: A PeoplePicker field was created and could bind the saved user properly; however, when the user account is deleted from Azure Active Directory (i.e. the user value is not resolved by the control People Picker anymore), the control shows nothing. This is not expected, and the control should show the text value.

#### Steps to Reproduce
Step 1: create a form with a People Picker control
Step 2: save the form with a user which is resolved against Azure AD.
Step 3: open the form again to ensure that the data binding works.
Step 4: delete the user from Azure AD.
Step 5: open the form again and see no value in the control.

Thank you & Regards,
Anthony Nguyen.

**Comment by AJIXuMuK** [comment]
@anthonynhn - finally the change has been done and will be available in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

Please, check out [#768](https://github.com/pnp/sp-dev-fx-controls-react/issues/768#issuecomment-751370297) for the details
