### ISSUE TITLE
Listview: how to generate iconFieldName

### ISSUE THREAD

**Issue by robiharid** [pnp/sp-dev-fx-controls-react#396]
My list view is displaying a list of .pdf and I just want to show their respective icons.

`
          iconFieldName="ServerRelativeUrl"`

Documentation states:

> Specify the items' property name that defines the file URL path

My items do not have a RelativeUrl property but they do have a ServerRedirectedEmbedUri, what property am I looking for here?

**Comment by scallin** [comment]
The **FileRef** field seems to work
```
sp.web.lists.getByTitle(Constants.libraryName).items
            .select('ID, Title, Author/Title, FileRef, Created, Modified, File')
            .expand('Author, File')
            .orderBy('Title')
            .get().then((data: any[]) => {
                console.log(data);
                this.setState({
                    items: data,
                    isLoading: false,
                });
            })
            .catch((err : any) => {
                console.dir(err);
        });
```
```
<ListView
  items={this.state.items}
  viewFields={viewFields}
  iconFieldName="FileRef"
  compact={true}
  selectionMode={SelectionMode.none}
  groupByFields={groupByFields}                        
  showFilter={false} />
```

![image](https://user-images.githubusercontent.com/20932971/80111372-cf975980-854d-11ea-81ec-de9a950a393b.png)

**Comment by joelfmrodrigues** [comment]
@robiharid did the answer provided by @scallin answer your question?
