### ISSUE TITLE
Placeholder: icon and text size are smaller than expected

### ISSUE THREAD

**Issue by dmitryrogozhny** [pnp/sp-dev-fx-controls-react#398]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
Please specify what version of the library you are using: [ 1.15.0 ]

#### Expected / Desired Behavior / Question
Here's the expected view of the Placeholder control:
![image](https://user-images.githubusercontent.com/8382522/67623673-bc226480-f830-11e9-811c-0c7131f369e7.png)

#### Observed Behavior
- I add the Placeholder to my web part.
- Build and deploy a package.
- Icon and text are displayed much smaller than expected.
![image](https://user-images.githubusercontent.com/8382522/67623668-ae6cdf00-f830-11e9-92a7-9d0ed29aae51.png)

The behavior is the same for the workbench page and regular SharePoint Online pages.

#### Steps to Reproduce
Add the Placeholder control to a web part and run the project.

**Comment by joelfmrodrigues** [comment]
@dmitryrogozhny did you ever had the chance to validate that the issue was fixed?

**Comment by dmitryrogozhny** [comment]
@joaojmendes haven't used it in a while. It was fixed the last time I've used it.
