### ISSUE TITLE
ListView: Typo in API docs

### ISSUE THREAD

**Issue by robiharid** [pnp/sp-dev-fx-controls-react#400]
(https://sharepoint.github.io/sp-dev-fx-controls-react/controls/ListView/)

the first occurrence of maxWidth should be minWidth

**Comment by JonasBjerke89** [comment]
I have fixed the typo in the docs and did a small PR on this (https://github.com/SharePoint/sp-dev-fx-controls-react/pull/446)

**Comment by joelfmrodrigues** [comment]
@robiharid thanks for reporting this.
@JonasBjerke89 many thanks for fixing it.
