### ISSUE TITLE
ListView: Change Row Size

### ISSUE THREAD

**Issue by robiharid** [pnp/sp-dev-fx-controls-react#401]
I have a list with a title and a description column.

I want to have the sizing of three rows for each item in my list. How can I change that using the ListView implementation?

**Comment by michaelmaillot** [comment]
Hi @robiharid,

This can be done through the `viewFields` prop, which is type of `IViewField` and contains properties such as `minWidth`, `maxWidth` and `isResizable`.

More info [here](https://pnp.github.io/sp-dev-fx-controls-react/controls/ListView/#implementation).

Does this answer to your question?
