### ISSUE TITLE
ListView: How to style header?

### ISSUE THREAD

**Issue by robiharid** [pnp/sp-dev-fx-controls-react#410]
I want to apply a style to my header row

Inspecting the element shows me the list view has two divs, both with role called 'presentation', one of them is the header with a class of DetailsHeader

how can I style this? Best to add onto the DetailsHeader?

EDIT: Better yet, how can I remove the header so that I can add my own Title? setting displayName: ' ', still declares the space around it

**Comment by michaelmaillot** [comment]
Hi @robiharid,

For now there's nothing available to customize header (only to set it as sticky or not).

But I think that this could be an improvment idea to suggest 🙂 .

Does this answer to your question?
