### ISSUE TITLE
Link does not work anymore on render item

### ISSUE THREAD

**Issue by rmendoza00** [pnp/sp-dev-fx-controls-react#411]
I'm using Link from "react-router-dom" before and it works perfectly but recently it's not working anymore. 

**import { Link } from "react-router-dom";
private _recommendationVewFields: IViewField[] = [
    {
      name: "",
      displayName: "",
      minWidth: 20,
      maxWidth: 20,
      sorting: false,
      isResizable: false,
      render: (item: IRecommendationItem) => {
         return (
           <Link to={this.props.routerURL + "/recommendation/" + item.ID}>
             <Icon iconName={item.Attachments ? "Attach" : null} />
          </Link>
         );       
      }
    }]**

Thanks .

**Comment by AJIXuMuK** [comment]
Hello @rmendoza00 
I don’t quite get how’s that related to the SPFx controls...
Could you please provide more details?

**Comment by rmendoza00** [comment]
Thanks @AJIXuMuK for the reply , I'm using the ListView control (https://sharepoint.github.io/sp-dev-fx-controls-react/controls/ListView/) in many of my spfx projects. The link does not work anymore inside the ListView control. I used the above code for the IViewfield.

![image](https://user-images.githubusercontent.com/12782914/68450994-ed833300-0227-11ea-9a73-3019f0ad05e2.png)

react-router-dom Link works on other control like button so I guess the ListView control does not support this action anymore. It happened with the latest updates of Microsoft.

**Comment by joelfmrodrigues** [comment]
@rmendoza00 I was reviewing this item and noticed that in your sample code you don't seem to be closing the Link tag - although not sure if related at all to your issue.
Are you still experiencing issues?
