### ISSUE TITLE
TaxonomyPicker selection panel unscrollable on mobile

### ISSUE THREAD

**Issue by martinewald** [pnp/sp-dev-fx-controls-react#414]
Hi, I noticed that the TaxonomyPicker  selection panel (the panel that opens if the Tag-Icon is pressed) is not scrollable on mobile. I tested on Android 9 (with Chrome 78) and iOS 13.1. If I simulate mobile on Chrome (via device toolbar) the scrolling works fine.

[X ] Bug
#### Version: 1.15.0

**Comment by Rafaelki** [comment]
Same issue with 1.19.0. If I simulate mobile on Chrome (via device toolbar) the scrolling works with the mouse wheel and the keyboard arrows but not with the touch.

**Comment by SaltySweats** [comment]
This is still an issue ... any update?

**Comment by michaelmaillot** [comment]
Hi everyone,

I've tested on latest version (3.15.0) with Edge version 115.0.1901.188, simulate mobile view: touch makes the scroll working.

Can you test / confirm on your side?
