### ISSUE TITLE
commonJS module configuration prevents externalizing package

### ISSUE THREAD

**Issue by baywet** [pnp/sp-dev-fx-controls-react#415]
Hi,

## Context
This package currently is configured to define it's module using the commonjs syntax. 
This results in being unable to use the unpkg as a CDN/external reference as "browsers don't understand commonjs module definitions"
Additionally the package is not available on any other CDN and doesn't ship a bundle (like the es5 bundle shipped by pnpjs)

## Error message
`Uncaught ReferenceError: exports is not defined`

## Solutions
- ship bundles for CDNs (second set of configuration)
- change the configuration to esnext, or es6, or umd (I'm not sure which one would be best in our case)

## Where the configuration is for reference: 
https://github.com/SharePoint/sp-dev-fx-controls-react/blob/bc3baf59b90796af8068192d31997fc24a6d54bc/tsconfig.json#L5
## Additional documentation for reference:
https://medium.com/computed-comparisons/commonjs-vs-amd-vs-requirejs-vs-es6-modules-2e814b114a0b
https://github.com/pnp/office365-cli/pull/1090

**Comment by AJIXuMuK** [comment]
fixed with move to v3

**Comment by baywet** [comment]
thanks for providing an update after all this time!
