### ISSUE TITLE
RichText state bug when clicking "outside" of component

### ISSUE THREAD

**Issue by SharePickle** [pnp/sp-dev-fx-controls-react#428]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

1.15.0

#### Description

Incorrect `state.editing` value is set when clicking on any layered components (Fabric UI layer) inside editor panel, for example, color picker or fonts dropdown.
This happens because `elementContains` returns `false` for Dropdown options, despite them being "inside" panel.

![image](https://user-images.githubusercontent.com/32567749/70322348-f53ff280-183a-11ea-849a-e70c3e336bbe.png)

```js
 _this.handleClickOutside = function (event) {
            // THIS LINE has the bug
            // Fabric Layer component is outside of the panel and host component
            var outside = !Utilities_1.elementContains(_this._wrapperRef, event.target);
            // Did we click outside?
            if (outside) {
                // If we are currently editing, stop editing
                // -- unless we're using the property pane or the dialog
                if (_this.state.editing) {
                    _this.setState({
                        editing: false
                    });
                }
            }
            else {
                // We clicked inside
                if (!_this.state.editing) {
                    // if we aren't currently editing, start editing
                    _this.setState({ editing: true });
                }
            }
        };
```

#### Expected / Desired Behavior / Question

When clicking inside editor panel state should not change to `editing = false`.

#### Observed Behavior
When clicking inside editor panel state changes to `editing = false` thus breaking component state.

#### Steps to Reproduce
Click ...  (more) on the quill editor bar, select any color or font size.

**EDIT**: hm, it's not a Layer issue, but the fact that when clicking on dropdown option it's being removed before `elementContains` has a chance to check if it's inside.

**Comment by SharePickle** [comment]
@michaelmaillot hey, we decided to not use this component, so I can't tell if it works, sorry.
I'm going to close this I think, as it's no longer relevant.

**Comment by stevesuk** [comment]
I have a similar issue.  If you place a <RichText> control inside a Fluent UI React <Panel> or <Modal> - the rich text editor toolbar seems to _not_ disappear when the the editor loses focus.  This is quite annoying if you have a series of fields on a form, because the toolbar tends to cover over the field above, making it unusable.  Anyone have a workaround?

**Comment by michaelmaillot** [comment]
Hi @stevesuk,

I confirm I can repro what you've experienced.

Would you mind declaring an issue with all the requested info, including screenshots?

**Comment by stevesuk** [comment]
> Would you mind declaring an issue with all the requested info, including screenshots?

Hello - yes, will certainly do that.
