### ISSUE TITLE
TaxonomyPicker: Available when loading from localhost?

### ISSUE THREAD

**Issue by frankok** [pnp/sp-dev-fx-controls-react#452]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [    1.16.0     ]

#### Expected / Desired Behavior / Question
Is the Term Store supposed to be available when loading the web part from localhost, or is this only available when packaged for production?

#### Observed Behavior
I build, bundle and package the web part without --ship or --production, and then deploy the sppkg file to the app catalog on my SharePoint Online dev tenant. I then check for trusting localhost:4321. 
When I then add the web part to a page, and try to type in terms or open the term set browser, nothing gets loaded. gulp serve --nobrowser is running.

The sample terms seems to work as expected when I run locally (using gulp serve).

**Comment by AJIXuMuK** [comment]
Hi @frankok!
Yes, it should be available. Please, check properties of the Taxonomy Picker in your web part. 
Maybe `termSetId` is set to the value from other tenant or something.

> The sample terms seems to work as expected when I run locally (using gulp serve).

In local workbench it just shows mock data, in SharePoint-hosted workbench it tries to load data from your actual Term Store.

**Comment by michaelmaillot** [comment]
Hi @frankok,

Is your question still relevant? Did you manage to make the control working in local build?

**Comment by frankok** [comment]
Hi, I honestly can't remember, since this issue is so old :-P
I will just close the case.
