### ISSUE TITLE
Group Picker Control

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#466]
[X] Enhancement

Hello, I am looking for/about to work on  a control to let the user select a Group from the SharePoint Groups within the current site. 

Does one exist already. Would that be useful to anyone else?
Thanks

**Comment by AJIXuMuK** [comment]
Hi @russgove!
It does not exist for sure.
Regarding usefulness - if it's useful one time, it might be useful for many people :) this is my opinion. But I will keep this one open for a discussion.

**Comment by AJIXuMuK** [comment]
Hey @russgove! Have you tried to use `PeoplePicker`? You can select `SharePoint Group` as a `PrincipalType` in there to work with SP groups...
Thanks to @beaucameron for pointing this out.

**Comment by russgove** [comment]
ah, thanks for pointing that out, let me give it a try.

**Comment by russgove** [comment]
PeoplePicker worked great. CLosing this issue
