### ISSUE TITLE
RichText issue with IE10 rendering

### ISSUE THREAD

**Issue by AnilKumarReddyK080** [pnp/sp-dev-fx-controls-react#472]
**Bug**: RichText component is not rendering on IE with the version 10.

I've installed **@pnp/spfx-controls-react** of version **1.16.0**. The RichText control works as expected on all the browsers except IE 10 or lower. In IE 10 or lower it throws an exception of Invalid component and with a exception stack details.

As soon as I remove the **import** reference and <RichText /> component from the code, component loads as expected.

Any help will be appreciated.
 
Thanks!

**Comment by AJIXuMuK** [comment]
@hugoabernier,

I believe you're the author of `RichText`.
Could you please help with this one?

**Comment by michaelmaillot** [comment]
Closing as IE10 support has ended: https://learn.microsoft.com/en-us/lifecycle/announcements/internet-explorer-10-end-of-support
