### ISSUE TITLE
FilePicker: default tab when opened shows hidden RecentTab

### ISSUE THREAD

**Issue by mpowney** [pnp/sp-dev-fx-controls-react#477]
#### Category
* [ ] Enhancement
* [x] Bug
* [ ] Question

#### Version

Please specify what version of the library you are using: [ 1.16.0  ]

#### Expected Behavior
When the Recent files tab is hidden via the ```hideRecentTab``` prop, the first non-hidden tab should be shown when the FilePicker is initiated, instead of the "Recent" tab.

If the following props were specified:
```
hideRecentTab={true}
hideWebSearchTab={true}
hideOrganisationalAssetTab={true}
hideOneDriveTab={true}
hideSiteFilesTab={true}
hideLinkUploadTab={true}
```
... the only available tab is the LocalUploadTab, therefore when the FilePicker is initiated the LocalUploadTab should be displayed (not the RecentTab).

#### Observed Behavior
When tabs are hidden in the FilePicker control, e.g. any of the following props are set to true:
```
hideRecentTab={true}
hideWebSearchTab={true}
hideOrganisationalAssetTab={true}
hideOneDriveTab={true}
hideSiteFilesTab={true}
hideLinkUploadTab={true}
```

The default tab shown when the FilePicker is displayed is the RecentTab.  The user must then navigate to the tab(s) that are not hidden.

#### Steps to Reproduce
1. Create a React component that renders the FilePicker control
2. Set the the props of the FilePicker control as follows:
```
hideRecentTab={true}
hideWebSearchTab={true}
hideOrganisationalAssetTab={true}
hideOneDriveTab={true}
hideSiteFilesTab={true}
hideLinkUploadTab={true}
```
3. Render the React component in a web browser and initiate the FilePicker control UI
4. Observe the default tab displayed is the RecentTab, even though that tab should be hidden

**Comment by AJIXuMuK** [comment]
Thank you @mpowney for reporting this!
We'll be working on it!

**Comment by Greg-Hitchon** [comment]
Also experiencing this issue. Any timeline on getting a fix?

**Comment by saurav2107** [comment]
I am also facing the same issue, any update on this issue?

**Comment by AJIXuMuK** [comment]
Hi all,
The issue has been fixed and will be included in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
