### ISSUE TITLE
DateTimePicker: adjusting maximum/minimum date

### ISSUE THREAD

**Issue by rememberDL** [pnp/sp-dev-fx-controls-react#497]
#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

#### Version
 1.16.0

#### Expected / Desired Behavior / Question
When using the datetimePicker I would like to have an opportunity to set maximum/minimum date like in Office UI Fabric

Thanks!

**Comment by PrasadKasireddy** [comment]
@AJIXuMuK  - I will pick this

**Comment by AJIXuMuK** [comment]
Great! Thank you @PrasadKasireddy!

**Comment by AJIXuMuK** [comment]
The PR has been merged and will be available in the next drop.

@rememberDL - you can check the functionality in the [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
