### ISSUE TITLE
Search in IconPicker doesn't work at all

### ISSUE THREAD

**Issue by valerydolyuk** [pnp/sp-dev-fx-controls-react#512]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version
[1.17.0]

Nothing happens when type text in search box.
Error in browser console: "IconPicker.js:52 Uncaught TypeError: Cannot read property 'length' of undefined"

Reason:
`onChange` handler expects 2 parameters (`_event` and `newValue`), but the method is called only with one parameter `newValue`.

Thanks!

**Comment by MarianoPrz** [comment]
Same problem here, there is a PR pending i see...

**Comment by AJIXuMuK** [comment]
Hi @valerydolyuk!
Thank you for reporting this bug!
The fix has been merged.
Could you please test it in beta version?
