### ISSUE TITLE
IconPicker shows selected icon only during the first opening

### ISSUE THREAD

**Issue by valerydolyuk** [pnp/sp-dev-fx-controls-react#513]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version
 [1.17.0]

#### Steps to Reproduce

1. Use `IconPicker` control with set `currentIcon` property in your app.
2. Open icon picker - everything is ok, icon is selected
3. Close picker
4. Open the same picker again - **current icon is not selected**

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @valerydolyuk!
Thank you for reporting this bug!
It has been fixed and the fix is available in beta version.
It will also be included in v 1.18.0.
