### ISSUE TITLE
IFrameDialog scrolling doesn't seem to work with list item form and isDlg=1

### ISSUE THREAD

**Issue by mtburkett** [pnp/sp-dev-fx-controls-react#515]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     6.13.4    ]

#### Expected / Desired Behavior / Question
I am using the iFrameDialog control in an SPFX development on SharePoint 2019 on prem. When I load a list form page using IsDlg=1 I and have set the scrolling property to 'yes' I expect that the dialog would load the page at the URL and if the content exceeded the size of the dialog specified by the length and width properties scrollbars would be shown.

#### Observed Behavior
The content returned exceeds the size of the dialog and no scrollbars are shown. Specifically the content is cut at the top (at the ribbon in the dialog).

Also, in the documentation the "seemless" property is noted as a string - in the interface a boolean is required. 
Additionally, the scrolling property is noted as being a string. What strings are acceptable? Is it expecting "yes", "true", "sure". I think if yes or no this should be a boolean as well.

#### Steps to Reproduce
Add an IFrameDialog component to a project as below:
```typescript
<IFrameDialog 
              url= {this.webURL + '/Lists/someList/DispForm.aspx?ID=13&IsDlg=1'}
              // iframeOnLoad={this._onIframeLoaded.bind(this)}
              hidden={false} // {this.state.hideDialog}
              // onDismiss={this._onDialogDismiss.bind(this)}
              scrolling={'yes'}
              modalProps={{
                  isBlocking: true,
                  className: 'customPNPDialog'                
              }}
              dialogContentProps={{
                className: 'customPNPDialogContent',
                type: DialogType.close,
                showCloseButton: true
              }}
              width={'600px'}
              height={'300px'}
            />
```
![image](https://user-images.githubusercontent.com/25694364/77768171-7e607c80-7018-11ea-96e3-c346a8e9d637.png)

**Comment by Gennady-G** [comment]
offtop but..

How  to dynamically call this IframeDialog with different urls?...

`<IFrameDialog url= {this.webURL + '/Lists/someList/DispForm.aspx?ID=13&IsDlg=1'} `

for example I want to open 

> http://google.com

 and then 

> http://yahoo.com
(I need to open different display forms..)
?

**Comment by AJIXuMuK** [comment]
Hi @mtburkett!
The `scrolling` parameter does work:
![scrolling-yes](https://user-images.githubusercontent.com/17036219/82401035-93043400-9a0d-11ea-8bb8-2c64f02c0deb.png)
It seems like SharePoint renders pages with no scroll.
I tested with other site displayed as iframe dialog content and the scroll displayed as expected:
![iframe](https://user-images.githubusercontent.com/17036219/82401694-5a655a00-9a0f-11ea-9d26-73ff4a541053.png)

**Comment by Matej4386** [comment]
I just found this closed topic - just to let others know. Workaround is:
`iframeOnLoad={(iframe: any) => {
                            const head = $(iframe).contents().find("head");
                            const css = '<style>***YOUR CSS****</style>';
                            $(head).append(css);
                        } 
                    }`

**Comment by AdiuTankT72** [comment]
Workaround for those without jQuery:
iframeOnLoad={(iframe: any) => { const head = iframe.contentDocument.head; const css = '<style>.ms-dialog body {overflow: inherit !important;}</style>'; head.insertAdjacentHTML("beforeend", css); }}
