### ISSUE TITLE
DateTimePicker: disable array of dates - "blackout" dates

### ISSUE THREAD

**Issue by mtburkett** [pnp/sp-dev-fx-controls-react#516]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 6.13.4 ]

#### Expected / Desired Behavior / Question
I would like to be able to pass an array of dates into the DateTimePicker control and have them become unselectable or disabled in the UI. SImilar to [https://eonasdan.github.io/bootstrap-datetimepicker/](url)

#### Observed Behavior
This functionality does not currently exist or is undocumented.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @mtburkett,

FYI the control uses the Fluent UI [DatePicker](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker) which can be definitely enhanced with a new prop that could target the component `calendarProps` in the end.

**Comment by joelfmrodrigues** [comment]
The pull request with support for this enhancement has now been merged and the new feature should be available within the beta release shortly (after a few minutes)
