### ISSUE TITLE
Open file picker without manual click

### ISSUE THREAD

**Issue by Dangerous-Mind** [pnp/sp-dev-fx-controls-react#517]
#### Category
[ x ] Enhancement

[ ] Bug

[ x ] Question

#### Version
[1.17.0]

#### Expected / Desired Behavior / Question
I'm making a webpart with and need to invoke the FilePicker when I click a option on a CommandBar (Office UI Fabric).
But I have no way of invoking it other then clicking in it  manualy.

I've tried getting the class and then clicking the button by javascript and it works.
But some times the page has several Upload options and it saves the attach on the wrong place because it invokes the wrong FilePicker.

Is there any option or way of doing or implementing a option for this?

**Comment by Matej4386** [comment]
Hello, just quick reply:
What about to wrap FilePicker in div with custom ID="thisElement" and then with for example jquery: $('#thisElement').find('.classToSelect').click()

I think that recommendation for input type=file is to have button (or some clickable text) that user invoke file picker.

**Comment by Dangerous-Mind** [comment]
> Hello, just quick reply:
> What about to wrap FilePicker in div with custom ID="thisElement" and then with for example jquery: $('#thisElement').find('.classToSelect').click()
> 
> I think that recommendation for input type=file is to have button (or some clickable text) that user invoke file picker.

Hi, thanks for your comment.
 
I used something similar. Generated a random ID to the parent element. Then added another random id for the button. 
I suppose I could use jQuery but I try not to import another framework just to add some lines of code.

```
    let attachForm = document.getElementById(this.state.id); // react element id = Math.random().toString()
    let attachId = Math.random().toString();
    attachForm.getElementsByClassName("pnp__file-picker__button")[0].id = attachId;
    document.getElementById(attachId).click();
```

Adding the Id to the File picker could help.

**Comment by michaelmaillot** [comment]
Hi @Dangerous-Mind,

Don't know if it was already available or not (even more if your request is still current), but there's a prop available for displaying (or not) the FilePicker panel which is `isPanelOpen`.

Is it something that you could use for your need?
