### ISSUE TITLE
FilePicker: filename is not visible on Upload tab

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/sp-dev-fx-controls-react#518]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.17.0]

#### Expected / Desired Behavior / Question
`FilePicker` shows preview (if possible) and filename.
#### Observed Behavior
The preview is there but filename is not presentent.
If there is no preview - there is no information about the file at all.
#### Steps to Reproduce
1. Add `FilePicker` to your component
2. Open Upload tab
3. Upload some file (for example, pdf)

**Comment by txalvita** [comment]
Anyway, recently i downloaded this controls into my project, and an alert was shown everytime I upload any file. Is this related with this bug resolution?

Regards.
