### ISSUE TITLE
ComboBoxListItemPicker - onSelectedItem passing data to callback method but with attributes value as 'undefined'

### ISSUE THREAD

**Issue by siddharth-vaghasia** [pnp/sp-dev-fx-controls-react#519]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  1.17.0       ]

#### Expected 

While overriding onSelectedItem method we should get an array of the selected items with Id and Title column.

Below is sample implementation.

`<ComboBoxListItemPicker listId='ba682bc2-351e-45ae-8cbe-b0512ba0291a'
                        columnInternalName='Title'
                        keyColumnInternalName='Id'
                        // filter="Title eq 'SPFx'"
                        onSelectedItem={this.onSelectedComboBoxItemPicker}
                        webUrl={this.props.context.pageContext.web.absoluteUrl}
                        spHttpClient={this.props.context.spHttpClient} 
                        multiSelect={true}
                       />`

` private onSelectedComboBoxItemPicker(data: { key: string; name: string }[]) {
    for (const item of data) {
      console.log(`Item value: ${item.key}`);
      console.log(`Item text: ${item.name}`);
    }
  }
`

#### Observed Behavior
We are getting Id and Title as undefined in the array. Please refer below screenshot.

![image](https://user-images.githubusercontent.com/9557557/77880774-0e056580-727b-11ea-96ba-6e89ef30a0aa.png)

Further analysis and a possible fix. 
![image](https://user-images.githubusercontent.com/9557557/77881109-d3e89380-727b-11ea-9285-b4e4e1dfd313.png)

Reference file = webpack:///../../../../src/controls/listItemPicker/ComboBoxListItemPicker.tsx

Thanks!

**Comment by RantingLemming** [comment]
Encountered similar issue and came to same conclusion/resolution as @siddharth-vaghasia.  This also seems only applicable to when the multiSelect prop is passed.  When not passing multiSelect, no results are returned at all.  The value still seems to be returned if I insert a console.log(option) into the above onChanged function, but the _else_ case doesn't return anything as this.selectedItems doesn't seem to get appropriately set the way it does when the multiSelect prop is included.

**Comment by mgwojciech** [comment]
Hi Guys,
Thanks for reporting this. One note (maybe that is not documented well), onSelectedItem always passes selected item, not whole array (same for single and multi select). You can check the details using onSelectedItem={(item) => {
          console.log(item);
        }}
You will notice that for single selection mode the selected property is undefined and for multi select You will get information if the value was selected or the selection was removed
![image](https://user-images.githubusercontent.com/31688852/78582623-da57ac00-7835-11ea-9c35-d672214f5f0d.png)
Hope that helps

**Comment by AJIXuMuK** [comment]
Thank all of you for active discussion!
The fix has been merged and available in the beta version.
Could you please test it on your end as well?
Thanks!

**Comment by siddharth-vaghasia** [comment]
@AJIXuMuK ...thanks...tested this...it is working as expected if we write call back with below syntax

```
private onSelectedComboBoxItemPicker(items:[]) {
    console.log("selected items:", items);
     }
  }
```

Call back method documented in markup is below, which won't copy values in key and name unless it is passed in the same format.... So I believe we should update the documentation to the above syntax. submitting a PR for same, please merge it if it make sense..!!

```
private onSelectedItem(data: { key: string; name: string }[]) {
  for (const item of data) {
    console.log(`Item value: ${item.key}`);
    console.log(`Item text: ${item.name}`);
  }
}
```

**Comment by AJIXuMuK** [comment]
The documentation has been merged as well.
