### ISSUE TITLE
Issue with carousel paging after integrating dots.

### ISSUE THREAD

**Issue by pk091990** [pnp/sp-dev-fx-controls-react#524]
I've followed [Carousel Improvement article](https://mmsharepoint.wordpress.com/2019/12/23/pnp-spfx-react-carousel-improvements-dot-navigation/) to integrate dots navigation with arrows in pnp carousel control.
Individually both arrows and dots are working fine but getting issue while working together.

Repro Steps:

1: Click on 2nd dot- landed me to the the 2nd element.
2: Click on Next arrow - only loading icon will appear.
3: Reload the page, again landed on the 2nd element. Now click on Previous arrow - landed me to the 5th element.
4: Click on the Previous arrow from 5th element - only loading icon will appear.

Let me know if someone else faced the same issue or any thoughts on the same.

**Comment by michaelmaillot** [comment]
Hi @pk091990,

FYI those features are available now:

* "autoplay" is available through isInfinite
* "indicator" is available through both indicatorsDisplay and indicatorShape

Is it what you were expecting?
