### ISSUE TITLE
ListItemAttachments and Hyphen

### ISSUE THREAD

**Issue by Gregghis** [pnp/sp-dev-fx-controls-react#526]
#304 ## Category
[ ] Enhancement
[ x] Bug
The ListItemAttachments remove the hyphens from filename during upload
[ ] Question

#### Version
@pnp/spfx-controls-react@1.15.0

#### Expected / Desired Behavior / Question
when I upload a file I'd like the name will not change

#### Observed Behavior
when I upload a file  that contains an hyphen, the "-" char it is replaced by an empty string

#### Steps to Reproduce
Choose a file with filename "sam-ple.pdf", upload using drag & drop of file picker
it is uploaded with filename "sample.pdf"

Thanks!

**Comment by Gregghis** [comment]
I confirm this issue still persists with version 1.17.0

**Comment by AJIXuMuK** [comment]
The fix is available in beta version and will be included in 1.18.0
