### ISSUE TITLE
PnP Taxonomy Picker missing Required property, ErrorMessage,onGetErrorMessage,classname,Id,

### ISSUE THREAD

**Issue by Harshagracy** [pnp/sp-dev-fx-controls-react#528]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

SPFx: 1.10.0
"@pnp/spfx-controls-react": "1.17.0",

#### Expected / Desired Behavior
Taxonomy Picker control is missing the following properties. It would be great to have them.

- Required
- ErrorMessage
- onGetErrorMessage
- className
- Id

**Comment by michaelmaillot** [comment]
Hi @Harshagracy,

Following features are now available:

* `required`
* `errorMessage`
* `onGetErrorMessage`

`className` & `id` could be enhancements indeed 🙂 

Hope that it helps.
