### ISSUE TITLE
FieldUserHoverCard in FieldUserRenderer doesn't updated

### ISSUE THREAD

**Issue by a1exymoroz** [pnp/sp-dev-fx-controls-react#542]
#### Category
[ ] Enhancement

[ x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.17.0 ]

#### Expected
displayName in props FieldUserHoverCard is updated after state changing in FieldUserRenderer

#### Steps to Reproduce
![GIF 17 04 2020 14-27-20](https://user-images.githubusercontent.com/28485877/79564631-b444ce00-80b7-11ea-8f5c-6bcb73b1d27f.gif)

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @a1exymoroz!
Thank you for reporting this!
It has been fixed and will be included in the next release.

Could you please test it in your scenario using [beta](https://sharepoint.github.io/sp-dev-fx-controls-react/beta/) version?

**Comment by a1exymoroz** [comment]
It is working, Thanks!

But I have 2 questions.
When will you update react?
How can I contribute?(you don't have CONTRIBUTION.md)
