### ISSUE TITLE
Clean-up the web part

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/sp-dev-fx-controls-react#548]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.17.0]

Currently the web part we're using for tests is awful: components are not structured, some of them are duplicated.
We need to clean-up the web part and potentially split components into groups to make navigation a bit easier.

**Comment by michaelmaillot** [comment]
Hi @AJIXuMuK,

I think that some improvments have been made, last ones by @GuidoZam 🙂  here: #1547
