### ISSUE TITLE
Add clear button to ListView filter text box

### ISSUE THREAD

**Issue by gobigfoot** [pnp/sp-dev-fx-controls-react#549]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.17.0]

#### Expected / Desired Behavior / Question
Add the ability for the user to quickly clear the filter box

#### Observed Behavior
No option to clear

#### Steps to Reproduce
N/A

**Comment by AJIXuMuK** [comment]
Hello @gobigfoot!
Thank you for reporting!
The issue has been addressed and will be included in the next release.
In a meantime you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
