### ISSUE TITLE
IFramePanel type={PanelType.medium} does not work

### ISSUE THREAD

**Issue by RyanHealy** [pnp/sp-dev-fx-controls-react#550]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
 1.16.0    

#### Expected / Desired Behavior / Question

<IFramePanel url={this.state.iFrameUrl}
             type={PanelType.medium}  //Use PanelType enum
             headerText="Panel Title"
             closeButtonAriaLabel="Close"
             isOpen={this.state.iFramePanelOpened}
             onDismiss={this._onDismiss.bind(this)}
             iframeOnLoad={this._onIframeLoaded.bind(this)} />

#### Observed Behavior
Requires int not PanelType value

<IFramePanel url={this.state.iFrameUrl}
             type={6} 
             headerText="Panel Title"
             closeButtonAriaLabel="Close"
             isOpen={this.state.iFramePanelOpened}
             onDismiss={this._onDismiss.bind(this)}
             iframeOnLoad={this._onIframeLoaded.bind(this)} />

#### Steps to Reproduce

Copy the example code from 
https://sharepoint.github.io/sp-dev-fx-controls-react/controls/IFramePanel/

Thanks! Keep up the good work!!

**Comment by AJIXuMuK** [comment]
Hi @RyanHealy.
Just tested and it works perfectly.

One thing to mention - the library is based on `office-ui-fabric-react` version 5.131.0.
So if you're using v6 (which is default for SPFx 1.10) you may need to uninstall it and install v5.
