### ISSUE TITLE
TreeView: Expand to selected

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/sp-dev-fx-controls-react#559]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.18.0]

Add ability to the `TreeView` component to expand the nodes to see `defaultSelectedKeys`.
For example, add `expandToSelected: boolean` property to the component.

**Comment by nanddeepn** [comment]
Me and @siddharth-vaghasia will look in to this.

**Comment by AJIXuMuK** [comment]
This is a closed issue.
@cclarke3 - if you experience problems please open a new one and provide details in there.
