### ISSUE TITLE
TreeView: there should be possibility to collapse the first level nodes by default.

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/sp-dev-fx-controls-react#561]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.18.0]

Currently `TreeView` by default renders the first level nodes as expanded. It might be an issue for enterprise scenarios.
We need to allow to collapse the first level nodes by default.
For example, we can use `defaultExpanded` property (currently impacts on level 2+, and there is an issue with this property - see #560 )

**Comment by nanddeepn** [comment]
Me and @siddharth-vaghasia will look in to this.
