### ISSUE TITLE
PnP PeoplePicker not working on full names

### ISSUE THREAD

**Issue by jnimmala** [pnp/sp-dev-fx-controls-react#565]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.16.0]

#### Expected / Desired Behavior / Question
Hello All, Below is the PnP Peoplepicker control code that I'm using. The issue that I'm having here is with space-character within the name. Say I have valid user "Rachel Green". If I type-in "Rachel" I get 40 different Rachel's. So I continue to type "Rachel " or "Rachel G" or "Rachel Green", I get no results found. Is there anyway to deal with space-char or able to search based on full name. (If I go by last name i.e Green, since I have only one colleague with Green I'm able to pick correct name).

```
 <PeoplePicker
                         peoplePickerCntrlclassName=""
                         context={this.props.context}
                         titleText=""
                         personSelectionLimit={1}
                         groupName={""}
                         showtooltip={false}
                         suggestionsLimit = {10}
                         disabled={false}
                         selectedItems={this._getSelectedProfile}
                         principalTypes={[PrincipalType.User]}
                         defaultSelectedUsers={this.state.defaultUser}
                         resolveDelay={1000}
                         errorMessage={this.state.required}
                       /> 
```
#### Observed Behavior
Able to select user by full name with space character in between first and last name

Thanks!

**Comment by joelfmrodrigues** [comment]
@jnimmala Thanks for reporting the issue. I have just tested this with version 2.X and it's working with full names.
Could you please confirm if this is working for you with a more recent version?
