### ISSUE TITLE
Question:  People Picker - way to "Add Me" to the field

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#575]
####
@AJIXuMuK @joelfmrodrigues 

#### Category
[ X ] Enhancement
[ X ] Question

#### Version
"@pnp/spfx-controls-react": "1.16.0",

#### Expected / Desired Behavior / Question
For the People Picker, I'm looking for an example of how to make it really easy to "Add Me" to a people picker field.  I already have my ID info so it's just a matter of triggering a state update to the property the PeoplePicker uses to show the elected users.

I was thinking something like a icon/button in the Field Label or even something as simple as CTRL-Clicking the picker just auto adds me.

Does anyone know if there is an example out there of how to accomplish this?  I'm guessing I can with the existing version... just not sure how without an example to follow.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @mikezimm,

There is no sample that I know of.
But you need to use `defaultSelectedUsers` property of the picker to provide current user.

Let's say you have an upper level control that contains `PeoplePicker`.
This control can also have a button `Add me` that will change the control's state.
And by changing the state in the `render` you could provide new array for `defaultSelectedUsers` that will include current user.

**Comment by mikezimm** [comment]
@AJIXuMuK , Thanks for the tip!

For the next person, I was able to get a button to work but it was more challenging than I expected.  The function, updating state and defaultSelectedUsers was easy.  Trying to get a button on the upper right inline with the field label was the hard part (at least for me).

Here's the result... don't mind the color background :)

![image](https://user-images.githubusercontent.com/49648086/85415265-1c41e580-b53b-11ea-9248-9a821133dc77.png)

Function where I build my button itself:  [IconButton.tsx](https://github.com/mikezimm/TrackMyTime7/blob/5e069d37cc37b53d9b8074fb720a52335726cf7e/src/webparts/trackMyTime7/components/createButtons/IconButton.tsx#L21)

Line where I call the button and then wrap it around the People Picker:  [ProjectEditPage.tsx](https://github.com/mikezimm/TrackMyTime7/blob/5e069d37cc37b53d9b8074fb720a52335726cf7e/src/webparts/trackMyTime7/components/Project/ProjectEditPage.tsx#L957)

PeoplePicker Wrapper div:  [ProjectEditPage.tsx](https://github.com/mikezimm/TrackMyTime7/blob/5e069d37cc37b53d9b8074fb720a52335726cf7e/src/webparts/trackMyTime7/components/Project/ProjectEditPage.tsx#L961)

Added 2 classes in the divs:  [.peopleBlock and .addMeButton](https://github.com/mikezimm/TrackMyTime7/blob/5e069d37cc37b53d9b8074fb720a52335726cf7e/src/webparts/trackMyTime7/components/Project/ProjectPage.module.scss#L54)
