### ISSUE TITLE
DateTime Picker noon/midnight issue with 12 hour format

### ISSUE THREAD

**Issue by c-eiser13** [pnp/sp-dev-fx-controls-react#576]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.18.0     ]

#### Expected / Desired Behavior / Question
When 12AM and 12PM are chosed in the drop down, returns date object with proper time value.

#### Observed Behavior
When selecting time in the drop down, if 12 PM is chosen, date is returned as midnight (12AM) and if 12 AM is selected in drop down, noon (12PM) is returned.

![datetimepicker](https://user-images.githubusercontent.com/42096464/83893883-2a5bcd80-a716-11ea-8ae0-56529aefdc4d.PNG)
![datetimepicker2](https://user-images.githubusercontent.com/42096464/83893902-30ea4500-a716-11ea-8e68-97586cce6317.PNG)

![datetimepickeram1](https://user-images.githubusercontent.com/42096464/83893909-33e53580-a716-11ea-81ef-92b33ce1efee.PNG)
![datetimepickeram2](https://user-images.githubusercontent.com/42096464/83893917-3778bc80-a716-11ea-96cc-d3196e161d3a.PNG)

I believe the only change needed is switching pm in the if statement to am. I believe this is the same or a similar issue to #402. I will test this fix then create a PR for review.

#### Steps to Reproduce
Use DateTime picker with 12 hour format and select 12PM or 12AM and view date object.

**Comment by AJIXuMuK** [comment]
The issue has been resolved and will be available in the next release.
