### ISSUE TITLE
How to do number formatting for currency?

### ISSUE THREAD

**Issue by srinutamada** [pnp/sp-dev-fx-controls-react#579]
I have requirement to show bar chart which contains $ amounts. I am able to create bar chart but $ amount and format number are not coming. So, its not looking appropriate.

How to make number format along with currency. Please provide sample code

**Comment by AJIXuMuK** [comment]
Hi @srinutamada!
`ChartControl` is just a wrapper around [Chart.js](https://www.chartjs.org).
I would recommend to check Chart.js documentation on how to format labels or axis values - whatever you need.

**Comment by srinutamada** [comment]
Thanks for your support. Please let me know if I am doing right thing or not

options: {
        tooltips: {
            callbacks: {
                label: function(tooltipItem, data) {
                    var label = data.datasets[tooltipItem.datasetIndex].label || '';
                    if (label) {
                        label += ': ';
                    }
                    label += {new Intl.NumberFormat("en-US", {
                                style: "currency",
                                currency: "CAD"
                            }).format(tooltipItem.xLabel)}
                    return label;
                }
            }
        }
    }
