### ISSUE TITLE
ListItemAttachments fails in Microsoft Teams Tab SPFx applications

### ISSUE THREAD

**Issue by joeljeffery** [pnp/sp-dev-fx-controls-react#582]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version
Please specify what version of the library you are using: [1.18.0]

#### Expected / Desired Behavior / Question
ListItemAttachments control should work on a Teams Tab. The window.location change in the onClickHref handler won't work in Microsoft Teams due to IFRAME security.

#### Observed Behavior
Clicking on an attachment icon in view or edit mode from a Tab in Microsoft Teams causes the Tab to crash, and the navigation attempt getting blocked.

#### Steps to Reproduce
Build an SPFx Teams Tab app that uses the ListItemAttachments control. Add an attachment. Then try opening the attachment.

Joel Jeffery
[w:joelblogs.co.uk](https://joelblogs.co.uk)
[t:@joelblogs](https://twitter.com/joelblogs)

**Comment by AJIXuMuK** [comment]
Thank you @joeljeffery for reporting and fixing the issue.
It will be available in the next release.
In a meanwhile you can test in in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
