### ISSUE TITLE
ListItemPicker could use a substring search instead of just startswith

### ISSUE THREAD

**Issue by joeljeffery** [pnp/sp-dev-fx-controls-react#583]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.18.0]

#### Expected / Desired Behavior / Question
I'd like the option of finding List Items in picker as a substring search rather than just starts-with.

#### Observed Behavior
Users need to know exactly how an item in the target list _starts_ in order to find it. This is only feasible for some use cases.

#### Steps to Reproduce
Create a List with many items with very different titles. Maybe all the city names in your country. Or dog breeds. Or cheeses. I'm pretty sure there's some CSVs of those somewhere 😉. Create a List with a lookup column into the first list. Build a test app/web part or something to use the ListItemPicker control on the lookup field.

Try and find a city/dog/cheese :)

Now, wouldn't that be better with a substring search?

You betcha.

Joel Jeffery
[w:joelblogs.co.uk](https://joelblogs.co.uk)
[t:@joelblogs](https://twitter.com/joelblogs)

**Comment by AJIXuMuK** [comment]
Thank you @joeljeffery for both proposing a change and implementing it!

This functionality will be available in the next release.

In a meanwhile you can test in in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
