### ISSUE TITLE
Map Control doesn't return display name or address details of locations

### ISSUE THREAD

**Issue by joeljeffery** [pnp/sp-dev-fx-controls-react#585]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1..0.18]

#### Expected / Desired Behavior / Question
The Map control uses OpenStreetMap.org's nominatim web service to perform searches and get location data. This returns a display name and can return address details.

SharePoint "Location" fields could use this data - albeit in a slightly different format.

Let's return this data along with the coordinates.

#### Observed Behavior
Only coordinates are returned by the Map.

#### Steps to Reproduce
Build an SPFx web part, hook up the Map control. Try and use the returned data to make a suitable value for a SharePoint Location field. Observe you could really use more data if it's there.

Joel Jeffery
[w:joelblogs.co.uk](https://joelblogs.co.uk)
[t:@joelblogs](https://twitter.com/joelblogs)

**Comment by AJIXuMuK** [comment]
Thank you @joeljeffery for submitting the idea and implementing it!

The changes have been merged and will be available in the next release.
In a meanwhile you can test in in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
