### ISSUE TITLE
Support for Bing Maps - draggable and static

### ISSUE THREAD

**Issue by joeljeffery** [pnp/sp-dev-fx-controls-react#586]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.18.0]

#### Expected / Desired Behavior / Question
Sometimes OpenStreetMaps fails to zoom. Right clicking the map and reloading the IFRAME in the browser makes the problem go away.

As an alternative, it would be nice to support Bing Maps to display the results of the nominatim web service call. 

#### Observed Behavior
Map sometimes fails to zoom, showing whole globe when coordinates and zoom level are passed in as props.

#### Steps to Reproduce
Pass in coordinates as props; pass in a zoom level. Observe occasional failure to zoom.

[reference](https://help.openstreetmap.org/questions/20335/embedded-html-displays-zoomed-out)

**Comment by AJIXuMuK** [comment]
Thank you @joeljeffery for submitting the idea and providing the implementation.

The changes have been merged and will be available in the next release.
In a meanwhile you can test in in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by joelfmrodrigues** [comment]
@joeljeffery were you able to test this issue after the new version was released?
