### ISSUE TITLE
When i am trying to get data from rich text box from list and bind it to pnp Rich text box nothing is visible in control, though the data is there in that state i have assigned, i have checked in developer tool.....but it is not showing

### ISSUE THREAD

**Issue by sunnysinha05** [pnp/sp-dev-fx-controls-react#588]
import * as React from 'react';
import styles from './RichTextTest.module.scss';
import { IRichTextTestProps } from './IRichTextTestProps';
import { escape } from '@microsoft/sp-lodash-subset';

import { sp } from "@pnp/sp";
import { RichText } from "@pnp/spfx-controls-react/lib/RichText";
import { autobind } from 'office-ui-fabric-react/lib/Utilities';
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

export interface ISpfxPnpRichtextState {
description: string;
SuccessMessage: string;
}

export default class RichTextTest extends React.Component<IRichTextTestProps, ISpfxPnpRichtextState,{}> {
constructor(props: IRichTextTestProps, state: ISpfxPnpRichtextState) {
super(props);
sp.setup({
spfxContext: this.props.context
});

this.state = { SuccessMessage: '', description: '' };
this._getDescription();
}
public render(): React.ReactElement {
return (
< RichText isEditMode={true} value={this.state.description} />
);
}

@autoBind
private async _getDescription() {
const item: any = await sp.web.lists.getByTitle("Employee Registration").items.getById(61).get();

console.log(this.state.description);
console.log(item.Description);

let dummyElement = document.createElement("DIV");
dummyElement.innerHTML = item.Description;
let outputText = dummyElement.innerText;

this.setState({ description: outputText });
}

@autoBind
private async _updateDescription() {
console.log(this.state.description);
const updatedItem = await sp.web.lists.getByTitle("Employee Registration").items.getById(61).update(
{
Description: this.state.description
});
this.setState({ SuccessMessage: 'Successfully saved' });
}
}

**Comment by sunnysinha05** [comment]
https://user-images.githubusercontent.com/61428258/84626648-175db000-af03-11ea-8835-ed62143e2484.png

**Comment by sunnysinha05** [comment]
i am getting the data but not binding/showing...please suggest...

![](https://user-images.githubusercontent.com/61428258/84626648-175db000-af03-11ea-8835-ed62143e2484.png)

**Comment by estruyf** [comment]
Thanks @sunnysinha05 for reporting this. We will do our best to find the issue and solve it.

**Comment by sunnysinha05** [comment]
Hi Team,
Any updates on this ?

**Comment by sunnysinha05** [comment]
Guys can you help please.

**Comment by AJIXuMuK** [comment]
Hi @sunnysinha05,

Is it still an issue? I've tried to repro, but it's working correctly.

Here is a brief test:

```typescript
public render(): React.ReactElement<IRichTextTestProps> {
    return (
      <div className={ styles.richTextTest }>
        <RichText isEditMode={true} value={this.state.description} />
        <PrimaryButton text={'Change description'} onClick={() => {
          this.setState({
            description: `description: ${Math.random()}`
          });
        }} />
      </div>
    );
  }
```
