### ISSUE TITLE
PeoplePicker in disabled state: can still delete defaultSelectedUsers

### ISSUE THREAD

**Issue by skantere** [pnp/sp-dev-fx-controls-react#589]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.17.0  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
PeoplePicker disabled = {true} defaultSelectedUsers = ["email@domain.com"]
I expect NOT to be able to delete default selected user by clicking on a cross.

#### Observed Behavior
I CAN delete the default user from a disabled control. selectedItems event fires. Once the control is empty is behaves as a disabled control should: i.e. I can't do anything further with it. 

#### Steps to Reproduce
<PeoplePicker 
    disabled = {true} 
   defaultSelectedUsers = ["email@domain.com"]
   ...
/>

Many thanks,

Sergey

**Comment by AJIXuMuK** [comment]
Hi @skantere!
It's a known issue of underlying Office UI Fabric picker component.
It will be fixed when we move the library to a newer version of OUIFR.
