### ISSUE TITLE
PeoplePicker The error message not showing

### ISSUE THREAD

**Issue by evdma** [pnp/sp-dev-fx-controls-react#590]
The error message still not showing

_Originally posted by @evdma in https://github.com/pnp/sp-dev-fx-controls-react/issues/420#issuecomment-646976090_

**Comment by AJIXuMuK** [comment]
Hi @evdma!
Thank you for reporting the issue.

The error message is showing when selected people are removed from the component.
It does not show up right after the component is rendered if there are no initially selected users.

I do believe that this is more or less correct behavior - I don't think it's a good idea to show error message right away before any interaction with the control (or at least form where it is located).

But I also believe that we could add some way to notify control to display the message from outside (for example, when Save button is clicked on your form).

Will such approach work for you?

**Comment by evdma** [comment]
Hi @AJIXuMuK !
It would be useful to add a message display when a button is clicked.
This is exactly the behavior I was trying to achieve.

**Comment by AJIXuMuK** [comment]
Hi @evdma!
I've added a new prop - `showRequiredError`.
You can set this prop to `true` to initiate flow to display required error message, if needed.
The fix will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by evdma** [comment]
@AJIXuMuK cool! Thank you
