### ISSUE TITLE
Org Assets Issue in FilePicker - Your organization tab is not shown

### ISSUE THREAD

**Issue by rabwill** [pnp/sp-dev-fx-controls-react#596]
#### Category 
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

1.19.0

#### Expected / Desired Behavior / Question
**Your organisation** tab shown to get images/files provided by your organization, where filepicker has not provided props to hide

#### Observed Behavior
**Your organization** is not displayed and when you debug there are issues in the code which makes the org tab not visible

#### Steps to Reproduce
- Your org assets are in the root site collection
- Add FilePicker controls
- No **Your organization** 

Further if this helps:

The issues are in the files

### FilePicker.tsx
Line 58 
The condition should be (instead of && operation || should be used and sometimes we are not passing this prop and will be undefined)
  if (this.props.hideOrganisationalAssetTab != undefined || !this.props.hideOrganisationalAssetTab ) {

### FileBrowserService.ts
Line 268 
Function buildAbsoluteUrl , need to have "/" if Library url does not start with a "/"

### OrgAssetsService.ts
Line 76
Null check for function _parseOrgAssetsLibraryItem 's 
libItem.ThumbnailUrl

It will be best to do null check for any property of the object, not only the item we need.

Hope that helps.
I can also take it up, if my approach of the fix sounds reasonable.

Thanks,
Rabia
   

Thanks!

**Comment by Timhaka** [comment]
Any news regarding this issue?

**Comment by AJIXuMuK** [comment]
Hi @rabwill!
Thanks for reporting that and providing steps for fix!

The fix will be available in the next release.
In a meanwhile you can test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).


BTW, I've added you Rabia as a contributor as you provided the solution! Thank you!

**Comment by rabwill** [comment]
Wohoo!! Thanks so much @AJIXuMuK ! You are awesome 🤩
