### ISSUE TITLE
File Picker Enhancement - add new Stock Images tab

### ISSUE THREAD

**Issue by c-eiser13** [pnp/sp-dev-fx-controls-react#597]
#### Category
[ X ] Enhancement

#### Version 

Please specify what version of the library you are using: [ 1.19.0 ]

#### Expected / Desired Behavior / Question
With the roll out of the new stock images tab on the default asset picker in SharePoint, we get questions on how to use it with this custom FilePicker we use in several web parts. It would be great if we could include stock images on the FilePicker control in this project, but not sure if Microsoft has or will make an API available for this? If there is an API available, I'd be willing to help implement this enhancement.

**Comment by hugoabernier** [comment]
@c-eiser13 it looks like a merge request to add this functionality was merged 2 days ago (see #593). 

I would imagine it'll appear in the next release

**Comment by c-eiser13** [comment]
@hugoabernier my apologies, I looked through the issues list and did not see anything, must have missed it! That is great news, thanks.
