### ISSUE TITLE
On Using multiple ListView controls, each ListView renders only 10 items on version 1.19.0

### ISSUE THREAD

**Issue by dnes24** [pnp/sp-dev-fx-controls-react#598]
Each ListView renders only 10 items

#### Expected / Desired Behavior / Question
It should render all items, we had 45 items in one ListView and 12 items in other ListView

#### Observed Behavior
But it showed only 10 items in each control

#### Steps to Reproduce
Add atleast 2 ListView controls and provide more than 10 items as input to each ListView

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @dnes24!
Thanks for reporting this!

Could you please provide more details? I can't reproduce it.

You can find sample code [here](https://github.com/AJIXuMuK/SPFx/tree/master/listview).

Please, let us know if there are still questions.
