### ISSUE TITLE
FilePicker: How to allow picking URLs of site pages?

### ISSUE THREAD

**Issue by msgx** [pnp/sp-dev-fx-controls-react#601]
#### Category
[ ] Enhancement
[ ] Bug
[x] Question

#### Version
Please specify what version of the library you are using: **v1.19.0**

#### Question 1
Is it possible to configure FilePicker component to display ASPX page files also? At least on the "Site" tab where I can pick a page from the SharePoint site. There is a task to provide users with ability to reference a page by its URL.

#### Question 2
As I can see from the code, there is an argument `includePageLibraries` in the [getSiteMediaLibraries()](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/services/FileBrowserService.ts#L61). However, all the calls of this method are parameterless. Is it planned to propagate this argument to FilePicker props?

**Comment by rickhellenthal** [comment]
Same issue here, we'd like to be able to browse the files in the SitePages tab using the FilePicker component, just like the picker in the Quick Links webpart. At the moment _(version 2.1.0)_ it is only possible to browse Documents and Site Assets.

Picker in Quick Links webpart
![image](https://user-images.githubusercontent.com/15320967/100591773-83d43c00-32f6-11eb-8bd1-17f3420bfd65.png)

Picker in FilePicker component (Hid everything except Site)
![image](https://user-images.githubusercontent.com/15320967/100592186-107efa00-32f7-11eb-865a-76b8efeb6c07.png)


Any updates on this issue?

**Comment by AJIXuMuK** [comment]
Hi @msgx - thank you for reporting this one!

The enhancement PR has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.5.0` has been released.
