### ISSUE TITLE
Pnp Taxonomy Picker onload validation

### ISSUE THREAD

**Issue by geltapatio** [pnp/sp-dev-fx-controls-react#602]
[x ] Bug

#### Expected / Desired Behavior / Question

TaxonomyPicker will display an error if the term reference is not valid because it was removed from the term store.
Before the user tries to save a list item, the user has to remove the invalid term(s).

#### Observed Behavior
TaxonomyPicker does not display an error indicating that the term has already been deleted from the term store. 
The user tries to save a list item, which contains a term field with invalid term ID. He does not realize that there is an error until he tries to save it.

#### Steps to Reproduce
The user edits a list item, which contains at least one term field.
The user selects a term with the TaxonomyPicker and saves it in a list item term field.
The selected term is removed from the term store
The user edits the same list item and saves it.
The user receives an error, indicating that term is not valid.

Current Version 
The term "Ablauf1_2ToDelete" does not exist in term store
![bild1_termnotexist_Nok](https://user-images.githubusercontent.com/9026810/87123279-ba95b100-c286-11ea-8bda-9d105361258e.JPG)

Thanks!
Luis Miguel Gamiz

**Comment by geltapatio** [comment]
I already fixed it and created a pull request [Pull Requestt](https://github.com/pnp/sp-dev-fx-controls-react/pull/603)

**Comment by AJIXuMuK** [comment]
Thank you @geltapatio for reporting and fixing it.

The PR has been merged and will be available in the next release.

Please, test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
