### ISSUE TITLE
Fluent UI Updates to SharePoint - WebPartTitle control too thin now

### ISSUE THREAD

**Issue by joshmcrty** [pnp/sp-dev-fx-controls-react#605]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.19.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

The WebPartTitle control should match the default web part title typeface, including font family, size, and weight.

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

In my tenant (on targeted release), the current WebPartTitle control no longer matches the default SharePoint web part titles because the font weight is set to `100` ([see here](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/webPartTitle/WebPartTitle.module.scss#L12)). The June 2020 roadmap podcast mentioned that Fluent UI is [rolling out to more areas of SharePoint](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=63777), so web part titles appear bolder now.

I can provide a PR to update the font weight if needed.

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

Create an SPFx web part using the PnP WebPartTitle control. The control styles will use the thin font treatment instead of the newer Fluent UI bolder style in a tenant that has the new Fluent UI styles rolled out to it.

**Comment by sympmarc** [comment]
Hi, @joshmcrty!

**Comment by clarktozer** [comment]
+1

**Comment by tallday** [comment]
+1

**Comment by anoopt** [comment]
+1

**Comment by maximreynaud** [comment]
+1

**Comment by dburgstaller-1992** [comment]
+1

**Comment by AJIXuMuK** [comment]
Hi @joshmcrty,
Thank you for reporting this!

Sorry for the long delay - finally it has been fixed and will be included in the next release.

In a meanwhile you can test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by jimmywim** [comment]
Just a quick one - do you know if the font-colour also now inverts when the Section background is set to the "darkest/fullest" slot? If not - I'll raise another issue to track that.

**Comment by joshmcrty** [comment]
@jimmywim it does if you pass the `themeVariant` to it.

**Comment by jimmywim** [comment]
@joshmcrty Perfect, thanks - just need to ask the pnp modern search folks nicely if they can pass it through xD
