### ISSUE TITLE
Bug in getting hours in DateTimePicker

### ISSUE THREAD

**Issue by mpalmer-sps** [pnp/sp-dev-fx-controls-react#606]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [  1.19.0   ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I'm pulling a date/time field value from a SharePoint Online List in a REACT webpart.
The data that I'm getting back is a JSON Object and the format looks like this:
![image](https://user-images.githubusercontent.com/12634625/86990031-8fa94100-c150-11ea-8daa-e1a461078a94.png)

#### Observed Behavior
When I add this to a DateTimePicker Control as show below:
![image](https://user-images.githubusercontent.com/12634625/86990160-d0a15580-c150-11ea-9bef-773a7765b711.png)

I'm getting an error from within the control itself that indicates "getHours" is not a function. 
![image](https://user-images.githubusercontent.com/12634625/86990271-14945a80-c151-11ea-9552-473e007fb8d6.png)

The line of code here appears to point to a function that perhaps I needed to install?
![image](https://user-images.githubusercontent.com/12634625/86990579-bddb5080-c151-11ea-8c86-894ffaecbb49.png)

I hope I'm just doing something wrong and that this is not a bug

Thanks!

**Comment by AJIXuMuK** [comment]
`getHours()` is a function available in `Date` instance.
You should do:
```typescript
const d = new Date(this.props.StartDt);
<DateTimePicker
  value={d} />
```

**Comment by mpalmer-sps** [comment]
Thanks AJIXuMuk,
The approach that I got working is clunky and I like yours better and will try that (see my approach below). 
I feel that more **robust** **documentation** on usage is really needed for these great controls....
![image](https://user-images.githubusercontent.com/12634625/86998725-d5bccf80-c165-11ea-813a-53b4a844ba6e.png)

**Comment by mpalmer-sps** [comment]
ok - so, here is the class that pulls the data and places it correctly in the controls:
![image](https://user-images.githubusercontent.com/12634625/86999625-e110fa80-c167-11ea-9751-3b766a1ad4d2.png)

**Comment by AJIXuMuK** [comment]
@mpalmer-sps - I agree that documentation is not always as good as it could be.
But for this specific situation the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/controls/DateTimePicker/#implementation) is correct:

| Property | Type | Required | Description |
| --- | --- | --- | --- |
value | Date | no | Default value of the `DatePicker`, if any |
