### ISSUE TITLE
[Caoursel] Changing pages doesn't work

### ISSUE THREAD

**Issue by siata13** [pnp/sp-dev-fx-controls-react#609]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.20.0 dev]

#### Expected / Desired Behavior / Question
Carousel paging doesn't work.

#### Observed Behavior
Carusel control doesn't move to next page in case triggerPageEvent is not set to true and moveNext/movePrevious handlers are undefined.

#### Steps to Reproduce
Initialize Carousel control without: onMoveNextClicked, onMovePrevClicked, triggerPageEvent properties. Control will not switch pages as it tries to execute undefined handlers (onMovePrevClicked, onMoveNextClicked).

**Comment by AJIXuMuK** [comment]
Thank you @siata13 for reporting and fixing the bug!
