### ISSUE TITLE
FolderPicker control not working

### ISSUE THREAD

**Issue by jorgesoprani** [pnp/sp-dev-fx-controls-react#614]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.19.0]

#### Expected / Desired Behavior / Question
I'm trying to use the FolderPicker control as it's documented, but the imports are not working.

#### Observed Behavior
I'm trying to import the component as it's documentend:
```
import { FolderPicker, IFolder } from "@pnp/spfx-controls-react/lib/FolderPicker";
```
But with that i get an error: '...has no exported member 'FolderPicker'" and "... has no exported member 'IFolder'"

#### Steps to Reproduce
All I did was installing the package in a recently created SPFX Reac app and trying to import the controls.

**Comment by AJIXuMuK** [comment]
Hi @jorgesoprani!
Thank you for reporting this!
Yes, it's a bug.

We will take care of it.

In a meantime, you can use the imports like that:
```typescript
import FolderPicker from '@pnp/spfx-controls-react/lib/controls/folderPicker/FolderPicker';
import { IFolder } from '@pnp/spfx-controls-react/lib/services/IFolderExplorerService';
```

**Comment by AJIXuMuK** [comment]
Starting v 1.20.0 you'll be able to use:
```typescript
import FolderPicker from '@pnp/spfx-controls-react/lib/controls/folderPicker/FolderPicker';
import { IFolder } from '@pnp/spfx-controls-react/lib/FolderPicker';
```

And later, in v2, it will be fixed completely.
