### ISSUE TITLE
IFrameDialog Issue

### ISSUE THREAD

**Issue by milindsaraswala** [pnp/sp-dev-fx-controls-react#615]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ v1.19.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Observed Behavior
I am using IFrameDialog from PnP react control in my spfx project. I have use below code on anchor tag in table row. IFrameDialog opens properly on first time click on each row. but when I click second time on the same link than size of the IFrameDialog become very small.

  <IFrameDialog
        hidden={modalDialog.dialogHide}
        url={href}
        width={'1000px'}
        height={'600px'}
        onDismiss={() => setModalDialog({ dialogHide: true })}
        modalProps={{ isBlocking: true }}
        dialogContentProps={{
          type: DialogType.normal,
          showCloseButton: true
        }}
      />

Thanks!

**Comment by milindsaraswala** [comment]
According to my test results, this should be a problem with this control. 

My test result:

When we first open a dialog, the outermost div of the control will have such a piece of CSS code.

![1608965](https://user-images.githubusercontent.com/479750/87522176-fa490800-c68d-11ea-9242-c87089404d17.png)


This CSS code disappeared when we closed the dialog and opened it again.

![1608967](https://user-images.githubusercontent.com/479750/87522250-0df46e80-c68e-11ea-8af6-f05cf9ff56d9.png)


This control has a default max-width,so the dialog becomes smaller.

![1608968](https://user-images.githubusercontent.com/479750/87522317-22386b80-c68e-11ea-802b-fd84d540b743.png)

**Comment by holmesrm23** [comment]
Also experiencing this bug.

**Comment by AJIXuMuK** [comment]
Thank you @milindsaraswala for reporting the issue.
We will be working on fixing it.

In a meanwhile you can modify you code:
```typescript
{!modalDialog.dialogHide && <IFrameDialog
  hidden={modalDialog.dialogHide}
  url={href}
  width={'1000px'}
  height={'600px'}
  onDismiss={() => setModalDialog({ dialogHide: true })}
  modalProps={{ isBlocking: true }}
  dialogContentProps={{
    type: DialogType.normal,
    showCloseButton: true
  }}
/>}
```
It will re-add the dialog each time when it should be displayed and will fix the issue.

**Comment by AJIXuMuK** [comment]
This one has been fixed and will be included in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
