### ISSUE TITLE
pressing tab clears the richtext box data.

### ISSUE THREAD

**Issue by sunnyEspireGit** [pnp/sp-dev-fx-controls-react#619]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Bug
#### Version

Please specify what version of the library you are using: [     "@pnp/spfx-controls-react": "1.19.0"    ]

#### Expected / Desired Behavior / Question
when we fill the data in "RichText control" and press tab to move to next control, it clears the data we have added in "RichText control".

#### Observed Behavior
when we fill the data in "RichText control" and press tab to move to next control, it **shouldn't** clears the data we have added in "RichText control".

#### Steps to Reproduce
simply add "RichText control" with other controls in custom form, enter the formatted values & press tab. It will clear the data once we press tab after adding data in "Rich text control".

Thanks!

**Comment by sunnyEspireGit** [comment]
any updates ?

**Comment by AJIXuMuK** [comment]
Hi @sunnyEspireGit,

Could you please provide more details as I can't reproduce the issue?

May it be the case that you're assigning `value` property of the control that is not updated?
