### ISSUE TITLE
ListView Sort Fires Selection

### ISSUE THREAD

**Issue by tom-daly** [pnp/sp-dev-fx-controls-react#621]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [      
 "@pnp/spfx-controls-react": "1.19.0",
   ]

#### Expected / Desired Behavior / Question
Why does the sort event fire the selection event? Is there any way to avoid this or detect that it was a sort event or a select event? 

#### Observed Behavior
The sort event is firing the selection event which is problematic for my case. 

#### Steps to Reproduce
background: I have code that opens a new window to an app passing some parameters.

- I first click a row, which fires the selection event. 
- then i click sort. 
- I can see it fires the selection event with no items and then fires it again with the selected item. 
- Each time I sort it also launches this new window with the last file clicked.

**Comment by AJIXuMuK** [comment]
Hi @tom-daly!
Thank you for reporting the issue.

It has been fixed and will be included in the next release.

In a meanwhile you can test the functionality in [beta](https://pnp.github.io/sp-dev-fx-controls-react/beta/) version.

**Comment by tom-daly** [comment]
thank you for your efforts!
