### ISSUE TITLE
Tree view default selected keys

### ISSUE THREAD

**Issue by vaithish** [pnp/sp-dev-fx-controls-react#622]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[ *] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Dynamic selection of Selected checkboxes are not working

#### Observed Behavior
  <TreeView
                      items={this.state.TreeLinks}
                      selectionMode={TreeViewSelectionMode.Single}
                      showCheckboxes={true}
                      selectChildrenIfParentSelected={false}
                      treeItemActionsDisplayMode={
                        TreeItemActionsDisplayMode.ContextualMenu
                      }
                      onExpandCollapse={this.onTreeItemExpandCollapse}
                      onRenderItem={this.renderCustomTreeItem}
                      expandToSelected={true}
                      defaultSelectedKeys={[**selectKey**]}
                      onSelect={this.onItemSelected}
                    />

When i pass a key, after the component has rendered and i want to re-render the component with other key.

There is no Property "SelectedKeys" like we do have in other controls

Thanks!

**Comment by nanddeepn** [comment]
Hi @vaithish 
During render, you can specify other keys to defaultSelectedKeys property. 
Please let me know, if I did not get your question right. Thanks

**Comment by David74000** [comment]
Hi @nanddeepn ,
I know it's been a while but I am focusing the same issue today. The treeview property called defaultSelectedKeys seems to be impossible to update after component is mount once, except by checking manually an entry. Is there a way to refresh the selected keys in the TreeView component ?
Thank you !
David
