### ISSUE TITLE
Richtext style error

### ISSUE THREAD

**Issue by mortizjimenez** [pnp/sp-dev-fx-controls-react#623]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[* ] Bug

[ ] Question

#### Version
1.19.00

#### Steps to Reproduce

First, we write a paragraph as normal text, select the text, click to open the extended menu and change the text size.

After that, we write another paragraph and click Heading 1 as font style, but not style is applied

[Richtext bug.zip](https://github.com/pnp/sp-dev-fx-controls-react/files/4981943/Richtext.bug.zip)

Code:
let value: string = "";
export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <div className={styles.helloWorld}>
        <RichText
          value={value}
          onChange={(text) => {
            value = text;
            return text;
          }}
        />
      </div>
    );
  }
}

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @mortizjimenez!
Thank you for reporting this!

Even in the video I can see that the style is applied.
If you click on the "Heading 1" text you'll see that it has Heading 1 Font Style and 15px as a size.
And if you look at the markup, you'll see that "Heading 1" is wrapped into `h2` element (which is a bit weird, but correct).

Please, let us know if it answers your concerns.
