### ISSUE TITLE
Updating state value tied to totalPages doesn't cause re-render of Pagination component

### ISSUE THREAD

**Issue by voltmer1** [pnp/sp-dev-fx-controls-react#626]
#### Category

[x ] Bug

#### Version

Please specify what version of the library you are using: [  1.19.0   ]

#### Expected / Desired Behavior / Question
Updating state value tied to totalPages property doesn't cause re-render of Pagination component

#### Observed Behavior
When passing a number from the property pane of an SPFx webpart to the totalPages property via state, the UI of the Pagination is not re-rendered, and if you click on the >> button it removes all the numbers.

#### Steps to Reproduce
Pass a number from the property pane of an SPFx webpart to the totalPages property via state, the UI of the Pagination is not re-rendered, and if you click on the >> button it removes all the numbers.

**Comment by erickalves05** [comment]
For anyone looking a solution without using the beta package, force the update changing the "key" of the element, like this:

`<Element key={this.state.key} />`

Then when you update the totalPages property:

`this.setState({ key: Math.random() });`

Taken from [here](https://stackoverflow.com/questions/30626030/can-you-force-a-react-component-to-rerender-without-calling-setstate). Not the best approach, but it works.

**Comment by voltmer1** [comment]
[erickalves05](https://github.com/erickalves05) I've tried this, with no luck. I am updating totalPages from the property pane and adding it to state = { totalPages: this.props.totalPages, key: Math.random() } on the component then on componentDidUpdate I did as you said and checked this.props.totalPages !== prevProps.totalPages and setState({ totalPages: this.props.totalPages, key: this.state.key } The pagination component still refuses to re-render.
