### ISSUE TITLE
ListView control should have file type depending on document name

### ISSUE THREAD

**Issue by jtlivio** [pnp/sp-dev-fx-controls-react#632]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [    1.19.0     ]

#### Expected / Desired Behavior / Question
Icons in ListView control should have file type depending on document name

#### Observed Behavior
No Icon, "Page" icon on a column
Can someone point me to the right point? no clue how to replicate this behavior

https://pnp.github.io/sp-dev-fx-controls-react/controls/ListView/

Thank You

**Comment by jtlivio** [comment]
`iconFieldName` is not set dinamically in the release version ("Server.RelativeUrl"), I'll try the beta version.

**Comment by jaxnz** [comment]
I'd like to add that I've achieved good success in SPFX DetailsList icons with the following:

```
let iconurl:string;
  if(element.File.Name.split('.').pop().toLowerCase() === 'pdf') {
    iconurl ='https://spoprod-a.akamaihd.net/files/fabric/assets/item-types/48/pdf.svg';
  }
  else {
    iconurl =`https://static2.sharepointonline.com/files/fabric/assets/brand-icons/document/svg/${element.File.Name.split('.').pop()}_16x1.svg`;
  }
```

I wonder whether it may be of any use in pnp ListView
