### ISSUE TITLE
How to set focus on pnp RichText control ? as the focus property missing in this control. 

### ISSUE THREAD

**Issue by sunnyEspireGit** [pnp/sp-dev-fx-controls-react#635]
#### Category
[ ] Question

#### Version

Please specify what version of the library you are using: [    "@pnp/spfx-controls-react": "1.19.0"     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
this._RichText.focus(); should work but throwing error that focus() property doesn't exist.

#### Observed Behavior
this._RichText.focus(); should work & not throw error .

#### Steps to Reproduce
 private _RichCtlSynopsis: RichText | null;

 <RichText ref={(c) => (this._RichCtlSynopsis = c)}
                  isEditMode={true}
                  onChange={(text)=>this.onChangeSynopsis(text)}
                  placeholder="Add Synopsis"
                  />

this._RichCtlSynopsis.getEditor.focus();    /   this._RichCtlSynopsis.focus();

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @sunnyEspireGit,
`this._RichCtlSynopsis.getEditor().focus();` should work.

**Comment by sunnyEspireGit** [comment]
@AJIXuMuK : Yes it is working......i was already using it, but missing braces after getEditor . this._RichCtlSynopsis.getEditor.focus();

Thanks for correction.
