### ISSUE TITLE
IFrameDialog height unable to resize relative to screen size, even if we provide in % it is taking default value. 

### ISSUE THREAD

**Issue by raghuram753** [pnp/sp-dev-fx-controls-react#636]
Below is the code I am using:

{this.state.showSiteUsersModal ?
                        <IFrameDialog
                            url={this.state.siteAddress}
                            onDismiss={this.closeSiteUsers}
                            hidden={!this.state.showSiteUsersModal}
                            modalProps={{
                                isBlocking: true
                            }}
                            dialogContentProps={{
                                showCloseButton: true,
                                type: DialogType.close,
                            }}
                            allowFullScreen={true}
                            allowTransparency={true}
                            width={'60%'}
                            height={'50%'}/>
                            : null }

width is getting auto adjusted relative to device, where as height is not getting adjusted with respective device.

Attached the screenshot, what ever the height we specify it is of same height.

![IFrameHeight](https://user-images.githubusercontent.com/66473078/90727798-7b289e80-e2e1-11ea-8f0b-9bec2a14b240.jpg)

**Comment by AJIXuMuK** [comment]
Hi @raghuram753,

The fix has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.5.0` has been released.
