### ISSUE TITLE
Cannot clear the Pnp People Picker 

### ISSUE THREAD

**Issue by harish2425** [pnp/sp-dev-fx-controls-react#637]
Cannot Clear or Reset   PNP People picker. I can able to get the User Details from SelectItems but i cannot Set the values.

Thanks in advance 

#### Category
[ ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @harish2425,

Please, provide details for the issue.
