### ISSUE TITLE
FolderExplorer/FolderPicker Controls does not let you explore sub folders if parent folder has apostrophe (') in its name.

### ISSUE THREAD

**Issue by saurav2107** [pnp/sp-dev-fx-controls-react#644]
#### Category
 [x] Bug

#### Version
Please specify what version of the library you are using: [1.19.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
FolderExplorer/FolderPicker Controls should display all folders and sub-folders having special characters in there name.

#### Observed Behavior
FolderExplorer/FolderPicker Controls have this issue, while exploring Folders within a Library, the control is not able to display sub folders if the Parent Folder has apostrophe (' or ') in its name.

![image](https://user-images.githubusercontent.com/1011594/91442301-e9d1a300-e871-11ea-950f-7e94b033f018.png)

#### Steps to Reproduce

User FolderExplorer / FolderPicker control from ap-dev-fx-controls-react in any SPFx webpart.
Navigate/Explore any document library have folders and sub folders containing apostrophe ( ' ) in there name.
The control gives a message "This folder doesn't have any subfolders."

**Comment by AJIXuMuK** [comment]
Hi @saurav2107!
Thank you for reporting the issue.
It has been fixed and will be included in the next release.
In a meanwhile you can test the fix in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
