### ISSUE TITLE
Request for more samples regarding "FieldFileTypeRenderer" to override fields 

### ISSUE THREAD

**Issue by aaclage** [pnp/sp-dev-fx-controls-react#647]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [ sp-dev-fx-controls-react v1.19.0  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

####  Question
It is possible that someone could create more samples regarding "FieldFileTypeRenderer" or the other fields  that is more clear on how to use this controls and how to override existing fields in Lists. 
https://pnp.github.io/sp-dev-fx-controls-react/controls/fields/main/

Thank you for your attention

**Comment by AJIXuMuK** [comment]
Hi @aaclage - the sample has been added to [PnP Extensions Sample Gallery](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-field-pnp-file-type-renderer)
