### ISSUE TITLE
RichText does not reflect the changed value

### ISSUE THREAD

**Issue by nbelyh** [pnp/sp-dev-fx-controls-react#650]
#### Category
[ ] Enhancement
[x] Bug
[x] Question

#### Version
Please specify what version of the library you are using: 1.19.0
Also tested in 2.0beta - still no luck.

#### Expected / Desired Behavior / Question
I expect the RichText control to show updated text if I change it's value property

#### Observed Behavior
The displayed value does not change.

#### Steps to Reproduce
Create default SPFx project using yeoman. 
Add dependency to spfx-controls-react to the project.

Then change the contents of the HelloWorld.tsx to:

```
import * as React from 'react';
import { IHelloWorldProps } from './IHelloWorldProps';
import { RichText } from "@pnp/spfx-controls-react/lib/RichText";

export default function HelloWorld(props: IHelloWorldProps) {

  const [html, setHtml] = React.useState('OLD');

  return (<div>
    {html}
    <RichText value={html} />
    <button onClick={() => setHtml('NEW')} >CLICK ME</button>
  </div>);
}
```

Open the project in the workbench.
Click the button "CLICK ME". 
Observe the HTML value changed, but the rich text is still displaying the old value.

**Comment by michaelmaillot** [comment]
Hi @nbelyh,

Do you still have issues with this? Latest version handles `value` change correctly.

**Comment by nbelyh** [comment]
Just re-check - now it looks fine. Closing the issue.
