### ISSUE TITLE
ListItemPicker selected values are not getting cleared or reset 

### ISSUE THREAD

**Issue by PavithraaPandiyan** [pnp/sp-dev-fx-controls-react#659]
Hello All,
I am using ListItemPicker control inside a panel in my react based spfx project solution.  I have a reset button in the panel, on click of reset button, the selected values in the ListItemPicker should be cleared. I kept the selected values in a state variable and tried to clear the state on click of reset button. This is  clearing the value of the state variable (checked in console), but i am able to see the values in the ListItemPicker HTML text box. Please suggest me possible ways to clear the selected values immediately in the ListItemPicker on click of reset button.

Sample Code:
 <ListItemPicker                            
                         listId={GUID ID IS PASSED}                       
                         columnInternalName='Title'  
                         keyColumnInternalName='Id'  
                         itemLimit={10}  
                         onSelectedItem={this.onTagSelectedItem.bind(this)}  
                         context={this.props.context}
                         defaultSelectedItems={this.state.tagSelectedValues} 
                         suggestionsHeaderText = "Suggested Tags" 
 />

**this.state.tagSelectedValues** --> I am saving the selected values in "tagSelectedValues" state variable and on click of reset button, i trying to set state as empty to "tagSelectedValues" ( **this.setState({tagSelectedValues:[]});**  ). But this is not clearing the values in the ListItemPicker HTML Text box immediately.
 

Thanks!

**Comment by tolui** [comment]
Same problem here, controller not refreshed to new value

**Comment by AJIXuMuK** [comment]
Hi @PavithraaPandiyan,
Thank you for reporting the issue. It has been fixed and will be included in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
