### ISSUE TITLE
Canadian french localization

### ISSUE THREAD

**Issue by vincepunkrock** [pnp/sp-dev-fx-controls-react#671]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

Add Canadian french localization. (Basically just use the same as fr-fr but in a fr-ca file.)

**Comment by AJIXuMuK** [comment]
Hi @vincepunkrock!

`fr-ca` localization has been added and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
