### ISSUE TITLE
Cannot add link in first line of Richtext 

### ISSUE THREAD

**Issue by moezbouattour** [pnp/sp-dev-fx-controls-react#672]
I m inable to add a link to richText component as first element in my html, it works if it's not the first element

**Comment by Abderahman88** [comment]
I've been working on this issue.

Kind regards, 

Abderahman

**Comment by AJIXuMuK** [comment]
Thank you @moezbouattour for reporting the issue.
It has been fixed and will be available in the next release.

In a meantime you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
