### ISSUE TITLE
People picker validation error and onchange event

### ISSUE THREAD

**Issue by SuleymanA** [pnp/sp-dev-fx-controls-react#673]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.0]

#### Expected / Desired Behavior / Question
I want to use the getErrorMessage or errorMessage to display a error message when the field is empty.

#### Observed Behavior
When I use getErrorMessage, the onChange event is never fired... when using the errorMessage property via a state property it never get's emptied (once the errorMessage is populated). I see the state changing and form getting updated but the errorMessage keeps displaying the error even if the property is empty string or null

#### Steps to Reproduce
Create a simple react component with just the people picker and try one of the following:

- use errorMessage property, controlled by a state property of the react component
- use getErrorMessage and onChange together

**Comment by carletto75** [comment]
Same issue here!

**Comment by AJIXuMuK** [comment]
Hi @SuleymanA!
Thank you for reporting this issue!

It seems similar to #730 that has been fixed and will be available in the next release. 
Could you please check [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) if that solves you problem as well?
