### ISSUE TITLE
PeoplePicker & KendoReact

### ISSUE THREAD

**Issue by matjazreberc** [pnp/sp-dev-fx-controls-react#674]
Hello, 

I have a question about PoplePicker & KendoReact.

Is it posible to combine PeoplePicker with KendoReact Input componet, or maybe some other way that i can use PeoplePicker with KendoReact?

Thank you, Matjaz Reberc

**Comment by AJIXuMuK** [comment]
Hi @matjazreberc,

There is no way to use KendoReact (or any other library) inside PnP React Controls.

What is the scenario where you need KendoReact input instead of Fluent UI Picker used in `PeoplePicker`?
