### ISSUE TITLE
PeoplePicker missing selectedItems missing

### ISSUE THREAD

**Issue by gbminnock** [pnp/sp-dev-fx-controls-react#675]
#### Category
[x ] Bug

#### Version
2.0.0

#### Expected / Desired Behavior / Question
Unable to retrieve the selectedItems using the people picker control
#### Observed Behavior
Seems to be missing from the interface: https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/peoplepicker/IPeoplePicker.ts but is referenced in the docs https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/

#### Steps to Reproduce
Simple use the control and add selectedItems and observe 
"Property 'selectedItems' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PeoplePicker> & ..."

Is their an alternative? 

Thanks,
Gary

**Comment by AJIXuMuK** [comment]
Hi @gbminnock,

`selectedItems` prop was renamed to `onChange`. So, please, use `onChange`.

I've updated documentation accordingly. It will be available in the next release.

**Comment by kanakanaidu** [comment]
thanks for the update. it saved one day efforts
