### ISSUE TITLE
issue with "Is Required" and "selectedItems" properties in Pnp People picker control in SPFx .

### ISSUE THREAD

**Issue by AnuradhaKumari24** [pnp/sp-dev-fx-controls-react#676]
Hi Team,

I am using SPFx with React with configuration:
NodeJs: 10.16.0
gulp@4.0.2
`yo@3.1.1

I am facing issue with people picker control.  I am not able to set values to "Is Required" and "selectedItems" properties.

**Comment by MudassarAli** [comment]
"Is Required" and "selectedItems" properties are not available in latest version. They are replaced with "required" and "onChange".

**Comment by AJIXuMuK** [comment]
Hi @AnuradhaKumari24!
Could you please check the latest version (2.1.0) and verify if the issue is still valid?
