### ISSUE TITLE
TreeView control checkboxes checked state are not retained

### ISSUE THREAD

**Issue by GokulPT** [pnp/sp-dev-fx-controls-react#677]
Hi,

I am facing a couple of issue in TreeView control in 1.20.0 version. 

1) When I expand a parent node, all the child nodes are expanded. I would like to know, if there is any property available to disable this behavior. The child nodes need to be in collapsed state and the user should expand them
2) The checkboxes checked state of the child nodes are not retained when we move from one screen to an another

**Comment by Abderahman88** [comment]
For the first question, I submitted a PR.
For the second question, do you mean when you change tabs in your browser? I've tried this and the states of the child nodes didn't change. (PS: I tested with Google Chrome)

**Comment by AJIXuMuK** [comment]
Hi @GokulPT!
As @Abderahman88 mentioned the first one has been implemented and will be available in the next release.
For the second one: if you **delete** the controls from the DOM while switching between screens then yes, the state will be lost as the controls will be re-created. It's a correct behavior for any React control.

So, if you have something like
```typescript
{treeViewScreen && <TreeView .../>}
{otherScreen && <OtherComponent .../>}
```
you will lose the state.
If you change it to something like:
```typescript
<div style={{ display: treeViewScreen ? 'block' : 'none' }}>
  <TreeView ... />
</div>
```
`TreeView` will remain the state.
