### ISSUE TITLE
PNP File Picker control- Library Name dropdown in the Upload tab

### ISSUE THREAD

**Issue by pk091990** [pnp/sp-dev-fx-controls-react#678]
#### Category
Enhancement

#### Version

Please specify what version of the library you are using: 1.19.0

####  Enhancement/ Question
I'm using File Picker Control and saving my file to default SharePoint Document library using "Upload " tab. Is there any way to embed Pnp list picker control in the Upload tab to allow users to select their specific library name from the dropdown before uploading the file ?

![image](https://user-images.githubusercontent.com/46436213/95074780-bade0500-072c-11eb-84df-bc34e3d35445.png)

**Comment by AJIXuMuK** [comment]
Hi @pk091990!
Unfortunately, any component is mostly a "blackbox".
I would recommend to place List Picker and File Picker one near another.
