### ISSUE TITLE
ListView  Drag and Drop option

### ISSUE THREAD

**Issue by aaclage** [pnp/sp-dev-fx-controls-react#679]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [   2.0.0.0     ]

#### Submission Guidelines
i was looking @pnp/spfx-controls-react and was surprise the control [ListView ](https://pnp.github.io/sp-dev-fx-controls-react/controls/ListView/) didn't have a "dragDropFiles" property. 

I access to the github to see the [code ](https://github.com/pnp/sp-dev-fx-controls-react/) and expand the control ListView  to have a "**dragDropFiles**" properties,  with [True/False] to enable/disable and a **custom handler "handleDrop**" that retrieves the files content.

Business case:
This could be used by developers that need access to files to sent into SharePoint library or other requirements that need to 
 manage the binary of files.

Questions:
There is any specific to don't have it? 
Makes sense to have it?
If yes to all and approval from the owners, can i make PR with associated changes, documentation, code style, comments and process to be align with the documentation in pnp to include this small feature?

Visual expectation:
![image](https://user-images.githubusercontent.com/8522348/95106356-b4ee2100-0738-11eb-8714-ba650a5c8fb3.png)

![image](https://user-images.githubusercontent.com/8522348/95106124-63de2d00-0738-11eb-992c-16c166d023d4.png)

Thanks!

**Comment by AJIXuMuK** [comment]
Thank you @aaclage for the suggestion!
It could be a great addition to the control!

**Comment by aaclage** [comment]
#682 follow up.

**Comment by aaclage** [comment]
Associated actions were made. I will close this ticket.
