### ISSUE TITLE
IFrameDialog - customize overlay color and dialog background

### ISSUE THREAD

**Issue by mgordic** [pnp/sp-dev-fx-controls-react#686]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [2.0.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Question
Is it possible / how to customize overlay colour and background colour of IFrameDialog?

Thanks!

**Comment by Abderahman88** [comment]
You can add custom styling to the IFrameDialog.

_Example_:
![dialogCodeRed](https://user-images.githubusercontent.com/36161889/96154695-621e2180-0f0f-11eb-9180-b9b5a90857cc.png)

_Result_:
![dialogRed](https://user-images.githubusercontent.com/36161889/96154679-59c5e680-0f0f-11eb-9d7c-f7d150105c20.PNG)

**Comment by AJIXuMuK** [comment]
Hi @mgordic,
As @Abderahman88 mentioned, you can use `modalProps.styles` property of the dialog.
`root` is used for the overlay styling, `main` - for the dialog itself:
```typescript
<IFrameDialog
  modalProps={{
    isBlocking: true,
    styles: {
      root: {
        backgroundColor: '#00ff00'
      },
      main: {
        backgroundColor: '#ff0000'
      }
    }
  }} ... />
```
