### ISSUE TITLE
Not able to set InitivalValues of TaxonomyPicker asynchronously

### ISSUE THREAD

**Issue by mohandivraniya** [pnp/sp-dev-fx-controls-react#692]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.0.0]

#### Expected / Desired Behavior / Question
I am using TaxonomyPicker control and want to populate it (set InitialValues property of control) with existing data via an asynchronous call. It should display data in term picker. 

#### Observed Behavior
I am not able to populate it once the control is initialized. If I pass hard coded value in react component controller in this.state, it accepts value and populates the control with it. 

#### Steps to Reproduce
Add a taxonomy picker control on react component
Set InitialValues property to a state property
On a button click, load metadata from SharePoint list, parse/convert it to IPickerTerms and set state property which is bound to initialValues property of taxonomy picker control. 

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @mohandivraniya.
Thank you for reporting this one!

There were changes to `TaxonomyPicker` related to #367 
It could fix your issue as well.

Could you please test [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) and let us know if the issue has gone or no.
