### ISSUE TITLE
File size without downloadFileContent in FilePicker

### ISSUE THREAD

**Issue by wilecoyotegenius** [pnp/sp-dev-fx-controls-react#699]
#### Category
[X] Enhancement
[ ] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.20.0 ]

#### Expected / Desired Behavior / Question
I suggest extending IFilePickerResult with size property, which will be filled when using Upload File tab. This information may be obtained from tab's input control without having to execute downloadFileContent(). Knowing the size of the file before having to wait for content download could be useful in some cases,

If you think this is a good idea, I will be happy to produce a pull request for this

**Comment by AJIXuMuK** [comment]
Hi @wilecoyotegenius,

I think it would be a great addition.
Feel free to produce a PR to `dev` branch.

**Comment by Abderahman88** [comment]
Hi @wilecoyotegenius 

I was working on showing the filesize in the 'Upload File' tab. (I misunderstood the question :) )

![imageFileSize](https://user-images.githubusercontent.com/36161889/96775404-cc3f3680-13e7-11eb-822b-e1002cd09154.PNG)

Maybe we should add an extra parameter to hide/show the filesize?

Good work!

**Comment by wilecoyotegenius** [comment]
What I focused on in this issue/PR was just to get the file size returned from file picker control. But showing the size in preview also sounds like a very useful addition.
I just wonder if it makes any sense to add an extra parameter to hide/show this value in preview - I am not sure if anybody would care to hide the info about size, especially if getting it does not require any additional processing (as upload tab is downloading the contents of the image to show it in preview anyway),

**Comment by Abderahman88** [comment]
@wilecoyotegenius My mistake :) I was thinking about something that was not necessary.

**Comment by AJIXuMuK** [comment]
Thank you @wilecoyotegenius for proposing the enhancement and implementing int!
