### ISSUE TITLE
 Richtext can we add image support

### ISSUE THREAD

**Issue by moezbouattour** [pnp/sp-dev-fx-controls-react#701]
Hello, the actual RichText component dont support adding images in the html, can you add this option ?
because now when i past a picture in richtext component it's add new image webpart

**Comment by Abderahman88** [comment]
I have made a PR to support images in the control.
It could be much better, but it's a start. :)

**Comment by moezbouattour** [comment]
> I have made a PR to support images in the control.
> It could be much better, but it's a start. :)

Thank you, do you know when will the release date ?

**Comment by Abderahman88** [comment]
@moezbouattour I don't know. @AJIXuMuK ?

**Comment by AJIXuMuK** [comment]
Hello @moezbouattour,

The next release date would probably be around mid November.

In a meanwhile you can use [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
