### ISSUE TITLE
People picker without webpart

### ISSUE THREAD

**Issue by LeonidasFettikus** [pnp/sp-dev-fx-controls-react#703]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version
 
2.0.4

Can I use the people picker control without a web part context? I am trying to use it on an ASPX-page which is part of a SharePoint-hosted app and I can't use web parts.

**Comment by AJIXuMuK** [comment]
Hi @LeonidasFettikus,

Unfortunately, no. The control uses SPFx `context` object that doesn't exist outside SharePoint Framework solutions.
