### ISSUE TITLE
Apply bug fixes also for version 1.

### ISSUE THREAD

**Issue by Matej4386** [pnp/sp-dev-fx-controls-react#707]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version 

Please specify what version of the library you are using: [1.17.0]

#### Question
Hello all,
it is possible to apply bug fixes (like RichText anchor bug #672) also for version 1.17.0 - i cant use version 2.0.0 because production environment is on Sharepoint 2019 on prem ... 
I know it is quite challenging to maintain two branches but i would really appreciate it. 

Thank you in advance.

**Comment by Abderahman88** [comment]
I'll try updating the V1 version. Stay tuned. =)

**Comment by Matej4386** [comment]
@Abderahman88 thank you very much ;-) It would be great to apply all bug fixes to v1 (if it ispossible of course) ...

**Comment by AJIXuMuK** [comment]
Hello @Matej4386!
@Abderahman88 made the fix. It will be available in the next `v1` release.

**Comment by Matej4386** [comment]
Thank you very much
