### ISSUE TITLE
TaxonomyPicker long term names reach out of TermPicker

### ISSUE THREAD

**Issue by mzbrandl** [pnp/sp-dev-fx-controls-react#709]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.0 and 2.1.0-beta.4b99c51]
Tested with both versions.

#### Expected / Desired Behavior / Question
Term name being shortened and staying within the TermPicker.

#### Observed Behavior
Term names extending beyond the TermPicker. The original term name is 64 characters long. It does get shortened to 37 characters, but it's not enough to stay inside the TermPicker.
![2020-10-23 11_28_45-Window](https://user-images.githubusercontent.com/32365313/96988008-11688300-1524-11eb-8206-045257628a0c.png)

#### Steps to Reproduce
Add a long term name to a TaxonomyPicker. The TaxonomyPicker lies within a 275px wide div. 
Is there a minimum width for TaxonomyPickers perhaps?

**Comment by mzbrandl** [comment]
I have found, that when reducing the max-width css property of the pickedTermRoot class, from 300px to 240px, the desired behavior occurs. 
But as far as I can tell, the TaxonomyPicker does not support custom styles, and the max-width would have to be set dynamically for changing picker width.

**Comment by AJIXuMuK** [comment]
Hi @mzbrandl!
Thank you for reporting the issue.
Could you please provide some test project to test it out?
I can't reproduce it on v2.1.0.

<img width="397" alt="Screen Shot 2020-11-06 at 4 21 59 PM" src="https://user-images.githubusercontent.com/17036219/98426069-56c0a080-204c-11eb-8076-90861a257657.png">
