### ISSUE TITLE
Taxonomy Picker - validateOnLoad - error message

### ISSUE THREAD

**Issue by dmoorjmalani** [pnp/sp-dev-fx-controls-react#710]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [ SPFX 1.11.0, spfx-controls-react - 2.0.0  ]

#### Question
I am using TaxonomyPicker setting it with some initial values, now, these values can be invalid (terms which may have been removed or merged), i am using validateOnLoad=true,  so that user can see the error message if any of the tag is not valid. But i am having hard time figuring out how to know the control is having a validation issue on submit. Can somebody please help?

Thanks!
Deepa Moorjmalani

**Comment by dmoorjmalani** [comment]
any updates on this?

**Comment by AJIXuMuK** [comment]
Hi @dmoorjmalani!
Thank you for the question.

There is no any API that returns invalid terms. The component just displays the error message if the terms were not found.

**Comment by dmoorjmalani** [comment]
Hi @AJIXuMuK - Thank you for reverting

I don't need to know which terms are invalid, I just need to know if there is any flag being set when there are invalid terms, so, that i can use that flag to stop user from submitting when there is error.
