### ISSUE TITLE
RichText losing focus onchange  SPFX - 1.11.0, spfx-controls-react - 2.0.0 

### ISSUE THREAD

**Issue by dmoorjmalani** [pnp/sp-dev-fx-controls-react#712]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   SPFX - 1.11.0, spfx-controls-react - 2.0.0      ]

#### Expected / Desired Behavior / Question
When anything is typed in the Rich Text, onchange is getting called and the Rich Text is losing focus, which should not happen

#### Observed Behavior
When anything is typed in the Rich Text, onchange() is getting called on the parent component, which sets state there and that results into the call of render() on parent and in the render() on parent, the child component is getting rendered with the changed value and the Rich Text is losing focus/cursor, when i change the tabs, the cursor comes back but it is set to the start of the input, this used to work with SPFX 1.10.0 and spfx-controls-react - 1.16.0.

#### Steps to Reproduce
Have parent child components, parent sends value to child as props on render(), in the child component have richtext box, onchange of which the onchange of parent would get called

#### Submission Guidelines
Thanks!
Deepa Moorjmalani

**Comment by Abderahman88** [comment]
I will check this out 👍

**Comment by Abderahman88** [comment]
Update spfx-controls-react to v2.1.0

![focusRT](https://user-images.githubusercontent.com/36161889/97633426-60d31580-1a34-11eb-9908-4260cf2ab9a7.gif)

**Comment by dmoorjmalani** [comment]
thank you @Abderahman88. it works with  spfx-controls-react to v2.1.0, but now I am having hard time setting initial value to the rich text. I am calling API on componentDidMount() and my rich text box  is using ref. i then set value to the box using ref. can you please look into this?
 <RichText
                    className={styles.richText}
                    ref={this.projectOverviewRef}
                    value={this.props.ProjectOverview}
                    isEditMode={true}
                    onChange={(text) => this.props.handleChange("ProjectOverview", text)}
                  />
 this.projectOverviewRef.current.handleChange(response[0]["PDS_Overview"]);

**Comment by Abderahman88** [comment]
Hi @dmoorjmalani,

See https://github.com/pnp/sp-dev-fx-controls-react/issues/345 (jcrocke9 answer)

I tested this and it works.

 If you have any questions, let me know.

**Comment by dmoorjmalani** [comment]
thank you so much @Abderahman88 , this solves it.
