### ISSUE TITLE
Getting Type errors in node_modules

### ISSUE THREAD

**Issue by spoman007** [pnp/sp-dev-fx-controls-react#714]
SPFX Version 1.4
2.1 Version

I get below error when I do `gulp serve`

![image](https://user-images.githubusercontent.com/8514338/97986463-06420c80-1dda-11eb-8154-83a56ea10e78.png)

I have created a brand new SPFX project targetting Sharepoint 2019. Then installed the sp-dev-fx-controls-react to use map control.

I start getting this error the moment I import anything from sp-dev-fx-controls-react.

Seems like something really simple but I am not able to understand it.

Thanks!!

**Comment by AJIXuMuK** [comment]
@spoman007 you need to use v1 of the controls. 
V2 is based on SPFx 1.11 and work in SPO only.

**Comment by spoman007** [comment]
@AJIXuMuK Thanks!!!!

I was really tricked by the wording. It says
`v2 version of the controls project has a minimal dependency on SharePoint Framework version 1.11.0. v1 has a minimal dependency on SharePoint Framework version 1.3.0. Be aware that the controls might not work in solutions your building for SharePoint 2016 with Feature Pack 2 on-premises. As for SharePoint 2016 with Feature Pack 2 version 1.1.0 of the SharePoint framework is the only version that can be used. SharePoint 2019 on-premises uses SharePoint framework v1.4.0 and therefore should be fine to use with these controls.`

It would be really nice if the dependency was mentioned little clearly. Maybe something like
`Version 2.x controls will not work with SPFX 1.4`

Thank you for your reply!!
