### ISSUE TITLE
'Carousel' component cannot be used as a JSX component. SPFX 2019 on premise latest version

### ISSUE THREAD

**Issue by tuuuks** [pnp/sp-dev-fx-controls-react#716]
#### Category
[ ] Enhancement

[x ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [ 2.1.0 ]

#### Expected / Desired Behavior / Question
Rendering of the carousel Component

#### Observed Behavior
'Carousel' cannot be used as a JSX component.

#### Steps to Reproduce
Try using the 'Carousel' component inside the latest spfx framework for on-premise 2019 sharepoint generated via yo @microsoft/sharepoint

#### Submission Guidelines
Full Error:
![image](https://user-images.githubusercontent.com/50074563/98114747-03145280-1ea6-11eb-9c7b-9e9933340786.png)

Scaffolding done with Yeoman 'yo @microsoft/sharepoint --latest'

The problem is i can't seem to be able to use the Carousel component in the suggested version. Do you have any advice to fix this problem? Am i doing something wrong, or is it bugged for the on-premise 2019 version?
Thank you

Thanks!

**Comment by aaclage** [comment]
@tuuuks 
You need to use V1 for SP2019 environment, version V2 only works for SharePoint Online.
Please give a look in documentation here:
https://pnp.github.io/sp-dev-fx-controls-react/ 

issue also talked #714 .

**Comment by tuuuks** [comment]
> @tuuuks
> You need to use V1 for SP2019 environment, version V2 only works for SharePoint Online.
> Please give a look in documentation here:
> https://pnp.github.io/sp-dev-fx-controls-react/
> 
> issue also talked #714 .

Thank you, started working when i downgraded to v1.20.00
