### ISSUE TITLE
ListView:  using both linkPropertyName & selectionMode

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#720]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version
"@pnp/spfx-controls-react": "2.0.0",

#### Expected / Desired Behavior / Question
I want to use selectionMode option and still be able to use linkPropertyName to open file.

#### Observed Behavior
I have my listView set up with selectionMode=Single
And I have linkPropertyName set so that I see a link (in my example I just put it on the Modified column).

What happens is if I click on what looks like the link, it will open my pnp panel... this part of my selection function.

Is there a reference on how I can check to see what field I'm looking at and then determine if it's a link and open the file instead?

Thanks!

![image](https://user-images.githubusercontent.com/49648086/98171751-3d89e980-1ebe-11eb-822d-6ff7e0a7a50e.png)

**Comment by mikezimm** [comment]
I was able to cobble this code up for the "selection" function but I'm wondering if there is a simpler or more elegant solution I'm missing:

In this case I have to chase down the target props and search for an href to see if it's a link.
It works but it's always takes a lot of digging  into the event props to find a way to test it.

_let isLink = e.srcElement && e.srcElement.href && e.srcElement.href.length > 0 ? true : false;_

```typescript
    private _onShowPanel = (item): void => {
  
        let e: any = event;
        console.log('_onShowPanel: e',e);
        console.log('_onShowPanel item clicked:',item);

        // This is the place where I am testing to see if a child node has an href...
        let isLink = e.srcElement && e.srcElement.href && e.srcElement.href.length > 0 ? true : false;

        if ( isLink === true ) {
            window.open(e.srcElement.href, '_blank');

        } else {
              //Code to set state and open panel here
        }
     }
```

**Comment by AJIXuMuK** [comment]
Hi @mikezimm!
If you want to handle the `click` I would recommend to override `render` method for the link column.
In that case you can provide your `onClick` handler.
In that handler you can open your file and additionally `preventDefault` and `stopPropagation` to avoid selection.

I would also ask you to create a separate enhancement issue to add `onClick` property for the link column type.
