### ISSUE TITLE
TaxonomyPicker should have required/mandatory property on it

### ISSUE THREAD

**Issue by mohandivraniya** [pnp/sp-dev-fx-controls-react#721]
#### Category
[x] Enhancement
#### Version
1.18.0

Please specify what version of the library you are using: [1.18.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
TaxonomyPicker should have required/mandatory property on it.

#### Observed Behavior
TaxonomyPicker does not have required/mandatory property on it.

#### Steps to Reproduce
Add TaxonomyPicker control to your react code. There is no required property to set. 

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @mohandivraniya!
There is `required` property in the `TaxonomyPicker`.
Please, refer the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/)
