### ISSUE TITLE
ListItemPicker: When use defaultSelectedItems, ListItemPicker allows you to select dublicate entries. 

### ISSUE THREAD

**Issue by bva999** [pnp/sp-dev-fx-controls-react#722]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.1.0 ]

#### Expected / Desired Behavior / Question
If you have specified some defaultSelectedItems values, the first time you use ListItemPicker in the suggestions list, you will find those values and will be able to select them.

**Comment by AJIXuMuK** [comment]
Thank you @bva999 for reporting the issue!
It has been fixed and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
