### ISSUE TITLE
Carousel height problem

### ISSUE THREAD

**Issue by tuuuks** [pnp/sp-dev-fx-controls-react#723]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [1.20.0]

#### Expected / Desired Behavior / Question
Carousel control seems to have issues with height. Expected behavior is a proper height carousel, where you can see all the information supplied into the control.

#### Observed Behavior
The Carousel control is incredibly small so it hides all the supplied information (title, description)

#### Steps to Reproduce
Add the carousel with proper data on spfx 2019 on premise latest release + spfx-controls version 1.20.0

Picture of the results: 
![image](https://user-images.githubusercontent.com/50074563/98225827-850f8480-1f55-11eb-83d5-93c62468c159.png)

The title and description actually do show up in the elements if you check the console. The problem is the incredibly small height, for which i have no idea why it's set that way. 

code:
https://pastebin.pl/view/fbae18bf

None of my styles feature a fixed height or something like that, the console output of the data supplied into the carousel is the following:
![image](https://user-images.githubusercontent.com/50074563/98226298-1f6fc800-1f56-11eb-88bb-2539f5818a78.png)

What am i missing? Why is the component so narrow?

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @tuuuks!
Thanks for reporting this one.
Current implementation expects the height to be specified in `contentContainerStyles` property.
Sample:
```typescript
<Carousel contentContainerStyles={styles.carouselImageContent}
/// ...
/>
```
```css
.carouselImageContent {
    height: 400px;
  }
```

**Comment by Ryujin-Jakka** [comment]
Hello guys,

I'm using this control on a web part with SPFX 1.4.1 on SP2019.
This control is fantastic!

I have only one question regarding the use of a React.CSSProperties to assign values dinamically.

This is the scenario.
I want to change width and height from the settings of the web part.
So, I'm using a PropertyFieldDimensionPicker to get some values.
![image](https://user-images.githubusercontent.com/8181519/161549487-432a4570-515c-418d-9e7d-7a4ebd135e3f.png)
The values are correctly assigned to the props of the component and then I use them in a React.CSSProperties variable.
Then I use this variable for the relative carousel property (contentContainerStyles), but it does not work at all.

I tried to debug the whole process and the data arrives correctly up to the control, but they are not used and therefore the carousel does not show anything (only the side arrows).
I tried instantiating a React.CSSProperties variable normally and tried instantiating a generic variable and then cast it. I also tried to add the string "! Important" for each parameter, but the browser does not display any of the parameters (width and height) inside the container class of the Carousel.

This is the defined style:
`let contentContainerCSS = {
      width: `${this.props.widthContainer}`,
      height: `${this.props.heightContainer}`,
      minWidth: `${this.props.minWidthContainer}`,
      minHeight: `${this.props.minHeightContainer}`
    } as React.CSSProperties;`

This is the Carousel control:
`<Carousel
          element={carouselElements}
          containerStyles={containerCSS}
          prevButtonStyles={styles.carouselBtn}
          nextButtonStyles={styles.carouselBtn}
          indicatorClassName={styles.indicator}
          contentContainerStyles = {contentContainerCSS}
          //contentContainerStyles={styles.contentContainer}
          isInfinite={this.props.isInfinite}
          pauseOnHover={this.props.pauseOnHover}
          slide = {this.props.slide}
          interval = {this.props.autoLoadInterval * 1000}
          buttonsLocation={CarouselButtonsLocation.center}
          buttonsDisplay={CarouselButtonsDisplay.buttonsOnly}
          indicatorShape={CarouselIndicatorShape.circle}          
          onMoveNextClicked={(index: number) => {  console.log(`Next button clicked: ${index}`); }}
          onMovePrevClicked={(index: number) => {  console.log(`Prev button clicked: ${index}`);  }}
/>`

If I use fixed values for width and height, inside a class in the module.scss file, and then I assign this class to the same property (contentContainerStyles), it works properly.
This is an example of the defined class used:
`  .contentContainer{
    width: 1920px;
    height: 350px;
    min-width: 400px;
    min-height: 300px;
  }`


So, at this point, there is something I can do to resolve this strange behavior?

**Comment by centtos26** [comment]
Hi, try this:
1. In scss
$altura: 250px;
:root {
  --baseAlturaImg: $altura;
}
.pnpImageCarousel {  
    .carouselContent {  
      height: var(--baseAlturaImg) !important;  
    } 
} 
2. Set
document.documentElement.style.setProperty('--baseAlturaImg',this.props.heightImgComunicados);
 <Carousel  
          buttonsLocation={CarouselButtonsLocation.center}  
          buttonsDisplay={CarouselButtonsDisplay.buttonsOnly}  
          contentContainerStyles={styles.carouselContent}
          isInfinite={true}
          indicators={false}
          indicatorShape={CarouselIndicatorShape.circle}  
          pauseOnHover={true}
          element={items}  
          containerButtonsStyles={styles.carouselButtonsContainer}  
          />  

I hope it helps you
