### ISSUE TITLE
FilePicker: Site Tab does not load document if we access SharePoint site in different language than default language of the site

### ISSUE THREAD

**Issue by kalpeshvaghela90** [pnp/sp-dev-fx-controls-react#724]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.16.0 ]

#### Expected 

FilePicker - Site Tab should work doesn't matter in which language we are accessing site.

#### Observed Behavior

If SharePoint site's default language is English, and if you access site in any other language then Site tab will show list of document library but if we click on any library then it doesn't get document from that document library (specially in case of default library i.e. Site Pages, Site Assets, Document Library) if document library title is multi lingual.

#### Steps to Reproduce
1. Create one site collection in English language
2. Deploy web part/extension which does have File picker used
3. Access site in different language than default language English
4. Open File Picker and click on Site Tab and select default library i.e. Site Assets/Documents/Site Pages
5. It will not show any documents

#### Submission Guidelines

I went through code and found that document library are being accessed using GetByTitle method.
![image](https://user-images.githubusercontent.com/70681641/98241404-e7d24180-1f90-11eb-844f-9ad93c381cd2.png)

It should not use List Title in order to get query in document library but it should use either list server relative URL or List Id

Thanks!

**Comment by AJIXuMuK** [comment]
Thank you @kalpeshvaghela90 for reporting that issue!

**Comment by AJIXuMuK** [comment]
Hi @kalpeshvaghela90,

I have implemented the fix. Could you please test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)?

**Comment by nbelyh** [comment]
@AJIXuMuK Now it seems that the folder browser stopped working altogether when navigating from the "Sites" view 😄 (works only on the root site). It throws an exception here (404, file not found), on any locale, `/site/AnySite/` url:

![image](https://user-images.githubusercontent.com/528366/100601008-5b523f00-3302-11eb-80ca-b8dc65d97375.png)

https://github.com/pnp/sp-dev-fx-controls-react/blob/56d7e014eb97377c4a2a7b3f8a93a8f2417c327d/src/services/FileBrowserService.ts#L30-L32

The thing is, it tries to do this: `getList('/Shared%20Documents')` 
When it actually should do this: `getList('/site/AnySite/Shared%20Documents')` 

Looks like getList() expects full relative url, not a partial one.

**Comment by AJIXuMuK** [comment]
Thank you @nbelyh! Good catch!

Now it should be fixed.
