### ISSUE TITLE
PNP SPFx FilePicker multi select

### ISSUE THREAD

**Issue by evlo** [pnp/sp-dev-fx-controls-react#725]
Hi,

i'm just beginning with react so I will not be doing pull request any time soon.

I have and feature request for enhancement of PNP SPFx FilePicker - would it be possible to add option for multi choice of files?

Thanks

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question

User is able to check multiple files in library by clicking on the checkbox in front of the filename that is already displayed in latest version of filepicker

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @evlo!
Thank you for the proposal.
We'll take a look into it.

**Comment by evlo** [comment]
I will open new one if I come across that need in the future and find out it would still be nice enhancement.

**Comment by joelfmrodrigues** [comment]
@cneSPFX0815 fair point, I think you are correct and I misinterpreted it. Thanks for your input!
@MonalisaBaltatescu still available to help? Can I assign this to you?

**Comment by MonalisaBaltatescu** [comment]
@joelfmrodrigues  Yes, I still want to contribute :)

**Comment by AJIXuMuK** [comment]
included in v3.6.0
