### ISSUE TITLE
Question:  Setting field widths correctly (like DatePicker, PeoplePicker, TextField etc)

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#726]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version
"@pnp/spfx-controls-react": "^2.1.0",

### Question
Can someone provide a guide or point to an example explaining how to field controls?  Nothing complex, just the width is fine.

For example, I am using a DateFieldPicker, TextField, PeoplePicker in my panel.

I set the width of the parent div element to something like 200px.

In the screenshot, the green line is the width.  And sometimes fields are the correct width (as in Notified date) and sometimes it's not (FollowupDate).

It's very frustrating because if I use F12, I can always find the right element to set to 100% (like the input box), and it works.  But when I try to actually apply that in my code it rarely works.

![image](https://user-images.githubusercontent.com/49648086/98453758-af666b00-212a-11eb-9a71-b945959ed1bb.png)

**Comment by AJIXuMuK** [comment]
Hi @mikezimm!
For the `DateTimePicker` - it has `width=100%`. So it should fit the width of the parent container. It's the same behavior as for default Fluent UI `TextField` or `Dropdown`.
I would recommend to analyze what styles you have set on the parent containers.

Here is the screenshot from one of my projects where I use `TextField` and `DateTimePicker` in the panel:
![datetimepicker](https://user-images.githubusercontent.com/17036219/98491762-bbb1fd00-21ea-11eb-9951-f016010afb2b.png)
