### ISSUE TITLE
PeoplePicker errorMessage not being removed

### ISSUE THREAD

**Issue by gbminnock** [pnp/sp-dev-fx-controls-react#730]
Category
[x ] Bug

Version
2.0.0

Expected / Desired Behavior / Question
When a user is picked I run some custom validation on the user. If the user is invalid an error message should show.
If this user is cleared and another user is selected where the user passes the validation then the error message should be cleared. 

Observed Behavior
1. PeoplePicker uses errorMessage to display an error (if a user does not pass some validation logic).
2. Error message variable is passed to PeoplePicker as a prop. 
3. If user is invalid error message is shown.
4. If this user is removed and another added which is a valid user then the errorMessage should clear but it does not. 
4.1 I can see that my prop for errorMessage contains the correct value "".
4.2 But I can see that the PeoplePicker contains a state value for errorMessage from the previous selected user.

Please see react component of peoplepicker

![image](https://user-images.githubusercontent.com/2708345/98815198-b210db00-241e-11eb-90eb-94b8cfbbfe11.png)

thanks,
Gary

**Comment by tarcisiopqdt** [comment]
I've same problem

**Comment by AJIXuMuK** [comment]
Hi @gbminnock,
Thank you for reporting this one!

It has been fixed and will be available in the next release.

In a meanwhile you can test the functionality in the [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by NickRCarlson** [comment]
This issue does not appear to be resolved. I'm using version 3.0 and have even downgraded to 2.6 and I'm seeing the same behavior descripted in this issue
