### ISSUE TITLE
Reduce bundle size (FilePicker)

### ISSUE THREAD

**Issue by nbelyh** [pnp/sp-dev-fx-controls-react#732]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [ 2.10 ]

#### Expected / Desired Behavior / Question

How can I reduce the FilePicker footprint? Now it's bigger than whole @fluentui  for example (and any other library), actually it's size seems to be somehow ridiculous 😄 Is it really the case, and FilePicker is that big, or am I misinterpreting the results? Check out this picture (produced by webpack-bundle-analyzer).

![image](https://user-images.githubusercontent.com/528366/99008072-be438800-2545-11eb-98bf-d7c0c55218d9.png)

Do you have any recommendations to optimize the bundle size?

**Comment by AJIXuMuK** [comment]
Thank you @nbelyh for reporting it!
I will investigate if we can do some optimizations.

**Comment by AJIXuMuK** [comment]
Hi @nbelyh,
I've updated the imports for the `FilePicker`. And now it looks much better.
The final size of the web part bundle that uses `FilePicker` decreased from 1.9 MB to 853 KB.

You can test new build using [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by nbelyh** [comment]
Sounds great. Will check it out 👍
