### ISSUE TITLE
ListView Control Sticky Header scrolling issue

### ISSUE THREAD

**Issue by ragu64** [pnp/sp-dev-fx-controls-react#734]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.1.0]

#### Expected / Desired Behavior / Question
With sticky header feature enable in the PnP ListView control with more 80 items, scrolling items missing  (large blank zone). It's seems a render problem (on Chrome browser press F12 twice, the missing items magically reappears).

Thanks!
![PnPJS Issue 734](https://user-images.githubusercontent.com/715870/99415378-05d86400-28f8-11eb-9ab7-dddb5510e692.png)

**Comment by aaclage** [comment]
Hi @ragu64 

I try with 100 items and was able to retrieve this error, this only happens in the filter or when you list all?

**Comment by ragu64** [comment]
I have three fields (as you can see in attached image), it's happen always.

**Comment by aaclage** [comment]
Did you try to load all in the sticky header without the append 10 random items and happen the same error?

**Comment by ragu64** [comment]
Same error. I think is SharePoint Online effect in local (non SPO) it's works fine.

**Comment by ragu64** [comment]
This is my react compoment used in my test spfx webpart:

[Action.zip](https://github.com/pnp/sp-dev-fx-controls-react/files/5561925/Action.zip)

**Comment by AJIXuMuK** [comment]
Hi @ragu64,

I can't repro your issue. I used your code to create a web part and it behaves correctly:
<img width="1267" alt="Screen Shot 2020-11-20 at 4 34 04 PM" src="https://user-images.githubusercontent.com/17036219/99862352-39acc700-2b4e-11eb-913e-d34d71613750.png">

**Comment by AJIXuMuK** [comment]
Could you try [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) of the library?

**Comment by ragu64** [comment]
> Hi @ragu64,
> 
> I can't repro your issue. I used your code to create a web part and it behaves correctly:
> <img alt="Screen Shot 2020-11-20 at 4 34 04 PM" width="1267" src="https://user-images.githubusercontent.com/17036219/99862352-39acc700-2b4e-11eb-913e-d34d71613750.png">

Hi, with more than 80 items the issue recurs

**Comment by ragu64** [comment]
> Could you try [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) of the library?

I wil try it.

Thanks a lot

**Comment by AJIXuMuK** [comment]
@ragu64 - I just double-checked, the property is still there.
Could you please check what version of the library you have in `package.json` file?

**Comment by ragu64** [comment]
> @ragu64 - I just double-checked, the property is still there.
> Could you please check what version of the library you have in `package.json` file?
You are right, the property stickyHeader is still there, sorry.
after install spfx-controls-react beta in my solution:
npm install @pnp/spfx-controls-react@next --save

this is the version in my package.json:
"@pnp/spfx-controls-react": "^2.2.0-beta.056c6d9",

**Comment by aaclage** [comment]
Ok i found the issue, The List View uses the DetailsList and this one uses lazy loading "Load Content by blocks of 100 or around that" only when default vertical scroll "From Page" the content of ListView is refresh by blocks. The fixe-header doesn't activate the Page scroll and cannot refresh because header is fix only by scroll. I will try to see if the refresh block can be call when scroll with fix header to get the content of that block.

**Comment by AJIXuMuK** [comment]
@aaclage - what if we go back to the implementation with [ScrollablePane](https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane)?

**Comment by aaclage** [comment]
@AJIXuMuK 
i will try that.

**Comment by aaclage** [comment]
@AJIXuMuK 
Ok works in old implementation with the lazy loading, i will revert to that control.

**Comment by aaclage** [comment]
@AJIXuMuK PR create with the revert to ScrollablePane.

**Comment by AJIXuMuK** [comment]
Thank you @aaclage!
The PR has been merged and will be available in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by ragu64** [comment]
Thank you guys, now ListView stickyHeader={true} in PnP Controls 2.3.0-beta, works fine!
