### ISSUE TITLE
TaxonomyPicker's picker icon not rendering on Classic SharePoint Pages

### ISSUE THREAD

**Issue by dmoorjmalani** [pnp/sp-dev-fx-controls-react#735]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ @pnp/spfx-controls-react@2.1.0 and SPFX 1.11.0        ]

#### Expected / Desired Behavior / Question
The picker icon and the cross icon that we use to remove the terms should get displayed in classic pages

#### Observed Behavior
The picker icon which we can click on to open up the panel is not displaying for classic SharePoint pages. The cross that we get to delete the term is also not coming up. I have used Taxonomy Picker in other projects and it has worked so far. 

#### Steps to Reproduce
I created a new spfx+react project using Yeoman (so that i have a clean start), installed  "@microsoft/tsdoc"@latest, because the build was giving an error, installed @pnp/spfx-controls-react latest and added Taxonomypicker in my component, the control works fine in gulp serve and modern pages, it is with the classic pages the css seems to be breaking.

Thank you,
Deepa Moorjmalani

**Comment by dmoorjmalani** [comment]
okay, i found a workaround from this [thread](https://github.com/microsoft/fluentui/issues/7900), basically the icons need to be loaded explicitly on webpart, using the following, but it used to work without these before. any intel? 

import { initializeIcons } from '@uifabric/icons';
initializeIcons();

**Comment by AJIXuMuK** [comment]
Hi @dmoorjmalani!
Thank you for reporting the issue!

The fix has beed implemented and will be available in the next release.

**Comment by dmoorjmalani** [comment]
@AJIXuMuK  - thank you so much!
