### ISSUE TITLE
Attachemnts control is not fully disabled

### ISSUE THREAD

**Issue by AdiuTankT72** [pnp/sp-dev-fx-controls-react#736]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  2.0.0  ]

#### Expected / Desired Behavior / Question
I am disabling the empty (no attachments) attachments control - user cannot add attachments.

#### Observed Behavior
The button "Add Attachment" is disabled by the red "Add" button is still enabled (this button is visible only when there are no attachments).

#### Steps to Reproduce

Thanks!

**Comment by Abderahman88** [comment]
Assign to me.

**Comment by Abderahman88** [comment]
@AdiuTankT72 Thanks for reporting this issue. 👍

**Comment by AJIXuMuK** [comment]
Thank you @AdiuTankT72 for reporting the issue and thank you @Abderahman88 for quick fix!
It will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
