### ISSUE TITLE
sessionStorage exceeds max-size when browsing large termsets

### ISSUE THREAD

**Issue by JohanFiske** [pnp/sp-dev-fx-controls-react#739]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.13.2]
_We tried the latest version also, but gives the same error._

#### Expected / Desired Behavior / Question
Browsable termsets with more than 1500 terms

#### Observed Behavior
When opening multiple large termsets the spinner is stuck and won't load the termset tree

#### Steps to Reproduce
Open a couple of taxonomy pickers with more than 1000 terms. After a few the spinner gets stuck and in the console this error occurs:
`Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of '[guid]' exceeded the quota.`

#### Workaround/Question
After selecting a term we're removing the termset-item from sessionStorage in order to not exceed the quota on the next load of a different termset, but it feels like a unnecessary workaround. Any ideas how this could be fixed without this workaround?

Thanks and regards,
Johan

**Comment by AJIXuMuK** [comment]
Hi @JohanFiske!
Thank you for reporting the issue!
@gautamdsheth has fixed it in #745 and it'll be available in the next release.
In a meantime you can test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
