### ISSUE TITLE
FolderExplorer and FolderPicker do not seem to work for document libraries

### ISSUE THREAD

**Issue by nbelyh** [pnp/sp-dev-fx-controls-react#741]
FolderExplorer and FolderPicker controls do not seem to work for the document libraries

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.1.0]

#### Description

Create a sample project with FolderExplorer, as specified in the documentation:
https://pnp.github.io/sp-dev-fx-controls-react/controls/FolderExplorer/
```
<FolderExplorer context={this.props.context}
                rootFolder={{
                  Name: 'Documents',
                  ServerRelativeUrl: `/sites/TestSite/Shared Documents`
                }}
                defaultFolder={{
                  Name: 'Documents',
                  ServerRelativeUrl: `/sites/TestSite/Shared Documents`
                }}
                onSelect={this._onFolderSelect}
                canCreateFolders={true} />
```

#### Expected

You see the folder explorer in the UI, showing corresponding folders/libraries.

#### Observed Behavior

The FolderExplorer does not work, it always shows "there are no folders" and throws this exception in console:
```
Error loading folders TypeError: Cannot read property 'filter' of undefined
    at FolderExplorerService.<anonymous> (FolderExplorerService.js:68)
    at step (FolderExplorerService.js:31)
    at Object.next (FolderExplorerService.js:12)
    at FolderExplorerService.js:6
    at new Promise (<anonymous>)
    at xI2j.__awaiter (FolderExplorerService.js:2)
    at FolderExplorerService._getDocumentLibraries (FolderExplorerService.js:58)
    at FolderExplorerService.<anonymous> (FolderExplorerService.js:51)
    at step (FolderExplorerService.js:31)
    at Object.next (FolderExplorerService.js:12)
```
Reasons (most probably pnpjs library modified after the FolderExplorer was last verified?)
1.  
`@pnp/sp/lists` is not included in the FileExplorerService.ts, here:
https://github.com/pnp/sp-dev-fx-controls-react/blob/dda0256dab865a47c56a971763bf44f18689a5dc/src/services/FolderExplorerService.ts#L1-L9

But is used here:
https://github.com/pnp/sp-dev-fx-controls-react/blob/dda0256dab865a47c56a971763bf44f18689a5dc/src/services/FolderExplorerService.ts#L44

The result is, web.lists is undefined and that result in the exception.

2. double encoding of folder paths (of the "%" symbol). This causes the list of folders to be always empty even after the change above.

https://github.com/pnp/sp-dev-fx-controls-react/blob/dda0256dab865a47c56a971763bf44f18689a5dc/src/services/FolderExplorerService.ts#L75

pnpjs (getFolderByServerRelativePath) also encodes it, in the referenced version 2.0.6 as well:
https://github.com/pnp/pnpjs/blob/183dc11edb65aa67f6e053e03fb28c5dbdb8a9a5/packages/sp/folders/web.ts#L58

**Comment by nbelyh** [comment]
Checked the history, seems to be broken by this commit actually:
https://github.com/pnp/sp-dev-fx-controls-react/commit/fc7d9fb087f6bd094ef63ac1992a875d701be15a

**Comment by gautamdsheth** [comment]
I did test with normal as well as some folders with special chars like `%` and `#` and it worked well, but it looks like I missed something. My bad. Sorry :(

**Comment by nbelyh** [comment]
My guess is that pnpjs version might have been updated and this part not re-checked?

**Comment by nbelyh** [comment]
Reaplced the PR with another to dev branch

**Comment by nbelyh** [comment]
Sorry for deleted PR (would be great if the maintainers can delete them 😅 
Have read the submission guidelines after creating PR. Now the branch is from dev and trargets dev.

**Comment by AJIXuMuK** [comment]
Hi @nbelyh, @gautamdsheth - I've merged the PR.

@gautamdsheth - could you please check [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) and confirm that it works correctly for the use-cases you were addressing in your previous PR?

Thank you!

**Comment by gautamdsheth** [comment]
@AJIXuMuK - works fine with the latest beta. Thanks

**Comment by nbelyh** [comment]
Thank you guys, then I'm closing the issue
