### ISSUE TITLE
TreeView - defaultSelectedKeys

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-controls-react#744]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.19.0      ]

#### Expected / Desired Behavior / Question

On TreeView control, use the defaultSelectedKeys property to select items by default when they are rendered

#### Observed Behavior

The defaultSelectedKeys property seems to be ignored by the control. I am unable to set a default selection or remove the current selection

#### Steps to Reproduce

Pass values to the property:
defaultSelectedKeys={['key1', 'key2']},

**Comment by AJIXuMuK** [comment]
Hi @joelfmrodrigues!
Thank you for reporting the issue!
Could you please try to update to the latest version (2.1.0) and check if the issue is still there. I checked it locally and it seems to be working.

**Comment by joelfmrodrigues** [comment]
@AJIXuMuK Thanks, I did update to the latest version and can confirm it's working. Sorry, forgot to come back here and close the issue.

**Comment by AJIXuMuK** [comment]
Awesome! Thank you for the confirmation!

**Comment by FaganSC** [comment]
I'm using version 2.1.0 and it's not working 

 <TreeView
              items={items}
              defaultExpanded={true}
              selectionMode={TreeViewSelectionMode.Single}
              showCheckboxes={true}
              defaultSelectedKeys={["Item3"]}
              onSelect={this.temp}
          />
