### ISSUE TITLE
FilePicker - select folder for upload

### ISSUE THREAD

**Issue by nbelyh** [pnp/sp-dev-fx-controls-react#746]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.1.0]

#### Desired Behavior

Would be really great if the FilePicker allowed you to select a place where to upload the file (target document library / target folder). Something like this one the "Upload" tab (it's completely blank now):

![image](https://user-images.githubusercontent.com/528366/100346127-a22ef480-2fe3-11eb-8db6-a425445639b4.png)

#### Alternative

Alternatively, it would be good enough to have a callback to render custom content for the upload tab ("renderUpload" or something like this). So that user can equip the file being uploaded with required additional information. This can be not necessarily the target folder only; it can also be some required properties for the target document library for example.

**Comment by AJIXuMuK** [comment]
Hi @nbelyh!
It's a good idea! Thank you for sharing!

**Comment by nbelyh** [comment]
@AJIXuMuK Do you think it would make more sense to add folder selector or a generic solution that would allow any fields (but these are to be implemented by user)? I think the second could be much easier to implement and more generic. The first one will provide extra value immediately though. But could be implemented as a test/example.

**Comment by AJIXuMuK** [comment]
@nbelyh - I would do the second.

And yes, it would be awesome to include example in the web part included in the project.

**Comment by nbelyh** [comment]
@AJIXuMuK Created related PR. Please kind check when you have time 😃

**Comment by AJIXuMuK** [comment]
Thank you @nbelyh - merged!

**Comment by nbelyh** [comment]
Have not noticed missing escape for the "|" symbol, the documentation comes out wrong - created a PR to fix.

**Comment by AJIXuMuK** [comment]
Thank you @nbelyh
