### ISSUE TITLE
FilePicker - "onChange" event does not exist despite being documented

### ISSUE THREAD

**Issue by nbelyh** [pnp/sp-dev-fx-controls-react#747]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [2.1.0]

#### Question

There is "onChange" even mentioned in the documentation:
https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/

| Property | Type | Required | Description |
| ---- | ---- | ---- | ---- |
| onChange | (filePickerResult: IFilePickerResult) => void | no | Handler when the file selection has been changed. |

Actually, this event does not seem to exist in the control. The one that does exist is called `onChanged` (notice 'd' at the end). But this one (with 'd') is never fired, it is only declared in the interface (but never triggered). You can verify that by simply trying full-text-search - the interface is the only place where it appears to exist in the FilePicker control. Practically, it is never called either.

Probably this event should be simply removed?

**Comment by AJIXuMuK** [comment]
Hi @nbelyh!
Thank you for reporting this one!

The fix has been implemented. Now `onChange` (without d) is called when the file is selected on Upload tab.

**Comment by nbelyh** [comment]
@AJIXuMuK  Thanks 👍
