### ISSUE TITLE
Unable to commit due to npm changelog script 

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-controls-react#752]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    2.2.0     ]

#### Expected / Desired Behavior / Question
Be able to commit a change. 

#### Observed Behavior
Unable to commit changes due to pre-commit configuration inside package.json.
Not sure if relevant, but this is happening when using WSL2 and node 10 (with nvm). 
Additional note: I also had to update the first line of `crate-changelog.js` and change `const changelog = require('../CHANGELOG.json');` to `const changelog = require('../CHANGELOG.JSON');` (upercase file extension) as Linux is case sensitive and was failing to reference the file - will also add a PR for this if required

``` JSON
"husky": {
    "hooks": {
      "pre-commit": "npm run changelog"
    }
  }
```

![image](https://user-images.githubusercontent.com/19577724/100554274-79c92380-328b-11eb-9073-cbf0258909f8.png)

#### Steps to Reproduce
Make a change and try to commit.

**Comment by AJIXuMuK** [comment]
@estruyf - could you please look into this one?

**Comment by joelfmrodrigues** [comment]
Hey @AJIXuMuK @estruyf any guidance on this? I can't do anything on this project with this error :( Can't even commit locally

Any chance one of you could create a PR to fix a bug on the TreeView control? When passing an empty array for sefaultSelectedKeys property, the control is not removing previous selection.
This can be fixed by adding:

```TypeScript
  public componentWillReceiveProps(nextProps: ITreeViewProps): void {
    const {
      items,
      defaultSelectedKeys,
      selectChildrenIfParentSelected,
    } = nextProps;
    if (defaultSelectedKeys) {
      const selectedItems = !defaultSelectedKeys ? [] : this.getSelectedItems(items, defaultSelectedKeys, selectChildrenIfParentSelected);
      this.setState({
        activeItems: selectedItems
      });
    }
  }
```

For testing, update:

1. Add new property to IControlsTestState
treeViewSelectedKeys?: string[];
2. Initialize state property on constructor with
treeViewSelectedKeys: ['gc1', 'gc3'],
3. Update control on ControlsTest.tsx to be:
```JSX
<div>
          <h3>Tree View</h3>
          <TreeView items={this.treeitems}
            defaultExpanded={false}
            selectionMode={TreeViewSelectionMode.Multiple}
            showCheckboxes={true}
            treeItemActionsDisplayMode={TreeItemActionsDisplayMode.ContextualMenu}
            defaultSelectedKeys={this.state.treeViewSelectedKeys}
            onExpandCollapse={this.onExpandCollapseTree}
            onSelect={this.onItemSelected}
            defaultExpandedChildren={true}
            //expandToSelected={true}
            // onRenderItem={this.renderCustomTreeItem}
          />
          <PrimaryButton onClick={() => { this.setState({ treeViewSelectedKeys: [] }); }}>Clear selection</PrimaryButton>

        </div>
```

**Comment by estruyf** [comment]
@joelfmrodrigues feel free to remove the `husky` pre-commit hook. That will make it work. Probably the git version or node version on your end doesn't support it.

**Comment by joelfmrodrigues** [comment]
@estruyf Thank you!

In case someone finds this thread while searching for the same error:
I deleted the husky pre-commit reference from package.json and it worked as expected. I kept my package.json outside of commit so the overall project setup is not affected.
