### ISSUE TITLE
DateTimePicker - hours dropdown not re-rendered when state changed programmatically

### ISSUE THREAD

**Issue by BreakfastMaintenance** [pnp/sp-dev-fx-controls-react#757]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.2.0 ]

#### Expected / Desired Behavior / Question

I have a DateTimePicker on a form that's showing time displayed as dropdowns. If I programmatically change the value of the component, the date portion re-renders successfully but not the hours portion. (Changes made via UI work normally as they fire the onChange handler.)

My specific use case is an Undo button on the form that reverts the form values back to what was initially retrieved from the server.

Initial value:

![image](https://user-images.githubusercontent.com/4473094/101062437-8e5a3400-3589-11eb-8f2e-c852b64eb442.png)

After change via UI:

![image](https://user-images.githubusercontent.com/4473094/101062480-99ad5f80-3589-11eb-9fcb-a6761605d9a8.png)

After Undo button pressed:

![image](https://user-images.githubusercontent.com/4473094/101062519-a467f480-3589-11eb-8f14-643c10ed262e.png)

I know the value is actually being changed correctly in code, because if I close the panel containing the form and re-open it the value is back to what I would expect it to be. Therefore I think it's a bug with the component and how it detects a change to the hours portion of the time value.

#### Observed Behavior

The time portion should change to reflect the current value in state, both hours and minutes.

#### Steps to Reproduce

Code to recreate issue:

``` javascript
interface Entity {
  dateTimeField: Date;
}

const defaultEntityState = {
  dateTimeField: new Date('October 17, 2020 13:12:00')
};

const ChildComponent: React.FC = () => {
  const [entity, setEntity] = React.useState<Entity>(defaultEntityState);
  
  const onFieldChange = (name: string) => (value: any) => {
    setEntity({
      ...entity, [name]: value
    });
  }
  
  const revertTimeToDefault = (_e) => {
    setEntity(defaultEntityState);
  }
  
  const fieldValue = entity && entity.dateTimeField;
  
  return (
    <>
      <button onClick={revertTimeToDefault} type="button">Revert DateTime</button>
      <DateTimePicker
        firstDayOfWeek={DayOfWeek.Monday}
        strings={DayPickerStrings}
        placeholder="Select a date..."
        showLabels
        dateConvention={DateConvention.DateTime}
        timeConvention={TimeConvention.Hours24}
        timeDisplayControlType={TimeDisplayControlType.Dropdown}
        onChange={onFieldChange('dateTimeField')}
        value={fieldValue instanceof Date ? fieldValue : null}
        />  
    </>
  );
}
```

`DayPickerStrings` is just the set of labels:

``` javascript
const DayPickerStrings: IDateTimePickerStrings = {
    dateLabel: 'Date',
    timeLabel: 'Time',
    timeSeparator: ':',
    amDesignator: 'AM',
    pmDesignator: 'PM',
    months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
    shortMonths: [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec',
    ],
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    shortDays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    goToToday: 'Go to today',
    prevMonthAriaLabel: 'Go to previous month',
    nextMonthAriaLabel: 'Go to next month',
    prevYearAriaLabel: 'Go to previous year',
    nextYearAriaLabel: 'Go to next year',
};
```

**Comment by AJIXuMuK** [comment]
Thank you @BreakfastMaintenance for reporting this!

The fix has been done and will be included in the next release.

In a meanwhile you can test it in the [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
