### ISSUE TITLE
Taxonomy Picker Control - Onchange event behavior

### ISSUE THREAD

**Issue by mahinthan** [pnp/sp-dev-fx-controls-react#761]
#### Category
[x ] Enhancement
[ ] Bug
[ x] Question

#### Version
Please specify what version of the library you are using: [    1.20.0    ]

#### Question
I'm using taxonomy picker control. While selecting terms from the panel, onchange event fires only when I click on Save from the footer. Can it be configured to fire the onchange event as the user select the terms?

#### Observed Behavior

- While I'm on panel, onchange event fires only when I click on save button from footer
- When I'm not using the panel, but selecting terms by typing in the autocomplete control, onchange event fires for every term selection
- I've used the termActions to display a label next to each term, so that user can click on that to select terms. It does fires the actionCallback event. Since, both custom action label and checkbox of terms are displayed, user may be confused, in which way to select the term.  Because selecting via custom action label, fires the event, while the checkbox selection does not fire the event.

**Comment by AJIXuMuK** [comment]
Hi @mahinthan,
Thank you for bringing this up!

I don't think `onChange` should fire when a user selects item in the panel. `onChange` fires when the values are changed in the picker. In the panel user can click **Cancel** instead of Save, and nothing will be changed in the picker in that case.

We can potentially add some additional handler like `onPanelTermSelected` or something.

**Comment by mahinthan** [comment]
Hi @AJIXuMuK ,

Thank you for the quick update.

I'm using this taxonomy picker control as a filter control. It means, I'm having a PnP ListView control displayed. Instead of showing the default filter available from ListView control, we are showing the taxonomy control, so that users can use that control/taxonomy control panel to filter items displayed on the ListView.

**Comment by AJIXuMuK** [comment]
Hi @mahinthan,

I've added `onPanelSelectionChange` property to the control. You can use it to get items while user selecting them in the panel, before Click or Save is clicked.
The changes will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by mahinthan** [comment]
Thanks @AJIXuMuK
