### ISSUE TITLE
Taxonomy Picker Control : Select Child items automatically

### ISSUE THREAD

**Issue by mahinthan** [pnp/sp-dev-fx-controls-react#765]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

Please specify what version of the library you are using: [   1.20.0     ]

#### Question
I'm using taxonomy picker control. When terms are heirarchical, while selecting the parent term, its not automatically selecting the child terms underneath that parent term.
I read AnchorId to be used to achieve. Do you have any working sample/etc to show how it can be used?

#### Observed Behavior
![image](https://user-images.githubusercontent.com/8817638/102063872-e1887e00-3df6-11eb-84f5-3d2f94137b82.png)

**Comment by AJIXuMuK** [comment]
Thank you @mahinthan for providing the feedback!

I've implemented the change - you can use `selectChildrenIfParentSelected` property of the `TaxonomyPicker`.
The change will be included in the next release.

In a meanwhile you can test the functionality [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by mahinthan** [comment]
Thanks @AJIXuMuK
