### ISSUE TITLE
People Picker should have ability just to display inactive users name (ideally the value fetched from 'Author/Title')

### ISSUE THREAD

**Issue by sankarkumar23** [pnp/sp-dev-fx-controls-react#768]
Enhancement.

People Picker should have the ability to assign the person (IPersonaProps) directly. This is useful just to display the inactive users when you have people picker in Edit form.. Just like how SharePoint lists users in Person column even the users' accounts are no longer valid.

Currently I am forced to show blank when you Edit the form this is very confusing to the end users.

We can fetch username from user field though the user is inactive.. for ex: (_api/web/lists('listid here')/items(1)?$select=ID,Author%2FTitle&expand=Author). This 'Title' would be displayed in OOB people picker box though the user is not active. Similarly we should also be able to assign the value to the PnP's people picker control.

Otherwise again we need to depend on NormalPeoplePicker to achieve this behavior.

This is somewhat related to the below issue
#https://github.com/SharePoint/sp-dev-docs/issues/5970
We all know SharePoint does not resolve the inactive users.. its SharePoint behavior.. nothing we can do there..
The issue can be resolved if we can provide the ability to display the username in the picker's textbox.

Here is my thought for fix.
Change the defaultSelectedUsers property from string or IPersonaProps
Ideally inactive users email would be null in OOB SharePoint... When email is null/empty just display the given 'initials' and 'text'.. if email has value just continue the current functionality. Basically apply filter to 'selectedPersons' and play around.

Of course.. need to update the document...on how to bind inactive users?

**Comment by sankarkumar23** [comment]
Can this be triaged quickly? This is a basic requirement and without this the control cannot be used for Edit forms. It's pretty much limited to for New Forms. Also, appears many people are looking for this implementation. Appreciate your response soonest.

**Comment by sympmarc** [comment]
@sankarkumar23 - Understand that this is an open source effort and everyone here volunteers their time to create these resources. You're also asking right in the middle of a time of year when many people are taking time off to spend the holidays with their families. The team here will take a look at this when they can. If your request seems as if it will benefit the larger community, they may implement it. Reminder: open source means you can contribute the fix/change, too.

**Comment by sankarkumar23** [comment]
I made the fix and created a pull request. Please review and accept if fix makes sense.
Currently the defaultSelectedUsers is accepting email or login name in string [].. I just extended it to accept the user title along with an append '|inactive'. So if string endswith '|inactive' it will be exclude it from the people search but still binds it to the control.

for example, assume if you you have an defaultPerson object with two properties email and title (user name of the inactive user) it can be assigned as shown below.
defaultSelectedUsers={this.props.defaultPerson.map(e => e.email || `${e.title}|inactive`)}

**Comment by sankarkumar23** [comment]
I made the fix and created a pull request. Please review and accept if fix makes sense.
Currently the defaultSelectedUsers is accepting email or login name in string [].. I just extended it to accept the user title along with an append '|inactive'. So if string endswith '|inactive' it will be exclude it from the people search but still binds it to the control.

for example, assume if you you have an defaultPerson object with two properties email and title (user name of the inactive user) it can be assigned as shown below. The email should be empty for inactive users.
defaultSelectedUsers={this.props.defaultPerson.map(e => e.email || `${e.title}|inactive)`}

**Comment by AJIXuMuK** [comment]
Thank you @sankarkumar23  for reporting this one and creating a PR.

**Comment by sankarkumar23** [comment]
> Thank you @sankarkumar23 for reporting this one and creating a PR.

@AJIXuMuK - Could you please push #773 also to 2.4.0

**Comment by sankarkumar23** [comment]
@AJIXuMuK - I have enhanced the fix as previous fix forces to verify the user is active or inactive before hand. With this new code if user is not found, ideally inactive user, the appended title will be shown. Appreciate your review. Also please see if this change can be pushed with 2.4.0 

Still got a punch because of https://github.com/pnp/pnpjs/issues/778. EMail is not available (in expand) for userfield with multi-select. Either you get email from sp.web.getUserById(id#) or just settle with Title field. If usefield is not multi-select there is no need to call sp.web.getUserById since "expand" itself provides both Title and EMail.

defaultSelectedUsers={["test@test.com/usertitle"]} //email can be active or inactive user's.
or
defaultSelectedUsers={["/usertitle"]} // this also works and just binds the title.

**Comment by AJIXuMuK** [comment]
Hi @sankarkumar23,

I've merged your latest update.

**Comment by sankarkumar23** [comment]
Thank you @AJIXuMuK.
