### ISSUE TITLE
Question about versions and npm

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#781]
@aaclage @estruyf  @joelfmrodrigues @Abderahman88 

#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version
That's the question :)  I'm just trying to get the update an older project to fix #576.

#### Expected / Desired Behavior / Question
I am trying to update my project because I need #576 change implemented to fix my issue.
According to that change, I need to be at 1.19 or later.

When I run these npm commands, I would expect it to update the package.json as well.
```bash
npm uninstall @pnp/spfx-controls-react
npm install @pnp/spfx-controls-react@1.21.1 --save --save-exact
```

#### Observed Behavior
Unless I'm doing something wrong, this is what it shows when I do that.
Why does it show dependencies of
"@pnp/spfx-controls-react": "^1.2.2",

Note that in my screenshot I'm showing I was updating a sample from spfx-webparts repo... I tried both my own project and after getting a similar result, I tried to update the sample repo.

![image](https://user-images.githubusercontent.com/49648086/104043215-7f2e5d80-51a9-11eb-96dd-fe0090735899.png)

#### Steps to Reproduce

```bash
npm uninstall @pnp/spfx-controls-react
npm install @pnp/spfx-controls-react@1.21.1 --save --save-exact
```

**Comment by AJIXuMuK** [comment]
Hi @mikezimm,

My only assumption is you're running the commands in another folder. Meaning you're updating some other project.

May it be the case?

**Comment by mikezimm** [comment]
@AJIXuMuK , you are 100% correct!  I looked at it 3 times and did not realize it.

A simple follow-up if I'm allowed,

Is there any substantial difference (in function or feature) between v1 and v2 in functionality outside of just compatibility with v1.11 projects?  Or do you add the same updates to both versions of the library?

Thanks again for the answer!

**Comment by AJIXuMuK** [comment]
@mikezimm,

v2 is more functional than v1. 
We're not actively adding functionality to v1 anymore - only by request.
Currently v2 already has some new components (for example [Dashboard](https://pnp.github.io/sp-dev-fx-controls-react/controls/Dashboard/)) that are not available in v1, and there are no plans to include them in v1.

**Comment by mikezimm** [comment]
@AJIXuMuK are bug fixes applied to both (assuming they have the same issue)?

Feel free to close with comment.

And again thank you for your answers

**Comment by AJIXuMuK** [comment]
@mikezimm - bug fixes are also added to v1 upon request.
