### ISSUE TITLE
After installation of version 2.3.0, File Picker is throwing error

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/sp-dev-fx-controls-react#782]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.3.0]

#### Expected / Desired Behavior / Question
I used following code from the git hub page :

import { FilePicker, IFilePickerResult } from '@pnp/spfx-controls-react/lib/FilePicker';
<FilePicker
          // bingAPIKey="<BING API KEY>"
          accepts={[".gif", ".jpg", ".jpeg", ".png"]}
          buttonIcon="FileImage"
          buttonLabel="Select image file for background"
          hideLinkUploadTab={false}
          hideLocalUploadTab={true}
          hideOneDriveTab={false}
          hideOrganisationalAssetTab={false}
          hideRecentTab={false}
          hideSiteFilesTab={false}
          hideStockImages={false}
          hideWebSearchTab={false}
          onSave={(filePickerResult1: IFilePickerResult) => { onChangeFilePicker(filePickerResult1); }}
          onChanged={(filePickerResult2: IFilePickerResult) => { onChangeFilePicker(filePickerResult2); }}
          context={props.contextWP}
        />}

Previously it was working fine in older version.

#### Observed Behavior
I have installed new version for a project in new SPFx project & it is thorowing error :
` Property 'onChanged' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FilePicker> & Readonly<IFilePickerProps> & Readonly<{ children?: ReactNode; }>'.`

#### Steps to Reproduce
Just installed 2.3.0

**Comment by AJIXuMuK** [comment]
Hello @gauravgoyal5,

You're probably updating from `v1` controls to `v2`.

Please, read the [Migrating from v1 to v2](https://pnp.github.io/sp-dev-fx-controls-react/guides/migrate-from-v1/) documentation as it describes breaking changes.
One of the breaking changes is renamed `onChange` handler.

**Comment by gauravgoyal5** [comment]
Hello @AJIXuMuK ,

I am using v2 with following dependencies & dev dependencies 
"dependencies": {
    "@fluentui/react": "7.145.0",
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-http": "1.11.0",
    "@microsoft/sp-lodash-subset": "^1.11.0",
    "@microsoft/sp-page-context": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/graph": "^2.0.13",
    "@pnp/pnpjs": "^2.0.13",
    "@pnp/sp": "^2.0.13",
    "@pnp/logging": "^2.0.13",
    "@pnp/spfx-controls-react": "^2.3.0",
    "@pnp/spfx-property-controls": "2.2.0",
    "mdbreact": "4.25.0",
    "office-ui-fabric-react": "7.145.0",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  },
  "devDependencies": {
    "@microsoft/microsoft-graph-types": "^1.12.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@types/bootstrap": "^4.3.0",
    "@types/chai": "3.4.34",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.3.35",
    "@types/mocha": "2.2.38",
    "@types/moment-timezone": "^0.5.13",
    "@types/node": "^12.0.12",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/sharepoint": "^2016.1.8",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "gulp-sequence": "1.0.0",
    "moment": "^2.24.0",
    "moment-timezone": "0.5.25",
    "webpack-bundle-analyzer": "^3.8.0"
  }
but still getting same issue.

**Comment by AJIXuMuK** [comment]
Hello @gauravgoyal5 
You have updated from `v1` to `v2`. 
There is a breaking change - `onChanged` renamed to `onChange`. 
Please, reference the migration doc I mentioned in the previous comment.
