### ISSUE TITLE
Gulp Bundle shows many warnings

### ISSUE THREAD

**Issue by PavelBrokhman** [pnp/sp-dev-fx-controls-react#784]
For more than 2 years we have used package which includes several web parts in it. 
We have decided to update one of the web part and use @pnp/sp module. When we used gulp bundle we got a lot warnings similar to below one. Code itself is working and we are getting proper results. Should we ignore those warnings?

`[33m./node_modules/@pnp/sp/items/index.js[39m
[33mModule Warning (from ./node_modules/source-map-loader/index.js):[39m
[33m(Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/index.ts': Error: Can't resolve '../../../../../packages/sp/items/index.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33mNonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/index.ts': Error: Can't resolve '../../../../../packages/sp/items/index.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33m    at emitWarning (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\lib\NormalModule.js:154:16)[39m
[33m    at C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\source-map-loader\index.js:80:7[39m
[33m    at doResolve (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:184:12)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn0 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)[39m
[33m    at resolver.doResolve (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn0 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn0 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)[39m
[33m    at resolver.doResolve (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn42 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn1 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m @ ./lib/webparts/webPartContentEditor/components/ScriptEditor.js 58:0-23[39m
[33m @ ./lib/webparts/webPartContentEditor/WebPartContentEditorWebPart.js[39m
[33m./node_modules/@pnp/sp/items/list.js[39m
[33mModule Warning (from ./node_modules/source-map-loader/index.js):[39m
[33m(Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/list.ts': Error: Can't resolve '../../../../../packages/sp/items/list.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33mNonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/list.ts': Error: Can't resolve '../../../../../packages/sp/items/list.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33m    at emitWarning (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\lib\NormalModule.js:154:16)[39m
[33m    at C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\source-map-loader\index.js:80:7[39m`

#### Category
[ ] Enhancement

[X] Bug

[nodX] Question

#### Version
v10.22.0
PS C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise> npm -- version

{ 'sp-enterprise': '0.0.1',
  npm: '6.14.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  modules: '64',
  napi: '6',
  nghttp2: '1.41.0',
  node: '10.22.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '6.8.275.32-node.58',
  zlib: '1.2.11' }
PS C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise> npm ls -g --depth=0 @microsoft/generator-sharepoint

C:\Users\pbrokhman\AppData\Roaming\npm
`-- @microsoft/generator-sharepoint@1.11.0 

#### Observed Behavior
When I have created new web part and used @pnp/sp logic with similar functionality as the updated web part, there was no such warnings. 

#### Steps to Reproduce
No idea.

**Comment by AJIXuMuK** [comment]
Hello @PavelBrokhman,

Seems like you're having issue with PnPJS, not PnP Reusable Controls.
PnPJS has [it's own repo](https://github.com/pnp/pnpjs/tree/version-2).
It also has a [Transition Guide](https://pnp.github.io/pnpjs/transition-guide/) documentation on how to update from `v1` to `v2`. Maybe, it is your case.
If not - please, submit a new issue in the PnPJS repo.

Thanks!
