### ISSUE TITLE
Chart Component not using Theme Colors

### ISSUE THREAD

**Issue by coreyroth** [pnp/sp-dev-fx-controls-react#785]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.4.0        ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Use of theme colors in charts.

#### Observed Behavior
According to the documentation, it says the chart component will try to use your current theme colors by default.  However, in every case I have tried it appears to be using the OfficeColorful1 palette. 

[Screenshot](https://unlimitedviz-my.sharepoint.com/:i:/p/corey/EVhWxHQqjItDtq8U8LC4dL4BL8Oric0uIU4vs00RKJJi7Q?e=NtHw9K)

#### Steps to Reproduce
I have tried using useTheme={true}.  I don't have any colors specified.

Here is the data parameter I am using:
`      this.setState({
        data: {
          labels: telemetryData.map(item => { return item.name; }),
          datasets: [
            {
              label: this.props.title,
              data: telemetryData.map(item => { return item.value; })
            }
          ]
        },
      });`

Here is the use of the component:
`<ChartControl type={ChartType.Doughnut} data={this.state.data} useTheme={true} />`

I don't believe I am doing anything wrong here, but maybe I am.  I might also be misunderstanding how the theme colors will be used.

**Comment by AJIXuMuK** [comment]
Hi @coreyroth,

According to the documentation

> By default, the ChartControl will attempt to use the environment theme colors and fonts for elements such as the chart background color, grid lines, titles, labels, legends, and tooltips. This includes support for dark themes and high contrast themes.

So, it does not use theme colors for the palette.
