### ISSUE TITLE
Webparts (having @pnp/spfx-property-controls installed in the solution) that have dependencies on library components that use the @pnp/spfx-controls-react package fail on gulp serve

### ISSUE THREAD

**Issue by ishanisuchak** [pnp/sp-dev-fx-controls-react#786]
#### Category
[ ] Enhancement

[ * ] Bug - [SPFXControlsReactError.zip](https://github.com/pnp/sp-dev-fx-controls-react/files/5848811/SPFXControlsReactError.zip)

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.21.1     ]

#### Expected / Desired Behavior / Question
The SPFx solution should build successfully if using the pnp spfx-controls

#### Observed Behavior
**Issue**

Webparts (having @pnp/spfx-property-controls installed in the solution) that have dependencies on library components that use the @pnp/spfx-controls-react package fail on gulp serve

**Error message**

Cannot find module 'ControlStrings'

**Observation**

This happens because the library component is trying to find the 'ControlStrings' its in own node_modules, which is absent because the @pnp/spfx-controls-react package is available as a dependency in the webpart node_modules itself.

#### Steps to Reproduce
1. Download and Unzip the attached solution
2. Run the following commands:

    ```powershell
    1. cd path-to-solution\LibraryComponent\
    2. npm install
    3. gulp bundle --ship
    4. npm link
    5. cd ..\Webpart
    6. npm install
    7. npm link path-to-solution\LibraryComponent\
    8. gulp serve
    ```

3. To remove the error, comment the lines indicated in the HelloWorld.tsx file

**Comment by AJIXuMuK** [comment]
Hi @ishanisuchak,
Thank you for reporting this one!

I don't think we can actually do something on our side for such a situation.

You can fix it manually by adding the next line in you web part's config under `localizedResources`:

```json
"ControlStrings": "node_modules/library-component/node_modules/@pnp/spfx-controls-react/lib/loc/{locale}.js"
```

It should make the trick.
