### ISSUE TITLE
ChartControl - any ideas on how to duplicate the github activity grid?

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-controls-react#790]
@hugoabernier 

#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Expected / Desired Behavior / Question
Does anyone have a good idea on how to make something like the github activity chart?

![image](https://user-images.githubusercontent.com/49648086/105745216-0a2e8800-5f0c-11eb-8890-75070b83cd95.png)

**Comment by mikezimm** [comment]
I did see this post which shows in theory how to do it.  Maybe I will give it a try.

https://bitsofco.de/github-contribution-graph-css-grid/

**Comment by AJIXuMuK** [comment]
@mikezimm I don't think we have such an ability in the library.

As you have correctly mentioned, you can do this with external libs and code examples.

Closing the issue as not related to the PnP controls.
