### ISSUE TITLE
TreeView - onSelect on click of text

### ISSUE THREAD

**Issue by Bhushan12986** [pnp/sp-dev-fx-controls-react#793]
#### Category
[x] Enhancement

[x] Bug

[x] Question

#### Version

Please specify what version of the library you are using: 2.4.0

#### Expected / Desired Behavior / Question
On click of tree node text OnSelect event should trigger.

#### Observed Behavior
On click of tree node text OnSelect event does not get triggered.

#### Steps to Reproduce
Create a sample tree using [this](https://pnp.github.io/sp-dev-fx-controls-react/controls/TreeView/) link without check boxes and selection mode to single.
Implement onSelect event, click on tree node text to check if onSelect event works or not on the click of text.

Sample
`<TreeView
        items={this.state.TreeLinks}
        defaultExpanded={false}
        selectionMode={TreeViewSelectionMode.Single}
        selectChildrenIfParentSelected={true}
        showCheckboxes={false}
        treeItemActionsDisplayMode={TreeItemActionsDisplayMode.Buttons}
        onSelect={this.onTreeItemSelect}
        onExpandCollapse={this.onTreeItemExpandCollapse}
        onRenderItem={this.renderCustomTreeItem}
      />`

Thanks!

**Comment by kunj-sangani** [comment]
Hi @Bhushan12986 ,

This is because the control is not rendering items hence when using Custom rendering for the TreeItem i.e.
onRenderItem={this.renderCustomTreeItem}

To allow the text to be clicked you need to use code something related to as mentioned in below sample code or do not use custom rendering of tree item

```
private renderCustomTreeItem(item: ITreeItem): JSX.Element {
    return (
      <span onClick={() => console.log(item)}>
        {
          item.iconProps &&
          <i className={"ms-Icon ms-Icon--" + item.iconProps.iconName} style={{ paddingRight: '4px' }} />
        }
        {item.label}
      </span>
    );
  }
  ```

Hope this helps you

**Comment by AJIXuMuK** [comment]
Marked as answered.
