### ISSUE TITLE
New control: Item Comments

### ISSUE THREAD

**Issue by ystetsyuk** [pnp/sp-dev-fx-controls-react#794]
#### Category
[ X] Enhancement

Recently a new feature was released for SharePoint Online: Comments for list item.
I am wondering whether you have any upcoming plans to develop a similar react component for viewing comments of a list item and with the ability to post a new comment as well?

**Comment by AJIXuMuK** [comment]
We don't have any particular plans for that.
But we're always very open for PRs :)

**Comment by kunj-sangani** [comment]
Hi @AJIXuMuK ,

Can you please assign this task to me I can add a new component and you can verify it and provide feedback

**Comment by AJIXuMuK** [comment]
@kunj-sangani - done!

**Comment by joelfmrodrigues** [comment]
Hey @kunj-sangani, I completely missed this issue and the fact that it was assigned to you...
I have recently reviewed a PR for this control. Could you please check it out?
If you were already working on the control (and I am really sorry if that was the case), perhaps we could add any additional features that your version has as upgrades to the existing one?

**Comment by AJIXuMuK** [comment]
Implemented a while ago.
