### ISSUE TITLE
[Rich Text]- Problem with bullets and number list

### ISSUE THREAD

**Issue by pk091990** [pnp/sp-dev-fx-controls-react#795]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.3.0 ]

#### Expected / Desired Behavior / Question
Bullets and Number list should work properly.

#### Observed Behavior
When I'm using Number list first time then it works fine. But If I'll write some more text or delete the previous text and try to use the number list second time on the same webpart then it doesn't work. I have to select bullets first and then number list.
Similar case is happening if I'm selecting bullets first instead of number.

![image](https://user-images.githubusercontent.com/46436213/106995820-bd696d80-67a5-11eb-8e91-836ee25d4882.png)

#### Steps to Reproduce
Add new webpart
Write some text and give numbering or bullets. It will work for the first time
Delete the text and again try to give the same you've given earlier either numbers or bullets
OR
Type some more text like I did in the above screenshot and try to give the same you've given earlier either numbers or bullets. It won't work.

Thanks!

**Comment by AJIXuMuK** [comment]
Thank you @pk091990 for reporting this one!

The fix has been implemented and will be included in the next release.
In a meantime you can test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Comment by pk091990** [comment]
Hi @AJIXuMuK , 
Mentioned issue has been fixed in the recent published 2.6.0 version. However notice another issue with rich text in this version . It was working fine with earlier version i.e. 2.3.0

Mentioning repro steps here. Let me know if you are able to repro it and I need to raise a separate issue for the same:

1: Add Rich text webpart
2: Copy paste any text and click outside of your webpart. 
3: Text will disappear with below error in console.
![image](https://user-images.githubusercontent.com/46436213/114008043-808e2580-987f-11eb-9144-fe1248e41956.png)
Debug:
![image](https://user-images.githubusercontent.com/46436213/114008388-d06cec80-987f-11eb-9ee4-3189f3ffd34c.png)

4: Its working fine if I'm manually writing any text instead of copy/paste.

**Comment by AJIXuMuK** [comment]
Hi @pk091990 - could you please open a separate issue for this one?

**Comment by pk091990** [comment]
> Hi @pk091990 - could you please open a separate issue for this one?

Raised [here](https://github.com/pnp/sp-dev-fx-controls-react/issues/877)

**Comment by rpuvvala-chwy** [comment]
In html file, i have added this tag<ejs-richtexteditor #toolsRTE id='alltoolRTE' [(value)]='contentValue' [toolbarSettings]='tools'>

            </ejs-richtexteditor>.
content value has email template info


I am trying to use bullet list and number list  . I place the cursor on 7th line, and click o bullet list, but i see the bullet is showing on first line, same with the number
