### ISSUE TITLE
SecurityTrimmedControl - Hide component user group

### ISSUE THREAD

**Issue by keerthivasu** [pnp/sp-dev-fx-controls-react#796]
**SecurityTrimmedControl** - Is there way to hide components based on the user specific groups in site using the pnp SecurityTrimmedControl

**Comment by kunj-sangani** [comment]
Hi @keerthivasu ,

Currently SecurityTrimmedControl only supports trimming based on Permission and not on group name

**Comment by joelfmrodrigues** [comment]
@keerthivasu as mentioned by @kunj-sangani,  the control does not support this at the moment but we would be happy to receive a PR if you have the chance to extend the control and contribute back 😀
Closing the item
