### ISSUE TITLE
ListView Selection - setState 

### ISSUE THREAD

**Issue by jaxnz** [pnp/sp-dev-fx-controls-react#798]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [v2.4.0]

#### Expected / Desired Behavior / Question
Expecting selection icons to hold state  

#### Observed Behavior
On selection - calling setState in _getSelection re-renders the selection icons - so they don't show up as selected - ant cannot be selected again

#### Steps to Reproduce

Same issue as #11 

```
  private _getSelection = (items: any[]) => {
    console.log('Selected items:', items);
    this.setState({
      selected: true,
    });
  }
```

```
<ListView
          key={'main'}
          items={this.state.items}
          viewFields={viewFields}
          compact={true}
          selectionMode={SelectionMode.multiple}
          selection={this._getSelection}
          showFilter={true}
          filterPlaceHolder="Search Policies..."
          dragDropFiles={true}
          onDrop={this._getDropFiles}
          stickyHeader={true} />
```

Thanks!

**Comment by jaxnz** [comment]
Still getting this issue - any help?

**Comment by AJIXuMuK** [comment]
@jaxnz the issue is still in Triage mode, meaning we haven't looked into it yet.

**Comment by AJIXuMuK** [comment]
Hi @jaxnz,

I cannot reproduce the issue using the code you've provided.
[listview-selection.zip](https://github.com/pnp/sp-dev-fx-controls-react/files/6013922/listview-selection.zip)


If you are controlling the items/selection state from your component you can also try [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) as we were recently fixing some issues with `ListView` selection.

**Comment by jaxnz** [comment]
Sorry for the late reply, I can confirm updating to the beta fixed the issue.

**Comment by Zerg00s** [comment]
Same issue, but installing beta with `npm install @pnp/spfx-controls-react@next --save` fixed it. thank you, @AJIXuMuK
