### ISSUE TITLE
pnp/sp PeoplePicker

### ISSUE THREAD

**Issue by matjazreberc** [pnp/sp-dev-fx-controls-react#800]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

2.4.0 Version

Please specify what version of the library you are using: [   2.4.0      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

Hello!

I have question about pnp/sp PeoplePicker.
PeoplePicker has property "required", but wen i use it in my form it is ignored.

This is my PeoplePicker code:
<PeoplePicker
                                    required={true}
                                        context={this.props.spContext}
                                        personSelectionLimit={1}
                                        onChange={this.hcRequestorPP}
                                        showHiddenInUI={false}
                                        principalTypes={[PrincipalType.User]}
                                        ensureUser={true}
                                        resolveDelay={1000}
                                        defaultSelectedUsers={this.props.pRequestor} 
                                        disabled={false}
                                        
                                        />

What am i doing wrong?

Thank you, Matjaz Reberc

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @matjazreberc,

The `required` flag, similarly to Fluent UI components, just specifies if the control renders with `*` in the label. It doesn't activate any validation or "blocking" of external form.

You should handle `onChange` event and implement the logic to disable the "Submit" button of your form if needed.

You can additionally use `errorMessage` or `onGetErrorMessage` props to provide error message for the situation when the picker is empty.

**Comment by matjazreberc** [comment]
Hello AJIXuMuK , thank you for you anwser. I find this "required" little confusing. Thank you, Matjaz
