### ISSUE TITLE
PeoplePicker with disabled={true} allows removal of items in it

### ISSUE THREAD

**Issue by evlo** [pnp/sp-dev-fx-controls-react#802]
#### Category
[ ] Enhancement
[ x ] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.21.1 ]

#### Expected / Desired Behavior / Question
PeoplePicker with `disabled={true}` will not allow deleting of users/groups

#### Observed Behavior
PeoplePicker with `disabled={true}` will shows "x" button that allows users to remove items (users/groups) from it

#### Steps to Reproduce
create PeoplePicker with `disabled={true}` and add user to it programmatically assigning to **defaultSelectedUsers** property

**Comment by AJIXuMuK** [comment]
Hi @evlo,

This is a know problem with Office UI Fabric v5 Picker.
You need to update to `v2` of the library where we use OUIFR v6. The issue is fixed there.
