### ISSUE TITLE
Treeview: Expand Nodes to selected node

### ISSUE THREAD

**Issue by mk0023** [pnp/sp-dev-fx-controls-react#804]
**Category**
[ ] Enhancement

[x] Bug

[] Question

**Version**

Please specify what version of the library you are using: [2.4.0]

**Expected / Desired Behavior / Question**
The Treeview control has a property "expandToSelected" which is described in the documentation as follows: "Specifies if the tree view is expanded to display selected nodes."

Setting this property to true causes the treeview to expand all nodes on the path to the currently selected node AND also expands the selected node itself if it has any children. 

In my opinion the selected node itself should not be expanded. Only the parent nodes, so that the selected node becomes visible.

Many thanks in advance.

**Comment by joelfmrodrigues** [comment]
@mk0023 thanks for reporting this. I agree that this seems like a bug as I was also not expecting the last selected node to be expanded when expandToSelection is set to true.
Took me a while to get into the logic, but I think this is now fixed on [this branch](https://github.com/pnp/sp-dev-fx-controls-react/tree/bug/804). Any chance you could test it?

@AJIXuMuK could you please also review my comments below to make sure that I am not changing how the control should work?

Properties that impact expand behaviour:

- defaultExpanded
- defaultExpandedChildren
- expandToSelected

When all set to false:
``` HTML
<TreeView items={this.treeitems}
    defaultExpanded={false}
    selectionMode={TreeViewSelectionMode.Multiple}
    showCheckboxes={true}
    treeItemActionsDisplayMode={TreeItemActionsDisplayMode.ContextualMenu}
    defaultSelectedKeys={this.state.treeViewSelectedKeys}
    onExpandCollapse={this.onExpandCollapseTree}
    onSelect={this.onItemSelected}
    defaultExpandedChildren={false}
    expandToSelected={false}
  // onRenderItem={this.renderCustomTreeItem}
/>
```

Result: 
![image](https://user-images.githubusercontent.com/19577724/111853490-2bf82a00-8913-11eb-8532-ec3894924e8f.png)


When defaultExpanded set to true, but defaultExpandedChildren set to false, only the root level is expanded
``` HTML
<TreeView items={this.treeitems}
    defaultExpanded={true}
    selectionMode={TreeViewSelectionMode.Multiple}
    showCheckboxes={true}
    treeItemActionsDisplayMode={TreeItemActionsDisplayMode.ContextualMenu}
    defaultSelectedKeys={this.state.treeViewSelectedKeys}
    onExpandCollapse={this.onExpandCollapseTree}
    onSelect={this.onItemSelected}
    defaultExpandedChildren={false}
    expandToSelected={false}
  // onRenderItem={this.renderCustomTreeItem}
  />
```

Result:
![image](https://user-images.githubusercontent.com/19577724/111853550-59dd6e80-8913-11eb-829d-8b4294c130b8.png)

When defaultExpanded set to true, and defaultExpandedChildren also set to true, all levels are expanded
``` HTML
  <TreeView items={this.treeitems}
    defaultExpanded={true}
    selectionMode={TreeViewSelectionMode.Multiple}
    showCheckboxes={true}
    treeItemActionsDisplayMode={TreeItemActionsDisplayMode.ContextualMenu}
    defaultSelectedKeys={this.state.treeViewSelectedKeys}
    onExpandCollapse={this.onExpandCollapseTree}
    onSelect={this.onItemSelected}
    defaultExpandedChildren={true}
    expandToSelected={false}
  // onRenderItem={this.renderCustomTreeItem}
  />
```

Result:
![image](https://user-images.githubusercontent.com/19577724/111853650-d1130280-8913-11eb-8760-ff59632d55be.png)


When expandToSelected set to true, and both defaultExpanded and  defaultExpandedChildren set to false, all levels are expanded only up to the selected items
``` HTML
  <TreeView items={this.treeitems}
    defaultExpanded={false}
    selectionMode={TreeViewSelectionMode.Multiple}
    showCheckboxes={true}
    treeItemActionsDisplayMode={TreeItemActionsDisplayMode.ContextualMenu}
    defaultSelectedKeys={this.state.treeViewSelectedKeys}
    onExpandCollapse={this.onExpandCollapseTree}
    onSelect={this.onItemSelected}
    defaultExpandedChildren={false}
    expandToSelected={true}
  // onRenderItem={this.renderCustomTreeItem}
  />
```

Result:
![image](https://user-images.githubusercontent.com/19577724/111853759-3c5cd480-8914-11eb-9c30-e8cd86cdecb2.png)

**Comment by AJIXuMuK** [comment]
@joelfmrodrigues - it seems like a correct behavior for me.

**Comment by mk0023** [comment]
@joelfmrodrigues: Great - Thank you very much for investigating and fixing this. I can confirm that your implementation now behaves as I would expect concerning the expansion of selected nodes.

An alternative fix I implemented locally would be to change the pathTo method in "TreeView.tsx" as shown in the following code, so that the target node itself does not get pushed to the nodesToExpand array.

```
private pathTo = (array: ITreeItem[], target: string): string => {

    let result: string;
    array.some(({ key, children = [] }) => {
      if (key === target) {
        // Remove the following line to no longer add the selected node itself to the array of nodes to expand.
        // this.nodesToExpand.push(key);
        result = key;
        return true;
      }
      let temp = this.pathTo(children, target);
      if (temp) {
        this.nodesToExpand.push(key);
        result = key + '.' + temp;
        return true;
      }
    });
    return result;
  }
```

I did not dive too deeply into the codebase so i am not sure what the better fix is...

**Comment by joelfmrodrigues** [comment]
@mk0023 Thanks, your approach is definitely better. I was trying to fix an issue, but you prevent it from happening 👍
Updated the branch with your code and get exactly the same result on my tests so will merge into dev-v2 and add you to the list of contributors for the next release

**Comment by mk0023** [comment]
@joelfmrodrigues: Great to hear!:-) Thank you very much!
