### ISSUE TITLE
ListItemPicker with 2 fields

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#805]
#### Category
[ ] Enhancement

[?] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 2.4.0  ]

I tried to use a calculated field as columnInternalName named "Project" The calculation is `=ProjectNumber&" "&Title 
`

#### Observed Behavior
It does not show any items "No data"

#### Steps to Reproduce
Make a calculated field and use it as columnInternalName 

Please make it work with Concatenation of fields or a calculated field.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @Ofer-Gal,
Thank you for reporting this one!

The enhancement has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.5.0` has been released.

**Comment by Ofer-Gal** [comment]
Thank you
