### ISSUE TITLE
ListView side by side 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#806]
Looking for a way (example?) to have 2 ListView side by side with option to drag and drop from left to right

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [   2.4.0    ]

#### Expected / Desired Behavior / Question
each ListView in half the width showing full height with headers. And the ability to drag and drop from one to the next.

#### Observed Behavior
Using office-ui-fabric-react Stack horizontal I get them side by side but it does not show in the right place and very short height and no header.
turns out the drop is only for files from explorer. Why not have an event to Drop from another ListView?

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @Ofer-Gal,

For now there is no way to "drag" files for `ListView` as the control is not in charge what data is currently displayed.

Will some event (like `onDragStart`) be enough for you?

**Comment by Ofer-Gal** [comment]
I think it will do if I get what was dragged.
thanks
