### ISSUE TITLE
New control : Animated dialog

### ISSUE THREAD

**Issue by anoopt** [pnp/sp-dev-fx-controls-react#815]
#### Category

- [x]  Enhancement
- [ ] Bug
- [ ] Question

#### Details

A new control called `Animated dialog` which is an enhanced version of Fabric UI react dialog.

The new control will be an extension of the Fabric UI dialog with some extra properties that will drive the animation i.e. 
- the way the dialog appears and hides
- an extra icon above the title (with some animation)

#### Demo

![Animated Dialog](https://user-images.githubusercontent.com/9694225/110113344-e253ff00-7daa-11eb-8046-8ca9c6ca281d.gif)

**Comment by AJIXuMuK** [comment]
Hi @anoopt,

I think it's an awesome enhancement!
Will you prep the PR?

**Comment by anoopt** [comment]
Sure Alex. Will do 👍

**Comment by anoopt** [comment]
Hi @AJIXuMuK - I installed the beta version of PnP SPFx controls to test this control and I get an error with the external css that is present in the code.

I have added `require('../../../node_modules/animate.css/animate.min.css');` in the [AnimatedDialog control](https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/controls/animatedDialog/AnimatedDialog.tsx#L10) and I thought this would get bundled as part of the package.

Am I missing something?

**Comment by AJIXuMuK** [comment]
Hi @anoopt,

Hmmm, yes, it should be bundled.
I'll take a closer look.

**Comment by AJIXuMuK** [comment]
Hey @anoopt - I got it fixed.
As we're developing a library, we need to reference items from `node_modules` not as relative ones, but as actual modules.

In case of animate.css - `require('animate.css/animate.min.css')`

**Comment by anoopt** [comment]
Ah. Thank you Alex for explaining the details. Very helpful.
