### ISSUE TITLE
Documentation: AccessibleAccordion link page is broken

### ISSUE THREAD

**Issue by AriGunawan** [pnp/sp-dev-fx-controls-react#818]
#### Category
⬜️ Enhancement
✅ Bug
⬜️ Question

#### Expected / Desired Behavior / Question
It should show the documentation page for AccessibleAccordion control.

#### Observed Behavior
It shows 404 not found.
![image](https://user-images.githubusercontent.com/8691985/110244967-de370580-7f93-11eb-9e32-6ae2c0560d16.png)

#### Steps to Reproduce
Click the **AccessibleAccordion** link in the left-hand side navigation, or
Click the **Controls** link in the header navigation

**Comment by AJIXuMuK** [comment]
Thank you @AriGunawan for reporting it!

The fix has been merged and will be available in the next release.
