### ISSUE TITLE
How to contribute our webparts

### ISSUE THREAD

**Issue by quantrpeter** [pnp/sp-dev-fx-controls-react#823]
Dear All
   We are [www.quantr.hk](https://www.quantr.hk) , a SharePoint dev company based in Hong Kong. In past years, we have completed many intranet project. We want to contirbute some webparts to this project. Is there a room for us? We want to contribute our "Staff Directory" webpart as our first step.
Thanks
Peter

**Comment by gautamdsheth** [comment]
Hey @quantrpeter , this repository is for React based controls. If you wish you contribute controls created using React, you can do that in this library.

For webparts/extensions contributions, you can do that in the https://github.com/pnp/sp-dev-fx-webparts and https://github.com/pnp/sp-dev-fx-extensions repositories. 
Thank you !

**Comment by AJIXuMuK** [comment]
Hello @quantrpeter!
Thank you for you interest in the community and intention to contribute to PnP libraries!

If you're willing to share your web part as a reusable control - feel free to create a PR to this repo.
If you want it to be a "sample" - use the repos that @gautamdsheth is mentioned above.

Also, it worth saying that PnP has [Sharing is Caring](https://pnp.github.io/sharing-is-caring/) initiative that helps people to start contributing.
Feel free to check it out as well.

**Comment by quantrpeter** [comment]
i will contribute this webpart, lets see if everyone think it is ok

![image](https://user-images.githubusercontent.com/50471577/110666709-894df600-8204-11eb-9d16-9c078d7e6bdb.png)

**Comment by AJIXuMuK** [comment]
@quantrpeter - [https://github.com/pnp/sp-dev-fx-webparts](https://github.com/pnp/sp-dev-fx-webparts) is probably a better fit for it.
