### ISSUE TITLE
FilePicker - React(?) crash on large folders

### ISSUE THREAD

**Issue by evlo** [pnp/sp-dev-fx-controls-react#826]
#### Category

- [ ] Enhancement
- [x] Bug
- [x] Question

#### Version

Please specify what version of the library you are using: [ 2.5.0 ]

#### Expected / Desired Behavior / Question
Being able to scroll even in large folders

#### Observed Behavior
Tested on two sites with folders with lot of files ~15000 and about 35000 in one folder, in both cases whole react crashes and ui gets closed, `Objects are not valid as a React child (found: [object Promise])` is the message in debug console. "15000" files library does have only files with names in latin alphabet.

#### Steps to Reproduce
Create library with 15000+ files

I dunno if this can be solved, it is mostly a question if it is even possible.

**Comment by AJIXuMuK** [comment]
Hi @evlo!
Thank you for reporting this one!
The fix has been merged and will be included in the next release!

**Comment by joelfmrodrigues** [comment]
@evlo please try updating to the latest release and open a new issue if you still experience problems.
Thanks for your contribution
