### ISSUE TITLE
Tab links are not working on the page.

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/sp-dev-fx-controls-react#827]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
When use go to site https://pnp.github.io/sp-dev-fx-controls-react/ and click on Controls tab, it should open proper listing of controls.

#### Observed Behavior
When clicking on the page , it is showing un-ordered and ugly page.
![image](https://user-images.githubusercontent.com/6926513/110741724-2cc9f580-825b-11eb-99e6-2d5988064bcf.png)

#### Steps to Reproduce
Go to ulr : https://pnp.github.io/sp-dev-fx-controls-react/
Click on Controls tab.

Thanks!

**Comment by gauravgoyal5** [comment]
Other links are also not working on this page:
https://github.com/pnp/sp-dev-fx-controls-react/blob/master/docs/documentation/docs/index.md

**Comment by sympmarc** [comment]
@gauravgoyal5 To your first point, I see this on many doc pages (not just PnP) when the CSS hasn't loaded correctly. Usually a refresh is all it takes.

**Comment by AJIXuMuK** [comment]
It's actually an issue with the link to Accessible Accordion. 
We already have a fix in dev branch. I'll probably cherry-pick it to master.

**Comment by AJIXuMuK** [comment]
fixed
