### ISSUE TITLE
Pnp People picker suggestion showing irrelevant names

### ISSUE THREAD

**Issue by RahiniRadha** [pnp/sp-dev-fx-controls-react#828]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [pnp 1.20.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Pnp people picker should show the related suggestions based on text typed in People picker box.

#### Observed Behavior
Suggestion list showing irrelevant values for the text typed in People picker box and also its always showing same set of suggestions whatever we type in the picker. The desired user not showing in full suggestion list.
This is working fine in SIT environment and the issue is occurring in UAT only.

#### Steps to Reproduce
1. Type first 3 character of the desired user's name in picker control
2. Suggestion list not showing any related values and showing irrelevant values

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @RahiniRadha,

I doubt it's a control issue if you have it working on one environment and not on another. I also can't reproduce it on my end.
Please, double-check the properties of the control. Maybe you specify the group that doesn't exist on your "SIT" environment.

**Comment by RahiniRadha** [comment]
Hi @AJIXuMuK,

Thanks for your feedback. We have left the "Group name" as blank to filter from all users for both SIT and UAT environment. Please refer below image for the control properties we have set.
![image](https://user-images.githubusercontent.com/79247922/110880587-dfa25e00-8304-11eb-9513-786e775a41f2.png)

We also suspect this would be a environment related issue, but unable to point to exact cause. 

We checked normal sharepoint classic people picker in UAT. In that too all users not coming in the suggestions, however able to add the desired user by clicking the "Checknames" or "Ctrl + k" options.

Please share your suggestions.

**Comment by AJIXuMuK** [comment]
@RahiniRadha - you basically answered your question by yourself. The issue is not related to the component.
It is related to the configuration.
