### ISSUE TITLE
Add alphabetic sorting for the ListItemPicker control

### ISSUE THREAD

**Issue by Brinky-ux** [pnp/sp-dev-fx-controls-react#829]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.5.0]

#### Expected / Desired Behavior / Question
I would like to have the ListItemPicker return the items sorted alphabetically. 

#### Observed Behavior
The ListItemPicker seems to return the items in the order in which they appear in the list.

**Comment by kunj-sangani** [comment]
Hi @AJIXuMuK ,

Can we add a property named "orderBy" and fetch the items based on this orderBy value provided . If we can do that can you please assign this bug to me I can help update the code and create a pull request and you can verify
