### ISSUE TITLE
PNP Rich Text Editor Control

### ISSUE THREAD

**Issue by njabs** [pnp/sp-dev-fx-controls-react#843]
#### Category

Bug

#### Version

1.0.1

#### Expected / Desired Behavior / Question

When I right align text the expected behavior is that the text will be right aligned but it does not. I can see that the right align class does get added when i inspect the control using dev tools ie.("ql-align-right") but it shows as left aligned when I display it on y my SPFX Application.

#### Steps to Reproduce
right align text on the Rich text editor save that text onto a SharePoint list and display the text on an spfx page. everything works 
accept for the right align.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @njabs,
Thank you fo reporting this.

v1.0.1 is pretty old. Could you please update to the latest `v2` version (2.6.0) and check if the issue is presented there.
