### ISSUE TITLE
Type 'WebPartContext' is not assignable to type 'BaseComponentContext'.

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#851]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [   3.0.0  ]

#### Expected / Desired Behavior / Question

Before 3.0.0 the `context={props.context}` for FilePicker and ListItemPicker was OK with WebPartContext inherited from the `context: this.context` from the web part class.

#### Observed Behavior

After upgrade to 3.0.0 , TS complains that "Type 'WebPartContext' is not assignable to type 'BaseComponentContext'."

I am OK for now by using  `context={props.context as any}` 
But I would like to know the right way to do it.

Thanks for a great collection!

**Comment by AJIXuMuK** [comment]
Thank you @Ofer-Gal for reporting this one.

`v3` is based on SPFx `v12` and up.

For SPFx `v11` use the latest `v2` release.

**Comment by Ofer-Gal** [comment]
Thank you

**Comment by NaffOff** [comment]
Hi @AJIXuMuK, 
Version 1.12 has been deprecated https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.0. 
Do you know if spfx controls will be to? For production releases, should we aim for 1.11/v2?

**Comment by HiltonGiesenow** [comment]
I'm getting this now with PeoplePicker, with SPFx 1.13.0 and "@pnp/spfx-controls-react": "^3.4.1"

**Comment by AJIXuMuK** [comment]
@HiltonGiesenow please, read my comments above.
You need to use beta version for now.

**Comment by HiltonGiesenow** [comment]
ah ok, I thought that was for the 3.4.0 release. Thanks, will do that. I presume you'll notify on this thread if there's an update?

**Comment by HiltonGiesenow** [comment]
I forgot to say : Thanks for the super-quick response @AJIXuMuK

**Comment by AJIXuMuK** [comment]
This thread is closed, so not sure...
But we will have a new release pretty soon.
We'll definitely announce the release on Twitter: https://twitter.com/M365PnPControls

**Comment by HiltonGiesenow** [comment]
Ok thanks. I'm trying the latest beta now (3.5.0-beta.1412592), but I'm still getting the same error. Should I open a new issue?

**Comment by AJIXuMuK** [comment]
Please, use my sample above and compare it with your solution.
Maybe modules were not updated or something.
Try to remove `package-lock.json` and `node_modules`, and run `npm i`.

**Comment by HiltonGiesenow** [comment]
I checked your sample, and I've matched 100% the versions of SPFX, @pnp/spfx-controls-react, and even office-ui-fabric-react just to be safe. I've removed `node_modules`, and `package-lock.json`, run `npm i`, reloaded VS.Code, but still no luck - same error. I got your sample working fine, albeit with the same error initially in Controls113WebPart.ts - I had to change line 57 to `context: this.context as any,`

**Comment by mhomol** [comment]
I also tried using your sample and got the same issue after running `gulp serve`

`Error - [tsc] src/webparts/controls113/Controls113WebPart.ts(57,19): error TS2322: Type 'WebPartContext' is not assignable to type 'BaseComponentContext'.`

**Comment by bhaidar** [comment]
Hi @AJIXuMuK 
I made sure to match the versions of the same package as in the sample you shared. I am still getting this error:

```
Type 'WebPartContext' is not assignable to type 'BaseComponentContext'.
  Types have separate declarations of a private property '_serviceScope'.ts(2322)
IPropertyFieldListPicker.d.ts(39, 5): The expected type comes from property 'context' which is declared here on type 'IPropertyFieldListPickerProps'
```

**Comment by ryanwishnow** [comment]
Did anyone ever find a fix?

**Comment by AJIXuMuK** [comment]
Once again: if you use SPFx 1.13 **use beta versions on controls for now**.
It does work.

Attached another example.

If you're updating existing solution, please, make sure to remove `package-lock.json` and `node_modules`. Also double-check the versions of SPFx modules and controls modules.
[context.zip](https://github.com/pnp/sp-dev-fx-controls-react/files/7574837/context.zip)

**Comment by ryanwishnow** [comment]
Hey Alex,

Appreciate your help. I followed your directions and matched the versions in your sample in my web part. I also deleted the `node_modules` folder. `package-lock.json` file, and ran an `npm install`

  `"dependencies": {
    "@microsoft/sp-core-library": "1.13.0",
    "@microsoft/sp-lodash-subset": "1.13.0",
    "@microsoft/sp-office-ui-fabric-core": "1.13.0",
    "@microsoft/sp-property-pane": "1.13.0",
    "@microsoft/sp-webpart-base": "1.13.0",
    "@pnp/spfx-property-controls": "3.3.0-beta.1482322"
  },`

I'm still receiving the same error

**Comment by jonsjonsson** [comment]
I was getting this on the PropertyFieldColumnPicker and this worked for me to get past this error. 
`context: this.context as any,`

**Comment by Mario-Po7** [comment]
I am getting this error using a PeoplePicker. 

My versions are:
pnp/spfx-controls-react v3.9.0
SPFx version 1.15.2

Shouldn't this be fixed or is it known that this combination of versions does not work?

**Comment by cardinalpipkin** [comment]
I'm getting this error as well
My versions are:
pnp/spfx-controls-react v3.10.0
SPFx version 1.15.0

My people picker is also not searching and giving a 400 response.

**Comment by Mario-Po7** [comment]
@cardinalpipkin The people picker returning a 400 response is most likely this issue: https://github.com/pnp/sp-dev-fx-controls-react/issues/1292. The PeoplePicker is broken in version 1.10.0. Just use 1.9.0 for the time being.

**Comment by cardinalpipkin** [comment]
@Mario-Po7 Do you mean SharePoint version 1.9.0? Can't I update "@pnp/spfx-controls-react": "^3.10.1 || 3.9.0",?

**Comment by Mario-Po7** [comment]
@cardinalpipkin That's exactly what I mean. And that is also the fix/workaround I used. The Problem is in spfx-controls-react. Not in Sharepoint. Maybe I should have been clearer.

**Comment by gretchunkim** [comment]
Issue is reproducible in  SPFx "1.15.2"
@pnp/sp": "^3.10.0",
    "@pnp/spfx-controls-react": "^3.12.0",
    "@pnp/spfx-property-controls": "^3.11.0 

Overcame issue using suggestion from @jonsjonsson  (A big) Thank you!

**Comment by lerayne** [comment]
Hi! 
Is this component ready for SPFx 1.16? I have the same issue and a couple of additional issues - for example it doesn't see the files in a site folder and defaultFolderAbsolutePath doesn't work too.

**Comment by priyanshi-rami** [comment]
Sometimes it solves just by 'npm audit fix --force'

**Comment by lhdeveloper** [comment]
Hey dudes!

I'm getting the same error when trying to use FilePicker.
`PropertyFieldFilePicker("filePicker", {
                      context: this.context,
                      filePickerResult: this.properties.filePickerResult,
                      onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
                      properties: this.properties,
                      onSave: (e: IFilePickerResult) => { console.log(e); this.properties.filePickerResult = e; },
                      onChanged: (e: IFilePickerResult) => { console.log(e); this.properties.filePickerResult = e; },
                      key: "filePickerId",
                      buttonLabel: "File Picker",
                      label: "File Picker",
                  })`

Error:
`Type 'WebPartContext' cannot be assigned to type 'BaseComponentContext'.
  Types have separate declarations of a private property '_serviceScope'.ts(2322)
IPropertyFieldFilePicker.d.ts(114, 5): Expected type comes from property 'context', which is declared here in type 'IPropertyFieldFilePickerProps'`

Dependency versions:
`"@microsoft/sp-core-library": "1.16.1",
"@microsoft/sp-property-pane": "^1.16.1",
    "@microsoft/sp-webpart-base": "^1.16.1",
"@pnp/spfx-controls-react": "^3.13.0",
    "@pnp/spfx-property-controls": "^3.12.0",`

**Comment by nazarbroslavskyi** [comment]
Hi) Also have this issues with PropertyFieldFilePicker
I am using: 
    "@microsoft/sp-component-base": "1.17.4",
    "@microsoft/sp-core-library": "1.17.4",
    "@pnp/spfx-controls-react": "3.15.0",
    "@pnp/spfx-property-controls": "3.14.0",
    
    
    ERROR: Type 'WebPartContext' is not assignable to type 'BaseComponentContext'.   Types have separate declarations of a private property '_serviceScope'.

**Comment by milchkafi** [comment]
WTF you breaking the API withwout notice?

**Comment by Krugerro** [comment]
Same for FilePicker. 
"@fluentui/react": "^7.199.1",
    "@microsoft/sp-component-base": "1.17.4",
    "@microsoft/sp-core-library": "1.17.4",
    "@microsoft/sp-lodash-subset": "1.17.4",
    "@microsoft/sp-office-ui-fabric-core": "1.17.4",
    "@microsoft/sp-property-pane": "1.17.4",
    "@microsoft/sp-webpart-base": "1.17.4",
    "@pnp/logging": "^3.17.0",
    "@pnp/sp": "^3.17.0",
    "@pnp/spfx-controls-react": "^3.15.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"

**Comment by joelfmrodrigues** [comment]
@dorin2006 what Ofer-Gal suggests is a way to overcome this. The PnP Controls solution is still on 1.17.3 and you are using 1.17.4, hence the differences

**Comment by dorin2006** [comment]
@Ofer-Gal @joelfmrodrigues  thanks!
