### ISSUE TITLE
add  "Drag and Drop" option to the "Upload" tab in FilePicker 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#853]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.0.0     ]

#### Expected / Desired Behavior / Question

Please add  "Drag and Drop" option to the "Upload" tab in FilePicker 
It works so well in ListView

Thank you in advance

**Comment by aaclage** [comment]
I could give a look how the control FilePicker was made and include.
Anyway i need to update the ListView drag and drop and could also include this feature in the control.

Let see what @AJIXuMuK or @joelfmrodrigues say.

Mockup:
![image](https://user-images.githubusercontent.com/8522348/112794632-7b52fe80-9067-11eb-99c4-bdea10178844.png)

**Comment by Ofer-Gal** [comment]
@aaclage I would rather have the hosting app deal with the dropped files.
Just my 2c

**Comment by aaclage** [comment]
Can you clarify you feedback, 
Are you saying the drag and drop should be directly in the control? Mockup below:
![image](https://user-images.githubusercontent.com/8522348/112904950-fe1c9d80-90e9-11eb-9980-3ef955f90b8e.png)
This option doesn't allow the folder choose option.

**Comment by Ofer-Gal** [comment]
Your first mockup had 
![image](https://user-images.githubusercontent.com/5054931/112906569-fd681500-90b1-11eb-91c7-635357ce2682.png)
I would like to have only the Files (many) picker and drop zone in the control. so the OnDrope event will give a FileList and so OnFilePick (or whatever you name it). 
Like so:
![image](https://user-images.githubusercontent.com/5054931/112907154-fe4d7680-90b2-11eb-8372-d925a189ba23.png)


If it is possible, It will be great. Thank you so much

**Comment by AJIXuMuK** [comment]
Thank you @Ofer-Gal for the suggestion.
I'm totally agree it would be a great enhancement and feels natural in the way you proposed it.

@aaclage - if you're able to look into it, it will be much appreciated.

**Comment by aaclage** [comment]
@AJIXuMuK 
Yes i am already working on this with, just give me some days.

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal many thanks for the great suggestion. @aaclage submitted a PR to add this functionality. You can check PR for details, but in summary, it adds a new upload option.
If you have the chance to test dev-v2, please let us know if it works for you.

**Comment by Ofer-Gal** [comment]
I see dev-v2 as a branch. 
I am too novice to know how to use it in my SPFx web part.
Can you make NPM package of it?

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal sorry for the late reply, been a bit too busy...
To use a dev version fo the controls within your project you can use [npm link](https://docs.npmjs.com/cli/v7/commands/npm-link):
1. remove the pnp controls package from your web part (if installed)
2. download or clone the source code as per target branch (dev-v2 in this case)
3. on the pnp controls folder with the source code, run `npm install` and `gulp bundle` to ensure that all is working 100%
4. still on the pnp controls folder with the source code, run `npm link` to create a shortcut that will work as a fake global module pointing to that local folder
5. on your web part, run `npm link @pnp/spfx-controls-react` to make the controls available in your web part solution as if they were installed

Let me know if you find any issues. You can also find a lot of information online on using npm link - some blog posts may explain it better than I did above.

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal this is now available in the latest release, so closing this item.
Many thanks for your contribution

@aaclage thanks for the PR!

**Comment by Ofer-Gal** [comment]
Thank you much. testing 2.7.0 and 3.1.0
