### ISSUE TITLE
Add Site Collection Pircker control

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#854]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

Would be nice to have a SiteCollectionPickerControl so a webpart could have a picker that  lets a user select a SiteCollection. I'm working on a webpart that can read contents from multiple site collections and the user needs to be able to specifty which ones. Probably not a wide audience, but I thought I'd suggest it. Probably also needs some SP admin permissions to read them all.

**Comment by AJIXuMuK** [comment]
@russgove  - I've implemented new `SitePicker` controls that will be included in the next release.
It allows to specify `mode` property to make it a "site collection" picker.

**Comment by russgove** [comment]
Thanks alex!
I am working on a tool to let us captuture the details of the M365 audit logs to sharepoint lists. I’ll definitively have a look.
Russell

**Comment by joelfmrodrigues** [comment]
@russgove  Closing this item as this should now be available as part of the last release.
Many thanks for your contribution!
