### ISSUE TITLE
TreeView - onSelect on click of text of node does not highlight or set background color to selected node.

### ISSUE THREAD

**Issue by Bhushan12986** [pnp/sp-dev-fx-controls-react#859]
#### Category
[x] Enhancement

[x] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [2.4.0]

#### Observed Behavior
On click of tree node text onSelect does not highlight or set background color. If clicked on blank space of containing DIV, highlights or sets background.

#### Steps to Reproduce
Create a sample tree using this link without check boxes and selection mode to single.
Implement onSelect event, click on tree node text to check if onSelect event highlight or set background color to the selected node.
Sample
```
<TreeView
  items={this.state.TreeLinks}
  defaultExpanded={false}
  selectionMode={TreeViewSelectionMode.Single}
  selectChildrenIfParentSelected={true}
  showCheckboxes={false}
  treeItemActionsDisplayMode={TreeItemActionsDisplayMode.Buttons}
  onSelect={this.onTreeItemSelect}
  onExpandCollapse={this.onTreeItemExpandCollapse}
  onRenderItem={this.renderCustomTreeItem}
/>
```

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @Bhushan12986.
Thank you for reporting this one. 
But you're using custom render for the item. 
It means you're responsible for highlighting the item when needed.
