### ISSUE TITLE
Adding a link in the RichText control does not work

### ISSUE THREAD

**Issue by cwparsons** [pnp/sp-dev-fx-controls-react#875]
#### Category

- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.0.0]

#### Expected / Desired Behavior / Question

When using the RichText control, adding a link does not work. This is similar to [another comment]( https://github.com/pnp/sp-dev-fx-controls-react/issues/795#issuecomment-815632971_) made on issue #795.

#### Observed Behavior

After clicking the *Save* button on the *Insert link* modal, a JavaScript error occurs:

quill.js
![image](https://user-images.githubusercontent.com/786967/114800209-42a16d80-9d67-11eb-8aaf-500b92bc9eac.png)

RichText.tsx
![image](https://user-images.githubusercontent.com/786967/114800236-54831080-9d67-11eb-9d72-cd72c844430f.png)

#### Steps to Reproduce

1. Run `npm run serve` to open up the SPFx workbench.
2. Add the test control.
3. Find the (invisible) RichText control midway down the page.
4. Click on the *Insert link* button.
5. Add an address and text to display to the modal.
6. Press save.

**Comment by AJIXuMuK** [comment]
Hi @cwparsons,

Thank you for reporting the issue. It has been fixed and will be included in the next release.

**Comment by joelfmrodrigues** [comment]
@cwparsons Closing this item as this should now be fixed as part of the last release. Please update to the latest release and open a new issue if you still experience problems.
Many thanks for your contribution
