### ISSUE TITLE
List View in Group By Sorting is not working as expected

### ISSUE THREAD

**Issue by sravankumar1107** [pnp/sp-dev-fx-controls-react#876]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[*] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
List View in Group by sorting to be sorted correctly
#### Observed Behavior
List View Group by on click of header selection sorting is triggering, sorting elements are not properly sorting.
For example in below screenshot i am sorting by date its not sorting properly.
![image](https://user-images.githubusercontent.com/25325127/114810643-d34e6c80-9dac-11eb-8526-53234e154b30.png)
 

#### Steps to Reproduce
add List view control and group by date column and show fields date field and sorting is not working expected

#### Submission Guideline.

Thanks!

**Comment by sravankumar1107** [comment]
Any update.. Please address the issue ASAP?

**Comment by AJIXuMuK** [comment]
@sravankumar1107 - we all here work on the library **voluntary** in our **spare time**.
There are no SLAs.

You are free to fix the issue by yourself and submit a PR. Please, reference the [contributing](https://pnp.github.io/sp-dev-fx-controls-react/guides/contributing/) documentation.

**Comment by HeShallNot** [comment]
Just gonna mention that this is related to #880 issue with numeric values treated as strings by the built-in sort function.

**Comment by AJIXuMuK** [comment]
If the date is passed as `string` - it is sorted as string. If you provide `Date` value instead - it will be sorted as date.

In the next release you'll be also able to implement your own sorting function and pass it as `prop` to the component:
```typescript
sortItems?: (items: any[], columnName: string, descending: boolean) => any[];
```

**Comment by sravankumar1107** [comment]
Hi @AJIXuMuK Thanks for your response. Currently as i see its pointed as date only and not the string. Here is the JSON for the reference:
**{"name": "MeetingDate_x005f_", "displayName": "Meeting Date", "sorting": true, "minWidth": 100,"maxWidth":150,"isResizable":true,"fieldType":"date","dateFormat":"DD/MM/YYYY"}**
But still sorting is not working out as you said. If my understanding is wrong..please correct me if i miss something.

**Comment by AJIXuMuK** [comment]
Hi @sravankumar1107,
This is definition of the field. 
But what is the data/value for that field for each list item you provide to the list view?
Is it date or string?
Like `date: "05/05/2021"` or `date: Dateobj`?

**Comment by joelfmrodrigues** [comment]
@sravankumar1107 there was an update for sorting as part of the latest release. Can you please update and test again?

**Comment by AJIXuMuK** [comment]
Fixed and no response.
