### ISSUE TITLE
Rich Text: Text disappear after copy/paste text or adding image

### ISSUE THREAD

**Issue by pk091990** [pnp/sp-dev-fx-controls-react#877]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.6.0 ]

#### Expected / Desired Behavior / Question
When using a rich text control, copy/paste text and image doesn't work.

#### Observed Behavior
Console error occurred when copy/paste any content or add a image.

#### Steps to Reproduce
1: Add Rich text webpart
2: Copy paste any text and click outside of your webpart.
3: Text will disappear with below error in console.
![image](https://user-images.githubusercontent.com/46436213/114824973-407cf480-9de3-11eb-8412-5d52711109f4.png)
Debug
![image](https://user-images.githubusercontent.com/46436213/114824987-45da3f00-9de3-11eb-8275-c810dbf28a14.png)

4: Its working fine if I'm manually writing any text instead of copy/paste.

**Comment by AJIXuMuK** [comment]
Thank you @pk091990 for reporting the issue!
It has been fixed and the fix will be included in the next release.

**Comment by AnandhaprabhuSp** [comment]
@AJIXuMuK  Approx when we can expect the next release?  since this is kind of blocking us from choosing the editor.

**Comment by AJIXuMuK** [comment]
@AnandhaprabhuSp - I would expect new release in the next 2 weeks. 
But you can install beta version from npm right away if that's a blocker. V2 beta already contains the needed changes.

**Comment by joelfmrodrigues** [comment]
@pk091990 this should now be fixed as part of the last release. Please update to the latest release and open a new issue if you still experience problems.
Many thanks for your contribution

**Comment by njabsDI** [comment]
Hi I installed  "@pnp/pnpjs": "^2.5.0-beta2" where as previosly I had pnp version 2.5.0 but still copy and paste does not work.
