### ISSUE TITLE
New Control: Dynamic form

### ISSUE THREAD

**Issue by ravichandran-blog** [pnp/sp-dev-fx-controls-react#878]
#### Category

- [x] Idea
- [ ]  Enhancement
- [ ]  Bug
- [ ]  Question

Can we include the form control, which can automatically take care of everything and completely controlled by the SharePoint list settings, 

I have already started to build this control, almost **80% done**. as of now, control can be support all field types except location.

If listItemId is empty, zero or undefined then new item saved in the list else existing item will be updated 
```html
<DynamicForm context={this.props.context} listId={"3071c058-549f-461d-9d73-8b9a52049a80"} listItemId={1}></DynamicForm>
```
**Output**
![image info](https://sptechnet.files.wordpress.com/2021/04/dynamic.png)

Please let me know your feedback and suggestions.

Thanks!

**Comment by russgove** [comment]
sounds like a great idea. if the list item i’d is null, does it create a new item?

**Comment by ravichandran-blog** [comment]
> sounds like a great idea. if the list item i’d is null, does it create a new item?
> […](#)
Yes, right

**Comment by AJIXuMuK** [comment]
@ravichandran-blog - I think it's a wonderful idea!

Would be happy to see the PR from you!

**Comment by ravichandran-blog** [comment]
> Would be happy to see the PR from you!

Thanks @AJIXuMuK

**Comment by Matej4386** [comment]
this is really great idea - will it also handle form validation based on column settings?

**Comment by ravichandran-blog** [comment]
Hi @Matej4386 ,

Yes, right. validation based on column settings, control development is done 100%, now I'm working for documentation. 

Thanks!

**Comment by Matej4386** [comment]
@ravichandran-blog that is really great. Looking forward for this control.

**Comment by ravichandran-blog** [comment]
Feeling wonderful :)

Submitted pull request,

https://github.com/pnp/sp-dev-fx-controls-react/pull/902

**Comment by AJIXuMuK** [comment]
@ravichandran-blog  please, do not close issues that are not released yet.

**Comment by ravichandran-blog** [comment]
Oops! Sorry @AJIXuMuK
