### ISSUE TITLE
Sorting on columns that aren't text doesn't seem to work correctly

### ISSUE THREAD

**Issue by scallin** [pnp/sp-dev-fx-controls-react#880]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [   1.19.0      ]

#### Expected / Desired Behavior / Question
Is there a way to override the default sorting functionality?  Sorting is built in, but treats all content as text, so number columns (like item ID) and date columns do not sort correctly.

#### Observed Behavior
If I add ListView with list items and a column to show the ID of the list items like this:

const viewFields: IViewField[] = [
  {
    name: 'ID',
    minWidth: 80,
    maxWidth: 90,
    isResizable: true,
    displayName: 'ID',
    sorting: true,
  }
]

Clicking on the column will sort the items like this:
1
10
100
14
15
2
20
etc.

#### Steps to Reproduce
Steps are provided above.

Thanks!

**Comment by HeShallNot** [comment]
Can confirm this issue as well. Sorting with column values that are numeric seems to be treated as strings instead which then fails to produce the correct order.

Here are some screenshots for both ascending and descending sorts of numeric columns failing to produce the correct order. An override function for sorting in the IViewField definition is a very good compromise as well.

![image](https://user-images.githubusercontent.com/46070928/116180054-e537f400-a74a-11eb-8830-80434fb4fa9a.png)

![image](https://user-images.githubusercontent.com/46070928/116180162-0993d080-a74b-11eb-9606-5ab8d21ceb99.png)

**Comment by AJIXuMuK** [comment]
Thank you @scallin for reporting this one.
Not sure about `v1` but in `v2` and `v3` sorting behavior depends on the type of actual data provided to the controls.
If `Id` has `number` value (like `Id: 5`) it will be sorted as `number`. If `Id` has `string` value (`Id: '5'`) it will be sorted as string.

Here are examples
**NUMBER**
<img width="543" alt="Screen Shot 2021-05-01 at 12 47 35 PM" src="https://user-images.githubusercontent.com/17036219/116793841-0c116580-aa7e-11eb-8679-b0b68f669121.png">
<img width="755" alt="Screen Shot 2021-05-01 at 12 48 08 PM" src="https://user-images.githubusercontent.com/17036219/116793847-192e5480-aa7e-11eb-9664-0eafc2c6800c.png">

**STRING**
<img width="189" alt="Screen Shot 2021-05-01 at 12 56 58 PM" src="https://user-images.githubusercontent.com/17036219/116793853-20edf900-aa7e-11eb-8056-bb0138dd44fd.png">
<img width="469" alt="Screen Shot 2021-05-01 at 12 58 35 PM" src="https://user-images.githubusercontent.com/17036219/116793857-26e3da00-aa7e-11eb-83b3-95ec942a063b.png">

But, anyway, I've added a new prop `sortItems` that allows to override default sorting behavior.
```typescript
sortItems?: (items: any[], columnName: string, descending: boolean) => any[];
```

It will be included in the next `v2` and `v3` releases.

**Comment by HeShallNot** [comment]
@AJIXuMuK many thanks for the quick response on this issue. but any chance this could be applied to `v1` as well? we have still have some tenants that needed to support `v1`. we have a local workaround but having an official fix would be really helpful in terms of maintainability.

Cheers~

**Comment by AJIXuMuK** [comment]
@HeShallNot - did you check that you provide numbers as field values, not strings?
I believe it should be enough in your situation. 

We can add this to `v1`, but we release version really seldom for `v1`.

**Comment by kodofix** [comment]
@AJIXuMuK if it's possible It will be great if you will add this fix to v1 I'm working with on prem and I just come across this problem now that my listView control sorting alphabetic
