### ISSUE TITLE
Stock images url is getting a 404 server error

### ISSUE THREAD

**Issue by nviolero** [pnp/sp-dev-fx-controls-react#882]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.0]

#### Expected / Desired Behavior / Question
The FilePicker control has a tab to get images from Stock Images, but is getting a 404 server error.

#### Observed Behavior
This is an example of the url that the FilePicker is generating to get the images from Stock images:
https://hubblecontent.osi.office.net/contentsvc/external/m365contentpicker/index.html?p=3&app=1001&aud=prod&channel=devmain&setlang=en-GB&msel=0&env=prod&premium=1&themecolors=%7B%22primaryColor%22%3A%22%23445068%22%2C%22textColor%22%3A%22%23333333%22%2C%22backgroundColor%22%3A%22%23ffffff%22%2C%22neutralLighterColor%22%3A%22%23f3f2f1%22%7D

As you can see, is getting a 404 error. It seems that it's been changed and now the correct one is:
https://hubblecontent.osi.office.net/contentsvc/m365contentpicker/index.html?p=3&app=1001&aud=prod&channel=devmain&setlang=en-GB&msel=0&env=prod&premium=1&themecolors=%7B%22primaryColor%22%3A%22%23445068%22%2C%22textColor%22%3A%22%23333333%22%2C%22backgroundColor%22%3A%22%23ffffff%22%2C%22neutralLighterColor%22%3A%22%23f3f2f1%22%7D

Just take the '/external' from the url.

#### Steps to Reproduce
Import a FilePicker in your project and try to browse an image using the Stock Images tab.

**Comment by Employee87** [comment]
Also noticed this too. Thanks for providing the working URL, I have that as a temporary fix now.

**Comment by AJIXuMuK** [comment]
Thank you @nviolero for reporting the issue.
It has been fixed and will be included in the next release.

**Comment by joelfmrodrigues** [comment]
@nviolero  Closing this item as this should now be fixed as part of the last release. Please update to the latest release and open a new issue if you still experience problems.
Many thanks for your contribution
