### ISSUE TITLE
Label for list item picker

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-controls-react#885]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [v3]

#### Question
Is there a way to set a label for the ListItemPicker control? I found `label `for ListPicker and `titleText `for PeoplePicker, but no equivalent for ListItemPicker.

**Comment by joelfmrodrigues** [comment]
Hi @PathToSharePoint, this control doesn't seem to have this property at the moment, but would be nice to have it aligned with the other controls. Would you be interested in implementing this and submitting a PR?

**Comment by AJIXuMuK** [comment]
Implemented a while ago.
