### ISSUE TITLE
OrganizationAssetTab for the pnp SPFX control : image file picker not available for some users

### ISSUE THREAD

**Issue by KavyalJ** [pnp/sp-dev-fx-controls-react#892]
#### Category

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   node js 10.24.1     ]

#### Expected / Desired Behavior / Question
We are using the PNP SPFX react file picker control: https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/ where  want the Organisation Asset tab to be visible

#### Observed Behavior
We have observed that the upload from the organization asset tab is not visible only for some users but it is visible to some even though they have the Same permission to SharePoint. We have set the "hideOrganisationalAssetTab" property as false and also tried not using this property at all. Still, the issue persists.
The issue was also observed on the local workbench.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @KavyalJ,
Thank you for reporting this one.
For the local workbench - it will not work as you're not connected to the tenant. It means there are no Org Assets.

For the general scenario - have you checked if the same users (who experience issue with the control) can access the Org Asset through OOB SharePoint UI (for example, when selecting an image for a SharePoint page)?
If no - it's not related to the control, but to the policies you have on the tenant.
