### ISSUE TITLE
add contenttype id to list picker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#894]
**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [latest        ]
Could we add a contentTypeID to the listpicker control. The ide would be that the list picker would only let you select lists that contained the selected content type.

**Comment by joelfmrodrigues** [comment]
@russgove I think this is a very useful scenario. I think the logic of the control would have to change a little bit to accommodate this, but if the check for content type is only done if the property is provided, then I assume it won't cause any negative impact when not specified.
Would you be interested in implementing this and submitting a PR?

**Comment by russgove** [comment]
yup, hope toe find some time to work on it this eek

**Comment by russgove** [comment]
^^week

**Comment by joelfmrodrigues** [comment]
@russgove that's great, I have assigned this item to you so other people are aware you may be working on it and not try to also implement it

**Comment by AJIXuMuK** [comment]
Thanks @russgove for both the proposal and the PR.

It has been merged and will be included in the next release.
