### ISSUE TITLE
sitePicker does not display initialsites until you click the dropdown to select

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#895]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ latest  ]

#### Expected / Desired Behavior / Question
When you set the initialsites option the title of the in ititialsite should appear as the selected site on the initial display.
#### Observed Behavior
the picker appears blank until you hit the dropdown, then the site you selected as the initiualsites displays.
#### Steps to Reproduce
            <SitePicker
                initialSites={[{ id: item.siteId, url: decodeURIComponent(item.siteUrl), title: "sd" }]}
                context={parentContext.webPartContext}
                label={'Select site to capture'}
                mode={'site'}
                allowSearch={false}
                multiSelect={false}
                onChange={(sites) => {
                    setItem((temp) => ({ ...temp, siteUrl: sites[0].url, captureToSiteId: sites[0].id, siteId: sites[0].id }));
                    console.log(sites);
                }}
                placeholder={'Select sites'}
                searchPlaceholder={'Filter sites'} />

**Comment by AJIXuMuK** [comment]
Thanks @russgove for reporting this! Good catch!
The fix has been implemented and will be included in the next release.
