### ISSUE TITLE
Installing spfx-controls-react@3.1.0 throws undefined ls-remote -h -t ssh://git@github.com/microsoftgraph/msgraph-typescript-typings.git

### ISSUE THREAD

**Issue by gurubn** [pnp/sp-dev-fx-controls-react#896]
[X ] Bug

[ X] Question

#### Version

[   3.1.0      ]

#### Expected / Desired Behavior / Question
When I run npm install @pnp/spfx-controls-react --save --save-exact, expectation is, it install the @pnp/spfx-controls-react control

#### Observed Behavior
Please let me know if I am running it wrongly.

I receive  below error when I run npm install @pnp/spfx-controls-react@3.1.0 --save --save-exact OR npm install @pnp/spfx-controls-react --save --save-exact

![image](https://user-images.githubusercontent.com/23011566/117555040-11614800-b05c-11eb-8a54-0c84f507058b.png)

when I run npm install @pnp/spfx-controls-react@3.0.0 --save --save-exact, it installs properly.

Can you please let me know if I am doing anything wrong while installing latest version (3.1.0) ?

#### Steps to Reproduce
1. Run npm install @pnp/spfx-controls-react --save --save-exact

Thanks a lot in advance!

**Comment by AJIXuMuK** [comment]
Hi @gurubn,
What versions of node, rpm and Gulp are you using?
I can install the latest version without any issues.

**Comment by gurubn** [comment]
Hi @AJIXuMuK ,

Thanks a lot for checking. I am using Node v10, npm V6 and Gulp v3.
I tried in different VM with above setup and it working properly, So it seems its something with my local configuration in other machine. I will reinstall the above configuration and try once. Thanks a ton again. 

As its not the issue with spfx-controls-react@3.1.0, I will close the this thread, I hope thats ok?.


Thanks,
Guru

**Comment by gurubn** [comment]
Issue is in my local configuration , not with spfx-controls-react@3.1.0. Hence closing this thread.
