### ISSUE TITLE
We are getting expand and collapse icon in the last node of the tree

### ISSUE THREAD

**Issue by sumitdeyonline** [pnp/sp-dev-fx-controls-react#900]
We are getting expand and collapse icon in the last node of the tree, in the last node should not be any expanded and collapse icon, otherwise, the user would be confused

![image](https://user-images.githubusercontent.com/23446009/117901804-fde2f680-b280-11eb-8f25-abefc71793c2.png)

**Comment by AJIXuMuK** [comment]
Hi @sumitdeyonline,

Could you provide the configuration of the control you're using as well as the items configuration?

I can't reproduce it in the simple sample:

<img width="445" alt="Screen Shot 2021-05-15 at 6 34 07 PM" src="https://user-images.githubusercontent.com/17036219/118382613-4154a200-b5ac-11eb-99af-9a211e1c4e7b.png">

**Comment by sumitdeyonline** [comment]
Thank you, Alex, for a look into this issue 
I was generating a tree structure with a huge dataset dynamically. When I added the children[] attribute on the last node in the tree structure, it starts working perfectly however, I don't know why it causes this issue. Is it required to add children[] in the last node?

**Comment by AJIXuMuK** [comment]
@sumitdeyonline no, it's not required. 
In my sample above - root 4 and root 5 don't have `children` property passed.

**Comment by sumitdeyonline** [comment]
Thank you @AJIXuMuK, it resolved my issue though.
