### ISSUE TITLE
Remove duplicate suggestions from ListItemPicker control

### ISSUE THREAD

**Issue by jduysen** [pnp/sp-dev-fx-controls-react#901]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [@pnp/spfx-controls-react@1.19.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_
I am trying to use the ListItemPicker control to suggest items from a list but the column in question doesn't contain unique values, so the suggestions sometimes show multiple items with the same name.  I would like to see if there is a way for this control to only show unique values or if there is a way that I could use this control to display a cleaned array that I have pulled into my webpart already, or if there is another control I should be using.  I am using version 1.19 on Sharepoint 2019.

Thanks in advance!

-James

**Comment by AJIXuMuK** [comment]
Hi @jduysen.
Could you please provide some additional details on the issue?
`ListItemPicker` just displays the items from a list. If you have items with the same title, you will see "kind of" duplicates in the list.
Another question - are you using SharePoint Online or On-Prem?
If Online - I'd strongly recommend to update to a newer version of the library (`v2.7.0` for SPFx <= 1.11 or `v3.1.0` for SPFx 1.12.1)
