### ISSUE TITLE
force refresh of lists in listpicker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#905]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [  latest       ]

#### Expected / Desired Behavior / Question
Hey, I have a webpart that lets the user select an existing list using the list picker  or create a new one.  If the user creates the new list i want the newly created list to be  selected in the listpikcer.

The listpicker is caching its list of lists , so even though i set the selectedList property to the ID of the new list it does not appear as selected. The only time the list gets reloaded in componentdidupdate is 
   if (
      prevProps.baseTemplate !== this.props.baseTemplate ||
      prevProps.includeHidden !== this.props.includeHidden ||
      prevProps.orderBy !== this.props.orderBy ||
      prevProps.webAbsoluteUrl !== this.props.webAbsoluteUrl
    ) {
      this.loadLists();
    }

Any way to have it refresh the list of lists? I was thinking we could just add a boolean 'refresh' switch to its props and also check that in the comnponentdidupdate.  then in my code i could just toggle the refresh prop.

Any thoughts on this. How is it solved elsewhere in the library.

**Comment by russgove** [comment]
arghh!! just added for lines of code to my PR and it failed. Any idea whats wrong. The change is working great locally.

**Comment by russgove** [comment]
forgot about this one! i think it’s included in my pr

**Comment by joelfmrodrigues** [comment]
@russgove just to double-check, is this change included on the PR that you submitted and was merged recently?

**Comment by russgove** [comment]
yes, this issue was fixed in my last pr
