### ISSUE TITLE
sitepicker does not reflect changes made to initialSites by other components

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#908]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[x ] Enhancement

[x ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [ latest  ]
hey alex, i have another 'issue?'. likely my musunderstanding as i interpreted initialsites to be analagous to 'selectedsites'.
I have two sitepickers on my component. When the user selects a site in the First one , i want the second one to be set to what the user selected in  the first one (he can change it later if he wants). I couldn't get it to work so as a test , I just added a button to the component to set the value of the first picker to an arbitrary site. That does not work either.  Any thoughts on this?
I'm happy to work on it if you can point me in the right direction.

Test component is shown below. I can send to github if you like.
Thanks
Russell

#### Expected / Desired Behavior / Question
other code should be able to change the selected sites after the initial display

#### Observed Behavior
other code cant  change the selected sites after the initial display
#### Steps to Reproduce
import styles from './HelloWorld.module.scss';
import { escape } from '@microsoft/sp-lodash-subset';
import { SitePicker } from "@pnp/spfx-controls-react/lib/SitePicker";
import * as React from 'react';
import { BaseComponentContext } from '@microsoft/sp-component-base';
export interface IHelloWorldProps {
  context: BaseComponentContext;
}
interface IHelloWorldState {
  siteUrl: string;
  siteId: string;
  siteTitle: string;
  captureToSiteId: string;
  captureToSiteUrl: string;
  captureToSiteTitle: string;
}
export default class HelloWorld extends React.Component<IHelloWorldProps, IHelloWorldState> {
  public constructor(props: IHelloWorldProps) {
    super(props);
    this.state = { siteId: null, siteTitle: null, siteUrl: null, captureToSiteId: null, captureToSiteTitle: null, captureToSiteUrl: null };
  }
  public render(): React.ReactElement<IHelloWorldProps> {
    console.log(this.state);
    return (
      <div className={styles.helloWorld}>
        <div className={styles.container}>
          <SitePicker

            initialSites={[{ id: this.state.siteId, url: decodeURIComponent(this.state.siteUrl), title: this.state.siteTitle }]}
            context={this.props.context}
            label={'Select site to capture'}
            mode={'site'}
            multiSelect={false}
            onChange={(sites) => {
              debugger;
              console.log('setting Item');
              if (this.state.captureToSiteId === this.state.siteId) {
                this.setState((temp) => ({ ...temp, siteUrl: sites[0].url, captureToSiteUrl: sites[0].url, siteId: sites[0].id, captureToSiteId: sites[0].id, siteTitle: sites[0].title, captureToSiteTitle: sites[0].title }));
              } else {
                this.setState((temp) => ({ ...temp, siteUrl: sites[0].url, siteId: sites[0].id, siteTitle: sites[0].title }));
              }
              console.log(this.state);
            }}
            placeholder={'Select sites'}
            searchPlaceholder={'Filter sites'} />
          <button onClick={
            (e) => {
              debugger;
              this.setState((temp) => ({
                ...temp,
                siteId: "f232b610-7177-4f15-8dd3-59662f47a1f2",
                siteTitle: "All Company",
                siteUrl: "https://russellwgove.sharepoint.com/sites/AllCompany.14022107136.tvymheuq",
                captureToSiteId: "f232b610-7177-4f15-8dd3-59662f47a1f2",
                captureToSiteTitle: "All Company",
                captureToSiteUrl: "https://russellwgove.sharepoint.com/sites/AllCompany.14022107136.tvymheuq"
              }
              ));
            }}>
          </button>
          <SitePicker
            initialSites={[{ id: this.state.captureToSiteId, url: decodeURIComponent(this.state.captureToSiteUrl), title: this.state.captureToSiteTitle }]}
            context={this.props.context}
            label={'Select site to save captured Audit Items to'}
            mode={'site'}
            multiSelect={false}
            onChange={(sites) => {
              this.setState((temp) => ({ ...temp, captureToSiteId: sites[0].id, captureToSiteUrl: sites[0].url, captureToSiteTitle: sites[0].title }));
              console.log(this.state);
            }}
            placeholder={'Select sites'}
            searchPlaceholder={'Filter sites'} />
        </div>
      </div>
    );
  }
}

**Comment by AJIXuMuK** [comment]
Hi @russgove,

Currently `SitePicker` works in "uncontrolled" mode only. You can provide the initial sites, but after that the selection is completely controlled by the control itself.

**Comment by russgove** [comment]
So if i changed it to update based on changes made to initialSites. Can I make a PR for this?

**Comment by russgove** [comment]
or submitted to add selected sites mproperty

**Comment by russgove** [comment]
This issues was fixed in my last pr
