### ISSUE TITLE
People picker not restricting to the configured group on-premises 2019

### ISSUE THREAD

**Issue by abhilashsavita** [pnp/sp-dev-fx-controls-react#911]
based on his analysis groupName property on the control does not restrict the user on-premises

**Comment by joelfmrodrigues** [comment]
@abhilashsavita can I please ask you to double-check that there is no confidential information shared in the images above? Are names/email addresses fictitious, and if not, could you please obfuscate them?

**Comment by joelfmrodrigues** [comment]
Edited original issue to remove images with sensitive information

**Comment by joelfmrodrigues** [comment]
@abhilashsavita is this still an issue?
