### ISSUE TITLE
Branche DEV npm install failed at @microsoft/mgt-react (mgt-components)

### ISSUE THREAD

**Issue by petkir** [pnp/sp-dev-fx-controls-react#912]
#### Category
[X] Question

#### Version

Branche DEV

initial NPM Package restore(install) failed
Used versions:
```
node v12.18.2  and v10.22.0
npm  v6.14.8
```

#### Expected / Desired Behavior / Question
build dev Branche

#### Steps to Reproduce
```
rm -rf node_modules
npm install 
```

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/@microsoft/mgt-components/@microsoft/microsoft-graph-types-beta@github:microsoftgraph/msgraph-typescript-typings#beta" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
```

```
20 silly saveTree ├─┬ @microsoft/mgt-react@2.1.0
20 silly saveTree │ ├─┬ @microsoft/mgt-components@2.1.0
20 silly saveTree │ │ ├─┬ @microsoft/mgt-element@2.1.0
20 silly saveTree │ │ │ ├─┬ @microsoft/microsoft-graph-client@2.2.1
20 silly saveTree │ │ │ │ ├─┬ msal@1.4.9
20 silly saveTree │ │ │ │ │ └── tslib@1.14.1
20 silly saveTree │ │ │ │ └── tslib@1.14.1
20 silly saveTree │ │ │ ├── idb@5.0.8
20 silly saveTree │ │ │ └─┬ lit-element@2.4.0
20 silly saveTree │ │ │   └── lit-html@1.3.0

```

**Comment by joelfmrodrigues** [comment]
@petkir thanks for reporting it. We were looking at this issue last night, can you confirm that you are testing with the latest code version from the dev branch? We did some changes that should have fixed it. Just tested again on my end and it worked.

**Comment by petkir** [comment]
@joelfmrodrigues  

you are absolutely right I made yesterday forward integration from the Fork around10pm(CEST) and wrote also the Issue, but I forgot to submit it. 
So I submitted it in the morning and I haven't checked the commits.

I apologize for the inconvenience.
it works version 2.2 mgt is working

**Comment by joelfmrodrigues** [comment]
@petkir absolutely no problem at all and thanks for raising it anyway. At least we tested it again :)
Will close this item
