### ISSUE TITLE
Rich text control does not display the correct theme colors for fonts.

### ISSUE THREAD

**Issue by jayprajapati** [pnp/sp-dev-fx-controls-react#913]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  2.4.0  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The font colors for the rich text control should be shown according to the applied SharePoint theme. On our SharePoint tenant, we are using a custom theme (based on the colors orange), however we can still see the default theme colors in the font colors palette (blue colors shades).

#### Observed Behavior
I believe that the theme colors should be reflected in the control based on the theme that is being used.

#### Steps to Reproduce
Apply any theme with different color shade in sharepoint site.
Verify the default theme colors for font in Richtext control panel.

Thanks!
![image](https://user-images.githubusercontent.com/19882668/119147077-e1a53d80-ba68-11eb-8c58-bb0e8a391aea.png)

**Comment by michaelmaillot** [comment]
Hi @jayprajapati,

By now (version 3.15.0) this should work now.

Can you confirm on your side?
