### ISSUE TITLE
New Control: Location Picker

### ISSUE THREAD

**Issue by ravichandran-blog** [pnp/sp-dev-fx-controls-react#915]
Can we include location picker control? this is the same as the out-of-box SharePoint location picker control. 

I was already started to build this control, around 70% of the development work is done.

![image](https://user-images.githubusercontent.com/21125180/119554160-fc094f00-bdb9-11eb-9518-ec9f5ed331cc.png)

#### Category
[X] New Control

Please let me know your suggestions.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @ravichandran-blog - sure, great addition.
Feel free to submit the PR. And we can then include this control in Dynamic Form as well

**Comment by ravichandran-blog** [comment]
Thanks @AJIXuMuK

**Comment by ravichandran-blog** [comment]
Hi @AJIXuMuK ,

Sorry for the delay, submitted a pull request 🙂 https://github.com/pnp/sp-dev-fx-controls-react/pull/933

**Comment by AJIXuMuK** [comment]
@ravichandran-blog - please do not closed unreleased issues.
