### ISSUE TITLE
DateTimePicker: month name is wrong in Spanish

### ISSUE THREAD

**Issue by cdragosf** [pnp/sp-dev-fx-controls-react#923]
#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  3.1.0  ]

#### Expected / Desired Behavior / Question
Translated month for May should be "Mayo" in Spanish ( /loc/es-es.js ). The actual translation "Puede" it's the translation for the verb "may" in English.

#### Observed Behavior
The date picker control is translating "May" month name as "Puede" and that's not the correct translation. The correct translation should be "Mayo".

#### Steps to Reproduce
Add a new DateTimePicker to an Webpart and try to select a date from May month with Spanish language on SharePoint Online. It will show "Puede" on the month name. 

![image](https://user-images.githubusercontent.com/19550972/120526955-15258780-c3da-11eb-92a6-54535053350e.png)

Thanks in advance!

**Comment by eduardpaul** [comment]
Fixed with https://github.com/pnp/sp-dev-fx-controls-react/pull/924

**Comment by joelfmrodrigues** [comment]
Many thanks both, the PR has been merged and the fix will be available in the next drop version (automatically released in a few minutes)
