### ISSUE TITLE
Unable to copy paste text along with image in Pnp Richtextbox

### ISSUE THREAD

**Issue by RahiniRadha** [pnp/sp-dev-fx-controls-react#927]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [pnp v1.20.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
User should able to copy paste text along with image in Pnp Richtextbox

#### Observed Behavior
Unable to copy paste text along with image in Pnp Richtextbox. 

We have used a Pnp rich textbox control in one of SPFx webpart. We are able to copy and paste text and images separately. But when we copy text along with image, the image not getting pasted in Richtextbox.

**Comment by michaelmaillot** [comment]
Hi @RahiniRadha,

I've tested this with latest version (3.15.0) and it works:

![spfx-controls-richtext-copypaste-image](https://github.com/pnp/sp-dev-fx-controls-react/assets/44271458/7a856be3-c6a7-4618-97d4-6f25ba54df82)

Can you confirm on your side?
