### ISSUE TITLE
[DateTimePicker] Expose allowTextInput from the underlying date picker to allow manual text input

### ISSUE THREAD

**Issue by wobba** [pnp/sp-dev-fx-controls-react#928]
#### Category
[x] Enhancement

#### Version

Please specify what version of the library you are using: [ v3.1 ]

#### Expected / Desired Behavior / Question

The underlying ui fabric date picker support manual string input, but this has explicitly been set to false in https://github.com/pnp/sp-dev-fx-controls-react/blob/a8b5bdc53c42f3814252091ae27e9e041133be9c/src/controls/dateTimePicker/DateTimePicker.tsx#L296

It would be great if this property was exposed as setting to pass in.

#### Observed Behavior
Not possible to enable text input on date picker.

#### Steps to Reproduce
Use a the date picker control.

**Comment by joelfmrodrigues** [comment]
@wobba just completed a PR related to this and will be available in the next release. 
If you would like to test it before, you can try the latest beta version (should be published in a few minutes from now)

**Comment by AJIXuMuK** [comment]
Implemented in v3.3.0
