### ISSUE TITLE
PropertyFieldCollectionData is not setting sortIdx on resulting collection when using 'Add and Save'

### ISSUE THREAD

**Issue by kpfeuffer** [pnp/sp-dev-fx-controls-react#929]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.6.0 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question

The PropertyPaneFieldCollectionData with enableSoting enabled always returns a collection with the corresponding sort-position.

#### Observed Behavior

When using the PropertyFieldCollectionData with enableSoriting set to true, the corresponding sortIdx is not set when using the Save & Add-Button, but the value is set when saving the panel again or using the Add-Buttons on the right side.

I've also created an [issue](https://github.com/pnp/sp-dev-fx-property-controls/issues/369) for the sp-dev-fx-property-controls, where the issue originally came up.

Thanks!

**Comment by AJIXuMuK** [comment]
Thank you @kpfeuffer for reporting the issue!

The fix has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).
