### ISSUE TITLE
Clear the contents of the People Picker control

### ISSUE THREAD

**Issue by SamehIbrahim** [pnp/sp-dev-fx-controls-react#934]
#### Category
[ ] Enhancement
[ ] Bug
[X] Question

#### Version

Please specify what version of the library you are using: [ 3.1.0 ]

#### Expected / Desired Behavior / Question
How to clear the contents of the People Picker control using react setState method  because the "selectedItems" property that was used to do that in earlier versions no longer exists in the version  [ 3.1.0 ]

**Comment by AJIXuMuK** [comment]
Hi @SamehIbrahim,
I suppose you've updated from `v1` of the controls.
The `selectedItems` property has been renamed to `onChange`. Here is the link to the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/guides/migrate-from-v1.html) with the changes.

Please let me know if that answers your question.
