### ISSUE TITLE
Populate a People Picker with a security group

### ISSUE THREAD

**Issue by icom50** [pnp/sp-dev-fx-controls-react#935]
#### Category
[X] Question

Please specify what version of the library you are using: [ v2.0 ]

#### Expected / Desired Behavior / Question

How to insert a security group for Azure in the people picker ?

#### Observed Behavior
I'm able to retrieve a Security group with a people picker by typing its name. But when it comes to populate a people picker with a security group, i'm unable to do it whether I try populating it with the security group name or Id. 

Is there a way to programatically populate a people picker with a security group the same way we would do it with a user ?

![image](https://user-images.githubusercontent.com/53513998/122024686-f3a8a080-cdc8-11eb-853f-aac7c072fa3f.png)

Thanks!

**Comment by joelfmrodrigues** [comment]
@icom50 I just tested this and was able to set a security group as the default selection

My group:
![image](https://user-images.githubusercontent.com/19577724/122308775-ef819d80-cf04-11eb-8e28-0c7fba80706e.png)

PeoplePicker with default selection
![image](https://user-images.githubusercontent.com/19577724/122308802-00caaa00-cf05-11eb-9dd8-a8b355de08da.png)

Code (reused one of the test controls from the test web part in this repository):
``` JSX
<PeoplePicker context={this.props.context}
    titleText="People Picker (pre-set global users)"
    principalTypes={[PrincipalType.User, PrincipalType.SharePointGroup, PrincipalType.SecurityGroup, PrincipalType.DistributionList]}
    defaultSelectedUsers={["pmo"]}
    onChange={this._getPeoplePickerItems}
    personSelectionLimit={2}
    ensureUser={true} />
```

Can you try adding `ensureUser={true}` to your control?

**Comment by icom50** [comment]
Oh yes it was juste that, it's work now thanks a lot.
