### ISSUE TITLE
Configure display labels of ListItemAttachments control

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-controls-react#942]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.2.0 ]

#### Expected / Desired Behavior / Question
Be able to configure labels displayed for ListItemAttachments control

#### Observed Behavior
Currently there are no properties to configure labels

**Comment by AJIXuMuK** [comment]
implemented a while ago.
