### ISSUE TITLE
Ability to configure Panel size of FieldCollectionData Panel

### ISSUE THREAD

**Issue by manojkgaai** [pnp/sp-dev-fx-controls-react#952]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

#### Version

Please specify what version of the library you are using: Version 2.6.0 

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._ 

#### Expected / Desired Behavior / Question
Ability to configure the panel size when more columns are used in FieldCollectionData.

#### Observed Behavior
Choice column options are truncated. input data is truncated.

#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/30728461/124906475-ba003980-e004-11eb-9181-914ef7f48a0a.png)

Thanks!

**Comment by michaelmaillot** [comment]
Hi @manojkgaai,

Latest version (3.15.0) includes a `panelProps` prop in which you can specify panel size. See [documentation](https://pnp.github.io/sp-dev-fx-controls-react/controls/FieldCollectionData/#implementation).

Is it what you've looked for?

**Comment by manojkgaai** [comment]
Thanks @michaelmaillot, it solved the issue, i could modify the control width inside the panels now.
