### ISSUE TITLE
[ComboBoxListItemPicker] defaultSelectedItems not working

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-controls-react#954]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.3.0 ]

#### Expected / Desired Behavior / Question
defaultSelectedItems should select default dropdown options

#### Observed Behavior
Property not working

#### Steps to Reproduce
Pass a key to defaultSelectedItems property

**Comment by Katli95** [comment]
Hey @joelfmrodrigues, real glad too see that you've spotted and fixed this, just ran into it. Do you know when this might be deployed?
And while I'm at it, might I ask the same question about #936?

P.s. Sorry for bugging you like this, but I've got a project waiting for both 😇

**Comment by AJIXuMuK** [comment]
@joelfmrodrigues - could you please specify the version when it was fixed?

**Comment by joelfmrodrigues** [comment]
@Katli95 this should be available since 3.4.0.
I'm sure it's working now as I worked on a project this week where it's being used
