### ISSUE TITLE
[ListItemPicker] add property to show all options by default 

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-controls-react#955]
#### Category
[x] Enhancement

#### Version

Please specify what version of the library you are using: [   3.3.0      ]

#### Expected / Desired Behavior / Question
Add a new property that allows all options to be loaded by default when clicking on the control to select an option. 

#### Observed Behavior
Controls always requires the user to type something before options are displayed

**Comment by AJIXuMuK** [comment]
implemented.
