### ISSUE TITLE
[ PeoplePicker ] Default selected items for groups

### ISSUE THREAD

**Issue by a1exymoroz** [pnp/sp-dev-fx-controls-react#958]
#### Category

[x] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [ "@pnp/spfx-controls-react": "^3.2.1" ]

#### Question

Why doesn't PeoplePicker have selected items for different types?
PeoplePicker has only defaultSelectedUsers for users. But if we use different types ([PrincipalType.SecurityGroup, PrincipalType.User, PrincipalType.SharePointGroup]), I'll have problem.

#### Observed Behavior

If we can use different types, we have to select different types.

#### Steps to Reproduce

1) Set different  principalTypes
`  principalTypes={[PrincipalType.SecurityGroup, PrincipalType.User, PrincipalType.SharePointGroup]}`
2) Set different selected items
`defaultSelectedUsers={[User, Sharepoint Group, Azure AD group]}`
3) If we use `defaultSelectedUsers`, we need emails. But Sharepoint group doesn't have a email.
If I use texts for `defaultSelectedUsers`, Azure AD group won't select

Thanks!

**Comment by AJIXuMuK** [comment]
Thanks @a1exymoroz for submitting both issue and fix!
