### ISSUE TITLE
[FilePicker] "Stock images" label not showing in portugues nor spanish

### ISSUE THREAD

**Issue by gabsnery** [pnp/sp-dev-fx-controls-react#959]
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
 [3.1.0]

#### Expected / Desired Behavior / Question
The label should show "Imagens de stock" in pt-pt and "Imágenes de stock" in es-es

#### Observed Behavior
Shows nothing 
pt-pt:
![image](https://user-images.githubusercontent.com/12504922/125499086-57078cb4-08a5-4645-bbbd-65d1bc9222ec.png)
es-es
![image](https://user-images.githubusercontent.com/12504922/125499337-1b2ead5e-4a46-465a-b16b-508dd0cefee3.png)

Thanks!me

**Comment by joelfmrodrigues** [comment]
Hi @gabsnery , thanks for raising this issue.
There were updates to localised string files recently. Could you please install the latest beta version and try again?
npm i @pnp/spfx-controls-react@3.3.0-beta.4da868a

**Comment by gabsnery** [comment]
> Hi @gabsnery , thanks for raising this issue.
> There were updates to localised string files recently. Could you please install the latest beta version and try again?
> npm i @pnp/spfx-controls-react@3.3.0-beta.4da868a

**Comment by gabsnery** [comment]
@joelfmrodrigues It worked =) 
Is there any date for v3.3.0 release?

**Comment by joelfmrodrigues** [comment]
@gabsnery we are trying to get it out this week if all goes to plan :) stay tunned :)
