### ISSUE TITLE
Open ListView link in new tab/window 

### ISSUE THREAD

**Issue by jduysen** [pnp/sp-dev-fx-controls-react#960]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [  1.19.0      ]

#### Expected / Desired Behavior / Question
Is there a way to open a link from the ListView component in a new tab/window by default?  I am able to create the link successfully for the list item by using the linkPropertyName in IViewField but it opens in the same tab as my webpart, which is not ideal.

Thanks in advance,

James
![Capture](https://user-images.githubusercontent.com/47751321/125518784-856b0dc7-320f-4872-a572-18c41b325313.PNG)

**Comment by joelfmrodrigues** [comment]
@modern-dev-dude many thanks for the input.
@jduysen were you able to resolve this?

**Comment by jduysen** [comment]
@joelfmrodrigues thanks for following up.  It looks like @modern-dev-dude recommendation will be the solution to this question.  

Thanks,

James

**Comment by modern-dev-dude** [comment]
@jduysen Glad to help, good luck in your implementation!
