### ISSUE TITLE
ListView - Clear Selection

### ISSUE THREAD

**Issue by jaxnz** [pnp/sp-dev-fx-controls-react#961]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [v3.2.1]

#### Expected / Desired Behavior / Question
Is it possible to either clear the selection, or update selection programmatically of a ListView?

#### Observed Behavior
Currently I have a button which shows after selection which then opens a dialog when clicked. If I show the dialog on selection, it creates a never ending dialog loop. If there was a way to clear selection then this could be stopped when the dialog closes.

Thanks!

**Comment by modern-dev-dude** [comment]
@jaxnz Could you put this in a code pen or give me minimum steps to reproduce?

**Comment by joelfmrodrigues** [comment]
@jaxnz if I understand your question correctly, have you tried to use defaultSelection property and pass it an empty array when you want to clear the selection? (Make sure the controls renders again with the new property value)
