### ISSUE TITLE
FilePicker tabs missing french translation

### ISSUE THREAD

**Issue by JoelM365** [pnp/sp-dev-fx-controls-react#972]
[X] Enhancement

[ ] Bug

[ ] Question

#### Version
[ 3.2.1 ]

Missing translation of "Stock Image" tab in french (maybe others ?)

![FilePicker missing french translation](https://user-images.githubusercontent.com/86789385/127133360-bfc691f3-f8a1-4900-95b6-8c5d47195666.png)

**Comment by joelfmrodrigues** [comment]
Hi @JoelM365 , there was a recent pull request (#957) which I think fixed this.
Can you please install the latest beta build and check if the issue is fixed?
