### ISSUE TITLE
Dynamic Form - ability to disable / hide fields in the form

### ISSUE THREAD

**Issue by jumpei-yamauchi** [pnp/sp-dev-fx-controls-react#974]
[x] Enhancement

Expected / Desired Behavior / Question

**Component**: Dynamic Form

Add the ability to disable / hide fields in the form

**Comment by gobigfoot** [comment]
You should hide the field on native list form. 

Navigate to the list and click "+ New" 

Using the dropdown on the form select "Edit Columns"
![image](https://user-images.githubusercontent.com/1820704/127371239-37a92285-9966-47ea-8906-ecd473184383.png)

Uncheck the fields you wish to hide

You can also adjust the order the fields appear on the form using drag and drop

Click "Save"

**Comment by joelfmrodrigues** [comment]
@jumpei-yamauchi did the comment from @gobigfoot answered your question?
