### ISSUE TITLE
Issue with PnP People Picker

### ISSUE THREAD

**Issue by SushmitaMishra** [pnp/sp-dev-fx-controls-react#977]
#### Category
[ ] Bug

#### Version

spfx-controls-react 2.8.0

#### Expected / Desired Behavior / Question
It should work same as OOB people picker control and should return users just by entering the first 4 letter(or few letters) of firstname.

#### Observed Behavior
While performing search, we need to type more characters for search to display the user. E.g we need to enter full firstname then a space and first letter of lastname for it to return the user. 

Thanks!

**Comment by Ajay8790** [comment]
@joelfmrodrigues  any updates on this? I am also facing the same issue in production environment.
Can you please guide me How to fix this ?

**Comment by MonalisaBaltatescu** [comment]
Hi, I want to contribute to this issue. Could you please assign me so I can start working on it?

**Comment by joelfmrodrigues** [comment]
Hi @MonalisaBaltatescu many thanks for volunteering, I have assigned the issue to you

**Comment by michaelmaillot** [comment]
Hi @SushmitaMishra & @Ajay8790,

Do you still have issue with the control?

I confirm the same behavior as @MonalisaBaltatescu from my side.
