### ISSUE TITLE
DateTimePicker - Can set value for date but not time.

### ISSUE THREAD

**Issue by jduysen** [pnp/sp-dev-fx-controls-react#981]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    1.19.0     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Observed Behavior
I am setting the value of the datetimepicker with a piece of state that is a Date object with a time that is different that current time.  I can set the date value without an issue but the time always defaults to the current time.

#### Steps to Reproduce
Set the value of datetimepicker to state of new Date Object with hour different than current hour.

![DateTimeIssue](https://user-images.githubusercontent.com/47751321/128379278-12d636eb-c80a-4dad-97e7-7b47bd6768ef.PNG)

**Comment by AJIXuMuK** [comment]
Hi @jduysen,
Thank you for reporting the issue.
Are you using the library in SharePoint on-prem or SharePoint Online?
If Online - could you please update to `v2` or `v3` of the controls?
`v1` is not actively maintained.

**Comment by jduysen** [comment]
Alex,
Thanks for the reply. Unfortunately our environment is Sharepoint 2019, so v1 is the only compatible version. I would like to use this library instead of getting approval for another 3rd party reach library if possible. The feature in question is really just a bonus that would save the user a few clicks, but would definitely be nice to have.

**Comment by AJIXuMuK** [comment]
@jduysen - would you be able to submit a PR for v1 to fix this issue?
I'll be happy to review it and include as part of v1 release.

**Comment by jduysen** [comment]
Alex, I cloned the v1 branch to my machine but am getting an SSL error (ERR_SSL_PROTOCOL_ERROR) and a bunch of typescript errors when I run gulp serve after running npm install.  I installed typescript 3.6.4 and that seemed to resolve the typescript errors, but even after running gulp trust-dev-cert I can't access the local workbench.  Unfortunately I cannot add system environment variables on this machine.  I will try to do this on a personal machine when I have the time, but wondering if you have thoughts on any other troubleshooting I may have missed?

**Comment by AJIXuMuK** [comment]
@jduysen  few things:
- v1 is based on node version 6 (maybe v8 will work as well). I would recommend to use nvm or nvs to host multiple versions of node on your machine
- For the certificate error try few thigs:
  - use hosted workbench, not local one
  - https://github.com/sharepoint/sp-dev-docs/issues/1002
  - open Network tab, select the failing request to manifests.js and open it in a separate tab. Proceed to unsecure

**Comment by jduysen** [comment]
Ok, I spun up a vm that I can install nvm on.  I cloned v1, installed everything using node v6 and am getting the below errors upon running gulp serve.  I would really like to contribute, but it seems like I might be in a small minority still using the older version of the library, so if it isn't worth your time to troubleshoot, please don't worry about it.  I can make the adjustments as mentioned above on a per project basis if I have a project that requires a datetime picker.

![image](https://user-images.githubusercontent.com/47751321/147004929-4d929536-ec55-4e57-bbea-3eff36a1ea47.png)

**Comment by jduysen** [comment]
Going to use workaround above.
