### ISSUE TITLE
what version of the library should be used for 2019 on prem

### ISSUE THREAD

**Issue by wallaceturner** [pnp/sp-dev-fx-controls-react#982]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

what version of the library should be used for 2019 on prem? Your [docs](https://pnp.github.io/sp-dev-fx-controls-react/index.html) imply [v1.1.0](https://www.npmjs.com/package/@pnp/spfx-controls-react/v/1.1.0) should be used:

>>The version is maintained for SharePoint On-Prem 2016 and 2019 implementations. Be aware that the controls might not work in solutions you're building for on-premises. As for on-premises solutions version **1.1.0** will get used.

Version 1.1.0 contains very few controls and i do note version 1.21.1 is the latest so I assume that the latest 1.x stream (1.21.1 as of today) should work with SP 2019 on prem? 

Could you please also clarify what is meant by `the controls might not work in solutions you're building for on-premises.` ? 
If version 1.x is its own source code separate from 3.x then why would controls be shipped in 1.x that 'might not work' - please clarify

**Comment by AJIXuMuK** [comment]
Hi @wallaceturner,
Thanks for the question.

`v1` is the correct version for on-prem implementations. It is based on SPFx v1.3. SharePoint 2016 uses SPFx v1.1. That's why some controls may not work there.
Hope it helps.

**Comment by wallaceturner** [comment]
Hi @AJIXuMuK thanks for your reply
Was a tad confusing because of this comment
>As for on-premises solutions version 1.1.0 will get used.

Perhaps prefixing 'SPFx 1.1.0' would help

thanks again
