### ISSUE TITLE
ComboboxListItemPicker should have option to sort the items in the picker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-controls-react#985]
#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.1.0  ]

#### Expected / Desired Behavior / Question
expect to see items in picker sorted alphabetcially
#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making items are shown in the sequence they were added

#### Steps to Reproduce
add items in the list in random order, and thats the order they get displayed in

**Comment by russgove** [comment]
looks like I can just add an optional orderBy paramneter to the existing src\common\dal\ListItemRepository  getListItemsByFilterClause method

**Comment by russgove** [comment]
i’ll have a pr in a day or two

**Comment by joelfmrodrigues** [comment]
PR merged and changes will be available on the next release
