### ISSUE TITLE
Location picker control availability 

### ISSUE THREAD

**Issue by ravichandran-blog** [pnp/sp-dev-fx-controls-react#991]
#### Category

[X] Question

Hi @AJIXuMuK ,

Sorry!, Can I know the reason why location picker control is not listed, 
![image](https://user-images.githubusercontent.com/21125180/129585555-9ac8d113-1039-4c9b-9269-1ddfa494a165.png)

**Comment by aaclage** [comment]
@ravichandran-blog did you update the documentation links?

**Comment by ravichandran-blog** [comment]
Thanks @aaclage 

I have prepared this file https://github.com/pnp/sp-dev-fx-controls-react/blob/v2-dev/docs/documentation/docs/controls/LocationPicker.md

but I don't which is the documentation link file, could you please let me know the file URL if possible

**Comment by aaclage** [comment]
@ravichandran-blog 

https://github.com/pnp/sp-dev-fx-controls-react/blob/master/docs/documentation/mkdocs.yml
https://github.com/pnp/sp-dev-fx-controls-react/blob/master/docs/documentation/docs/index.md

**Comment by AJIXuMuK** [comment]
@ravichandran-blog the fix for the documentation is in `dev` branch. It will be fixed when we release a new version.

**Comment by aaclage** [comment]
@ravichandran-blog @AJIXuMuK 
yes 'dev' branch was just looking for the links

**Comment by ravichandran-blog** [comment]
@AJIXuMuK and @aaclage 

Thanks for the information
