### ISSUE TITLE
TaxonomyPicker Style

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#996]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [  3.2.1  ]

#### Expected / Desired Behavior / Question

Since you are using "office-ui-fabric-react": "7.156.0" I expected to be able to style it the same as controls from that.

#### Observed Behavior

there is no property for styling (the label and such)

#### Steps to Reproduce
`						<TaxonomyPicker allowMultipleSelections={false}
							termsetNameOrID="Document Type" panelTitle="Select Document Type" label="Document Type"
							context={props.context} placeholder={'Start typing or click the label'}
							onChange={onTaxPickerChange} style={textFieldStyles} //this errors
							isTermSetSelectable={false} />`
#### Submission Guidelines

Is there another way to style the control and the lable?

Thanks!

**Comment by Martin-Leonhartsberger-Habau** [comment]
I have the same question regarding PeoplePicker.
It was a pain to find out, how to change the width of the suggestion callout (it is fixed to 180px in in office-ui-fabric-react).
This post / answer helped me out: https://stackoverflow.com/questions/64510173/how-to-change-the-width-of-normalpeoplepicker-dropdown

![image](https://user-images.githubusercontent.com/66724076/134346051-0dc5c810-1109-40a1-b23d-af08c8ca2b03.png)

**Comment by joelfmrodrigues** [comment]
@Martin-Leonhartsberger-Habau there is a new `styles` property that was added to the PeoplePicker control recently (around 2 months ago) that possibly does what you need. Could you please check and open a separate issue if still required (to avoid switching the context of this item)?

**Comment by joelfmrodrigues** [comment]
@Ofer-Gal is this still required? Have you tried out the [modern-looking taxonomy picker](https://pnp.github.io/sp-dev-fx-controls-react/controls/ModernTaxonomyPicker/) in case it suits your requirements?
If still required, would something like the `styles` property of the PeoplePicker work for you?

**Comment by Ofer-Gal** [comment]
I got this working long time ago.  Sorry I did not close then.
