### ISSUE TITLE
Taxonomy picker - useSessionStorage property integration

### ISSUE THREAD

**Issue by Whiteshark57** [pnp/sp-dev-fx-controls-react#998]
Category
[x] Enhancement

[ ] Bug

[ ] Question

Version

Please specify what version of the library you are using: [1.21.1]

Expected / Desired Behavior / Question

Could you please update the taxonomy picker control to integrate the useSessionStorage property as it is in the 3.2.1 version?

Observed Behavior

In version 1.21.1, the taxonomy picker control doesn't have the useSessionStorage property available.

Steps to Reproduce

1- Configure a taxonomy picker control.
2- Try to use the useSessionStorage property.
![image](https://user-images.githubusercontent.com/74719323/130746042-769ea687-bb9a-4634-91ce-3c2239d5131e.png)

![image](https://user-images.githubusercontent.com/74719323/130746500-2f0d02db-e5a4-45c4-a378-d17df92fe6cd.png)

**Comment by joelfmrodrigues** [comment]
@Whiteshark57  just doing some house cleaning...could you please confirm if this issue is now resolved?

**Comment by Whiteshark57** [comment]
@joelfmrodrigues 
Hi, yes I confirm this issue is resolved.
See you.

**Comment by joelfmrodrigues** [comment]
@Whiteshark57 many thanks for confirming, will close this issue
