### ISSUE TITLE
FolderPicker not working for subweb

### ISSUE THREAD

**Issue by mhintner** [pnp/sp-dev-fx-controls-react#999]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  3.2.1       ]

#### Expected / Desired Behavior / Question
FolderPicker shows Libraries/Folders of subweb as specified in 'ServerRelativeUrl'

#### Observed Behavior
FolderPicker shows 'This folder doesn't have any subfolders.'

#### Steps to Reproduce
FolderPicker only works within the current web, as soon as 'ServerRelativeUrl' points to a subweb, no libraries/folders are shown.

**Comment by joelfmrodrigues** [comment]
@petkir really sorry as I missed that you have tagged me here.
That's a good question, although updating everything to support subwebs may be a big task. I think updating one control at a time may be easier to manage and test. @AJIXuMuK any thoughts on updating all controls to support subwebs?

Regarding the FolderPicker control, as it seems that you have already looked into it, would you be interested in submitting a PR?

**Comment by petkir** [comment]
Hi @joelfmrodrigues 

the next couple of weeks I will not manage it, but I will give it a try.

I would add a Property to the control. 
If it is set, the control will show Libs and Folders from that Site/Web.
Subweb Selection has to be outside this control. 

And yes to change all controls is a big task, but I will look to the other too, to support this.

**Comment by AJIXuMuK** [comment]
Hey @petkir @joelfmrodrigues - I would do one step at a time.
Totally agree with the idea of additional property. To be "aligned" with other controls, we can do similarly to `ListPicker` and add:
```typescript
/**
   * Absolute Web Url of target site (user requires permissions)
   */
  webAbsoluteUrl?: string;
```

If the property is set - use it, otherwise use the url from the context.

**Comment by mrrobertsson** [comment]
Hi,

I have similar issues with FolderPicker, I had to implement my own solution by using the FolderExplorer instead, where I could set the absoluteUrl. 

How is it going with this, I see that it has been a while since the topic was discussed.

**Comment by frankyvc** [comment]
+1 same issue, need absoluteUrl for FolderPicker

**Comment by joelfmrodrigues** [comment]
@mhintner could you please confirm if this issue is now resolved based on the pull request from @petkir ?

**Comment by jackpoz** [comment]
just for reference, https://github.com/pnp/sp-dev-fx-controls-react/pull/1340 deals with FilePicker while https://github.com/pnp/sp-dev-fx-controls-react/pull/1345 deals with FolderPicker (so related to this issue)
